ACEmulator/ACE-World-16PY-Patches

- Database/Patches/FixBrokenBracers/Quick Fix for Broken Bracers.sql
Resolves ACEmulator/ACE#1129
Co-Authored-By: OptimShi <optimshi@users.noreply.github.com>
> Quick Fix for Broken Bracers

- Database/Patches/TODUpdates/2 SpellTableExtendedData/05137 Augmented Understanding III.sql
- Database/Patches/TODUpdates/2 SpellTableExtendedData/05153 Augmented Understanding I.sql
- Database/Patches/TODUpdates/2 SpellTableExtendedData/05154 Augmented Understanding II.sql
- Database/Patches/TODUpdates/2 SpellTableExtendedData/05175 Facility Hub Recall.sql
- Add four TOD+ Era spells: Augmented Understanding I, Augmented Understanding II, Augmented Understanding III, and Facility Hub Recall
> Add Four TOD+ Era Spells

- Database/Patches/TODUpdates/6 LandBlockExtendedData/22DC.sql
- Database/Patches/TODUpdates/6 LandBlockExtendedData/22E3.sql
- Database/Patches/TODUpdates/6 LandBlockExtendedData/23DA.sql
- Database/Patches/TODUpdates/6 LandBlockExtendedData/23DD.sql
- Database/Patches/TODUpdates/9 WeenieDefaults/Clothing/Clothing/31239 Poet's Shirt.sql
- Database/Patches/TrainingAcademy/9 WeenieDefaults/SQL/Portal/31061 Central Courtyard.sql
- Fix incorrectly renamed quest on Central Courtyard portal, so it matches quest stamped by Training Master
- Add Poet's Shirt
- Add Westwatch town spawn data
> Add Westwatch and fix TA portal

- Database/Patches/2005-07-ThroneOfDestiny/6 LandBlockExtendedData/1134.sql
- Database/Patches/2005-07-ThroneOfDestiny/6 LandBlockExtendedData/C6A9.sql
- Database/Patches/2005-08-FriendAndFoe/3 TreasureTable/Wielded/02014.sql
- Database/Patches/2005-08-FriendAndFoe/3 TreasureTable/Wielded/02015.sql
- Database/Patches/2005-08-FriendAndFoe/3 TreasureTable/Wielded/02016.sql
- Database/Patches/2005-08-FriendAndFoe/3 TreasureTable/Wielded/02017.sql
- Database/Patches/2005-08-FriendAndFoe/3 TreasureTable/Wielded/02018.sql
- Database/Patches/2005-08-FriendAndFoe/6 LandBlockExtendedData/0EBA.sql
- Database/Patches/2005-08-FriendAndFoe/6 LandBlockExtendedData/1134.sql
- Database/Patches/2005-08-FriendAndFoe/6 LandBlockExtendedData/2B20.sql
- Database/Patches/2005-08-FriendAndFoe/6 LandBlockExtendedData/3BE7.sql
- Database/Patches/2005-08-FriendAndFoe/6 LandBlockExtendedData/43EE.sql
- Database/Patches/2005-08-FriendAndFoe/6 LandBlockExtendedData/5B9C.sql
- Database/Patches/2005-08-FriendAndFoe/6 LandBlockExtendedData/64D5.sql
- Database/Patches/2005-08-FriendAndFoe/6 LandBlockExtendedData/88BF.sql
- Database/Patches/2005-08-FriendAndFoe/6 LandBlockExtendedData/BA9F.sql
- Database/Patches/2005-08-FriendAndFoe/9 WeenieDefaults/Clothing/Armor/31392 Raven Hand Aegis.sql
- Database/Patches/2005-08-FriendAndFoe/9 WeenieDefaults/CraftTool/CraftAlchemyBase/23361 Chorizite Formula.sql
- Database/Patches/2005-08-FriendAndFoe/9 WeenieDefaults/Creature/Human/31338 Gronk the Hammer.sql
- Database/Patches/2005-08-FriendAndFoe/9 WeenieDefaults/Creature/Human/31339 Bandit Forger.sql
- Database/Patches/2005-08-FriendAndFoe/9 WeenieDefaults/MeleeWeapon/31838 Hammer of Discipline.sql
- Add Shanrek the Forger in Bandit Castle, Camp Blacksmith, Chef Jonus, Dionaea, Drozer, Edobar the Esoteric, Farmer Kao, Fiun Gaya, Hea Kassoka, Jacob Durstan, Jin Ghao, Larnia, Markis, Hinkel, Ricardo
- Add spawn locations for Forger's Hideout
- Remove duplicate Tanami Kei and Anasha
- Create new wielded treasure table entries for Bandit Forger and Raven Hands
> Landblock spawns for Friend and Foe

- Database/Patches/2017-01-EndOfRetail/6 LandBlockExtendedData/SQL/DA3B.sql
Added Shoichi for Tusker Guard KT to Lin
> Added Shoichi for Tusker Guard KT

- Database/Patches/2005-07-ThroneOfDestiny/6 LandBlockExtendedData/0191.sql
- Database/Patches/2005-07-ThroneOfDestiny/6 LandBlockExtendedData/27EC.sql
- Database/Patches/2005-07-ThroneOfDestiny/6 LandBlockExtendedData/B470.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Container/29472 Corpse.sql
- Database/Patches/2005-08-FriendAndFoe/6 LandBlockExtendedData/27EC.sql
- Database/Patches/2005-08-FriendAndFoe/9 WeenieDefaults/Creature/Fiun/31296 Fiun Gaya.sql
- Database/Patches/2005-08-FriendAndFoe/9 WeenieDefaults/Creature/Human/31728 Mancanza the Wanderer.sql
- Database/Patches/2005-08-FriendAndFoe/9 WeenieDefaults/Creature/Sclavus/31663 Ssavashka the Devoted.sql
- Database/Patches/2013-02-BalanceOfPower/6 LandBlockExtendedData/32D9.sql
- Database/Patches/2013-02-BalanceOfPower/6 LandBlockExtendedData/7D64.sql
- Database/Patches/2013-02-BalanceOfPower/6 LandBlockExtendedData/DA55.sql
- Add new Mountain Sewer, new Yanshi town spawns, Keminub, Iaret, and Sacmisi
- Fix reported issue with corpse at the end of the Lugian Ice Tunnels; ActivationResponse was incorrectly set to 1, instead of 2
Ready for merging
> Add a few spawn maps missed in previous PR

- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Generic/19199 Nullified Statue of a Gromnie.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Generic/19204 Nullified Statue of a Skeleton.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Generic/19206 Nullified Statue of a Tumerok.sql
- Change Nullified Statues back to generic weenies
> Fix Nullified Statues

- Database/Patches/2005-07-ThroneOfDestiny/6 LandBlockExtendedData/33D9.sql
- Database/Patches/2010-10-FromDarknessLight/6 LandBlockExtendedData/32D9.sql
- Database/Patches/2010-10-FromDarknessLight/6 LandBlockExtendedData/7D64.sql
- Database/Patches/2010-10-FromDarknessLight/6 LandBlockExtendedData/A9B3.sql
- Database/Patches/2010-10-FromDarknessLight/6 LandBlockExtendedData/DB55.sql
- Add Jaffres Dini's spawn data to Sanamar
- Add Scrivener of the Void to Holtburg, Yaraq, Shoushi, and Sanamar locations
> Add five spawn data entries

- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/SkillAlterationDevice/43400 Void Magic Gem of Enlightenment.sql
- Add missed Void Gem of Enlightenment
> Add missed Void Gem of Enlightenment

- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Clothing/Armor/37189 Olthoi Celdon Gauntlets.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Clothing/Armor/37192 Olthoi Celdon Girth.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Clothing/Armor/37197 Olthoi Celdon Helm.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Clothing/Armor/37205 Olthoi Celdon Sleeves.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Clothing/Armor/37209 Olthoi Celdon Sollerets.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Human/34259 Donatello Linante.sql
- Database/Patches/2005-08-FriendAndFoe/9 WeenieDefaults/Creature/Human/31641 San Ming.sql
- Fix quest names in San Ming's emote table
- Fix ClothingPriority on Olthoi Celdon armor
- Add Donatello Linante
> Fix quest names in San Ming's emote table

- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Olthoi/23990 Olthoi Swarm Eviscerator.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Olthoi/24299 Olthoi Swarm Drone.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Olthoi/24302 Olthoi Swarm Legionary.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Olthoi/24304 Olthoi Swarm Nymph.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Olthoi/24306 Olthoi Swarm Worker.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Olthoi/24309 Olthoi Swarm Eviscerator.sql
- Database/Patches/2005-08-FriendAndFoe/9 WeenieDefaults/Misc/70024 Tomb Rubble.sql
- Update Olthoi Swarm mobs for loot tier updates, per wiki
- Add Tomb Rubble weenie
> Update Olthoi Swarm death treasure

- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Clothing/Armor/28815 Kul'dir.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Clothing/Armor/28853 Kam'shir.sql
- Update two shields to Generic items
> Update two shields to Generic items

- Database/Patches/2017-01-EndOfRetail/6 LandBlockExtendedData/SQL/708F.sql
Add Hall of Metos Portal to Zaikhal area
> Add Hall of Metos Portal to Zaikhal area

- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Human/42140 Warden.sql
> warden from give to refuse for explorer mace

- Database/Patches/2010-04-SheddingSkin/9 WeenieDefaults/Creature/Wisp/42668 Intense Corroding Crystalline Wisp.sql
- Database/Patches/2010-04-SheddingSkin/9 WeenieDefaults/Creature/Wisp/42670 Shivering Crystalline Wisp.sql
- Database/Patches/2010-04-SheddingSkin/9 WeenieDefaults/Creature/Wisp/42671 Intense Incalescent Crystalline Wisp.sql
Enable EdgeSlide to minimize pit falls
> Update Aetheria Wisps

- Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/03818 Curse of Raven Fury.sql
Number of projectiles for this should be 8 based on pcap data.
> Update 03818 Curse of Raven Fury.sql

- Database/Patches/2005-07-ThroneOfDestiny/4 CraftTable/06020 Deadly Prismatic Atlatl Dart.sql
- Database/Patches/2005-07-ThroneOfDestiny/4 CraftTable/06021 Deadly Prismatic Atlatl Dart.sql
- Fix the deadly prismatic dart recipes
> Fix the deadly prismatic dart recipes

- Database/Patches/2010-04-SheddingSkin/9 WeenieDefaults/Gem/44880 Armor Middle Reduction Tool.sql
Updated Use, LongDesc strings and Sellbable bool for Armor Middle Reduction Tool based on log data
> Armor Middle Reduction Tool

- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37187 Olthoi Alduressa Gauntlets.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37188 Olthoi Amuli Gauntlets.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37189 Olthoi Celdon Gauntlets.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37190 Olthoi Koujia Gauntlets.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37192 Olthoi Celdon Girth.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37195 Olthoi Alduressa Helm.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37196 Olthoi Amuli Helm.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37197 Olthoi Celdon Helm.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37198 Olthoi Koujia Kabuton.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37200 Olthoi Alduressa Leggings.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37201 Olthoi Amuli Leggings.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37202 Olthoi Celdon Leggings.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37203 Olthoi Koujia Leggings.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37205 Olthoi Celdon Sleeves.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37206 Olthoi Koujia Sleeves.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37207 Olthoi Alduressa Boots.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37208 Olthoi Amuli Sollerets.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37209 Olthoi Celdon Sollerets.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37211 Olthoi Koujia Sollerets.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37214 Olthoi Celdon Breastplate.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37215 Olthoi Koujia Breastplate.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37217 Olthoi Alduressa Coat.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37299 Olthoi Amuli Coat.sql
- Add version 2 property to new Olthoi armor revision
- Add missing ArmorType property to Olthoi armor
> Add versioning and ArmorTypes to Olthoi Armor

- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/PKModifier/Misc/00854 Altar of Bael'Zharon.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/PKModifier/Misc/00855 Altar of Asheron.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/PKModifier/Misc/08510 Adja's Memorial.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/PKModifier/Misc/29034 Eye of Darkness.sql
MinimumTimeSincePk changed from 3 hours to 15 minutes at some point in time
> Alter the Altars

- Database/Patches/2005-08-FriendAndFoe/9 WeenieDefaults/Misc/31668 Tome of Blood and Bone.sql
Reverts ACEmulator/ACE-World-16PY-Patches#199
> Revert "Update 31668 Tome of Blood and Bone.sql"

- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Banderling/30683 Withered Banderling Hierophant.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Banderling/30684 Withered Banderling Hierophant.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Drudge/30680 Withered Drudge Seraph.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Drudge/30681 Withered Drudge Seraph.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Drudge/30682 Withered Drudge Seraph Mystic.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Tumerok/30686 Withered Transcendent Tumerok.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Tumerok/30687 Withered Revered Tumerok Shaman.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Tumerok/30688 Withered Revered Tumerok Shaman.sql
- Correct ClothingBase for Withered Banderling Hierophant
- Correct ClothingBase for Withered Drudge Seraph
- Correct SetupDID and ClothingBase for Withered Drudge Seraph Mystic
- Correct SetupDID, PaletteBase, ClothingBase, and PaletteTemplate for Withered Tumeroks
> Correct Withered mobs looks

- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Caster/22080 Impious Staff.sql
- Database/Patches/2008-06-Dispatch/9 WeenieDefaults/Creature/Human/38034 Roderick.sql
- Update Impious Staff to include WeaponType property
- Correct wcid that Roderick hands out for Impious Staff quest
Corrects https://github.com/ACEmulator/ACE-World-16PY-Patches/issues/216
> Impious Staff update

- Database/Patches/2005-07-ThroneOfDestiny/8 QuestDefDB/LetterToCelcyndQuest.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Book/04797 Letter to Celcynd.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Human/04794 Brentsella.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Human/04796 Mindorla.sql
- Update reward for handing in Celcynd's Ring
- Add 6 day quest timer for Letter To Celcynd pickup from chest in the Old Warehouse
> Update Letter to Celcynd quest

- Database/Patches/2005-07-ThroneOfDestiny/8 QuestDefDB/distilleryambrosiaquest.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Human/05152 Jilsaya bint Dah.sql
- Database/Patches/2010-08-TheRisenPrincess/6 LandBlockExtendedData/0159.sql
- Database/Patches/2010-08-TheRisenPrincess/9 WeenieDefaults/Chest/04886 Chest.sql
- Database/Patches/2010-08-TheRisenPrincess/9 WeenieDefaults/Portal/Portal/04943 Abandoned Shops Portal.sql
- Update Distillery Ambrosia pickup timer to 6 days
- Update Distillery Ambrosia turn-in reward from Jilsaya bint Dah
- Update Abandoned Shops dungeon mobs and quest chest
- Update entry portal for color and 40+ requirement
> Update AbandonedShops quest

- Database/Patches/2005-07-ThroneOfDestiny/8 QuestDefDB/distillerynectarquest.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Human/05046 Lord Aleval.sql
- Database/Patches/2010-08-TheRisenPrincess/6 LandBlockExtendedData/0164.sql
- Database/Patches/2010-08-TheRisenPrincess/8 QuestDefDB/distilleryambrosiaquest2.sql
- Database/Patches/2010-08-TheRisenPrincess/9 WeenieDefaults/Chest/45878 Chest.sql
- Database/Patches/2010-08-TheRisenPrincess/9 WeenieDefaults/Food/45877 Distillery Ambrosia.sql
- Database/Patches/2010-08-TheRisenPrincess/9 WeenieDefaults/Portal/Portal/04895 Lost Distillery Portal.sql
- Update NPC for EoR reward
- Update Lost Distillery dungeon mobs and quest chest
- Add new Distillery Ambrosia and pickup timer separate from original versions
- Update pickup timer for Distillery Nectar
- Update dungeon entry portal for color and 40+ requirement
> Update Lost Distillery quest

- Database/Patches/2005-07-ThroneOfDestiny/8 QuestDefDB/nantowaterbottlequest.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Human/05121 Shin Ro.sql
- Database/Patches/2010-08-TheRisenPrincess/6 LandBlockExtendedData/0168.sql
- Database/Patches/2010-08-TheRisenPrincess/9 WeenieDefaults/Chest/05756 Chest.sql
- Database/Patches/2010-08-TheRisenPrincess/9 WeenieDefaults/Portal/Portal/04923 Water Temple Portal.sql
- Update Bottle of Water pickup timer
- Update NPC reward for quest item turn-in
- Update Water Temple dungeon mobs and quest chest
- Update entry portal for color and 40+ requirement
> Update Water Temple quest

- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/MeleeWeapon/45545 Training Budiaq.sql
- Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/03847 Cataracts of Xik Minru.sql
- Fix incorrect AttackType on Training Budiaq
- Update destination on Cataracts of Xik Minru spell
> Fix spell and weapon

- Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/06159 Thorn Volley.sql
- Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/06160 Thorns.sql
- Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/06165 Deadly Thorn Volley.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/ProjectileSpell/52492 Thorn Bolt.sql
Fix WCID and number of projectiles.
> Update Thorn Spells

- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Human/05152 Jilsaya bint Dah.sql
Was 70200 / Seasoned Explorer Staff Cast /. Corrected to 70202 / Seasoned Explorer Sword Cast /
> Correct Give on wcid 5152

- Database/Patches/2010-06-FillingInTheBlanks/6 LandBlockExtendedData/SQL/A9B3.sql
- Database/Patches/2010-06-FillingInTheBlanks/9 WeenieDefaults/SQL/Creature/Chicken/25578 The Chicken.sql
> Why did The Chicken cross the road?

- Database/Patches/2005-07-ThroneOfDestiny/2 SpellTableExtendedData/02977 Portal spell to a hidden place.sql
- Database/Patches/2005-07-ThroneOfDestiny/6 LandBlockExtendedData/013E.sql
- Database/Patches/2005-07-ThroneOfDestiny/6 LandBlockExtendedData/536D.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Portal/05515 Burial Temple Portal.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Portal/15275 Nuhmudira's Dungeon.sql
- Burial Temple
- Nuhmudira's Dungeon
> Fix position issues with some dungeons

- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Portal/05606 Folthid Cellar Portal.sql
> Update 05606 Folthid Cellar Portal.sql

- Database/Patches/2010-06-FillingInTheBlanks/9 WeenieDefaults/SQL/Creature/Chicken/25578 The Chicken.sql
due to changes to RunRate calculation in ACE
> Update 25578 The Chicken.sql

- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Margul/25864 Stalking Margul.sql
- Adding chance to drop Butterscotch Suckling, per LSD data
> Update 25864 Stalking Margul.sql

- Database/Patches/2009-03-WhoWatchesTheVirindi/6 LandBlockExtendedData/SQL/7E64.sql
- Database/Patches/2009-03-WhoWatchesTheVirindi/6 LandBlockExtendedData/SQL/A9B2.sql
- Database/Patches/2009-03-WhoWatchesTheVirindi/6 LandBlockExtendedData/SQL/DB54.sql
- Database/Patches/2009-03-WhoWatchesTheVirindi/8 QuestDefDB/SQL/PaidRareExchanger.sql
- Database/Patches/2009-03-WhoWatchesTheVirindi/9 WeenieDefaults/SQL/Creature/Human/40462 Rare Exchanger.sql
- Database/Patches/2009-03-WhoWatchesTheVirindi/9 WeenieDefaults/SQL/Creature/Human/40463 Rare Exchanger.sql
- Database/Patches/2009-03-WhoWatchesTheVirindi/9 WeenieDefaults/SQL/Creature/Human/40464 Rare Exchanger.sql
- Database/Patches/2013-09-TheQuestForFreedom/9 WeenieDefaults/SQL/Key/Key/52033 Exquisite Casino Key.sql
Return the Rare Exchanger NPC to the Casinos
> Restore Rare Exchanger

- Database/Patches/2017-01-EndOfRetail/8 QuestDefDB/SQL/DeewainAttacked_0411.sql
- Database/Patches/2017-01-EndOfRetail/8 QuestDefDB/SQL/DeewainGaveNote_0411.sql
- Database/Patches/2017-01-EndOfRetail/8 QuestDefDB/SQL/DeewainStarted_0411.sql
- Database/Patches/2017-01-EndOfRetail/8 QuestDefDB/SQL/KillTaskSnowTusker0111.sql
- Database/Patches/2017-01-EndOfRetail/8 QuestDefDB/SQL/QuestRewardTimerOne.sql
- Database/Patches/2017-01-EndOfRetail/8 QuestDefDB/SQL/TurnedInCrystallineShard0311.sql
These flags are used in contract system validation testing.
> Add Various Quest flags

- Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/05330 Gear Knight Invasion Area Camp Recall.sql
-  Update destination per OptimShi
> Update 05330 Gear Knight Invasion Area Camp Recall.sql

- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/MeleeWeapon/25905 Needletooth.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/MeleeWeapon/25906 Mace of Dissonance.sql
- Two weapon MoA updates from LSD
> Two weapon MoA updates

- Database/Patches/2006-01-Reprisals/6 LandBlockExtendedData/0049.sql
- Database/Patches/2006-01-Reprisals/6 LandBlockExtendedData/1830.sql
- Database/Patches/2006-01-Reprisals/6 LandBlockExtendedData/1831.sql
- Database/Patches/2006-01-Reprisals/6 LandBlockExtendedData/1832.sql
- Database/Patches/2006-01-Reprisals/6 LandBlockExtendedData/27EC.sql
- Database/Patches/2006-01-Reprisals/8 QuestDefDB/EntemarreKiller.sql
- Database/Patches/2006-01-Reprisals/8 QuestDefDB/PickedUpEntemarresHead.sql
- Database/Patches/2006-01-Reprisals/9 WeenieDefaults/Clothing/Armor/32630 Whispering Blade Gloves.sql
- Database/Patches/2006-01-Reprisals/9 WeenieDefaults/Creature/Human/32628 Hashina.sql
- Database/Patches/2006-01-Reprisals/9 WeenieDefaults/Creature/Human/70753 Baron Entemarre.sql
- Database/Patches/2006-01-Reprisals/9 WeenieDefaults/Generic/70755 Entemarre's Head.sql
- Database/Patches/2006-01-Reprisals/9 WeenieDefaults/Portal/Portal/70752 Camp Entemarre.sql
- Database/Patches/2006-01-Reprisals/9 WeenieDefaults/Portal/Portal/70754 Camp Entemarre Surface.sql
Baron of Entemarre Completed
Sorry Forked the changes so I can work with a clean base. Resubmitting.
> Reprisals (Jan 06): Head of Baron Entemarre

- Database/Patches/2011-01-LearningFromExperience/9 WeenieDefaults/SQL/Creature/Human/30627 Cyphis Suldow.sql
- Database/Patches/2011-01-LearningFromExperience/9 WeenieDefaults/SQL/Creature/Human/30629 Aludi al-Jaladh.sql
I changed the XP for turn-ins for both Banderling Haunt and Drudge Aviator quests to what they were after the Learning from Experience update.
> I updated XP for quest turn-ins

- Database/Patches/2005-06-PreTOD/AddCandethTownCrier.sql
First time creating a pull request. This adds the town crier to Candeth Keep.
> Add Candeth Town Crier

- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Gem/Gem/31001 Asheron's Benediction.sql
Useful to have for server admins.
> ToD Preorder Gem

- Database/Patches/2006-01-Reprisals/9 WeenieDefaults/Creature/Human/30265 Fabian Strinjelli.sql
Add, , (30265,  19, False) /* Attackable */
> Update 30265 Fabian Strinjelli.sql

- Database/Patches/2006-01-Reprisals/9 WeenieDefaults/Clothing/Armor/32630 Whispering Blade Gloves.sql
Fixed the Whispering Blade Gloves, Mana Fix.
> Cur Mana Fix

- Database/Patches/2008-01-Recollections/9 WeenieDefaults/Generic/Misc/36907 Pitiful Pine Tree.sql
- Database/Patches/2008-01-Recollections/9 WeenieDefaults/Generic/Misc/36909 Festivus Rug.sql
- Database/Patches/2008-01-Recollections/9 WeenieDefaults/Generic/Misc/36910 Jubilee Rug.sql
- Database/Patches/2008-01-Recollections/9 WeenieDefaults/Generic/Misc/36912 Wood Stove.sql
- Database/Patches/2008-01-Recollections/9 WeenieDefaults/Generic/Misc/36913 Grand Bed.sql
- Database/Patches/2008-01-Recollections/9 WeenieDefaults/Generic/Misc/36914 Pile of Presents.sql
- Database/Patches/2008-01-Recollections/9 WeenieDefaults/Generic/Misc/36916 Snow Drift.sql
- Database/Patches/2008-01-Recollections/9 WeenieDefaults/Generic/Misc/36922 Big Wreath.sql
https://asheron.fandom.com/wiki/Recollections
> Some housing items from 2008-01-Recollections

- Database/Patches/2006-12-ColdTracks/8 QuestDefDB/SnowmakerUsed.sql
- Database/Patches/2006-12-ColdTracks/9 WeenieDefaults/Caster/34412 Orb of Eternal Frost.sql
- Database/Patches/2006-12-ColdTracks/9 WeenieDefaults/Gem/34406 Pack Scold.sql
- Database/Patches/2006-12-ColdTracks/9 WeenieDefaults/Gem/34407 Abominable Pack Snowman.sql
- Database/Patches/2006-12-ColdTracks/9 WeenieDefaults/Generic/34399 Doll House.sql
- Database/Patches/2006-12-ColdTracks/9 WeenieDefaults/Generic/34400 Holiday Hearth.sql
- Database/Patches/2006-12-ColdTracks/9 WeenieDefaults/Generic/34401 Holiday Lights.sql
- Database/Patches/2006-12-ColdTracks/9 WeenieDefaults/Generic/34404 Holiday Feast.sql
- Database/Patches/2006-12-ColdTracks/9 WeenieDefaults/Generic/34405 Mr. P. Holiday Pack Doll.sql
- Database/Patches/2006-12-ColdTracks/9 WeenieDefaults/Hooker/Misc/34403 Snowmaker.sql
https://asheron.fandom.com/wiki/Cold_Tracks
> Some items from 2006-12-ColdTracks

- Database/Patches/2009-10-GearsOfChange/9 WeenieDefaults/Clothing/Jewerly/41483 Compass.sql
- Database/Patches/2009-10-GearsOfChange/9 WeenieDefaults/Clothing/Jewerly/41484 Goggles.sql
- Database/Patches/2009-10-GearsOfChange/9 WeenieDefaults/Clothing/Jewerly/41485 Pocket Watch.sql
- Database/Patches/2009-10-GearsOfChange/9 WeenieDefaults/Clothing/Jewerly/41486 Puzzle Box.sql
- Database/Patches/2009-10-GearsOfChange/9 WeenieDefaults/Clothing/Jewerly/41487 Mechanical Scarab.sql
- Database/Patches/2009-10-GearsOfChange/9 WeenieDefaults/Clothing/Jewerly/41488 Top.sql
This PR adds the folder structure and the base weenies for trinkets.
> Add 2009-10-GearsOfChange baseline trinkets.

- Database/Patches/2013-10-ShatteredMasks/9 WeenieDefaults/Clothing/Clothing/52193 Mukkir Wings.sql
https://asheron.fandom.com/wiki/Mukkir_Wings
> Mukkir Wings Cloak

- Database/Patches/2013-12-TheHolidayRush/MeleeWeapon/52398 Walking Cane.sql
https://asheron.fandom.com/wiki/Walking_Cane
> Walking Cane 2013-12-TheHolidayRush

- Database/Patches/2006-12-ColdTracks/9 WeenieDefaults/Caster/34412 Orb of Eternal Frost.sql
Remove
65, 1) /* Placement - RightHandCombat */
Add
46, 512) /* DefaultCombatStyle - Magic /
52, 1) / ParentLocation - RightHand /
53, 1) / PlacementPosition - RightHandCombat */
69, False) /* IsSellable *
> Update Orb of Eternal Frost

- Database/Patches/2008-03-FoolishAmbition/9 WeenieDefaults/MeleeWeapon/35377 Replica BloodScorch.sql
- Database/Patches/2009-10-GearsOfChange/9 WeenieDefaults/MeleeWeapon/40652 Great BloodScorch.sql
https://asheron.fandom.com/wiki/Replica_BloodScorch
https://asheron.fandom.com/wiki/Great_BloodScorch
> Replica BloodScorch and Great BloodScorch Weapons

- Database/Patches/2010-07-FillingInTheBlanks/9 WeenieDefaults/Clothing/Armor/43049 Knorr Academy Gauntlets.sql
- Database/Patches/2010-07-FillingInTheBlanks/9 WeenieDefaults/Clothing/Armor/43051 Knorr Academy Greaves.sql
- Database/Patches/2010-07-FillingInTheBlanks/9 WeenieDefaults/Clothing/Armor/43052 Knorr Academy Pauldrons.sql
- Database/Patches/2010-07-FillingInTheBlanks/9 WeenieDefaults/Clothing/Armor/43053 Knorr Academy Boots.sql
- Database/Patches/2010-07-FillingInTheBlanks/9 WeenieDefaults/Clothing/Armor/43054 Knorr Academy Tassets.sql
- Database/Patches/2010-07-FillingInTheBlanks/9 WeenieDefaults/Clothing/Armor/43068 Knorr Academy Helm.sql
- Database/Patches/2012-08-TheRisenPrincess/9 WeenieDefaults/Chest/04791 Chest.sql
- Database/Patches/2012-08-TheRisenPrincess/9 WeenieDefaults/Chest/04886 Chest.sql
- Database/Patches/2012-08-TheRisenPrincess/9 WeenieDefaults/Chest/05054 Chest.sql
- Database/Patches/2012-08-TheRisenPrincess/9 WeenieDefaults/Chest/05756 Chest.sql
- Database/Patches/2012-08-TheRisenPrincess/9 WeenieDefaults/Chest/45878 Chest.sql
- Fix probability on town stamp chests
- Fix text description on Yanshi chest drop
> Stamp chests fix

- Database/Patches/2009-01-ShiftingTactics/9 WeenieDefaults/Clothing/Clothing/39977 Gladiatorial Leggings.sql
- Database/Patches/2009-01-ShiftingTactics/9 WeenieDefaults/Clothing/Clothing/39978 Gladiatorial Tunic.sql
- Database/Patches/2009-01-ShiftingTactics/9 WeenieDefaults/Clothing/Clothing/39979 Ceremonial Leggings.sql
- Database/Patches/2009-01-ShiftingTactics/9 WeenieDefaults/Clothing/Clothing/39980 Ceremonial Tunic.sql
- Database/Patches/2009-01-ShiftingTactics/9 WeenieDefaults/Clothing/Clothing/39981 Protective Leggings.sql
- Database/Patches/2009-01-ShiftingTactics/9 WeenieDefaults/Clothing/Clothing/39982 Protective Tunic.sql
https://asheron.fandom.com/wiki/Shifting_Tactics
> Clothing items from 2009-01-ShiftingTactics

- Database/Patches/2009-02-UnfinishedBusiness/9 WeenieDefaults/Caster/Caster/40139 Tome of Caustics.sql
- Database/Patches/2009-02-UnfinishedBusiness/9 WeenieDefaults/Caster/Caster/40140 Tome of Flame.sql
- Database/Patches/2009-02-UnfinishedBusiness/9 WeenieDefaults/Caster/Caster/40141 Tome of Chill.sql
https://asheron.fandom.com/wiki/Tome_of_Chill
https://asheron.fandom.com/wiki/Tome_of_Caustics
https://asheron.fandom.com/wiki/Tome_of_Flame
> Tome casters from 2009-02-UnfinishedBusiness

- Database/Patches/2010-08-QuietBeforeTheStorm/6 LandBlockExtendedData/2170.sql
- Database/Patches/2010-08-QuietBeforeTheStorm/9 WeenieDefaults/Misc/43142 Ornate Gear Marker.sql
- Database/Patches/2010-08-QuietBeforeTheStorm/9 WeenieDefaults/Vendor/43144 Lintareal.sql
https://asheron.fandom.com/wiki/Lintareal
> Lintareal - 2010-08-QuietBeforeTheStorm

- Database/Patches/2007-10-Masked Memories/9 WeenieDefaults/Misc/36518 Colosseum Coin.sql
Change from generic to stackable
Add StackUnitEncumbrance and StackUnitValue from PCAP
Remove placement position
Remove weenie_properties_bool fields
> Make colo coin stackable, cleanup weenie

- Database/Patches/2007-03-AncientEnemies/9 WeenieDefaults/Generic/80006 Graveyard Master Gen.sql
- Set probability to -1 for both entries to fix log spam
> Update Graveyard Master Generator

- Database/Patches/2011-01-LearningFromExperience/9 WeenieDefaults/SQL/Creature/Human/24248 Royal Guard.sql
- Update XP rewards given by Royal Guard (Olthoi Weapons Quest) to Learning From Experience patch ( https://asheron.fandom.com/wiki/Olthoi_Weapons_Quest#Update_History )
> Update XP rewards given by Royal Guard

- Database/Patches/2010-06-ShiftingGears/6 LandBlockExtendedData/5465.sql
- Database/Patches/2010-06-ShiftingGears/9 WeenieDefaults/Portal/01013 Destroyed Portal to Arwic.sql
- Database/Patches/2010-06-ShiftingGears/9 WeenieDefaults/Portal/01016 Destroyed Eastham Portal.sql
- Database/Patches/2010-06-ShiftingGears/9 WeenieDefaults/Portal/01017 Destroyed Glenden Wood Portal.sql
- Database/Patches/2010-06-ShiftingGears/9 WeenieDefaults/Portal/01018 Destroyed Portal to Hebian-To.sql
- Database/Patches/2010-06-ShiftingGears/9 WeenieDefaults/Portal/01022 Destroyed Mayoi Portal.sql
- Database/Patches/2010-06-ShiftingGears/9 WeenieDefaults/Portal/01023 Destroyed Qalaba'r Portal.sql
- Database/Patches/2010-06-ShiftingGears/9 WeenieDefaults/Portal/01025 Destroyed Portal to Rithwic.sql
- Database/Patches/2010-06-ShiftingGears/9 WeenieDefaults/Portal/01026 Destroyed Portal to Samsur.sql
- Database/Patches/2010-06-ShiftingGears/9 WeenieDefaults/Portal/01032 Destroyed Portal to Zaikhal.sql
- Database/Patches/2010-06-ShiftingGears/9 WeenieDefaults/Portal/04036 Destroyed Uziz Portal.sql
- Database/Patches/2010-06-ShiftingGears/9 WeenieDefaults/Portal/04037 Destroyed Baishi Portal.sql
- Database/Patches/2010-06-ShiftingGears/9 WeenieDefaults/Portal/04038 Destroyed Tufa Portal.sql
- Database/Patches/2010-06-ShiftingGears/9 WeenieDefaults/Portal/04042 Destroyed Plateau Portal.sql
- Database/Patches/2010-06-ShiftingGears/9 WeenieDefaults/Portal/06086 Destroyed Portal to Neydisa Castle.sql
- Update older portal wcids to be Destroyed Portals
- Update town portals in Sanctum Residential Halls to use the newer, not destroyed portal wcids
> Destroy, Destroy, Portals

- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Statue/25720 Tree.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Statue/25723 Tree.sql
- Two tree NPCs updated from PY16 data, with motiontable entries from PCAP data, per bug report and fix discussed in ACE bugs Discord channel
> Update motiontable DIDs on trees

- Database/Patches/2005-08-FriendAndFoe/9 WeenieDefaults/Creature/Golem/70037 Blood Golem.sql
- Fix missing CombatTable entry
> Blood Golem

- Database/Patches/2005-08-FriendAndFoe/9 WeenieDefaults/Creature/Human/31841 Chef Jonus.sql
Add , (31841,  19, False) /* Attackable */
> Update 31841 Chef Jonus.sql

- Database/Patches/2009-10-GearsOfChange/4 CraftTable/8384 Recipe Major Armature Applied Step3.sql
Update salvage type from tinker to imbue.
> Update 8384 Recipe Major Armature Applied Step3.sql

- Database/Patches/2007-07-IntelligentDesigns/9 WeenieDefaults/MeleeWeapon/80020 Club of Undead Bashing.sql
Fix dmg variance and proc rate
https://asheron.fandom.com/wiki/Club_of_Undead_Bashing
> Update 80020 Club of Undead Bashing.sql

- Database/Patches/2005-10-TricksAndTreats/9 WeenieDefaults/Creature/Human/28979 Camryn, Nuhmudira's Student.sql
- Database/Patches/2005-10-TricksAndTreats/B GameEventDefDB/EventRoadsBegin.sql
- Database/Patches/2005-10-TricksAndTreats/B GameEventDefDB/EventRoadsEnd.sql
- Switch the active event from EventRoadsBegin to EventRoadsEnd to make Camryn the active NPC in Xi Ru's Chapel
- Restore ordering of emote table for Camryn but maintain issuing the Gem of Arcane Corruption
> Event roads switch

- Database/Patches/2005-08-FriendAndFoe/9 WeenieDefaults/Chest/31298 Chest.sql
- Prevent Fiun Gaya's chest, containing the hatchet, from locking on first reset
> Gayas chest

- Database/Patches/2011-05-LostCityOfNeftet/9 WeenieDefaults/Ammunition/44213 Burning Sands Atlatl Dart.sql
> Update 44213 Burning Sands Atlatl Dart.sql

- Database/Patches/2005-08-FriendAndFoe/9 WeenieDefaults/Creature/Human/31842 Hinkel.sql
- Add missing Attackable false bool to 31842 Hinkel
Reported by discord user **ethereal**
> Update 31842 Hinkel.sql

- Database/Patches/2009-03-WhoWatchesTheVirindi/9 WeenieDefaults/Creature/Human/40462 Rare Exchanger.sql
- Database/Patches/2009-03-WhoWatchesTheVirindi/9 WeenieDefaults/Creature/Human/40463 Rare Exchanger.sql
- Database/Patches/2009-03-WhoWatchesTheVirindi/9 WeenieDefaults/Creature/Human/40464 Rare Exchanger.sql
- Database/Patches/2009-05-SecretsOfTheApostates/6 LandBlockExtendedData/8090.sql
- Database/Patches/2009-05-SecretsOfTheApostates/6 LandBlockExtendedData/BB9F.sql
- Database/Patches/2009-05-SecretsOfTheApostates/6 LandBlockExtendedData/E44D.sql
- Database/Patches/2009-05-SecretsOfTheApostates/8 QuestDefDB/PaidComponentExchanger.sql
- Database/Patches/2009-05-SecretsOfTheApostates/9 WeenieDefaults/Creature/Human/40770 Component Exchanger.es
- Database/Patches/2009-05-SecretsOfTheApostates/9 WeenieDefaults/Creature/Human/40770 Component Exchanger.sql
https://asheron.fandom.com/wiki/Component_Exchanger
> Component Exchanger - 2009-05-SecretsOfTheApostates

- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Human/48777 Grularr Wa'ydo.sql
Dress npc and weenie cleanup from pcap
> Update 48777 Grularr Wa'ydo.sql

- Database/Patches/2012-02-MasterOfArms/9 WeenieDefaults/MeleeWeapon/27451 Gibbering Claw.sql
Update from base to EOR
DMG from 20 -> 48
Change WeaponSkill from 13 (UA) to 46 (FW)
Change WieldSkillType from 13 (UA) to 46 (FW)
Add WeaponType 1 - UA
https://asheron.fandom.com/wiki/Gibbering_Claw
> Create 27451 Gibbering Claw.sql

- Database/Patches/2010-07-FillingInTheBlanks/8 QuestDefDB/MonthlyQuestBiWeeklyOne0710.sql
- Database/Patches/2010-07-FillingInTheBlanks/8 QuestDefDB/MonthlyQuestMonthlyOne0710.sql
- Database/Patches/2010-07-FillingInTheBlanks/9 WeenieDefaults/Creature/Human/43028 Ansar El-Kerdany.es
- Database/Patches/2010-07-FillingInTheBlanks/9 WeenieDefaults/Creature/Human/43028 Ansar El-Kerdany.sql
- Database/Patches/2010-07-FillingInTheBlanks/9 WeenieDefaults/Creature/Human/43029 Niccolo De Luca.sql
- Database/Patches/2010-07-FillingInTheBlanks/9 WeenieDefaults/Creature/Human/43030 Esmond Fielding.es
- Database/Patches/2010-07-FillingInTheBlanks/9 WeenieDefaults/Creature/Human/43030 Esmond Fielding.sql
- Database/Patches/2012-09-LessonsFromThePast/9 WeenieDefaults/Gem/Gem/46755 Contract for Stipend_ General.sql
- Database/Patches/2013-09-TheQuestForFreedom/9 WeenieDefaults/SQL/Gem/Gem/44820 Contract for Quest of the Month_ Weekly #1.sql
- Database/Patches/2013-09-TheQuestForFreedom/9 WeenieDefaults/SQL/Gem/Gem/44821 Contract for Quest of the Month_ Weekly #2.sql
- Database/Patches/2013-09-TheQuestForFreedom/9 WeenieDefaults/SQL/Gem/Gem/44822 Contract for Quest of the Month_ Weekly #3.sql
This PR adds, 
Ansar El-Kerdany w/ quest & contract
Esmond Fielding w/ quest & contract
Niccolo De Luca npc & contract only
Add bonded true and isSellable false to 46755 Contract for Stipend_ General.sql
> Monthly Explorer Society Quests

- Database/Patches/2011-10-CloakOfDarkness/9 WeenieDefaults/Creature/Human/11809 Lieutenant Kenneth.sql
- Database/Patches/2011-10-CloakOfDarkness/9 WeenieDefaults/Creature/Human/11810 Ufet, Prophet of Blades.sql
- Database/Patches/2011-10-CloakOfDarkness/9 WeenieDefaults/Creature/Human/11811 Shosa Kiroji Matanui.sql
- Fixed a missing reward for Assault Greatsword on 11811.
- Updated rewards with end of retail Gambling Tokens.
> Assault Weapon NPC Emote Table Updates

- Database/Patches/2009-10-GearsOfChange/9 WeenieDefaults/Portal/41590 Gearknight Lord's Tower.sql
> Update 41590 Gearknight Lord's Tower.sql

- Database/Patches/2009-10-GearsOfChange/9 WeenieDefaults/Portal/41594 Gearknight Lord's Tower.sql
> Update 41594 Gearknight Lord's Tower.sql

- Database/Patches/2005-07-ThroneOfDestiny/6 LandBlockExtendedData/8090.sql
- Database/Patches/2005-07-ThroneOfDestiny/6 LandBlockExtendedData/BB9F.sql
- Database/Patches/2005-07-ThroneOfDestiny/6 LandBlockExtendedData/E44D.sql
- Database/Patches/2017-01-EndOfRetail/6 LandBlockExtendedData/SQL/2B11.sql
This pr adds, 
Missing Garbage Barrel to Candeth Keep
Missing Garbage Barrel to the three MFK Areas
> Add missing garbage barrels to mfk area and candeth keep

- Database/Patches/2011-05-LostCityOfNeftet/9 WeenieDefaults/Creature/Anekshay/48801 Janthef.sql
- Database/Patches/2011-05-LostCityOfNeftet/9 WeenieDefaults/Creature/Anekshay/48814 Janthef.sql
- Database/Patches/2011-05-LostCityOfNeftet/9 WeenieDefaults/Creature/Anekshay/48815 Janthef.sql
For whatever reason this worked pre- 2991 PR. Needed to go back and add Max/Init INT values.
> Update Janthefs Gen

- Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/04076 Empyrean Enlightenment.sql
Update to add +60 points instead of +30
> Update 04076 Empyrean Enlightenment.sql

- Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/04062 Empyrean Aegis.sql
> Update 04062 Empyrean Aegis.sql

- Database/Patches/2011-06-StiringsInTheDark/6 LandBlockExtendedData/D777.sql
- Database/Patches/2011-06-StiringsInTheDark/6 LandBlockExtendedData/DB74.sql
- Database/Patches/2011-06-StiringsInTheDark/8 QuestDefDB/PickedUpDanshaKiBelongings.sql
- Database/Patches/2011-06-StiringsInTheDark/9 WeenieDefaults/Creature/Human/06847 Yu Vuo-Ki.sql
- Database/Patches/2011-06-StiringsInTheDark/9 WeenieDefaults/Creature/Human/06848 Dansha-Ki.sql
- Database/Patches/2011-06-StiringsInTheDark/9 WeenieDefaults/Generic/Misc/06879 Dansha-Ki's Belongings.sql
- Update Yu Vuo-Ki's placement and make her a permanent spawn
- Update Dansha-Ki's spawn to be permanent
- Add pickup timer to Dansha-Ki''s Belongings
- Remove some unneeded event start/stop
> Dryreach rescue

- Database/Patches/2006-09-ComeWhatFollows/9 WeenieDefaults/Creature/Human/33966 Belinda du Loc.sql
- Database/Patches/2006-09-ComeWhatFollows/9 WeenieDefaults/MeleeWeapon/33940 Enhanced Crystal Sword.sql
Updated Belinda Du Loc to add the Enhanced Crystal Sword exchange for the crystal sword as well as the XP reward for giving her back the Enhanced sword.
https://asheron.fandom.com/wiki/Enhanced_Crystal_Sword
http://acpedia.org/wiki/Enhanced_Crystal_Sword
> Belinda Du Loc update to patch Come what Follows 09/2006

- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Clothing/Armor/25840 Snarl's Jerkin.sql
Someone updated ValidLocations but failed to also update ClothingPriority to match.
> Update 25840 Snarl's Jerkin.sql

- Database/Patches/2008-03-FoolishAmbition/9 WeenieDefaults/MeleeWeapon/35377 Replica BloodScorch.sql
add
, (35377, 138,       2) /* SlayerDamageBonus */
, (35377, 156,    0.05) /* ProcSpellRate */
update
, (35377, 147,     0.3) /* CriticalFrequency */   from 0.25
remove 
, (35377,  10,    1048576) /* CurrentWieldedLocation - MeleeWeapon */
> Update 35377 Replica BloodScorch.sql

- Database/Patches/2009-10-GearsOfChange/9 WeenieDefaults/MeleeWeapon/40652 Great BloodScorch.sql
add
, (40652, 138,       2) /* SlayerDamageBonus */
, (40652, 156,    0.05) /* ProcSpellRate */
update
, (40652, 147,     0.3) /* CriticalFrequency */ from 0.25
remove 
, (40652,  10,   33554432) /* CurrentWieldedLocation - TwoHanded */
> Update 40652 Great BloodScorch.sql

- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Vendor/20205 Apprentice Scrivener of Creature Magic.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Vendor/20206 Apprentice Scrivener of Creature Magic.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Vendor/20207 Master Scrivener of Creature Magic.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Vendor/20208 Grand Master Scrivener of Creature Magic.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Vendor/20209 Journeyman Scrivener of Creature Magic.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Vendor/20210 Scrivener of Creature Magic.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Vendor/30014 Grand Master Scrivener of Life Magic.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Vendor/30023 Master Scrivener of Creature Magic.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Vendor/30024 Grand Master Scrivener of Creature Magic.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Vendor/30026 Scrivener of Creature Magic.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Vendor/49598 Scrivener of Creature Magic.sql
Update Scriveners to match EOR/PCAPS
> Update Scriveners to match EOR/PCAPS

- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Vendor/30038 Archmage Luchessa du Lamiere.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Vendor/30067 Scribe Copiara Parolinnis.sql
- Database/Patches/2005-08-FriendAndFoe/9 WeenieDefaults/Vendor/01387 Merchant.sql
- Database/Patches/2009-10-GearsOfChange/9 WeenieDefaults/Vendor/Creature/00656 Farnum the Provisioner.sql
- Database/Patches/2009-10-GearsOfChange/9 WeenieDefaults/Vendor/Creature/31955 Janus Roma the Shopkeep.sql
Misc Vendor Updates to EOR/PCAPS
> Misc Vendor Updates to EOR/PCAPS

- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Vendor/Creature/00654 Degel Parson the Scrivener.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Vendor/Creature/00666 Wylreda the Scribe.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Vendor/Creature/00675 Magus Gondibyr Langarl.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Vendor/Creature/00717 Scribe Renald the Younger.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Vendor/Creature/00731 Ystig Marson the Barkeeper.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Vendor/Creature/00819 Kai Go-Sou the Scribe.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Vendor/Creature/00840 Brother Gonun the Scribe.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Vendor/Creature/00869 Fenza Tan the Scribe.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Vendor/Creature/00970 Gailadu the Scribe.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Vendor/Creature/00981 Sutaiya bint Yil the Scribe.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Vendor/Creature/00992 Jizal al-Nurla the Scribe.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Vendor/Creature/01044 Wasifa al-Kani the Scribe.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Vendor/Creature/01056 Uthab ibn Yafij the Scribe.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Vendor/Creature/01821 Sifida bint Naril the Scribe.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Vendor/Creature/01832 Barshid al-Juhir the Scribe.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Vendor/Creature/02258 Denki Sokuto the Scribe.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Vendor/Creature/02299 Hiruhi Fensen the Scribe.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Vendor/Creature/04443 Gylfolma the Scribe.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Vendor/Creature/04545 Tekai Shou the Scribe.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Vendor/Creature/04554 Scribe Lashi Oi.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Vendor/Creature/04684 Bashkiya the Scribe.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Vendor/Creature/04701 Scribe Tashwi ibn Sayat.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Vendor/Creature/06861 Scribe Muhiza bint Murqidh.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Vendor/Creature/08439 Natalie the Scribe.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Vendor/Creature/11385 Yusnar ibn Lomaq the Grocer.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Vendor/Creature/11393 Brother Samir ibn Lomaq the Monk.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Vendor/Creature/24590 Odvik the Inn Keeper.sql
Add The New Alchemy - 24855 to vendors to match EOR/PCAPS
> Add The New Alchemy to vendors to match EOR/PCAPS

- Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/Creature/Golem/27254 Copper Golem Kingpin.sql
- Update Copper Golem Kingpin's minions to be Copper Golems
> Update Copper Golem Kingpin

- Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/05753 Cloaked in Skill.sql
Thanks to @OptimShi for providing these values
EnchantmentManager update in code repo still pending
> updating Cloaked in Skill to match retail pcap

- Database/Patches/2010-11-FromDarknessLight/6 LandBlockExtendedData/0139.sql
- Database/Patches/2010-11-FromDarknessLight/6 LandBlockExtendedData/0148.sql
- Database/Patches/2010-11-FromDarknessLight/6 LandBlockExtendedData/014A.sql
- Database/Patches/2010-11-FromDarknessLight/6 LandBlockExtendedData/01B5.sql
- Database/Patches/2010-11-FromDarknessLight/6 LandBlockExtendedData/01D4.sql
- Database/Patches/2010-11-FromDarknessLight/6 LandBlockExtendedData/01D5.sql
- Database/Patches/2010-11-FromDarknessLight/6 LandBlockExtendedData/526F.sql
- Database/Patches/2010-11-FromDarknessLight/6 LandBlockExtendedData/536A.sql
- Database/Patches/2010-11-FromDarknessLight/6 LandBlockExtendedData/564D.sql
- Database/Patches/2010-11-FromDarknessLight/6 LandBlockExtendedData/564E.sql
- Database/Patches/2010-11-FromDarknessLight/6 LandBlockExtendedData/6448.sql
- Database/Patches/2010-11-FromDarknessLight/6 LandBlockExtendedData/AD7D.sql
- Database/Patches/2010-11-FromDarknessLight/6 LandBlockExtendedData/D836.sql
- Update Iron Golem spawns to Copper Golems
> Update locations for Iron Golem change

- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Shadow/25663 Void Knight.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Shadow/25665 Wretched.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Shadow/31280 Twisted Shadow.sql
- Cleanup
- Rebalance Wretched and Void Knight skills for increased primary attributes
> Shadows three

- Database/Patches/2007-10-Masked Memories/9 WeenieDefaults/Gem/Misc/36365 Chimeric Axe of the Quiddity Summoning Gem.sql
- Database/Patches/2007-10-Masked Memories/9 WeenieDefaults/Gem/Misc/36366 Chimeric Bow of the Quiddity Summoning Gem.sql
- Database/Patches/2007-10-Masked Memories/9 WeenieDefaults/Gem/Misc/36367 Chimeric Balister of the Quiddity Summoning Gem.sql
- Database/Patches/2007-10-Masked Memories/9 WeenieDefaults/Gem/Misc/36368 Chimeric Dagger of the Quiddity Summoning Gem.sql
- Database/Patches/2007-10-Masked Memories/9 WeenieDefaults/Gem/Misc/36369 Chimeric Mace of the Quiddity Summoning Gem.sql
- Database/Patches/2007-10-Masked Memories/9 WeenieDefaults/Gem/Misc/36370 Chimeric Eye of the Quiddity Summoning Gem.sql
- Database/Patches/2007-10-Masked Memories/9 WeenieDefaults/Gem/Misc/36371 Chimeric Lance of the Quiddity Summoning Gem.sql
- Database/Patches/2007-10-Masked Memories/9 WeenieDefaults/Gem/Misc/36372 Chimeric Stave of the Quiddity Summoning Gem.sql
- Database/Patches/2007-10-Masked Memories/9 WeenieDefaults/Gem/Misc/36373 Chimeric Blade of the Quiddity Summoning Gem.sql
- Database/Patches/2007-10-Masked Memories/9 WeenieDefaults/Gem/Misc/36374 Chimeric Fist of the Quiddity Summoning Gem.sql
- Database/Patches/2007-10-Masked Memories/9 WeenieDefaults/Gem/Misc/41855 Chimeric Two Handed Blade of the Quiddity Summoning Gem.sql
> Fix typos in chimeric quiddity gems

- Database/Patches/2005-09-UnderCoverOfNight/9 WeenieDefaults/Creature/Moarsman/31914 Scummy Moarsman.sql
> Update 31914 Scummy Moarsman.sql

- Database/Patches/2017-01-EndOfRetail/6 LandBlockExtendedData/SQL/E632.sql
Move Tai Wo from Tou-Tou to Mayoi
https://asheron.fandom.com/wiki/Tai_Wo
> Move Tai Wo from Tou-Tou to Mayoi

- Database/Patches/2007-06-Evolution/6 LandBlockExtendedData/E53D.sql
- Database/Patches/2007-06-Evolution/9 WeenieDefaults/Creature/Tusker/35776 Ook.sql
Recreate our friend Ook,
https://asheron.fandom.com/wiki/Ook
> Ook - 2007-06-Evolution

- Database/Patches/2006-02-AChangeInTactics/8 QuestDefDB/BraceletOfPassage.sql
- Database/Patches/2006-02-AChangeInTactics/9 WeenieDefaults/Clothing/Jewelry/32703 Bracelet of Passage.sql
- Database/Patches/2006-02-AChangeInTactics/9 WeenieDefaults/Portal/32712 Castle Pietrus.sql
- Add Portal to Castle Pietrus
- Modify Bracelet of Passage to activate portal, when worn
> Update portal for Castle Pietrus

- Database/Patches/2005-12-ThroughSacrificeStrength/9 WeenieDefaults/Creature/Unsorted/32397 Antius Blackmoor Memorial.sql
- Update Antius Blackmoor Memorial statue to display createlist items correctly
> Update Antius Blackmoor Memorial statue

- Database/Patches/2010-07-FillingInTheBlanks/9 WeenieDefaults/Caster/43043 Paradox-touched Olthoi Wand.sql
- Database/Patches/2010-07-FillingInTheBlanks/9 WeenieDefaults/Caster/43056 Paradox-touched Olthoi Wand.sql
- Database/Patches/2010-07-FillingInTheBlanks/9 WeenieDefaults/Clothing/Shields/35887 Paradox-touched Olthoi Shield.sql
- Database/Patches/2010-07-FillingInTheBlanks/9 WeenieDefaults/MeleeWeapon/35913 Paradox-touched Olthoi Axe.sql
- Database/Patches/2010-07-FillingInTheBlanks/9 WeenieDefaults/MeleeWeapon/35914 Paradox-touched Olthoi Katar.sql
- Database/Patches/2010-07-FillingInTheBlanks/9 WeenieDefaults/MeleeWeapon/35915 Paradox-touched Olthoi Spear.sql
- Database/Patches/2010-07-FillingInTheBlanks/9 WeenieDefaults/MeleeWeapon/35916 Paradox-touched Olthoi Sword.sql
- Database/Patches/2010-07-FillingInTheBlanks/9 WeenieDefaults/MeleeWeapon/43041 Paradox-touched Olthoi Staff.sql
- Database/Patches/2010-07-FillingInTheBlanks/9 WeenieDefaults/MeleeWeapon/43042 Paradox-touched Olthoi Great Sword.sql
- Database/Patches/2010-07-FillingInTheBlanks/9 WeenieDefaults/MeleeWeapon/43046 Paradox-touched Olthoi Dagger.sql
- Database/Patches/2010-07-FillingInTheBlanks/9 WeenieDefaults/MeleeWeapon/43047 Paradox-touched Olthoi Mace.sql
- Database/Patches/2010-07-FillingInTheBlanks/9 WeenieDefaults/MissileLauncher/35912 Paradox-touched Olthoi Atlatl.sql
- Database/Patches/2010-07-FillingInTheBlanks/9 WeenieDefaults/MissileLauncher/43044 Paradox-touched Olthoi Bow.sql
- Database/Patches/2010-07-FillingInTheBlanks/9 WeenieDefaults/MissileLauncher/43045 Paradox-touched Olthoi Crossbow.sql
for reviewers, 
slayer damage
spell proc rate
crit frequency
> Paradox-touched Olthoi Weapons and Shield

- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Food/Food/28833 Gonjoku's Mana Infusion.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Food/Food/29106 Bobo's Stout.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Food/Food/29108 Tusker Pus.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Food/Food/29109 Tusker Spit Ale.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Food/Misc/27670 Distilled Mana Potion.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Food/Misc/30107 Refreshing Elixir.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Food/Misc/31196 Mana Potion.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Food/Misc/31197 Stamina Potion.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Food/Misc/31198 Potion of Healing.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Food/Misc/38794 Black Market Health Elixir.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Food/11140 Olthoi Egg.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Food/27669 Tumerok Salted Meat.sql
Update some food items to pcaps/eor
http://ac.yotesfan.com/compare/food.php
> Update some food items to pcaps/eor

- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Human/06873 Ulgrim the Unpleasant.sql
Add Marshmallow Eep emotes to Ulgrim the Unpleasant
https://asheron.fandom.com/wiki/Larry%27s_Ruined_Garden
> Add Marshmallow Eep emotes to 06873 Ulgrim the Unpleasant.sql

- Database/Patches/2014-02-Spring2014/3 TreasureTable/Gauntlet Chest-2960.sql
- Database/Patches/2014-02-Spring2014/9 WeenieDefaults/Chest/52794 Gauntlet Vault.sql
- Database/Patches/2014-02-Spring2014/9 WeenieDefaults/Jewelry/52785 Red Society Band.sql
- Database/Patches/2014-02-Spring2014/9 WeenieDefaults/Jewelry/52786 Green Society Band.sql
- Database/Patches/2014-02-Spring2014/9 WeenieDefaults/Jewelry/52787 Brown Society Locket.sql
- Database/Patches/2014-02-Spring2014/9 WeenieDefaults/Jewelry/52788 Yellow Society Locket.sql
- Database/Patches/2014-02-Spring2014/9 WeenieDefaults/Jewelry/52789 Purple Society Band.sql
- Database/Patches/2014-02-Spring2014/9 WeenieDefaults/Jewelry/52790 Blue Society Band.sql
- Database/Patches/2014-02-Spring2014/9 WeenieDefaults/Key/52784 Gauntlet Vault Key.sql
Vault, Vault Key, Vault DT profile (2960), Society Jewelry.
> Gauntlet Vault

- Database/Patches/2010-07-FillingInTheBlanks/9 WeenieDefaults/Clothing/Armor/43050 Knorr Academy Girth.sql
Knorr Girth dropped on ground was sleeves, Fixed to show as girth now
> Update 43050 Knorr Academy Girth.sql

- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37191 Olthoi Gauntlets.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37193 Olthoi Girth.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37194 Olthoi Greaves.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37199 Olthoi Helm.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37204 Olthoi Pauldrons.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37211 Olthoi Sollerets.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37212 Olthoi Tassets.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37213 Olthoi Bracers.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37216 Olthoi Breastplate.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Generic/Armor/37291 Olthoi Shield.sql
This fixes an issue with lootgen
> Add version to Olthoi Armor

- Database/Patches/2006-07-TowardAncientShores/9 WeenieDefaults/Generic/Generator/70113 Lesser Dark Isle Generator.sql
- Database/Patches/2006-07-TowardAncientShores/9 WeenieDefaults/Generic/Generator/70114 Higher dark Isle Generator.sql
- Database/Patches/2006-07-TowardAncientShores/9 WeenieDefaults/Stackable/38613 Black Coral.sql
- Database/Patches/2008-08-AncientPowers/8 QuestDefDB/TaskDIBlackCoralComplete.sql
- Database/Patches/2008-08-AncientPowers/8 QuestDefDB/TaskDIBlackCoralStarted.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Creature/Human/38602 Hidoshi Kawara ES.es
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Creature/Human/38602 Hidoshi Kawara.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Creature/Human/38605 Manto Sakara ES.es
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Creature/Human/38605 Manto Sakara.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Creature/Human/38608 Daisei Chirana ES.es
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Creature/Human/38608 Daisei Chirana.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Gem/Gem/44487 Contract for Black Coral Collection.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Gem/Gem/44539 Contract for Black Coral Collection.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Gem/Gem/44548 Contract for Black Coral Collection.sql
Add black coral weenie
Add black coral to DI generators
Add 3 society NPCs
Add quest entries
Add contracts
> Black Coral Collection - Dark Isle Society Tasks

- Database/Patches/2009-10-GearsOfChange/9 WeenieDefaults/Creature/GearKnight/41551 Iron Blade Overseer.sql
- Database/Patches/2009-10-GearsOfChange/9 WeenieDefaults/Creature/Unknown/70350 Large Shattered Aetherium Core.sql
- Database/Patches/2009-10-GearsOfChange/9 WeenieDefaults/Generic/Misc/70350 Large Shattered Aetherium Core.sql
- Database/Patches/2009-10-GearsOfChange/9 WeenieDefaults/MeleeWeapon/41611 Greatsword of Iron Flame.sql
- Database/Patches/2009-10-GearsOfChange/9 WeenieDefaults/Stackable/41541 Shattered Aetherium Core Sample.sql
Add Overseer's weapon. Fix drop for core.
> Update Iron Blade Overseer

- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Knathtead/29310 K'nath D'dot.sql
remove
, (29310, 101, True ) /* CanGenerateRare */
, (29310, 102, True ) /* CorpseGeneratedRare */;
> Update 29310 K'nath D'dot.sql

- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/CraftTool/TinkeringMaterial/20980 Salvaged Alabaster.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/CraftTool/TinkeringMaterial/20981 Salvaged Armoredillo Hide.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/CraftTool/TinkeringMaterial/20982 Salvaged Bronze.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/CraftTool/TinkeringMaterial/20983 Salvaged Ceramic.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/CraftTool/TinkeringMaterial/20991 Salvaged Reedshark Hide.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/CraftTool/TinkeringMaterial/20993 Salvaged Steel.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/CraftTool/TinkeringMaterial/20995 Salvaged Wool.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/CraftTool/TinkeringMaterial/21045 Salvaged Copper.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/CraftTool/TinkeringMaterial/21061 Salvaged Marble.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/CraftTool/TinkeringMaterial/21077 Salvaged Silver.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/CraftTool/TinkeringMaterial/29581 Salvaged Steel.sql
Files copied from https://github.com/ACEmulator/ACE-World-16PY/tree/175a073a3ab24e8fe87ed5c2ad714f3d9557de02/Database/3-Core/9%20WeenieDefaults/SQL/CraftTool/TinkeringMaterial
Only change is updating TargetType to match https://github.com/ACEmulator/ACE-PCAP-Exports/tree/4ed5b7d65b1f55b0f979c8d1320d114ce3068b26/Database/3-Core/9%20WeenieDefaults/SQL/CraftTool/TinkeringMaterial
Armor -> Vestements
> updating steel salvage profile TargetTypes to match end of retail

- Database/Patches/2011-05-LostCityOfNeftet/6 LandBlockExtendedData/8866.sql
- Database/Patches/2011-08-ARisingDarkness/9 WeenieDefaults/Creature/A'nekshay/44637 Sha-dekanma ES.es
- Database/Patches/2011-08-ARisingDarkness/9 WeenieDefaults/Creature/A'nekshay/44637 Sha-dekanma.sql
> Add A'nekshay Slayer Gem NPC

- Database/Patches/2005-08-FriendAndFoe/9 WeenieDefaults/Vendor/01387 Merchant.sql
- Add missing Torn Journal Page - Page 2
> Update 01387 Merchant.sql

- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/MeleeWeapon/42662 Chitin Cracker.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/MeleeWeapon/42663 Revenant's Scythe.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/MeleeWeapon/42664 Spear of Lost Truths.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/MeleeWeapon/42665 Itaka's Naginata.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/MeleeWeapon/42666 Decapitator's Blade.sql
> Update Rare 2 handers

- Database/Patches/2011-05-LostCityOfNeftet/9 WeenieDefaults/Ammunition/44214 Burning Sands Bolt.sql
> Update 44214 Burning Sands Bolt.sql

- Database/Patches/2011-05-LostCityOfNeftet/9 WeenieDefaults/Ammunition/44212 Burning Sands Arrow.sql
> Update 44212 Burning Sands Arrow.sql

- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/MeleeWeapon/MeleeWeapon/45113 Hammer.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/MeleeWeapon/MeleeWeapon/45114 Acid Hammer.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/MeleeWeapon/MeleeWeapon/45115 Lightning Hammer.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/MeleeWeapon/MeleeWeapon/45116 Flaming Hammer.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/MeleeWeapon/MeleeWeapon/45117 Frost Hammer.sql
- Add missing DefaultCombatStyle - OneHanded to finesse hammers
> Fix finesse hammers

- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Gromnie/01614 Jade Gromnie.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Gromnie/01615 Ash Gromnie.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Gromnie/11526 Ebon Gromnie.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Gromnie/11527 Sable Gromnie.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Gromnie/23551 Adolescent Ash Gromnie.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Gromnie/25596 Amethyst Gromnie.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Gromnie/25597 Emerald Gromnie.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Gromnie/25598 Ruby Gromnie.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Gromnie/25599 Sapphire Gromnie.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Gromnie/27710 Brass Gromnie.sql
- Update PaletteTemplate on five Gromnies
- Add five missing Gromnies
> Update Gromnie palette

- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Clothing/Jewelry/30360 Ring of Channeling.sql
fix icon
https://asheron.fandom.com/wiki/Ring_of_Channeling
> Update 30360 Ring of Channeling.sql

- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Food/Food/36445 Chocolate Gromnie.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Food/Food/39108 Chocolate Gromnie.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Key/Key/09477 Monty's Golden Key.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Key/Key/09478 Arshid's Golden Key.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Key/Key/09479 Gan-Zo's Golden Key.sql
Just in case something gives them out
> Update Old Casino Keys

- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Gem/Gem/30220 Astyrian's Jewel.sql
- Database/Patches/2010-12-DeadOfWinter/9 WeenieDefaults/Gem/43189 Gem of Knowledge.sql
- Database/Patches/2011-10-CloakOfDarkness/9 WeenieDefaults/Gem/Gem/30800 Black Glass Array.sql
- Database/Patches/2011-10-CloakOfDarkness/9 WeenieDefaults/Gem/Gem/44719 Gem of Lesser Luminance.sql
- Database/Patches/2011-10-CloakOfDarkness/9 WeenieDefaults/Gem/Gem/44720 Gem of Greater Luminance.sql
- Database/Patches/2012-08-TheRisenPrincess/9 WeenieDefaults/Gem/Gem/52300 Contract for Kill_ Tou-Tou Shadow Flyers.sql
- Database/Patches/2012-08-TheRisenPrincess/9 WeenieDefaults/Gem/Gem/52301 Contract for Kill_ Tou-Tou Grievver Shredders.sql
- Database/Patches/2012-08-TheRisenPrincess/9 WeenieDefaults/Gem/Gem/52302 Contract for Kill_ Tou-Tou Devourer Marguls.sql
- Database/Patches/2012-08-TheRisenPrincess/9 WeenieDefaults/Gem/Gem/52303 Contract for Kill_ Tou-Tou Shadows.sql
- Database/Patches/2012-08-TheRisenPrincess/9 WeenieDefaults/Gem/Gem/52304 Contract for Kill_ Tou-Tou Void Lords.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Gem/Food/11135 Vesayen Style Fried Olthoi Egg.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Gem/Food/11136 Fried Olthoi Egg.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Gem/Food/11137 Hard Boiled Olthoi Egg.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Gem/Gem/03696 Blue Gem.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Gem/Gem/05084 Calling Stone.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Gem/Gem/07316 Dansha-Ki's Gem of Portal Recall.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Gem/Gem/27512 Nanner Island Portal Gem.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Scroll/Writable/28933 Scroll of Arcanum Salvaging I.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Scroll/Writable/28935 Scroll of Arcanum Salvaging III.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Scroll/Writable/28936 Scroll of Arcanum Salvaging IV.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Scroll/Writable/28937 Scroll of Arcanum Salvaging V.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Scroll/Writable/28938 Scroll of Arcanum Salvaging VI.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Scroll/Writable/28939 Scroll of Arcanum Salvaging VII.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Scroll/Writable/28940 Scroll of Arcanum Enlightenment I.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Scroll/Writable/28942 Scroll of Arcanum Enlightenment III.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Scroll/Writable/28943 Scroll of Arcanum Enlightenment IV.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Scroll/Writable/28944 Scroll of Arcanum Enlightenment V.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Scroll/Writable/28945 Scroll of Arcanum Enlightenment VI.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Scroll/Writable/28946 Scroll of Arcanum Enlightenment VII.sql
> Misc weenie updates to EOR/PCAP

- Database/Patches/2005-07-ThroneOfDestiny/8 QuestDefDB/sishaltislithiskillcount.sql
- Database/Patches/2007-09-DarkMaterials/6 LandBlockExtendedData/8090.sql
- Database/Patches/2007-09-DarkMaterials/8 QuestDefDB/SishaltiSlithisKillCount.sql
- Database/Patches/2007-09-DarkMaterials/8 QuestDefDB/SishaltiSlithisKillTask.sql
- Database/Patches/2007-09-DarkMaterials/9 WeenieDefaults/Creature/Human/36233 Zava bint Laurma.es
- Database/Patches/2007-09-DarkMaterials/9 WeenieDefaults/Creature/Human/36233 Zava bint Laurma.sql
- Database/Patches/2007-09-DarkMaterials/9 WeenieDefaults/Creature/Slithis/24867 Sishalti Eye Stalk.sql
- Database/Patches/2007-09-DarkMaterials/9 WeenieDefaults/Creature/Slithis/24868 Sishalti Tendril.sql
- Database/Patches/2007-09-DarkMaterials/9 WeenieDefaults/Creature/Slithis/24869 Sishalti Tentacle.sql
- Moved the quest flags from the ToD folder to the month when the quests first appeared
- Updated Sishalti Eye Stalk, Tendril, and Tentacle to include kill quest string
- Added Zava bint Laurma (quest giver)
- Updated landblock 8090 to include Zava
> Add Sishalti Slithis Kill Task

- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Book/30985 Letter From Home.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Book/30986 Letter From Home.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Book/30987 Letter From Home.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Book/30988 Letter From Home.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Book/43018 Letter From Home.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Book/43019 Letter From Home.sql
Cleanup weenie / change to current weenie format
Update EncumbranceVal from 100 to 5 per EOR/PCAP
30985 and 30986 had incorrect book data, was switched
43018 was missing r at end of class name
> Cleanup letters from home

- Database/Patches/2006-04-ShiningRunesAndShadowedHands/8 QuestDefDB/RabbitHutchKeyPickupTimer.sql
Update from 13days to 20hrs, move to correct folder structure
https://asheron.fandom.com/wiki/Son_of_Pooky_Quest
> Update Son of Pooky to EOR quest timer

- Database/Patches/2005-07-ThroneOfDestiny/8 QuestDefDB/templeofxikminru.sql
change timer from 20 days to 20 hours per EOR
https://asheron.fandom.com/wiki/Aurulent_Key
https://asheron.fandom.com/wiki/The_Temple_of_Xik_Minru
> Update Aurulent Key timer for The Temple of Xik Minru to 20 hours

- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/MeleeWeapon/30601 Stiletto.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/MeleeWeapon/30602 Lightning Stiletto.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/MeleeWeapon/30603 Flaming Stiletto.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/MeleeWeapon/30604 Frost Stiletto.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/MeleeWeapon/30605 Acid Stiletto.sql
- Match AttackType to PCAP'ed data for stilettos and DamageType for non-elemental stiletto
- Bool, int, and float cleanup
> Fix Stiletto data points

- Database/Patches/2005-10-TricksAndTreats/9 WeenieDefaults/Container/32198 Pumpkin Backpack.sql
- Matched properties to Pack 136 wcid
> Update 32198 Pumpkin Backpack

- Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/Food/43504 Draught of Revitalization.sql
Mag log here, 
http://ac.yotesfan.com/weenies/items/43504
> Update 43504 Draught of Revitalization.sql

- Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/Creature/Wall/52283 Frozen Crystal.sql
Match PCAP, 
https://github.com/ACEmulator/ACE-PCAP-Dynamics-Exports/blob/831fb2c9d7d2a8ce0a52123e017c7c09a9651745/Database/3-Core/9%20WeenieDefaults/SQL/Creature/Unsorted/52283%20Frozen%20Crystal.sql
> Update 52283 Frozen Crystal.sql

- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/MeleeWeapon/06853 Rapier.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/MeleeWeapon/28498 Noble Rapier.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/MeleeWeapon/28997 Burun Slaying Rapier.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/MeleeWeapon/29933 Regal Rapier.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/MeleeWeapon/45104 Acid Rapier.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/MeleeWeapon/45105 Lightning Rapier.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/MeleeWeapon/45106 Flaming Rapier.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/MeleeWeapon/45107 Frost Rapier.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/MeleeWeapon/45395 Rapier.sql
- Match AttackType to PCAP'ed data for rapiers and DamageType for non-elemental stiletto
- Float cleanup
> Fix rapiers

- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/MeleeWeapon/30946 Poniard.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/MeleeWeapon/30947 Poniard.sql
- Match AttackType to PCAP'ed data for creature wielded poniards
- Property cleanup
> Fix Poniards

- Database/Patches/2013-10-ShatteredMasks/9 WeenieDefaults/Caster/52190 Casting Jack o' Lantern.sql
- Database/Patches/2013-10-ShatteredMasks/9 WeenieDefaults/Caster/52191 Casting Jack o' Lantern.sql
- Database/Patches/2013-10-ShatteredMasks/9 WeenieDefaults/Caster/52192 Casting Jack o' Lantern.sql
- Database/Patches/2013-10-ShatteredMasks/9 WeenieDefaults/Clothing/Armor/52201 Accursed Scarecrow Mask.sql
**Added**
52190 - Original Version
52191 - Flaming Version
52192 - Glowing Version
PCAP captured them at 10% MeleeD Wikis have it at 20%
> Added Pumpkin Casters / Mask

- Database/Patches/2013-09-TheQuestForFreedom/9 WeenieDefaults/SQL/Caster/Caster/03721 Orb of Black Fire.sql
Change
, (3721,   8,  100674114) /* Icon */
to
, (3721,   8,  100668730) /* Icon */
to match EOR/PCAP
This resolves, 
https://www.accpp.net/bug-report/b6275180-7669-440d-a140-e411f57d4bd7
> Update 03721 Orb of Black Fire.sql

- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Human/30974 Baby Thrungus.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Human/30975 Baby Thrungus.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Human/30976 Baby Thrungus.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Human/30977 Baby Thrungus.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Human/30978 Baby Thrungus.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Human/30980 Baby Thrungus.sql
attributes/vitals were pcapped here, 
https://github.com/ACEmulator/ACE-PCAP-Dynamics-Exports/blob/master/Database/3-Core/9%20WeenieDefaults/SQL/Creature/Thrungus/30976%20Baby%20Thrungus.sql
> Baby Thrungus fixes

- Database/Patches/2007-08-CorruptedSovereigns/9 WeenieDefaults/Creature/Paradox Olthoi/35888 Paradox-touched Olthoi Queen.sql
> Update 35888 Paradox-touched Olthoi Queen.sql

- Database/Patches/2007-02-RekindlingTheLight/3 TreasureTable/1005 Colo Vault.sql
this pr fixes https://github.com/ACEmulator/ACE-World-16PY-Patches/issues/689
> update colo vault to more closely match eor data

- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/ShallowsShark/07109 Shallows Devourer.sql
Correct color to match:
http://acpedia.org/wiki/Shallows_Devourer
> Update 07109 Shallows Devourer.sql

- Database/Patches/2005-10-TricksAndTreats/6 LandBlockExtendedData/33D9.sql
- Database/Patches/2005-10-TricksAndTreats/6 LandBlockExtendedData/A0A4.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Chest/Container/09460 Monty's Golden Chest.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Chest/Container/09461 Arshid's Golden Chest.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Chest/Container/09462 Gan-Zo's Golden Chest.sql
Pumpkin Buffer was located at 29.8n 27.3e (mt face 180) as seen in http://acpedia.org/images/3/3a/Pumpkin_Buffer_Live.jpg which is in A1A4, not A0A4
> Correct Pumpkin Buffers.sql

- Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/Creature/Undead/43689 Frozen Wight Captain.sql
- Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/Creature/Undead/43690 Frozen Wight.sql
- Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/Creature/Undead/43691 Frozen Wight Sorcerer.sql
- Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/Creature/Undead/43821 Frozen Wight Captain.sql
- Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/Creature/Undead/43822 Frozen Wight.sql
- Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/Creature/Undead/43823 Frozen Wight Sorcerer.sql
- Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/Creature/Undead/45003 Frozen Wight.sql
- Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/Creature/Undead/45008 Frozen Wight Sorcerer.sql
- Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/Creature/Undead/45009 Frozen Wight.sql
- Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/Creature/Undead/45010 Frozen Wight Captain.sql
- Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/Creature/Undead/45012 Frozen Wight Sorcerer.sql
- Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/Creature/Undead/45014 Frozen Wight Captain.sql
- Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/Creature/Undead/45016 Frozen Wight High Acolyte.sql
- Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/Creature/Undead/51316 Frozen Wight Archer.sql
- Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/Creature/Undead/51360 Frozen Wight Guardian Captain.sql
- Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/Creature/Undead/51361 Frozen Wight Guardian.sql
- Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/Creature/Undead/51363 Frozen Wight Guardian Sorcerer.sql
This should bring all wights into spec with each other.
Frozen valley white resistance float updates
Update frozen archers to stubborn missile
> Update Frozen Wight Resistance Floats

- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Clothing/Armor/25528 Hearty Reedshark Robe.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Clothing/Clothing/07428 Aerlinthe Patron Shirt.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Clothing/Clothing/07429 Aerlinthe Monarch Shirt.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Clothing/Clothing/27654 Coarse Hide Shirt.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Clothing/Clothing/28072 Aphus Lounging Shirt.sql
- Database/Patches/2005-10-TricksAndTreats/9 WeenieDefaults/Clothing/Clothing/32188 Festival Shirt.sql
- Database/Patches/2005-10-TricksAndTreats/9 WeenieDefaults/Clothing/Clothing/32189 Festival Shirt.sql
- Database/Patches/2005-10-TricksAndTreats/9 WeenieDefaults/Clothing/Clothing/32190 Festival Shirt.sql
- Database/Patches/2005-10-TricksAndTreats/9 WeenieDefaults/Clothing/Clothing/32191 Festival Shirt.sql
- Database/Patches/2005-10-TricksAndTreats/9 WeenieDefaults/Clothing/Clothing/32192 Festival Shirt.sql
- Database/Patches/2005-10-TricksAndTreats/9 WeenieDefaults/Clothing/Clothing/32193 Festival Shirt.sql
- Database/Patches/2005-10-TricksAndTreats/9 WeenieDefaults/Clothing/Clothing/32194 Festival Shirt.sql
- Database/Patches/2005-10-TricksAndTreats/9 WeenieDefaults/Clothing/Clothing/32195 Festival Shirt.sql
- Database/Patches/2005-10-TricksAndTreats/9 WeenieDefaults/Clothing/Clothing/32196 Festival Shirt.sql
- Database/Patches/2005-10-TricksAndTreats/9 WeenieDefaults/Clothing/Clothing/32197 Festival Shirt.sql
- Database/Patches/2005-10-TricksAndTreats/9 WeenieDefaults/Clothing/Clothing/34105 Festival Shirt.sql
- Database/Patches/2005-10-TricksAndTreats/9 WeenieDefaults/Clothing/Clothing/34106 Festival Shirt.sql
- Database/Patches/2005-10-TricksAndTreats/9 WeenieDefaults/Clothing/Clothing/34107 Festival Shirt.sql
- Database/Patches/2005-10-TricksAndTreats/9 WeenieDefaults/Clothing/Clothing/34108 Festival Shirt.sql
- Database/Patches/2005-10-TricksAndTreats/9 WeenieDefaults/Clothing/Clothing/34109 Festival Shirt.sql
- Database/Patches/2005-10-TricksAndTreats/9 WeenieDefaults/Clothing/Clothing/34212 Festival Shirt.sql
- Database/Patches/2005-10-TricksAndTreats/9 WeenieDefaults/Clothing/Clothing/36437 Festival Shirt.sql
- Database/Patches/2005-10-TricksAndTreats/9 WeenieDefaults/Clothing/Clothing/36438 Festival Shirt.sql
- Database/Patches/2005-10-TricksAndTreats/9 WeenieDefaults/Clothing/Clothing/36439 Festival Shirt.sql
- Database/Patches/2005-10-TricksAndTreats/9 WeenieDefaults/Clothing/Clothing/36440 Festival Shirt.sql
- Database/Patches/2005-10-TricksAndTreats/9 WeenieDefaults/Clothing/Clothing/36451 Festival Shirt.sql
- Database/Patches/2005-10-TricksAndTreats/9 WeenieDefaults/Clothing/Clothing/39112 Festival Shirt.sql
> update validlocations on some clothing items

- Database/Patches/2007-10-Masked Memories/9 WeenieDefaults/CraftTool/TinkeringMaterial/21066 Salvaged Peridot.sql
- Database/Patches/2007-10-Masked Memories/9 WeenieDefaults/CraftTool/TinkeringMaterial/21088 Salvaged Yellow Topaz.sql
- Database/Patches/2007-10-Masked Memories/9 WeenieDefaults/CraftTool/TinkeringMaterial/21089 Salvaged Zircon.sql
- Database/Patches/2007-10-Masked Memories/9 WeenieDefaults/CraftTool/TinkeringMaterial/36634 Foolproof Peridot.sql
- Database/Patches/2007-10-Masked Memories/9 WeenieDefaults/CraftTool/TinkeringMaterial/36635 Foolproof Yellow Topaz.sql
- Database/Patches/2007-10-Masked Memories/9 WeenieDefaults/CraftTool/TinkeringMaterial/36636 Foolproof Zircon.sql
this pr fixes https://github.com/ACEmulator/ACE-World-16PY-Patches/issues/697
> update TargetType for defense imbue salvage to match eor pcaps

- Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/04280 Deck of Hands Favor.sql
Changed stat_Mod_Val from 2 to 15 to match Retail.
> Update 04280 Deck of Hands Favor.sql

- Database/Patches/2008-05-Introductions/9 WeenieDefaults/Caster/37478 Spectral Staff.sql
- Database/Patches/2008-05-Introductions/9 WeenieDefaults/Caster/37585 Soul Bound Staff.sql
Just a comment fix to avoid confusion
> comment fix on spectral casting staff

- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Ammunition/15295 Greater Frost Atlatl Dart.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Ammunition/15438 Deadly Quarrel.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Ammunition/15439 Deadly Acid Quarrel.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Ammunition/15440 Deadly Armor Piercing Quarrel.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Ammunition/15441 Deadly Blunt Quarrel.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Ammunition/15442 Deadly Broadhead Quarrel.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Ammunition/15444 Deadly Fire Quarrel.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Ammunition/15445 Deadly Frog Crotch Quarrel.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Ammunition/15446 Deadly Frost Quarrel.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Ammunition/20967 Deadly Blunt Atlatl Dart.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Ammunition/20970 Deadly Fire Atlatl Dart.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Ammunition/20971 Deadly Frog Crotch Atlatl Dart.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Ammunition/21351 Chorizite Quarrel.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Ammunition/21352 Deadly Chorizite Quarrel.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Ammunition/24551 Deadly Barbed Quarrel.sql
- Database/Patches/2007-10-Masked Memories/9 WeenieDefaults/Ammunition/36522 Greater Deadly Blunt Quarrel.sql
- Database/Patches/2011-05-LostCityOfNeftet/9 WeenieDefaults/Ammunition/43942 Greater Prismatic Arrow.sql
- Database/Patches/2011-05-LostCityOfNeftet/9 WeenieDefaults/Ammunition/43951 Deadly Prismatic Arrow.sql
- Database/Patches/2011-05-LostCityOfNeftet/9 WeenieDefaults/Ammunition/43953 Deadly Prismatic Atlatl Dart.sql
- Database/Patches/2011-05-LostCityOfNeftet/9 WeenieDefaults/Ammunition/43956 Deadly Prismatic Quarrel.sql
- Database/Patches/2011-05-LostCityOfNeftet/9 WeenieDefaults/Ammunition/43957 Greater Prismatic Quarrel.sql
- Database/Patches/2011-05-LostCityOfNeftet/9 WeenieDefaults/Ammunition/43958 Prismatic Quarrel.sql
- Database/Patches/2011-05-LostCityOfNeftet/9 WeenieDefaults/Ammunition/44368 Greater Deadly Blunt Arrow.sql
- Database/Patches/2011-05-LostCityOfNeftet/9 WeenieDefaults/Ammunition/44369 Greater Deadly Blunt Atlatl Dart.sql
- Database/Patches/2011-05-LostCityOfNeftet/9 WeenieDefaults/Ammunition/44370 Greater Deadly Blunt Quarrel.sql
http://ac.yotesfan.com/compare/ammo.php
> misc ammo updates to match pcaps/eor

- Database/Patches/2007-03-AncientEnemies/1 RegionDescExtendedData/462E.sql
- Database/Patches/2007-03-AncientEnemies/9 WeenieDefaults/Generic/87005 GY Day Pyre Five Camp Gen.sql
- Database/Patches/2007-03-AncientEnemies/9 WeenieDefaults/MeleeWeapons/35095 Pyre Claw.sql
- Database/Patches/2007-03-AncientEnemies/9 WeenieDefaults/MeleeWeapons/35096 Pyre Blade.sql
Adjust a Pyre Camp spawn for better variance
Add RegionData that got left behind during the push
More tuning on Skeleton Pyre weapons
> Graveyard Tweak

- Database/Patches/2011-05-LostCityOfNeftet/9 WeenieDefaults/CraftTool/CraftFletchingIntermediate/44072 Wrapped Bundle of Deadly Prismatic Arrowheads.sql
- Database/Patches/2011-05-LostCityOfNeftet/9 WeenieDefaults/CraftTool/CraftFletchingIntermediate/44073 Wrapped Bundle of Greater Prismatic Arrowheads.sql
- Database/Patches/2011-05-LostCityOfNeftet/9 WeenieDefaults/CraftTool/CraftFletchingIntermediate/44224 Wrapped Bundle of Greater Deadly Blunt Arrowheads.sql
> match some wrapped bundles of arrowheads to pcaps/eor

- Database/Patches/2007-03-AncientEnemies/9 WeenieDefaults/Creatures/Wisp/41970 Hatred Wisp.sql
- Database/Patches/2007-03-AncientEnemies/9 WeenieDefaults/Creatures/Wisp/41971 Sorrow Wisp.sql
Added KillTask to Night spawned WIsps.
> Added GY KT to Night Wisps

- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Ammunition/09232 Soulrender Arrow.sql
- Database/Patches/2007-10-Masked Memories/9 WeenieDefaults/Ammunition/36391 Olthoi Acid Bolt.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Ammunition/38782 Raider Lightning Bolt.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Ammunition/48036 AcidQuarrel.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Ammunition/48037 LightningQuarrel.sql
- Database/Patches/2010-08-QuietBeforeTheStorm/9 WeenieDefaults/Ammunition/43151 Gear Blade Slashing Atlatl Dart.sql
- Database/Patches/2010-08-QuietBeforeTheStorm/9 WeenieDefaults/Ammunition/43152 Gear Blade Slashing Bolt.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Ammunition/MissileWeapon/03598 Armor Piercing Arrow.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Ammunition/MissileWeapon/03604 Broadhead Quarrel.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Ammunition/MissileWeapon/05304 Greater Arrow.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Ammunition/MissileWeapon/05305 Greater Fire Arrow.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Ammunition/MissileWeapon/05306 Greater Acid Arrow.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Ammunition/MissileWeapon/05307 Greater Frost Arrow.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Ammunition/MissileWeapon/05308 Greater Lightning Arrow.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Ammunition/MissileWeapon/05309 Greater Armor Piercing Arrow.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Ammunition/MissileWeapon/05310 Greater Blunt Arrow.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Ammunition/MissileWeapon/05312 Greater Frog Crotch Arrow.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Ammunition/MissileWeapon/05313 Greater Quarrel.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Ammunition/MissileWeapon/05314 Greater Acid Quarrel.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Ammunition/MissileWeapon/05315 Greater Frost Quarrel.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Ammunition/MissileWeapon/05316 Greater Lightning Quarrel.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Ammunition/MissileWeapon/05317 Greater Fire Quarrel.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Ammunition/MissileWeapon/05318 Greater Armor Piercing Quarrel.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Ammunition/MissileWeapon/05319 Greater Blunt Quarrel.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Ammunition/MissileWeapon/05320 Greater Broadhead Quarrel.sql
http://ac.yotesfan.com/compare/ammo.php
> More ammo fixes to match eor/pcap

- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Generic/Gem/24269 Small Olthoi Grub.sql
- Database/Patches/2020-11-AnniversaryEvent/9 WeenieDefaults/Creature/Human/69994 Night Club Attendant.sql
- Database/Patches/2020-11-AnniversaryEvent/FireworksStopgap.sql
Removing TimeToRot from base. There is no good reason for this property to exist on this item.
> Create 24269 Small Olthoi Grub.sql

- Database/Patches/2005-10-TricksAndTreats/9 WeenieDefaults/Gem/32216 Pack Gold Remoran.sql
- Database/Patches/2006-09-ComeWhatFollows/9 WeenieDefaults/Gem/Gem/33965 Tipped Pack Cow.sql
- Database/Patches/2006-12-ColdTracks/9 WeenieDefaults/Gem/34406 Pack Scold.sql
- Database/Patches/2006-12-ColdTracks/9 WeenieDefaults/Gem/34407 Abominable Pack Snowman.sql
- Database/Patches/2006-12-ColdTracks/9 WeenieDefaults/Generic/Misc/34405 Mr. P. Holiday Pack Doll.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Book/Writable/29916 Pack Asheron.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Book/Writable/29917 Pack Bael'Zharon.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Book/Writable/29918 Pack Gaerlan.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Book/Writable/29919 Pack Burun Kukuur.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Book/Writable/29920 Pack Levistras.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Book/Writable/29921 Pack Martine.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Book/Writable/29922 Pack Ancient Olthoi Queen.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Food/14910 Wedding Cake.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Gem/Gem/09169 Plush Tusker.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Gem/Gem/09170 Velveteen Olthoi.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Gem/Gem/09171 Pack Mosswart.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Gem/Gem/09172 Pack Drudge.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Gem/Gem/09173 Pack Ursuin.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Gem/Gem/09174 Pack Lugian.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Gem/Gem/09175 Pack Cow.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Gem/Gem/09176 Pack Grievver.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Gem/Gem/09177 Pack Scarecrow.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Gem/Gem/09178 Pack Virindi.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Gem/Gem/09179 Pack Golem.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Gem/Gem/09180 Pack Idol.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Gem/Gem/22620 Carved Tusker Statue.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Gem/Gem/25534 Tremendous Monouga Pack Doll.sql
This PR will need a shard update script created to accompany it. 
Removed timetorot from pack dolls and wedding cake
Changed some pack dolls from generic to gem to match pcap
> Remove timetorot from pack dolls

- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Creature/OlthoiLarvae/24961 Olthoi Eviscerator Grub.sql
update PHYSICS_EFFECT_TABLE_DID (22) to match PCAP
Error with Olthoi Eviscerator Grub - 24961
PHYSICS_EFFECT_TABLE_DID (22):
- ACE: 872415265
- PCAP: 872415396
> Update 24961 Olthoi Eviscerator Grub.sql

- Database/Patches/2020-11-AnniversaryEvent/9 WeenieDefaults/Creature/Human/69994 Night Club Attendant.sql
- Fix loopcount warning message
> Fix Night Club Attendant

- Database/Patches/2008-05-Introductions/9 WeenieDefaults/Portal/37513 Armory.sql
- Database/Patches/2008-05-Introductions/9 WeenieDefaults/Portal/37514 Forges.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Creature/Undead/38713 Shambling Archivist.sql
Lower skills
fix a few bad portals
> Nerf Shambling Archivist

- Database/Patches/2007-03-AncientEnemies/9 WeenieDefaults/Creatures/Ghost/35268 Spectral Dread.sql
- Database/Patches/2007-03-AncientEnemies/9 WeenieDefaults/Creatures/Ghost/35270 Spectral Dread.sql
- Database/Patches/2007-03-AncientEnemies/9 WeenieDefaults/Creatures/Ghost/35400 Corrupted Dread.sql
- Database/Patches/2007-03-AncientEnemies/9 WeenieDefaults/Creatures/Ghost/37452 Corrupted Dread.sql
- Database/Patches/2007-03-AncientEnemies/9 WeenieDefaults/Creatures/Ghost/41961 Corrupted Dread.sql
- Database/Patches/2007-03-AncientEnemies/9 WeenieDefaults/Creatures/Ghost/45165 Corrupted Dread.sql
- Database/Patches/2007-03-AncientEnemies/9 WeenieDefaults/Creatures/Ghost/45182 Corrupted Dread.sql
- Database/Patches/2007-03-AncientEnemies/9 WeenieDefaults/Creatures/Skeleton/35097 Pyre Skeleton.sql
- Database/Patches/2007-03-AncientEnemies/9 WeenieDefaults/Creatures/Skeleton/35098 Pyre Champion.sql
- Database/Patches/2007-03-AncientEnemies/9 WeenieDefaults/Creatures/Skeleton/35099 Pyre Minion.sql
- Database/Patches/2007-03-AncientEnemies/9 WeenieDefaults/Creatures/Skeleton/37458 Pyre Minion.sql
- Database/Patches/2007-03-AncientEnemies/9 WeenieDefaults/Creatures/Skeleton/37459 Pyre Skeleton.sql
- Database/Patches/2007-03-AncientEnemies/9 WeenieDefaults/Creatures/Skeleton/40926 Pyre Skeleton.sql
- Database/Patches/2007-03-AncientEnemies/9 WeenieDefaults/Creatures/Skeleton/41963 Pyre Skeleton.sql
- Database/Patches/2007-03-AncientEnemies/9 WeenieDefaults/Creatures/Skeleton/41964 Pyre Champion.sql
- Database/Patches/2007-03-AncientEnemies/9 WeenieDefaults/Creatures/Skeleton/41965 Pyre Minion.sql
- Database/Patches/2007-03-AncientEnemies/9 WeenieDefaults/Creatures/Skeleton/45173 Pyre Champion.sql
- Database/Patches/2007-03-AncientEnemies/9 WeenieDefaults/Creatures/Skeleton/45174 Pyre Skeleton.sql
- Database/Patches/2007-03-AncientEnemies/9 WeenieDefaults/Creatures/Skeleton/45175 Pyre Minion.sql
- Database/Patches/2007-03-AncientEnemies/9 WeenieDefaults/Creatures/Skeleton/46816 Pyre Champion.sql
- Database/Patches/2007-03-AncientEnemies/9 WeenieDefaults/Creatures/Skeleton/52308 Pyre Minion.sql
- Database/Patches/2007-03-AncientEnemies/9 WeenieDefaults/Creatures/Skeleton/52309 Pyre Champion.sql
- Database/Patches/2007-03-AncientEnemies/9 WeenieDefaults/Creatures/Undead/41966 Wight.sql
- Database/Patches/2007-03-AncientEnemies/9 WeenieDefaults/Creatures/Undead/41968 Wight Captain.sql
- Database/Patches/2007-03-AncientEnemies/9 WeenieDefaults/Creatures/Undead/46815 Wight Blade Sorcerer.sql
Update Trophy Drop Rates
Adjust Spectral and Corrupted Dread stats
Adjust a few mobs to the proper loot tier
> GY Mob Tweaks

- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Creature/Moarsman/38650 Blighted Grimy Moarsman.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Creature/Moarsman/38652 Blighted Scummy Moarsman.sql
Missed combat tables on Grimy and Scummy Moarsman
> Add Missing Combat Table on two Moarsman

- Database/Patches/2005-10-TricksAndTreats/9 WeenieDefaults/Creature/Human/08402 Tsua Kagemata.sql
- Database/Patches/2005-10-TricksAndTreats/9 WeenieDefaults/Creature/Human/08404 Alexander the Deft.sql
- Database/Patches/2006-01-Reprisals/9 WeenieDefaults/Creature/Human/08403 Janda Sulifiya.sql
- Database/Patches/2010-11-FromDarknessLight/4 CraftTable/07650 Gurog Body.sql
- Database/Patches/2010-11-FromDarknessLight/4 CraftTable/07651 Gurog Body with one Leg.sql
- Database/Patches/2010-11-FromDarknessLight/4 CraftTable/07652 Gurog Torso with Arms.sql
- Database/Patches/2010-11-FromDarknessLight/4 CraftTable/07653 Gurog Torso with an Arm.sql
- Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/CraftTool/44864 Gurog Arm.sql
- Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/CraftTool/44865 Gurog Body.sql
- Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/CraftTool/44866 Gurog Torso with an Arm.sql
- Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/CraftTool/44867 Gurog Torso with Arms.sql
- Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/CraftTool/44868 Gurog Torso with a Head.sql
- Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/CraftTool/44869 Gurog Body with one Leg.sql
- Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/CraftTool/44870 Gurog Leg.sql
- Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/Creature/Gurog/43391 Gurog Minion.sql
- Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/Creature/Gurog/43392 Gurog Henchman.sql
- Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/Creature/Gurog/43393 Gurog Soldier.sql
- Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/Creature/Gurog/43394 Gurog Henchman.sql
- Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/Creature/Gurog/43395 Gurog Minion.sql
- Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/Creature/Gurog/43396 Gurog Soldier.sql
- Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/Creature/Gurog/43516 Gurog Soldier.sql
- Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/Creature/Gurog/51357 Gurog Guardian Henchman.sql
- Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/Creature/Gurog/51358 Gurog Guardian Minion.sql
- Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/Creature/Gurog/51359 Gurog Guardian Soldier.sql
- Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/Creature/Gurog/70366 Gurog Guardian.sql
Tuning stats and create lists on Gurogs to better align with retail
Added Gurog body parts and recipes to players can build Gurog Guise
Updated mask makers
> Gurog Tune up - Add Gurog Guise

- Database/Patches/2006-01-Reprisals/9 WeenieDefaults/Caster/32488 Winter Orb.sql
Changed INT32 prop 16 from 1 to 6291460 to fix the use issue
> Hotfix for Winter Orb (32488)

- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Golem/27564 Coral Golem Viceroy.sql
Color correction to match http://acpedia.org/wiki/Coral_Golem_Viceroy and ACCPP screenshots
> Update 27564 Coral Golem Viceroy.sql

- Database/Patches/2005-11-AshesAndDust/9 WeenieDefaults/Portal/32282 Collegium Occultus Portal.sql
Correct portal restrictions
http://acpedia.org/wiki/Collegium_Occultus
> Update 32282 Collegium Occultus Portal.sql

- Database/Patches/2012-12-AGrowingTwilight/9 WeenieDefaults/Creature/Crystal/48713 Blazing Crystal.sql
- Database/Patches/2012-12-AGrowingTwilight/9 WeenieDefaults/Creature/Crystal/48715 Prism Shard.sql
- Database/Patches/2012-12-AGrowingTwilight/9 WeenieDefaults/Creature/Golem/48712 Char Golem.sql
**Updates**
Added loot to Char Golem and Prism Shard
Updated Blazing Crystals ClothingBase/Palette and lowered health regen rate.
> Updates to Crystal Core Quest

- Database/Patches/2006-12-ColdTracks/4 CraftTable/08100.sql
- Database/Patches/2006-12-ColdTracks/6 LandBlockExtendedData/9F29.sql
- Database/Patches/2006-12-ColdTracks/8 QuestDefDB/frozenpresentpickuptimer.sql
- Database/Patches/2006-12-ColdTracks/8 QuestDefDB/hotcoalpickuptimer.sql
- Database/Patches/2006-12-ColdTracks/9 WeenieDefaults/CraftTool/34386 Hot Coal.sql
- Database/Patches/2006-12-ColdTracks/9 WeenieDefaults/CraftTool/34425 Frozen Present.sql
- Database/Patches/2006-12-ColdTracks/9 WeenieDefaults/CraftTool/36897 Present.sql
- Database/Patches/2006-12-ColdTracks/9 WeenieDefaults/Creature/Golem/87122 Scold.sql
- Database/Patches/2006-12-ColdTracks/9 WeenieDefaults/Creature/Golem/87124 Scold Chunk.sql
- Database/Patches/2006-12-ColdTracks/9 WeenieDefaults/Creature/Golem/87126 Scold Lump.sql
- Database/Patches/2006-12-ColdTracks/9 WeenieDefaults/Creature/Snowman/87120 Abominable Snowman.sql
- Database/Patches/2006-12-ColdTracks/9 WeenieDefaults/Generic/None/87121 AoFH Abominable Snowman Generator.sql
- Database/Patches/2006-12-ColdTracks/9 WeenieDefaults/Generic/None/87123 AoFH Scold Generator.sql
- Database/Patches/2006-12-ColdTracks/9 WeenieDefaults/Generic/None/87125 AoFH Scold Chunk Generator.sql
- Database/Patches/2006-12-ColdTracks/9 WeenieDefaults/Generic/None/87127 AoFH Scold Lump Generator.sql
- Database/Patches/2006-12-ColdTracks/9 WeenieDefaults/Pet/34397 Pet Snowman.sql
- Database/Patches/2006-12-ColdTracks/9 WeenieDefaults/PetDevice/34421 Magic Hat.sql
- Database/Patches/2006-12-ColdTracks/B GameEventDefDB/assaultonfrosthavenevent.sql
- Database/Patches/2008-01-Recollections/9 WeenieDefaults/Clothing/36772 Banner.sql
**Server Operated Event**
@event start assaultonfrosthavenevent
@event stop assaultonfrosthavenevent
**Added**
**Creature**
Abominable Snowman
Scold
Scold Chunk
Scold Lump
**Items**
Hot Coal
Magic Hat / Pet Snowman
Frozen Present
Present
Banner
(Gens)
**Landblocks**
9F29
> Assault on Frost Haven Quest and Missing Items

- Database/Patches/2010-01-ReforgingThePast/8 QuestDefDB/MagnificentBraceletPickupTimer.sql
- Database/Patches/2010-01-ReforgingThePast/9 WeenieDefaults/Chest/24138 Oswald's Chest.sql
- Database/Patches/2010-01-ReforgingThePast/9 WeenieDefaults/Generic/Misc/42107 Magnificent Bracelet.sql
- Database/Patches/2011-01-LearningFromExperience/9 WeenieDefaults/SQL/Creature/Human/24153 Aaminah.sql
- Database/Patches/2011-01-LearningFromExperience/9 WeenieDefaults/SQL/Creature/Human/24153_Aaminah.es
Updated NPC to EoR XP rewards
Added Magnificent Bracelet to chest for Oswald's Dirk quest (with pickup timer)
> Updates to Heart of Innocence and Oswald's Dirk quests

- Database/Patches/2010-01-ReforgingThePast/9 WeenieDefaults/Creature/Niffis/30389 Reijiri.sql
- Database/Patches/2010-01-ReforgingThePast/9 WeenieDefaults/Creature/Niffis/30389_Reijiri.es
> Updated XP Reward in Niffis Fighting Pits

- Database/Patches/2006-01-Reprisals/9 WeenieDefaults/Creature/Fallen/30886 Fallen Tumerok.sql
- Database/Patches/2006-01-Reprisals/9 WeenieDefaults/Creature/Fallen/30887 Fallen Shadow.sql
- Database/Patches/2006-01-Reprisals/9 WeenieDefaults/Creature/Fallen/30888 Fallen Grievver.sql
- Database/Patches/2006-01-Reprisals/9 WeenieDefaults/Creature/Fallen/30889 Fallen Crystal Shard.sql
- Database/Patches/2006-01-Reprisals/9 WeenieDefaults/Creature/Fallen/30890 Fallen Lugian.sql
- Database/Patches/2006-01-Reprisals/9 WeenieDefaults/Creature/Fallen/30891 Fallen Drudge.sql
- Database/Patches/2006-01-Reprisals/9 WeenieDefaults/Creature/Fallen/30892 Fallen Rift.sql
- Database/Patches/2006-01-Reprisals/9 WeenieDefaults/Creature/Fallen/30893 Fallen Marionette.sql
- Database/Patches/2006-01-Reprisals/9 WeenieDefaults/Creature/Fallen/30894 Fallen Mite.sql
- Database/Patches/2006-01-Reprisals/9 WeenieDefaults/Creature/Fallen/30895 Fallen Doll.sql
- Database/Patches/2006-01-Reprisals/9 WeenieDefaults/Creature/Fallen/30896 Fallen Margul.sql
Correcting Drop rate of Sezzherei's Lair (Portal Gem) to 100% per Release Notes of Jan 2006. http://acpedia.org/wiki/Announcements_-_2006/01_-_Reprisals#Release_Notes
> Sezzherei's Lair (Portal Gem) 100% drop rate

- Database/Patches/2017-01-EndOfRetail/6 LandBlockExtendedData/SQL/A9B3.sql
> Update Holtburg Area

- Database/Patches/2005-12-ThroughSacrificeStrength/9 WeenieDefaults/Creature/Unsorted/32528 Portal Pillar.sql
- Database/Patches/2005-12-ThroughSacrificeStrength/9 WeenieDefaults/Creature/Unsorted/80047 Portal Pillar.sql
- Database/Patches/2005-12-ThroughSacrificeStrength/9 WeenieDefaults/Creature/Unsorted/80048 Portal Pillar.sql
- Add missing MaxGeneratedObjects 3 property to the Portal Pillars
> Fix missing property on Portal Pillars

- Database/Patches/2013-12-TheHolidayRush/9 WeenieDefaults/Creature/Unsorted/87237 Gift Box.sql
- Database/Patches/2013-12-TheHolidayRush/9 WeenieDefaults/Creature/Unsorted/87237.es
- Database/Patches/2013-12-TheHolidayRush/9 WeenieDefaults/Creature/Unsorted/87238 Gift Box.sql
- Database/Patches/2013-12-TheHolidayRush/9 WeenieDefaults/Creature/Unsorted/87238.es
- Database/Patches/2013-12-TheHolidayRush/9 WeenieDefaults/Creature/Unsorted/87239 Gift Box.sql
- Database/Patches/2013-12-TheHolidayRush/9 WeenieDefaults/Creature/Unsorted/87239.es
- Database/Patches/2013-12-TheHolidayRush/9 WeenieDefaults/Creature/Unsorted/87240 Gift Box.sql
- Database/Patches/2013-12-TheHolidayRush/9 WeenieDefaults/Creature/Unsorted/87240.es
- Database/Patches/2013-12-TheHolidayRush/9 WeenieDefaults/Creature/Unsorted/87241 Gift Box.sql
- Database/Patches/2013-12-TheHolidayRush/9 WeenieDefaults/Creature/Unsorted/87241.es
- Database/Patches/2013-12-TheHolidayRush/9 WeenieDefaults/Creature/Unsorted/87242 Gift Box.sql
- Database/Patches/2013-12-TheHolidayRush/9 WeenieDefaults/Creature/Unsorted/87242.es
- Database/Patches/2013-12-TheHolidayRush/9 WeenieDefaults/Creature/Unsorted/87243 Gift Box.sql
- Database/Patches/2013-12-TheHolidayRush/9 WeenieDefaults/Creature/Unsorted/87243.es
- Database/Patches/2013-12-TheHolidayRush/9 WeenieDefaults/Creature/Unsorted/87244 Gift Box.sql
- Database/Patches/2013-12-TheHolidayRush/9 WeenieDefaults/Creature/Unsorted/87244.es
- Database/Patches/2013-12-TheHolidayRush/9 WeenieDefaults/Creature/Unsorted/87245 Gift Box.sql
- Database/Patches/2013-12-TheHolidayRush/9 WeenieDefaults/Creature/Unsorted/87245.es
- Database/Patches/2013-12-TheHolidayRush/9 WeenieDefaults/Creature/Unsorted/87246 Gift Box.sql
- Database/Patches/2013-12-TheHolidayRush/9 WeenieDefaults/Creature/Unsorted/87246.es
- Database/Patches/2013-12-TheHolidayRush/9 WeenieDefaults/Creature/Unsorted/87247 Gift Box.sql
- Database/Patches/2013-12-TheHolidayRush/9 WeenieDefaults/Creature/Unsorted/87247.es
- Database/Patches/2013-12-TheHolidayRush/9 WeenieDefaults/Creature/Unsorted/87248 Gift Box.sql
- Database/Patches/2013-12-TheHolidayRush/9 WeenieDefaults/Creature/Unsorted/87248.es
Text changed to make meta happy at end
> Adjust Hidden Presents giftboxes

- Database/Patches/2012-08-TheRisenPrincess/9 WeenieDefaults/Creature/Human/46014 Umbral Guard.sql
- Database/Patches/2012-08-TheRisenPrincess/9 WeenieDefaults/Creature/Human/46015 Royal Guard.sql
- Database/Patches/2012-08-TheRisenPrincess/9 WeenieDefaults/Creature/Human/46016 Umbral Guard.sql
- Database/Patches/2012-08-TheRisenPrincess/9 WeenieDefaults/Creature/Human/46017 Royal Guard.sql
- Database/Patches/2012-08-TheRisenPrincess/9 WeenieDefaults/Creature/Human/46018 Royal Guard.sql
- Database/Patches/2012-08-TheRisenPrincess/9 WeenieDefaults/Creature/Human/52272 Royal Guard.sql
Corrected the Tou-Tou KT NPC Tells.  Pulled the correct tells from a meta that worked in retail.  Most tells were not pcaped.
> Tou-Tou KT NPC Fixes

- Database/Patches/2006-02-AChangeInTactics/9 WeenieDefaults/Creature/ViamontianKnight/32700 Viamontian Portal Mage.sql
Fixed CombatTable and upped spell probability:
> 2020-12-14 15:01:39,653 ERROR: Viamontian Portal Mage (8000228D).GetCombatManeuver() - CombatTable is null
> Update 32700 Viamontian Portal Mage.sql

- Database/Patches/2009-10-GearsOfChange/9 WeenieDefaults/MissleLauncher/43132 Gear Crossbow.sql
- Database/Patches/2010-02-WintersKnight/9 WeenieDefaults/SQL/MissileLauncher/42301 Gear Crossbow.sql
- Database/Patches/2010-02-WintersKnight/9 WeenieDefaults/SQL/MissileLauncher/42302 Gear Crossbow.sql
- Database/Patches/2010-02-WintersKnight/9 WeenieDefaults/SQL/MissileLauncher/42303 Gear Crossbow.sql
- Database/Patches/2010-02-WintersKnight/9 WeenieDefaults/SQL/MissileLauncher/42304 Gear Crossbow.sql
- Database/Patches/2010-02-WintersKnight/9 WeenieDefaults/SQL/MissileLauncher/42305 Gear Crossbow.sql
- Database/Patches/2010-02-WintersKnight/9 WeenieDefaults/SQL/MissileLauncher/42306 Gear Crossbow.sql
- Database/Patches/2010-02-WintersKnight/9 WeenieDefaults/SQL/MissileLauncher/42307 Gear Crossbow.sql
- Database/Patches/2010-02-WintersKnight/9 WeenieDefaults/SQL/MissileLauncher/42308 Gear Crossbow.sql
- Database/Patches/2010-02-WintersKnight/9 WeenieDefaults/SQL/MissileLauncher/42309 Gear Crossbow.sql
- Database/Patches/2010-02-WintersKnight/9 WeenieDefaults/SQL/MissileLauncher/42310 Gear Crossbow.sql
Added Missile Weapons - Weapons Skill to X-bows.
> Added WepSkill to X-bows

- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/AcidElemental/14513 Caustic.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/AcidElemental/14516 Caustic.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/FireElemental/05712 Inferno.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/FireElemental/07487 Inferno.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/FrostElemental/14875 Hyem.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/LightningElemental/07094 Synnast.sql
- Database/Patches/2006-09-ComeWhatFollows/8 QuestDefDB/KilltaskElementalWait_0609.sql
- Database/Patches/2006-09-ComeWhatFollows/8 QuestDefDB/KilltaskElemental_0609.sql
- Database/Patches/2006-09-ComeWhatFollows/9 WeenieDefaults/CraftTool/Gem/33956 Crystal of Acidic Elemental Essence.sql
- Database/Patches/2006-09-ComeWhatFollows/9 WeenieDefaults/CraftTool/Gem/33957 Crystal of Electric Elemental Essence.sql
- Database/Patches/2006-09-ComeWhatFollows/9 WeenieDefaults/CraftTool/Gem/33958 Crystal of Frozen Elemental Essence.sql
- Database/Patches/2006-09-ComeWhatFollows/9 WeenieDefaults/CraftTool/Gem/33959 Crystal of Fiery Elemental Essence.sql
- Database/Patches/2006-09-ComeWhatFollows/9 WeenieDefaults/Creature/Human/33967 Zahir.sql
- Database/Patches/2006-09-ComeWhatFollows/9 WeenieDefaults/Creature/Human/33967_Zahir.es
Updated Creatures and NPC for Elemental Kill Task Quest and Turn Ins.
> Elemental Kill Task

- Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/03929 Rossu Morta Chapterhouse Recall.sql
updating to match retail drop location inside of the Rossu Morta Chapterhouse
> Updating drop location

- Database/Patches/2006-10-DanceOfTheDead/8 QuestDefDB/AndrilosLivesExtraXP.sql
- Database/Patches/2006-10-DanceOfTheDead/8 QuestDefDB/AndrilosLivesExtraXPWait.sql
- Database/Patches/2006-10-DanceOfTheDead/8 QuestDefDB/BlueFacePaintTurnIn.sql
- Database/Patches/2006-10-DanceOfTheDead/8 QuestDefDB/LunnumsReturnComplete1006.sql
- Database/Patches/2006-10-DanceOfTheDead/8 QuestDefDB/LunnumsReturnStarted1006.sql
- Database/Patches/2006-10-DanceOfTheDead/8 QuestDefDB/UndeadSlayerWait.sql
- Database/Patches/2006-10-DanceOfTheDead/8 QuestDefDB/ritualchestkeypickuptimer.sql
- Database/Patches/2006-10-DanceOfTheDead/9 WeenieDefaults/Creature/Fiun/32595 Fiun Layeel.sql
- Database/Patches/2006-10-DanceOfTheDead/9 WeenieDefaults/Creature/Fiun/32595_Fiun_Layeel.es
- Database/Patches/2006-10-DanceOfTheDead/9 WeenieDefaults/Portal/32811 Bookcase.sql
- Database/Patches/2006-10-DanceOfTheDead/9 WeenieDefaults/Portal/34057 Temple Entrance.sql
- Database/Patches/2006-10-DanceOfTheDead/9 WeenieDefaults/Portal/85001 Bookcase.sql
> Update to Fiun Layeel and Undead Slayer quest

- Database/Patches/2008-05-Introductions/9 WeenieDefaults/Gem/Misc/37472 Mace Stamped Spectral Ingot.sql
> Update 37472 Mace Stamped Spectral Ingot.sql

- Database/Patches/2012-08-TheRisenPrincess/6 LandBlockExtendedData/Encounter/F85B.sql
- Database/Patches/2012-08-TheRisenPrincess/6 LandBlockExtendedData/Encounter/F85C.sql
- Database/Patches/2012-08-TheRisenPrincess/6 LandBlockExtendedData/Encounter/F85D.sql
- Database/Patches/2012-08-TheRisenPrincess/6 LandBlockExtendedData/Encounter/F85E.sql
- Database/Patches/2012-08-TheRisenPrincess/6 LandBlockExtendedData/Encounter/F95C.sql
- Database/Patches/2012-08-TheRisenPrincess/6 LandBlockExtendedData/Encounter/F95D.sql
- Database/Patches/2012-08-TheRisenPrincess/6 LandBlockExtendedData/Encounter/F95E.sql
- Database/Patches/2012-08-TheRisenPrincess/9 WeenieDefaults/Generic/Generators/80505 Tou-Tou Beach Area KT Gen.sql
New Beach area Gen and Added Encounters for Beach area for critters to count against Tou-Tou KTs
> Tou-Tou KT Beach Encounters

- Database/Patches/2008-03-FoolishAmbition/8 QuestDefDB/pieceofknathcorepickuptimer.sql
Changed to 20 hour pickup timer.
> Updated Piece of Knath Core pickup timer to 20hrs

- Database/Patches/2012-08-TheRisenPrincess/9 WeenieDefaults/Generic/Generators/80500 Tou-Tou Lum Area Gen.sql
- Database/Patches/2012-08-TheRisenPrincess/9 WeenieDefaults/Generic/Generators/80510 Tou-Tou Shreader Grievver Lum Area Gen.sql
- Database/Patches/2012-08-TheRisenPrincess/9 WeenieDefaults/Generic/Generators/80511 Tou-Tou Devourer Margul Lum Area Gen.sql
- Database/Patches/2012-08-TheRisenPrincess/9 WeenieDefaults/Generic/Generators/80512 Tou-Tou Panumbris Shadow Lum Area Gen.sql
- Database/Patches/2012-08-TheRisenPrincess/9 WeenieDefaults/Generic/Generators/80513 Tou-Tou Shadow Flyer Lum Area Gen.sql
Reducing the chance for 1 creature spawning (was at 40%, for Grievvers, shadows, flyers and marguls, now down to 20%).  Also slightly adjusted spawn chance for more creatures.  End result is a slightly denser downtown Tou-Tou.
> Tou-Tou Gen update

- Database/Patches/2012-08-TheRisenPrincess/9 WeenieDefaults/Generic/Generators/80500 Tou-Tou Lum Area Gen.sql
- Database/Patches/2012-08-TheRisenPrincess/9 WeenieDefaults/Generic/Generators/80503 Tou-Tou Area NO Lum Gen.sql
- Database/Patches/2012-08-TheRisenPrincess/9 WeenieDefaults/Generic/Generators/80504 Tou-Tou Area NOLumNOKT Gen.sql
- Database/Patches/2012-08-TheRisenPrincess/9 WeenieDefaults/Generic/Generators/80510 Tou-Tou Shreader Grievver Lum Area Gen.sql
- Database/Patches/2012-08-TheRisenPrincess/9 WeenieDefaults/Generic/Generators/80511 Tou-Tou Devourer Margul Lum Area Gen.sql
- Database/Patches/2012-08-TheRisenPrincess/9 WeenieDefaults/Generic/Generators/80512 Tou-Tou Panumbris Shadow Lum Area Gen.sql
- Database/Patches/2012-08-TheRisenPrincess/9 WeenieDefaults/Generic/Generators/80513 Tou-Tou Shadow Flyer Lum Area Gen.sql
Updated max gen on the three main Tou-Tou crater encounter gens
> Tou tou gen update mimor

- Database/Patches/2013-05-CuratingCorruption/6 LandBlockExtendedData/586C.sql
- Database/Patches/2013-05-CuratingCorruption/6 LandBlockExtendedData/8C43.sql
- Database/Patches/2013-05-CuratingCorruption/8 QuestDefDB/BTMCompleted_0513.sql
- Database/Patches/2013-05-CuratingCorruption/8 QuestDefDB/BTMPickup_0513.sql
- Database/Patches/2013-05-CuratingCorruption/8 QuestDefDB/BTMStarted_0513.sql
- Database/Patches/2013-05-CuratingCorruption/8 QuestDefDB/chestchorizite51280.sql
- Database/Patches/2013-05-CuratingCorruption/9 WeenieDefaults/Book/51301 Translated Message Shard.sql
- Database/Patches/2013-05-CuratingCorruption/9 WeenieDefaults/Book/51302 Virindi Sentinel's Message Shard.sql
- Database/Patches/2013-05-CuratingCorruption/9 WeenieDefaults/Chest/51280 Chorizite Chest Masked Preface.sql
- Database/Patches/2013-05-CuratingCorruption/9 WeenieDefaults/Creature/Simulacrum/51285 Simulacrum Shifter.sql
- Database/Patches/2013-05-CuratingCorruption/9 WeenieDefaults/Creature/Simulacrum/51288 Simulacrum Mimic.sql
- Database/Patches/2013-05-CuratingCorruption/9 WeenieDefaults/Creature/Virindi/51286 Virindi Sentinel.sql
- Database/Patches/2013-05-CuratingCorruption/9 WeenieDefaults/Creature/Virindi/51287 Virindi Clandestine.sql
- Database/Patches/2013-05-CuratingCorruption/9 WeenieDefaults/Creature/Virindi/51297 Virindi Delegate Yanshi.sql
- Database/Patches/2013-05-CuratingCorruption/9 WeenieDefaults/Creature/Virindi/51298 Virindi Delegate Masked Preface.sql
- Database/Patches/2013-05-CuratingCorruption/9 WeenieDefaults/Creature/Virindi/51300 Virindi Keeper.sql
- Database/Patches/2013-05-CuratingCorruption/9 WeenieDefaults/Door/51284 Sealed Door.sql
- Database/Patches/2013-05-CuratingCorruption/9 WeenieDefaults/Door/51313 Sealed Door.sql
- Database/Patches/2013-05-CuratingCorruption/9 WeenieDefaults/Gem/Gem/51337 Contract for Behind the Mask.sql
- Database/Patches/2013-05-CuratingCorruption/9 WeenieDefaults/Generic/Generator/72161 Masked Preface Chorizite Chest Gen.sql
- Database/Patches/2013-05-CuratingCorruption/9 WeenieDefaults/Key/72158 Sealed Crackling Key.sql
- Database/Patches/2013-05-CuratingCorruption/9 WeenieDefaults/Key/72159 Sealed Sparkling Key.sql
- Database/Patches/2013-05-CuratingCorruption/9 WeenieDefaults/Portal/51282 Masked Preface.sql
- Database/Patches/2013-05-CuratingCorruption/9 WeenieDefaults/Portal/51283 Surface.sql
- Database/Patches/2013-05-CuratingCorruption/9 WeenieDefaults/Portal/51296 Portal.sql
- Database/Patches/2013-05-CuratingCorruption/ES/51297 Virindi Delegate Yanshi.es
- Database/Patches/2013-05-CuratingCorruption/ES/51298 Virindi Delegate Masked Preface.es
Quest Dream Reaver Investigation from 2013-05 Curating Corruption (depends on PR #771).
> Dream Reaver Investigation

- Database/Patches/2009-12-GainingGround/4 CraftTable/04499 Aqua Vitae.sql
- Database/Patches/2009-12-GainingGround/4 CraftTable/04500 Aqua Vitae.sql
- Database/Patches/2009-12-GainingGround/4 CraftTable/04501 Aqua Vitae.sql
- Database/Patches/2009-12-GainingGround/4 CraftTable/04502 Aqua Vitae.sql
- Database/Patches/2009-12-GainingGround/4 CraftTable/04503 Aqua Vitae.sql
- Database/Patches/2009-12-GainingGround/4 CraftTable/04504 Aqua Vitae.sql
Here is a quick update of the last_Modified values.  I tested on my DB to ensure it's working.
I figured it would be easier to PR to your release branch since the other code hasn't been merged to master yet.
> Addendum to PR #790, Update the last_Modified fields for the updated Aqua Vitae rows

- Database/Patches/2005-08-FriendAndFoe/8 QuestDefDB/UntransDreamSaltAsh.sql
- Database/Patches/2005-08-FriendAndFoe/8 QuestDefDB/UntransGraelRebellionPickup.sql
- Database/Patches/2005-08-FriendAndFoe/8 QuestDefDB/UntransSongOfGrael.sql
- Untranslated books' pickup timers updated
> Grael's Rage cooldown update

- Database/Patches/2012-02-MasterOfArms/9 WeenieDefaults/Gem/Gem/30198 Elysa's Crystal.sql
- Database/Patches/2012-02-MasterOfArms/9 WeenieDefaults/Gem/Gem/30223 Thorsten's Crystal.sql
- Database/Patches/2012-02-MasterOfArms/9 WeenieDefaults/Gem/Gem/30236 Thorsten's Crystal.sql
- Database/Patches/2012-02-MasterOfArms/9 WeenieDefaults/Gem/Gem/30238 Thorsten's Crystal.sql
- Database/Patches/2012-02-MasterOfArms/9 WeenieDefaults/Gem/Gem/30243 Elysa's Crystal.sql
- Database/Patches/2012-02-MasterOfArms/9 WeenieDefaults/Gem/Gem/30244 Thorsten's Crystal.sql
Overwriting original 16py Rares:
30198 Elysa's Crystal
30223 Thorsten's Crystal
30236 Thorsten's Crystal
30238 Thorsten's Crystal
30243 Elysa's Crystal
30244 Thorsten's Crystal
> Update to Rares (MoA)

- Database/Patches/2005-07-ThroneOfDestiny/8 QuestDefDB/AugGemFlag.sql
- Database/Patches/2005-07-ThroneOfDestiny/8 QuestDefDB/AugmentationBlankGemAcquired.sql
- Database/Patches/2005-07-ThroneOfDestiny/8 QuestDefDB/AugmentationProvingGroundAccess.sql
- Database/Patches/2005-07-ThroneOfDestiny/8 QuestDefDB/BlankAug.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Gem/Gem/44393 Contract for Aug Gem_ Sir Bellas.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Misc/29295 Blank Augmentation Gem.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Portal/28711 Augmentation Realm Lower Level.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Portal/30056 Augmentation Realm Main Level.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Portal/30057 Augmentation Realm Main Level.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Portal/30058 Augmentation Realm Main Level.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Portal/30059 Augmentation Realm Main Level.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Portal/30060 Augmentation Realm Main Level.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Portal/30061 Augmentation Realm Upper Level.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Portal/30062 Augmentation Realm Main Level.sql
- Database/Patches/2007-02-RekindlingTheLight/9 WeenieDefaults/SQL/Creature/Fiun/28698 Fiun Rehlyun.sql
- Database/Patches/2008-08-AncientPowers/8 QuestDefDB/SocietyAugReward_0210.sql
Updated quest names surrounding Bellas to match retail so contract will function
Added contract
Sync Society aug timer to 6 days, down from 7.
To coincide with shard script.
> Add Bellas Aug Contract, Adjust Society Aug timer to 6 days

- Database/Patches/2009-10-GearsOfChange/9 WeenieDefaults/Gem/Gem/70378 Dull Aetherium Ore Fragment.sql
- Database/Patches/2010-03-LayOfTheLand/8 QuestDefDB/DullAetheriumCoreFragment.sql
Create pickup timer for Dull Aetherium Core Fragment, 20 hours
> Create pickup timer for Dull Aetherium Core Fragment

- Database/Patches/2008-03-FoolishAmbition/8 QuestDefDB/engravedashenkeypickuptimer.sql
> Updated Engraved Ashen key timer

- Database/Patches/2013-05-CuratingCorruption/6 LandBlockExtendedData/19BC.sql
- Database/Patches/2013-05-CuratingCorruption/6 LandBlockExtendedData/586E.sql
- Database/Patches/2013-05-CuratingCorruption/8 QuestDefDB/HiveWarriorPincer_0513.sql
- Database/Patches/2013-05-CuratingCorruption/8 QuestDefDB/chestchorizite51327.sql
- Database/Patches/2013-05-CuratingCorruption/9 WeenieDefaults/Chest/51327 Chorizite Chest Hive Warrior Mound.sql
- Database/Patches/2013-05-CuratingCorruption/9 WeenieDefaults/Clothing/Jewelry/51374 Bracelet of Storms.sql
- Database/Patches/2013-05-CuratingCorruption/9 WeenieDefaults/Creature/Elemental/72173 Lightning Cloud.sql
- Database/Patches/2013-05-CuratingCorruption/9 WeenieDefaults/Creature/Human/10842 Behdo Yii.sql
- Database/Patches/2013-05-CuratingCorruption/9 WeenieDefaults/Creature/Olthoi/51213 Olthoi Hive Warrior.sql
- Database/Patches/2013-05-CuratingCorruption/9 WeenieDefaults/Creature/Olthoi/51215 Olthoi Hive Warrior.sql
- Database/Patches/2013-05-CuratingCorruption/9 WeenieDefaults/Creature/Virindi/51314 Virindi Sentry.sql
- Database/Patches/2013-05-CuratingCorruption/9 WeenieDefaults/Gem/Gem/51216 Hive Gem of Dispelling.sql
- Database/Patches/2013-05-CuratingCorruption/9 WeenieDefaults/Gem/Gem/51437 Contract for Olthoi Hive Warrior Pincer.sql
- Database/Patches/2013-05-CuratingCorruption/9 WeenieDefaults/Generic/Misc/51214 Hive Warrior Pincer.sql
- Database/Patches/2013-05-CuratingCorruption/9 WeenieDefaults/Portal/51325 Hive Warrior Mound.sql
- Database/Patches/2013-05-CuratingCorruption/9 WeenieDefaults/Portal/51326 Surface.sql
Hive Warrior Pincer quest from 2013-05 Curating Corruption.
> Hive Warrior Pincer Quest

- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Food/Misc/30107 Refreshing Elixir.sql
> Update 30107 Refreshing Elixir.sql

- Database/Patches/2010-02-WintersKnight/8 QuestDefDB/gearxbowwait.sql
Changed from 6 days to 20 hours.
> Update Gear X Bow Wait Timer

- Database/Patches/2005-07-ThroneOfDestiny/6 LandBlockExtendedData/03FE.sql
- Resync landblock 03FE with PCAP
> Fix Mossy Cave

- Database/Patches/2006-09-ComeWhatFollows/9 WeenieDefaults/MeleeWeapon/33945 Enhanced Fetid Dirk.sql
- Add missing PhysicsState INT
> Update 33945 Enhanced Fetid Dirk.sql

- Database/Patches/2006-09-ComeWhatFollows/9 WeenieDefaults/Clothing/Armor/33949 Enhanced Gauntlets of Marksmanship.sql
Added Palette, changed ClothingBase.
> Update to Enhanced Gauntlets of Marksmanship

- Database/Patches/2005-09-UnderCoverOfNight/6 LandBlockExtendedData/C9E2.sql
Merwart Pelagurg was completed but wasn't added to LB.
> Added Merwart Pelagurg to LB

- Database/Patches/2005-08-FriendAndFoe/9 WeenieDefaults/Creature/HeaTumerok/31709 Hea Kassoka.sql
- Database/Patches/2005-08-FriendAndFoe/9 WeenieDefaults/Creature/HeaTumerok/31709_Hea_Kassoka.es
Hea Kassoka had text out of order and added delays, also extent to Say.
> Cleaned up Hea Kassoka Emotes

- Database/Patches/2009-02-UnfinishedBusiness/9 WeenieDefaults/Creature/Wisp/40127 Shivering Crystalline Wisp.sql
- Database/Patches/2009-02-UnfinishedBusiness/9 WeenieDefaults/Creature/Wisp/40128 Corroding Crystalline Wisp.sql
- Database/Patches/2009-02-UnfinishedBusiness/9 WeenieDefaults/Creature/Wisp/40129 Voltaic Crystalline Wisp.sql
- Database/Patches/2009-02-UnfinishedBusiness/9 WeenieDefaults/Creature/Wisp/40130 Crystalline Wisp.sql
- Database/Patches/2009-02-UnfinishedBusiness/9 WeenieDefaults/Creature/Wisp/40131 Incalescent Crystalline Wisp.sql
- Database/Patches/2009-02-UnfinishedBusiness/9 WeenieDefaults/Creature/Wisp/40134 Crystalline Wisp.sql
Lowered MagicD to match init_calc and raised light weapon skill to match.
> Balance to Low Level Wisps at Crag

- Database/Patches/2005-07-ThroneOfDestiny/6 LandBlockExtendedData/4AF6.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Ruschk/29342 Ruschk Laktar.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Ruschk/29343 Ruschk Draktehn.sql
- Database/Patches/2006-10-DanceOfTheDead/8 QuestDefDB/KillTaskRuschk_0301.sql
- Database/Patches/2006-10-DanceOfTheDead/8 QuestDefDB/ReceivedSmallIceTotem.sql
- Database/Patches/2006-10-DanceOfTheDead/9 WeenieDefaults/Creature/Human/34037 Commander Rylane di Cinghalle.sql
- Database/Patches/2006-10-DanceOfTheDead/9 WeenieDefaults/Creature/Human/34037_Commander_Rylane_di_Cinghalle.es
- Database/Patches/2006-10-DanceOfTheDead/9 WeenieDefaults/Creature/Ruschk/87219 Ruschk Totem Guardian.sql
- Database/Patches/2006-10-DanceOfTheDead/9 WeenieDefaults/Creature/Unsorted/87221 Ruschk Ice Totem.sql
- Database/Patches/2006-10-DanceOfTheDead/9 WeenieDefaults/Creature/Unsorted/87221_Ruschk_Ice_Totem.es
- Database/Patches/2006-10-DanceOfTheDead/9 WeenieDefaults/Generic/Misc/87220 Small Ruschk Ice Totem.sql
- Database/Patches/2007-02-RekindlingTheLight/9 WeenieDefaults/SQL/Creature/Ruschk/35153 Ruschk Draktehn.sql
**Added-**
KTs to critters
**Creatures:**
Ruschk Totem Guardian
**NPCs:**
Commander Rylane di Cinghalle
Ruschk Ice Totem
**Items:**
Small Ruschk Ice Totem
> Ruschk Kill Task

- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/ViamontianKnight/28653 Viamontian Knight.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/ViamontianKnight/30290 Viamontian Knight.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/ViamontianKnight/30856 Viamontian Knight.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Misc/34034 Alchemy Table.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Misc/34034_Alchemy_Table.es
- Database/Patches/2006-10-DanceOfTheDead/8 QuestDefDB/KillTaskTorgashsTasks_0301.sql
- Database/Patches/2006-10-DanceOfTheDead/8 QuestDefDB/ReceivedVialofstrangefluid.sql
- Database/Patches/2006-10-DanceOfTheDead/9 WeenieDefaults/Creature/Ruschk/34036 Torgash.sql
- Database/Patches/2006-10-DanceOfTheDead/9 WeenieDefaults/Creature/Ruschk/34036_Torgash.es
**Added-**
KTs to critters
**Items:**
Vial of strange fluid
**Updated:**
Torgash
Alchemy Table
> Torgash's Tasks

- Database/Patches/2011-05-LostCityOfNeftet/9 WeenieDefaults/Creature/Human/43911 Sakeenah Qureshi.sql
- Database/Patches/2011-05-LostCityOfNeftet/9 WeenieDefaults/Creature/Human/43911_Sakeenah_Qureshi.es
- Database/Patches/2011-05-LostCityOfNeftet/9 WeenieDefaults/Creature/Human/43940 Carlyle Wolnoth.sql
- Database/Patches/2011-05-LostCityOfNeftet/9 WeenieDefaults/Stackable/43912 Acid Natural Resistance.sql
- Database/Patches/2011-05-LostCityOfNeftet/9 WeenieDefaults/Stackable/43913 Fire Natural Resistance.sql
- Database/Patches/2011-05-LostCityOfNeftet/9 WeenieDefaults/Stackable/43914 Electrical Natural Resistance.sql
- Database/Patches/2011-05-LostCityOfNeftet/9 WeenieDefaults/Stackable/43919 Token of Resistance Augmentation Changing.sql
- Database/Patches/2011-05-LostCityOfNeftet/9 WeenieDefaults/Stackable/43920 Cold Natural Resistance.sql
- Database/Patches/2011-05-LostCityOfNeftet/9 WeenieDefaults/Stackable/43921 Slashing Natural Resistance.sql
- Database/Patches/2011-05-LostCityOfNeftet/9 WeenieDefaults/Stackable/43922 Piercing Natural Resistance.sql
- Database/Patches/2011-05-LostCityOfNeftet/9 WeenieDefaults/Stackable/43923 Bludgeon Natural Resistance.sql
**Added-**
**NPC's:**
Sakeenah Qureshi
Carlyle Wolnoth
**Items:**
Token of Resistance Augmentation Changing
Acid Natural Resistance 
Fire Natural Resistance 
Cold Natural Resistance 
Electrical Natural Resistance 
Bludgeon Natural Resistance
Piercing Natural Resistance 
Slashing Natural Resistance
> Resistance Augmentation Changing

- Database/Patches/2007-10-Masked Memories/9 WeenieDefaults/Gem/Gem/36499 Dark Monolith Caverns.sql
Colosseum Coin Collector - Dark Monolith Caverns
> Create 36499 Dark Monolith Caverns.sql

- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Vendor/Creature/06856 Berkholt the Burly Barkeep.sql
Update Berkholt to EOR/PCAP from base,
Max health 45 -> 46
Add, 
The Zongo Papers - 32273
Lost Pet - 31311
Dark Dealings - 31384
Branwyn's Tears - 31982
A Shadow Spire on the Caul - 33181 (Weenie not in ACE World)
A Strange Swamp Temple - 34281 (Weenie not in ACE World)
Halls of Metos - 35043 (Weenie not in ACE World)
http://ac.yotesfan.com/compare/vendors.php
> Create 06856 Berkholt the Burly Barkeep.sql

- Database/Patches/2011-10-CloakOfDarkness/9 WeenieDefaults/Vendor/09504 Boddry the Chancy.sql
- Database/Patches/2011-10-CloakOfDarkness/9 WeenieDefaults/Vendor/09505 Ashadi bint Samaq.sql
- Database/Patches/2011-10-CloakOfDarkness/9 WeenieDefaults/Vendor/09506 Haya Su Ka.sql
Update Boddry the Chancy, Ashadi bint Samaq and Haya Su Ka to EOR/PCAP
http://ac.yotesfan.com/compare/vendors.php
> Update Boddry the Chancy, Ashadi bint Samaq and Haya Su Ka

- Database/Patches/2008-03-FoolishAmbition/9 WeenieDefaults/Creature/Human/87201 Celestial Illuminator.sql
> Missing Body Table on Celestial Illuminator

- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Eater/28639 Voracious Eater.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Eater/28640 Eater.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Eater/28642 Engorged Eater.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Monouga/04212 Tremendous Monouga.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Penguin/28658 Sycophantic Penguin.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Penguin/28659 Uber Penguin.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Penguin/28660 Uber Penguin.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Penguin/28661 Uber Penguin.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Penguin/28662 Penguin.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Penguin/28663 Arrogant Penguin.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Penguin/28665 Rebellious Penguin.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Ruschk/28668 Ruschk Warlord.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Thrungus/28672 Button Thrungus.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Thrungus/28673 Deathcap Thrungus.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Thrungus/28674 Enoki Thrungus.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Thrungus/28675 Portobello Thrungus.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Thrungus/28677 Thrungus.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Thrungus/28678 Beefsteak Thrungus.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/ViamontianKnight/28651 Viamontian Mercenary.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/ViamontianKnight/28652 Viamontian Tribune.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/ViamontianKnight/28653 Viamontian Knight.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/ViamontianKnight/28654 Viamontian Commander.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/ViamontianKnight/28655 Viamontian Hand.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/ViamontianKnight/28656 Viamontian Lord.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/ViamontianKnight/28657 Viamontian Man-at-Arms.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/ViamontianKnight/28716 Sir Bellas.sql
> Misc pcap updates to some creatures

- Database/Patches/2006-06-FromTheDarkestDepths/9 WeenieDefaults/Portal/33305 Northern Temple Catacombs.sql
- Database/Patches/2006-06-FromTheDarkestDepths/9 WeenieDefaults/Portal/33306 Western Temple Catacombs.sql
> Update to Raising Graels Island portals

- Database/Patches/2009-03-WhoWatchesTheVirindi/3 TreasureTable/02090.sql
- Database/Patches/2009-03-WhoWatchesTheVirindi/3 TreasureTable/02091.sql
- Database/Patches/2009-03-WhoWatchesTheVirindi/6 LandBlockExtendedData/SQL/2842.sql
- Database/Patches/2009-03-WhoWatchesTheVirindi/6 LandBlockExtendedData/SQL/2942.sql
- Database/Patches/2009-03-WhoWatchesTheVirindi/6 LandBlockExtendedData/SQL/8090.sql
- Database/Patches/2009-03-WhoWatchesTheVirindi/8 QuestDefDB/SQL/UncoverRenegadesComplete0309.sql
- Database/Patches/2009-03-WhoWatchesTheVirindi/8 QuestDefDB/SQL/UncoverRenegadesStarted0309.sql
- Database/Patches/2009-03-WhoWatchesTheVirindi/9 WeenieDefaults/Book/Misc/40489 Apostate Message Shard.sql
- Database/Patches/2009-03-WhoWatchesTheVirindi/9 WeenieDefaults/Book/Misc/40490 Apostate Orders.sql
- Database/Patches/2009-03-WhoWatchesTheVirindi/9 WeenieDefaults/Book/Misc/40491 Apostate Orders.sql
- Database/Patches/2009-03-WhoWatchesTheVirindi/9 WeenieDefaults/Creature/GotrokLugian/40492 Gotrok Aetherium Miner.sql
- Database/Patches/2009-03-WhoWatchesTheVirindi/9 WeenieDefaults/Creature/GotrokLugian/40493 Gotrok Mining Foreman.sql
- Database/Patches/2009-03-WhoWatchesTheVirindi/9 WeenieDefaults/Creature/Human/40488 Aruq ibn Balthar.sql
- Database/Patches/2009-03-WhoWatchesTheVirindi/9 WeenieDefaults/Creature/Human/40488_Aruq_ibn_Balthar.es
- Database/Patches/2009-03-WhoWatchesTheVirindi/9 WeenieDefaults/Creature/Tumerok/40496 Hea Apostate Warlord.sql
- Database/Patches/2009-03-WhoWatchesTheVirindi/9 WeenieDefaults/Creature/Virindi/40498 Apostate Master.sql
- Database/Patches/2009-03-WhoWatchesTheVirindi/9 WeenieDefaults/Creature/Virindi/40499 Apostate Servant.sql
- Database/Patches/2009-03-WhoWatchesTheVirindi/9 WeenieDefaults/Door/40500 Barracks Door.sql
- Database/Patches/2009-03-WhoWatchesTheVirindi/9 WeenieDefaults/Door/40501 Headquarters Door.sql
- Database/Patches/2009-03-WhoWatchesTheVirindi/9 WeenieDefaults/Key/40494 Apostate Citadel Barracks Key.sql
- Database/Patches/2009-03-WhoWatchesTheVirindi/9 WeenieDefaults/Key/40497 Apostate Citadel Headquarters Key.sql
- Database/Patches/2009-03-WhoWatchesTheVirindi/9 WeenieDefaults/Portal/40502 Apostate Citadel Barracks.sql
- Database/Patches/2009-03-WhoWatchesTheVirindi/9 WeenieDefaults/Portal/40503 Apostate Citadel Headquarters.sql
- Database/Patches/2009-03-WhoWatchesTheVirindi/9 WeenieDefaults/Portal/40504 Surface.sql
- Database/Patches/2009-03-WhoWatchesTheVirindi/9 WeenieDefaults/Portal/40505 Apostate Citadel Mines.sql
- Database/Patches/2011-06-StiringsInTheDark/9 WeenieDefaults/Gem/Gem/44399 Contract for Uncovering the Renegades.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Creature/Human/08266 Diyas al-Yat.sql
- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Creature/Human/08266_Diyas_al-Yat.es
**Added**
**Creatures:**
Gotrok Aetherium Miner
Gotrok Mining Foreman
Hea Apostate Warlord
Apostate Master
**Items:**
Keys
Portals
Doors
Apostate Message Shard
Apostate Orders (2)
**NPCs:**
Aruq ibn Balthar
Diyas al-Yat (Update)
> Uncovering the Renegades Quest

- Database/Patches/2011-05-LostCityOfNeftet/9 WeenieDefaults/Creature/Golem/44033 Burning Sands Golem.sql
- Database/Patches/2011-05-LostCityOfNeftet/9 WeenieDefaults/Creature/Golem/44034 Burning Sands Golem.sql
- Database/Patches/2011-05-LostCityOfNeftet/9 WeenieDefaults/Creature/Golem/87018 Small Sand Golem.sql
Changed WCID# of summoned Small Sand Golem to not clash with what is found on Ulgrim's Island.
> Added different Small Sand Golem

- Database/Patches/2008-01-Recollections/9 WeenieDefaults/Creature/Virindi/36931 Dream Marauder.sql
> XP Update 36931 Dream Marauder.sql

- Database/Patches/2011-12-PresentDilemma/9 WeenieDefaults/Clothing/Armor/22720 Ketnan.sql
- Database/Patches/2011-12-PresentDilemma/9 WeenieDefaults/Clothing/Armor/45033 Hoory Mattekar Over-robe Crate.sql
This is an update to the vendor that already exists (Ketnan) to sell the Hoory Mattekar Over-robe Crate as well as updated the Hoory Mattekar Over-robe Crate to appropriately spawn the robe.
[22720 Ketnan and 45033 Hoory Mattekar Over-robe Crate.zip](https://github.com/ACEmulator/ACE-World-16PY-Patches/files/6393320/22720.Ketnan.and.45033.Hoory.Mattekar.Over-robe.Crate.zip)
> Hoory Mattekar Over-robe Add

- Database/Patches/2011-04-DarkDeliveries/9 WeenieDefaults/Creature/Unsorted/43986 Menhir.sql
- Database/Patches/2011-04-DarkDeliveries/9 WeenieDefaults/Creature/Unsorted/43987 Menhir.sql
- Database/Patches/2011-04-DarkDeliveries/9 WeenieDefaults/Generic/87169 HaltDericostRitual StopGap Gen.sql
> Updates to Halt Dericost Ritual Quest

- Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/03962 Bound to the Law.sql
updated to match spell description, used by item 33622 - Jitte of Law
> update spell - Bound to the Law

- Database/Patches/2009-03-WhoWatchesTheVirindi/9 WeenieDefaults/Clothing/Armor/40446 Upgraded Enscorcelled Robe.sql
- Database/Patches/2009-03-WhoWatchesTheVirindi/9 WeenieDefaults/Clothing/Armor/40447 Upgraded Armsman's Robe.sql
- Database/Patches/2009-03-WhoWatchesTheVirindi/9 WeenieDefaults/Clothing/Armor/40448 Upgraded Marksman's Robe.sql
- Database/Patches/2012-02-MasterOfArms/9 WeenieDefaults/Clothing/Armor/29543 Armsman's Robe.sql
Updated Armsman's Robe 29543 to have the new buff spells from Master of Arms
> Create 29543 Armsman's Robe.sql

- Database/Patches/2006-08-ShatteringTheDark/9 WeenieDefaults/Clothing/Armor/33825 Sawato Bandit's Mask.sql
Correct clothing base, shade, and current mana.
> Update 33825 Sawato Bandit's Mask.sql

- Database/Patches/2007-03-AncientEnemies/9 WeenieDefaults/Generic/Armor/35295 Shield of Perfect Light.sql
> Update 35295 Shield of Perfect Light.sql

- Database/Patches/2006-07-TowardAncientShores/9 WeenieDefaults/Creature/Mukkir/33037 Vile Mukkir.sql
- Database/Patches/2006-07-TowardAncientShores/9 WeenieDefaults/Creature/Mukkir/33538 Fanatical Mukkir Ward Guardian.sql
Corrected palette template for 33037 Vile Mukkir and 33538 Fanatical Mukkir Ward Guardian.
> Corrected Mukkir Palette

- Database/Patches/2012-08-TheRisenPrincess/9 WeenieDefaults/Clothing/Armor/45960 Amateur Explorer Vambraces.sql
- Database/Patches/2012-08-TheRisenPrincess/9 WeenieDefaults/Clothing/Armor/45979 Seasoned Explorer Vambraces.sql
Note that existing versions of these will need to be updated to display proper dyed icons and appearance when placed in world.
> Fixed SETUP_DID on Explorer Vambrances

- Database/Patches/2009-12-GainingGround/6 LandBlockExtendedData/49A7.sql
Add Crafter of Greatblades for 2H Quiddity Weapon to landblock
> Add Crafter of Greatblades for 2H Quiddity Weapon

- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Portal/53445 Radiant Blood Gauntlet.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Portal/53446 Celestial Hand Gauntlet.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Portal/53447 Eldrytch Web Gauntlet.sql
Removing Quest Restriction for gauntlet portals per retail
> Remove Quest Restriction

- Database/Patches/2005-08-FriendAndFoe/9 WeenieDefaults/MeleeWeapon/31390 Raven Sabra.sql
- Update Raben Sabra from Slash only to Slash and Piercing for supporting pierce combat motion, without getting wrong DamageType
> Update 31390 Raven Sabra.sql

- Database/Patches/2008-06-Dispatch/9 WeenieDefaults/Creature/Unsorted/38024 Strange Pillar.sql
Change useradius to 10 to match PCAP
Change respawn from 3secs to 240secs to prevent exploitation and to match respawn time to similar weenies in ace world. 
Requires PR #3613 to work correctly. 
https://github.com/ACEmulator/ACE/pull/3613
> Update 38024 Strange Pillar.sql

- Database/Patches/2008-01-Recollections/9 WeenieDefaults/Generic/Misc/36921 Snownado.sql
add burden value 0 and use and long description to maych yotes.
http://ac.yotesfan.com/weenies/items/36921
> Update 36921 Snownado.sql

- Database/Patches/2007-05-ProdigalSons/6 LandBlockExtendedData/E922.sql
- Database/Patches/2007-05-ProdigalSons/6 LandBlockExtendedData/EB1D.sql
- Database/Patches/2007-05-ProdigalSons/8 QuestDefDB/KilltaskMosswartTownsfolkWait_0507.sql
- Database/Patches/2007-05-ProdigalSons/8 QuestDefDB/KilltaskMosswartTownsfolk_0507.sql
- Database/Patches/2007-05-ProdigalSons/9 WeenieDefaults/Creature/Human/35606 Corporal Massein.sql
- Database/Patches/2007-05-ProdigalSons/9 WeenieDefaults/Creature/Human/35606_Corporal_Massein.es
- Database/Patches/2007-05-ProdigalSons/9 WeenieDefaults/Creature/Mosswart/35389 Mosswart Townsfolk.sql
**Added:**
**Creatures**
Mosswart Townsfolk
**NPCs**
Corporal Massein
**LBs**
E922
> Mosswart Townsfolk Kill Task

- Database/Patches/2010-11-FromDarknessLight/8 QuestDefDB/JournalofaSoldierPickup.sql
- Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/Book/43517 Journal of a Soldier.sql
- Add pickup timer to Journal of a Soldier
> Soldiers journal fix

- Database/Patches/2006-03-DownTwistingPaths/8 QuestDefDB/PickedUpRuschkFuneraryFetish.sql
- Database/Patches/2006-03-DownTwistingPaths/8 QuestDefDB/PickedUpUmbralCrucibleBase.sql
- Database/Patches/2006-03-DownTwistingPaths/8 QuestDefDB/PickedUpUmbralCrucibleTop.sql
- Add missing quest pickup timer entries
> Add missing pickup timers

- Database/Patches/2007-02-RekindlingTheLight/9 WeenieDefaults/SQL/Creature/Harvest/36527 Pumpkin Vine.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Creature/Moarsman/38280 Brood Mother.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Creature/Moarsman/38282 Brood Mother.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Creature/Moarsman/38283 Brood Mother.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Creature/Moarsman/38293 Spawn Watcher.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Creature/Moarsman/38351 Gate Watcher.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Creature/Moarsman/38650 Blighted Grimy Moarsman.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Creature/Moarsman/38651 Blighted Mucky Moarsman.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Creature/Moarsman/38652 Blighted Scummy Moarsman.sql
- Database/Patches/2013-06-DreamsOfTorment/9 WeenieDefaults/Gem/Gem/51605 Contract for Journey To Madness.sql
> Minor PCAP Creaturetype fixes

- Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/Creature/Tusker/43594 Snow Tusker Leader.sql
- Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/Creature/Tusker/51350 Snow Tusker Leader.sql
Fixes the issue with Snow Tuskers in dungeon giving Luminance, count towards KT and giving T8 loot.  This removes Luminance Award, Killtask credit and changed from T8 loot to T7 loot for this dungeon
> Frozen Valley Tusker Den update

- Database/Patches/2009-12-GainingGround/9 WeenieDefaults/CraftTool/Gem/CraftAlchemyIntermediate/24683 Aqua Vitae.sql
- Update Aqua Vitae to match PCAP
> Update Aqua Vitae stacksize

- Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Vendor/Creature/42806 Barkeeper Benedetta.sql
create appearance, match to pcap, cleanup
> Update 42806 Barkeeper Benedetta.sql

- Database/Patches/2012-08-TheRisenPrincess/3 TreasureTable/DeathTreasure/DeathTreasureDID 1015.sql
For creatures in a T8 area that should be T7
> Create DeathTreasureDID 1015.sql

- Database/Patches/2014-01-ForcesOfNature/9 WeenieDefaults/Creature/Phyntos Wasp/52618 Brier Wasp Hive.sql
> Update 52618 Brier Wasp Hive.sql

- Database/Patches/2012-12-AGrowingTwilight/9 WeenieDefaults/Creature/Crystal/48723 Crystal.sql
> Update 48723 Crystal.sql

- Database/Patches/2012-12-AGrowingTwilight/9 WeenieDefaults/Creature/Crystal/48717 Crystal.sql
> Update 48717 Crystal.sql

- Database/Patches/2006-02-AChangeInTactics/9 WeenieDefaults/Book/70921 Atlan's Coded Notebook.sql
> Update 70921 Atlan's Coded Notebook.sql

- Database/Patches/2014-01-ForcesOfNature/9 WeenieDefaults/Creature/Anekshay/52583 A'nekshen Storm Caller.sql
- Database/Patches/2014-01-ForcesOfNature/9 WeenieDefaults/Creature/Anekshay/52585 A'nekshen Storm Reaver.sql
- Database/Patches/2014-01-ForcesOfNature/9 WeenieDefaults/Creature/Anekshay/52587 A'nekshen Thorn Dancer.sql
- Database/Patches/2014-01-ForcesOfNature/9 WeenieDefaults/Creature/Anekshay/52589 A'nekshen Thorn Reaver.sql
- Database/Patches/2014-01-ForcesOfNature/9 WeenieDefaults/Creature/Anekshay/53365 Wind Fury.sql
- Database/Patches/2014-01-ForcesOfNature/9 WeenieDefaults/Creature/Anekshay/72000 NightBrier.sql
- Database/Patches/2014-01-ForcesOfNature/9 WeenieDefaults/Creature/Anekshay/72189 A'nekshen Storm Corruptor.sql
- Database/Patches/2014-01-ForcesOfNature/9 WeenieDefaults/Creature/Anekshay/72190 A'nekshen Corrupt Thorn Reaver.sql
- Database/Patches/2014-01-ForcesOfNature/9 WeenieDefaults/Creature/Anekshay/72194 A'nekshen Corrupt Storm Reaver.sql
- Database/Patches/2014-01-ForcesOfNature/9 WeenieDefaults/Creature/Anekshay/72195 A'nekshen Thorn Corruptor.sql
- Database/Patches/2014-01-ForcesOfNature/9 WeenieDefaults/Creature/Elemental/52626 Oaken Guardian.sql
- Database/Patches/2014-01-ForcesOfNature/9 WeenieDefaults/Creature/Elemental/72001 Norshuntyr.sql
- Database/Patches/2014-01-ForcesOfNature/9 WeenieDefaults/Creature/Wisp/52627 Guardian Wisp.sql
- Database/Patches/2014-01-ForcesOfNature/9 WeenieDefaults/Creature/Wisp/52628 Corrupted Guardian Wisp.sql
- Database/Patches/2014-01-ForcesOfNature/9 WeenieDefaults/Creature/Zefir/52519 Zefir Thorn Stalker.sql
- Database/Patches/2014-01-ForcesOfNature/9 WeenieDefaults/Creature/Zefir/52575 Zefir Thorn Reaver.sql
Lowered special move probability from 0.2 to 0.1 on Taunt for all mobs.
> Viridian Rise Mob Revisions

- Database/Patches/2014-01-ForcesOfNature/9 WeenieDefaults/Creature/Unsorted/52986 Blossoming Nightbloom.es
- Database/Patches/2014-01-ForcesOfNature/9 WeenieDefaults/Creature/Unsorted/52986 Blossoming Nightbloom.sql
- Database/Patches/2014-01-ForcesOfNature/9 WeenieDefaults/Creature/Unsorted/53011 Amber Crystal.es
- Database/Patches/2014-01-ForcesOfNature/9 WeenieDefaults/Creature/Unsorted/53011 Amber Crystal.sql
- Database/Patches/2014-01-ForcesOfNature/9 WeenieDefaults/Creature/Unsorted/53060 Viridian Portal Area 0-1.es
- Database/Patches/2014-01-ForcesOfNature/9 WeenieDefaults/Creature/Unsorted/53060 Viridian Portal.sql
- Database/Patches/2014-01-ForcesOfNature/9 WeenieDefaults/Creature/Unsorted/53217 Corrupted Amber Crystal.es
- Database/Patches/2014-01-ForcesOfNature/9 WeenieDefaults/Creature/Unsorted/53217 Corrupted Amber Crystal.sql
Amber Crystal, Corrupted Amber Crystal and Blossoming Nightbloom now delete self after giving a reward.
Added viridian flag quest check to the Viridian Rise entrance portal.
> Amber Crystal and Nightbloom Updates

- Database/Patches/2006-02-AChangeInTactics/9 WeenieDefaults/Creature/Sclavus/24858 Issk.sql
- Database/Patches/2006-02-AChangeInTactics/9 WeenieDefaults/Creature/Virindi/24859 Vincadi.sql
- Add missing Shield skill reward to Issk
- Correct Diamond Heart item for Shield skill for Vincadi
> Harbinger Reward Corrections

- Database/Patches/2008-09-RisksAndRewards/6 LandBlockExtendedData/24C0.sql
- Database/Patches/2008-09-RisksAndRewards/8 QuestDefDB/KillTaskTentacleofTthuunWait_0908.sql
- Database/Patches/2008-09-RisksAndRewards/8 QuestDefDB/KillTaskTentacleofTthuun_0908.sql
- Database/Patches/2008-09-RisksAndRewards/8 QuestDefDB/PluckerofEyes_Repeat.sql
- Database/Patches/2008-09-RisksAndRewards/9 WeenieDefaults/Creature/Human/38820 Tamara du Cinghalle.sql
- Database/Patches/2008-09-RisksAndRewards/9 WeenieDefaults/Creature/Human/38820_Tamara_du_Cinghalle.es
- Database/Patches/2008-09-RisksAndRewards/9 WeenieDefaults/Creature/Sclavus/87480 Sclavus Acolyte of T'thuun.sql
- Database/Patches/2008-09-RisksAndRewards/9 WeenieDefaults/Creature/Slithis/38822 Eye-covered Tentacles of T'thuun.sql
- Database/Patches/2008-09-RisksAndRewards/9 WeenieDefaults/Creature/Slithis/38822_Eye-covered_Tentacles_of_Tthuun.es
- Database/Patches/2008-09-RisksAndRewards/9 WeenieDefaults/Creature/Slithis/38826 Eyestalk of T'thuun.sql
- Database/Patches/2008-09-RisksAndRewards/9 WeenieDefaults/Creature/Slithis/38827 Tendril of T'thuun.sql
- Database/Patches/2008-09-RisksAndRewards/9 WeenieDefaults/Creature/Slithis/38828 Tentacle of T'thuun.sql
- Database/Patches/2008-09-RisksAndRewards/9 WeenieDefaults/Creature/Slithis/39040 Tendril of T'thuun.sql
- Database/Patches/2008-09-RisksAndRewards/9 WeenieDefaults/Generic/Misc/87481 Plucked Eye of T'thuun.sql
- Database/Patches/2008-09-RisksAndRewards/9 WeenieDefaults/Missile/MissileWeapon/33459 Shadow Bolt.sql
**Added:**
**NPCs:**
Tamara du Cinghalle
Eye-covered Tentacles of T'thuun
**Creatures:**
Eyestalks and Tendrils/Tentacles
**Items:**
Plucked Eye of T'thuun
> Eye of T'thuun Quest

- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Portal/42923 Surface.sql
- Database/Patches/2010-05-Celebration/4 CraftTable/08522 Chunk of Ore.sql
- Database/Patches/2010-05-Celebration/6 LandBlockExtendedData/1203.sql
- Database/Patches/2010-05-Celebration/6 LandBlockExtendedData/200F.sql
- Database/Patches/2010-05-Celebration/8 QuestDefDB/ChunkyOre_TurnIns.sql
- Database/Patches/2010-05-Celebration/8 QuestDefDB/ChunkyOre_Wait.sql
- Database/Patches/2010-05-Celebration/8 QuestDefDB/WellBalancedLugianGreataxePickupTimer.sql
- Database/Patches/2010-05-Celebration/9 WeenieDefaults/CraftTool/Misc/42918 Ore Deposit.sql
- Database/Patches/2010-05-Celebration/9 WeenieDefaults/CraftTool/Misc/42920 Ore Deposit.sql
- Database/Patches/2010-05-Celebration/9 WeenieDefaults/CraftTool/Misc/42921 Ore Deposit.sql
- Database/Patches/2010-05-Celebration/9 WeenieDefaults/Creature/Elemental/42922 Water Elemental.sql
- Database/Patches/2010-05-Celebration/9 WeenieDefaults/Creature/Lugian/42929 Lugian Miner.sql
- Database/Patches/2010-05-Celebration/9 WeenieDefaults/Creature/Lugian/42929_Lugian_Miner.es
- Database/Patches/2010-05-Celebration/9 WeenieDefaults/Creature/Lugian/42930 Mine Foreman.sql
- Database/Patches/2010-05-Celebration/9 WeenieDefaults/Creature/Lugian/42930_Mine_Foreman.es
- Database/Patches/2010-05-Celebration/9 WeenieDefaults/Creature/Lugian/42931 Mine Chamberlain.sql
- Database/Patches/2010-05-Celebration/9 WeenieDefaults/Creature/Lugian/42931_Mine_Chamberlain.es
- Database/Patches/2010-05-Celebration/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/42932 Well-Balanced Lugian Greataxe.sql
- Database/Patches/2010-05-Celebration/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/42948 Well-Balanced Lugian Greataxe.sql
- Database/Patches/2010-05-Celebration/9 WeenieDefaults/Stackable/Misc/42875 Chunk of Ore.sql
**Added:**
**Quests:**
Chunky Ore Collection
Well-Balanced Lugian Greataxe Quest
**NPCs:**
Lugian Miner
Mine Foreman
Mine Chamberlain
**Items:**
Chunk of Ore
Ore Deposit
Well-Balanced Lugian Greataxe
**Creatures:**
Water Elemental
> Withered Atoll Lugian Mine

- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Human/11506 Zharalim.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Human/12186 Zharalim.sql
- Database/Patches/2008-02-TheBeastWithManyHeads/3 TreasureTable/03501.sql
- Database/Patches/2008-02-TheBeastWithManyHeads/8 QuestDefDB/SwordofSorokuPickupTimer.sql
- Database/Patches/2008-02-TheBeastWithManyHeads/9 WeenieDefaults/Clothing/Armor/87463 Shou-jen Jika-Tabi.sql
- Database/Patches/2008-02-TheBeastWithManyHeads/9 WeenieDefaults/Clothing/Armor/87464 Shou-jen Shozoku Sleeve Gauntlets.sql
- Database/Patches/2008-02-TheBeastWithManyHeads/9 WeenieDefaults/Clothing/Armor/87465 Shou-jen Shozoku Jacket.sql
- Database/Patches/2008-02-TheBeastWithManyHeads/9 WeenieDefaults/Clothing/Armor/87466 Shou-jen Shozoku Trousers.sql
- Database/Patches/2008-02-TheBeastWithManyHeads/9 WeenieDefaults/Creature/Human/00188 Bandit Mage.sql
- Database/Patches/2008-02-TheBeastWithManyHeads/9 WeenieDefaults/Creature/Human/01210 Mercenary.sql
- Database/Patches/2008-02-TheBeastWithManyHeads/9 WeenieDefaults/Creature/Human/01218 Thief.sql
- Database/Patches/2008-02-TheBeastWithManyHeads/9 WeenieDefaults/Creature/Human/37082 Tanada Soroku.sql
- Database/Patches/2008-02-TheBeastWithManyHeads/9 WeenieDefaults/Creature/Human/37084 Tanada Burrows Sapper.sql
- Database/Patches/2008-02-TheBeastWithManyHeads/9 WeenieDefaults/Creature/Human/37085 Tanada Burrows Enforcer.sql
- Database/Patches/2008-02-TheBeastWithManyHeads/9 WeenieDefaults/Gem/37088 Invitation to the Battle Burrows.sql
- Database/Patches/2008-02-TheBeastWithManyHeads/9 WeenieDefaults/MeleeWeapon/34344 Yaoji.sql
- Database/Patches/2008-02-TheBeastWithManyHeads/9 WeenieDefaults/MeleeWeapon/37083 Sword of Soroku.sql
**Added:**
**Creatures:**
Tanada Soroku
Tanada Burrows Sapper
Tanada Burrows Enforcer
**Items:**
Invitation to the Battle Burrows
Sword of Soroku
**Note:** Updated creatures that dropped the invitation.
> Tanada Battle Burrows Quest

- Database/Patches/2008-08-AncientPowers/8 QuestDefDB/KillTaskMcGreggorTentacleWait_0908.sql
- Database/Patches/2008-08-AncientPowers/8 QuestDefDB/KillTaskMcGreggorTentacle_0908.sql
- Database/Patches/2008-08-AncientPowers/8 QuestDefDB/WeedingoftheDeruTree_Repeat.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Creature/Human/80439 Valerian McGreggor.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Creature/Human/80439_Valerian_McGreggor.es
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Creature/Slithis/38825 Tentacle of T'thuun.sql
- Database/Patches/2008-09-RisksAndRewards/6 LandBlockExtendedData/F732.sql
Updated Valerian McGreggor
Added KillTask to Tentacle
> Weeding of the Deru Tree

- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Creature/Human/38461 Arcanum Mana-smith.es
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Creature/Human/38461 Arcanum Mana-smith.sql
Added turn in for 38880 Lord Grymar's Ancient Emblem of Mhoire.
> Update 38461 Arcanum Mana-smith

- Database/Patches/2014-01-ForcesOfNature/4 CraftTable/08913 Luminous Amber Helm of Healing.sql
- Correct the recipeID in the recipe for Luminous Amber Helm of Healing
> Update 08913 Luminous Amber Helm of Healing.sql

- Database/Patches/2012-06-NobleSacrifice/9 WeenieDefaults/Creature/Virindi/45856 Virindi Keeper.sql
- Database/Patches/2012-06-NobleSacrifice/9 WeenieDefaults/Creature/Virindi/45859 Virindi Guard.sql
- Database/Patches/2012-06-NobleSacrifice/9 WeenieDefaults/Creature/Virindi/45897 Virindi Jailor.sql
- Database/Patches/2012-06-NobleSacrifice/9 WeenieDefaults/Creature/Virindi/45899 Virindi Jailor.sql
- Database/Patches/2012-06-NobleSacrifice/9 WeenieDefaults/Creature/Virindi/45901 Virindi Jailor.sql
Reduced Virindi Keeper, Guard and Jailor skills found in the Virindi Rescue quest based on pcap values.
> Virindi Rescue Nerf

- Database/Patches/2008-02-TheBeastWithManyHeads/6 LandBlockExtendedData/00A6.sql
- Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/04247 Tanada Battle Burrows Portal Sending.sql
Updated Portal sending, added LB.
> Tanada Battle Burrows Updates

- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Human/29094 Portal Guardian.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Human/29094_Portal_Guardian.es
Added TurnToTarget on give and ES file.
> Portal Guardian Update

- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Creature/Sclavus/38592 Vaeshok.sql
upped the al on body parts, adjusted resists
> Update 38592 Vaeshok.sql

- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Creature/Moarsman/38280 Brood Mother.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Creature/Moarsman/38281 Brood Mother.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Creature/Moarsman/38282 Brood Mother.sql
- Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Creature/Moarsman/38283 Brood Mother.sql
- DirectBroadcast: You have cleared out this Spawning Pool for now.
> added on death message

- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/MeleeWeapon/48584 Icy Club.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/MeleeWeapon/48588 Glacial Blade.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Missile/48586 Ice Shard.sql
http://ac.yotesfan.com/weenies/items/48586
http://ac.yotesfan.com/weenies/items/48588
> vaeshok weapon change per pcap

- Database/Patches/2013-10-ShatteredMasks/9 WeenieDefaults/Caster/51989 Rynthid Tentacle Wand.sql
- Database/Patches/2013-10-ShatteredMasks/9 WeenieDefaults/Caster/51990 Life-attuned Rynthid Tentacle Wand.sql
- Database/Patches/2013-10-ShatteredMasks/9 WeenieDefaults/Caster/51991 Nether-attuned Rynthid Tentacle Wand.sql
- Add missing DefaultCombatStyle - Magic to Rynthid wand
- Remove extraneous properties from three Rynthid wands
> Rynthid wands

- Database/Patches/2005-08-FriendAndFoe/9 WeenieDefaults/Creature/Human/31376 Sarkin Killcrane.sql
- Add missing Fragment of Yaja's Arm turn-in
> Update 31376 Sarkin Killcrane.sql

- Database/Patches/2013-10-ShatteredMasks/9 WeenieDefaults/Creature/Human/52139 Varinia.sql
Adds the NPC Varinia to Arwic. 
She's already part of the landblock instance, so only adding the weenie itself is needed.
> Add Varinia

- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Human/05694 Fanzen San the Translator.sql
- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Human/05694_Fanzen_San_the_Translator.es
> Fanzen San the Translator Fix

- Database/Patches/2010-11-FromDarknessLight/8 QuestDefDB/BloodstoneFactoryLargeTomePickup.sql
- Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/Book/43810 Large Tome.sql
- Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/Creature/Undead/70364 Lord Kastellar.sql
The previous version of the large tome had UNIQUE_INT set which wasn't backed up by Wiki or log file. Removed this and added a quest timer...
> Fixed Large Tome drop on Lord Kastellar, added quest flag

- Database/Patches/2011-11-MasterOfDesign/9 WeenieDefaults/Creature/Human/44999 Sir Daeglan.sql
Previous updated included the correct .ES script for this NPC, but the actual NPC Weenie was not properly updated with that ES.
> Updated out-of-date Sir Deaglan

- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/MeleeWeapon/45534 Training Hand Axe.sql
- Add missing DefaultCombatStyle - OneHanded property
> Training Hand Axe Fix

- Database/Patches/2013-05-CuratingCorruption/6 LandBlockExtendedData/23BC.sql
- Database/Patches/2013-05-CuratingCorruption/6 LandBlockExtendedData/586D.sql
- Database/Patches/2013-05-CuratingCorruption/8 QuestDefDB/HiveEvisPincer_0513.sql
- Database/Patches/2013-05-CuratingCorruption/8 QuestDefDB/chestchorizite51323.sql
- Database/Patches/2013-05-CuratingCorruption/9 WeenieDefaults/Chest/51323 Chorizite Chest Hive Eviscerator Burrow.sql
- Database/Patches/2013-05-CuratingCorruption/9 WeenieDefaults/Clothing/Jewelry/51373 Bracelet of Thorns.sql
- Database/Patches/2013-05-CuratingCorruption/9 WeenieDefaults/Creature/Human/10842 Behdo Yii.sql
- Database/Patches/2013-05-CuratingCorruption/9 WeenieDefaults/Creature/Olthoi/51210 Olthoi Hive Eviscerator.sql
- Database/Patches/2013-05-CuratingCorruption/9 WeenieDefaults/Creature/Olthoi/51212 Olthoi Hive Eviscerator.sql
- Database/Patches/2013-05-CuratingCorruption/9 WeenieDefaults/Gem/Gem/51438 Contract for Olthoi Hive Eviscerator Pincer.sql
- Database/Patches/2013-05-CuratingCorruption/9 WeenieDefaults/Generic/Misc/51211 Hive Eviscerator Pincer.sql
- Database/Patches/2013-05-CuratingCorruption/9 WeenieDefaults/Portal/51321 Hive Eviscerator Burrow.sql
- Database/Patches/2013-05-CuratingCorruption/9 WeenieDefaults/Portal/51322 Surface.sql
Adds the Olthoi Hive Eviscerator Pincer Quest. Includes additions of olthoi hive eviscerators, pincer, dungeon, contract, and reward bracelet, plus modifications to Behdo Yii to give rewards.
> Olthoi Hive Eviscerator Pincer Quest

- Database/Patches/2007-08-CorruptedSovereigns/9 WeenieDefaults/Creature/Tusker/35941 Dark Bobo.sql
**All your nerf are belong to us**
> Nerf Dark Bobo

- Database/Patches/2007-01-BridgingTheVastDivide/9 WeenieDefaults/MeleeWeapon/34580 Stone Axe.sql
- Database/Patches/2007-01-BridgingTheVastDivide/9 WeenieDefaults/MeleeWeapon/34584 Guruk Fist.sql
- Database/Patches/2007-02-RekindlingTheLight/4 CraftTable/08504 Alembic Mucor.sql
- Database/Patches/2007-02-RekindlingTheLight/4 CraftTable/08505 Mucor-altered Granite.sql
- Database/Patches/2007-02-RekindlingTheLight/4 CraftTable/08506 Mucor-altered Mahogany.sql
- Database/Patches/2007-02-RekindlingTheLight/4 CraftTable/08507 Mucor-altered Opal.sql
- Database/Patches/2007-02-RekindlingTheLight/4 CraftTable/08508 Channeling Bone Sword.sql
- Database/Patches/2007-02-RekindlingTheLight/4 CraftTable/08509 Channeling Stone Axe.sql
- Database/Patches/2007-02-RekindlingTheLight/4 CraftTable/08510 Channeling Bone Dagger.sql
- Database/Patches/2007-02-RekindlingTheLight/4 CraftTable/08511 Channeling Guruk Fist.sql
- Database/Patches/2007-02-RekindlingTheLight/4 CraftTable/08512 Channeling Stone Mace.sql
- Database/Patches/2007-02-RekindlingTheLight/4 CraftTable/08513 Channeling Stone Spear.sql
- Database/Patches/2007-02-RekindlingTheLight/4 CraftTable/08514 Channeling Repugnant Staff.sql
- Database/Patches/2007-02-RekindlingTheLight/4 CraftTable/08515 Channeling Bone Bow.sql
- Database/Patches/2007-02-RekindlingTheLight/4 CraftTable/08516 Channeling Bone Crossbow.sql
- Database/Patches/2007-02-RekindlingTheLight/4 CraftTable/08517 Opal Repugnant Staff.sql
- Database/Patches/2007-02-RekindlingTheLight/9 WeenieDefaults/Caster/Caster/34991 Opal Repugnant Staff.sql
- Database/Patches/2007-02-RekindlingTheLight/9 WeenieDefaults/CraftTool/Misc/34965 Mucor-altered Mahogany.sql
- Database/Patches/2007-02-RekindlingTheLight/9 WeenieDefaults/CraftTool/Misc/87420 Alembic Mucor.sql
- Database/Patches/2007-02-RekindlingTheLight/9 WeenieDefaults/CraftTool/Misc/87421 Mucor-altered Granite.sql
- Database/Patches/2007-02-RekindlingTheLight/9 WeenieDefaults/CraftTool/Misc/87422 Mucor-altered Opal.sql
- Database/Patches/2007-02-RekindlingTheLight/9 WeenieDefaults/MeleeWeapon/34994 Channeling Stone Axe.sql
- Database/Patches/2007-02-RekindlingTheLight/9 WeenieDefaults/MeleeWeapon/34998 Channeling Guruk Fist.sql
- Database/Patches/2007-02-RekindlingTheLight/9 WeenieDefaults/MeleeWeapon/87423 Channeling Bone Dagger.sql
- Database/Patches/2007-02-RekindlingTheLight/9 WeenieDefaults/MeleeWeapon/87424 Channeling Stone Mace.sql
- Database/Patches/2007-02-RekindlingTheLight/9 WeenieDefaults/MeleeWeapon/87425 Channeling Stone Spear.sql
- Database/Patches/2007-02-RekindlingTheLight/9 WeenieDefaults/MeleeWeapon/87426 Channeling Repugnant Staff.sql
- Database/Patches/2007-02-RekindlingTheLight/9 WeenieDefaults/MissileLauncher/MissileWeapon/34995 Channeling Bone Bow.sql
- Database/Patches/2007-02-RekindlingTheLight/9 WeenieDefaults/MissileLauncher/MissileWeapon/34999 Channeling Stone Hatchet.sql
- Database/Patches/2007-02-RekindlingTheLight/9 WeenieDefaults/MissileLauncher/MissileWeapon/87427 Channeling Bone Crossbow.sql
Recipes...... Also added items that I forgot.....
> Added Recipes for Mucor Enhanced

- Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Portal/41233 Reaving Facility.sql
- Database/Patches/2008-04-UppingTheAnte/6 LandBlockExtendedData/00D9.sql
- Database/Patches/2008-04-UppingTheAnte/6 LandBlockExtendedData/0F38.sql
- Database/Patches/2009-05-SecretsOfTheApostates/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/40616 Fire Spadone.sql
- Database/Patches/2009-09-CogsintheMachine/6 LandBlockExtendedData/3FB1.sql
- Database/Patches/2009-09-CogsintheMachine/6 LandBlockExtendedData/CE95.sql
- Database/Patches/2009-09-CogsintheMachine/8 QuestDefDB/AetheriumCoreFragmentPickupTimer.sql
- Database/Patches/2009-09-CogsintheMachine/8 QuestDefDB/UnleashGearKnightComplete0909.sql
- Database/Patches/2009-09-CogsintheMachine/8 QuestDefDB/UnleashGearKnightStart0909.sql
- Database/Patches/2009-09-CogsintheMachine/9 WeenieDefaults/Creature/GearKnight/41224 Iron Blade Lieutenant.sql
- Database/Patches/2009-09-CogsintheMachine/9 WeenieDefaults/Creature/GearKnight/41224_Iron_Blade_Lieutenant.es
- Database/Patches/2009-09-CogsintheMachine/9 WeenieDefaults/Creature/GearKnight/41228 Iron Blade Arrival Guard.sql
- Database/Patches/2009-09-CogsintheMachine/9 WeenieDefaults/Creature/Human/41227 Hei Shou.sql
- Database/Patches/2009-09-CogsintheMachine/9 WeenieDefaults/Creature/Human/41227_Hei_Shou.es
- Database/Patches/2009-09-CogsintheMachine/9 WeenieDefaults/Creature/Simulacrum/41231 Reaver Simulacrum.sql
- Database/Patches/2009-09-CogsintheMachine/9 WeenieDefaults/Creature/Virindi/41229 Apostate Reaving Master.sql
- Database/Patches/2009-09-CogsintheMachine/9 WeenieDefaults/Creature/Virindi/41229_Apostate_Reaving_Master.es
- Database/Patches/2009-09-CogsintheMachine/9 WeenieDefaults/Door/41232 Arrival Chamber.sql
- Database/Patches/2009-09-CogsintheMachine/9 WeenieDefaults/Generic/Misc/41226 Aetherium Core Fragment.sql
- Database/Patches/2009-09-CogsintheMachine/9 WeenieDefaults/Key/41230 Arrival Chamber Key.sql
- Database/Patches/2009-09-CogsintheMachine/9 WeenieDefaults/Portal/41234 Arrival Chamber.sql
- Database/Patches/2009-09-CogsintheMachine/9 WeenieDefaults/Portal/41235 Surface.sql
- Database/Patches/2012-10-SeedsofHope/9 WeenieDefaults/Gem/46908 Contract for Unleash the Gearknights.sql
**Needs WieldedTreasureType from PR# 963**
**Added:**
**NPCs:**
Hei Shou
**Creatures:**
Iron Blade Lieutenant
Iron Blade Arrival Guard
Apostate Reaving Master
Reaver Simulacrum
**Items:**
Aetherium Core Fragment
Arrival Chamber Key
Arrival Chamber Door
Portal(s)
Contract
> Unleash the Gearknights Quest

- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/05753 Pickaxe.sql
- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/07580 Pickaxe.sql
- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/25469 Hiyp the Toad's pickaxe.sql
- Update the skills to MoA on pickaxes, per PCAP data
> Update Skills on pickaxes

- Database/Patches/4 CraftTable/08102 Skeletal Falatacot Key.sql
Changed Recipe ID / deleted what flatten created.
> Fixed Skeletal Falatacot Key Recipe

- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/35407 Burnja's Board with Nails.sql
- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/37083 Sword of Soroku.sql
- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/37402 Club of Surprising Cunning.sql
- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/40088 Empowered Sword of Lost Light.sql
- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/42932 Well-Balanced Lugian Greataxe.sql
- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/42948 Well-Balanced Lugian Greataxe.sql
- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/87477 Club of Remarkable Cunning.sql
> Fixed Weapon Crit Frequency

- Database/Patches/9 WeenieDefaults/Missile/MissileWeapon/52733 Vortex Thorn.sql
> Update 52733 Vortex Thorn

- Database/Patches/9 WeenieDefaults/Generic/Misc/41226 Aetherium Core Fragment.sql
Added description / Attuned/Bonded
> Update Aetherium Core Fragment

- Database/Patches/9 WeenieDefaults/Creature/Golem/48924 Clay Golem Kachi.sql
- Database/Patches/9 WeenieDefaults/Creature/Golem/48925 Bronze Golem Kachi.sql
- Database/Patches/9 WeenieDefaults/Creature/Golem/48926 Iron Golem Kachi.sql
- Database/Patches/9 WeenieDefaults/Creature/Golem/48929 Bronze Golem Sekkou.sql
> Save Karul Bug Fixes

- Database/Patches/9 WeenieDefaults/Creature/Unsorted/35103 Corpse of a Servitor of Asheron.sql
- Database/Patches/9 WeenieDefaults/Creature/Unsorted/35103_Corpse_of_a_Servitor_of_Asheron.es
- Database/Patches/9 WeenieDefaults/Creature/Unsorted/35104 Corpse of a Servitor of Asheron.sql
- Database/Patches/9 WeenieDefaults/Creature/Unsorted/35104_Corpse_of_a_Servitor_of_Asheron.es
Changed from Generation: Dead to Heartbeat: Dead....
> Update Corpse of a Servitor of Asheron

- Database/Patches/8 QuestDefDB/PortalServitorItemsStarted.sql
- Database/Patches/9 WeenieDefaults/Creature/Golem/34467 Portal Servitor.sql
- Database/Patches/9 WeenieDefaults/Creature/Golem/34467_Portal_Servitor.es
Made it so it matched retail meta.
> Update to Portal Servitor

- Database/Patches/6 LandBlockExtendedData/934B.sql
- Database/Patches/8 QuestDefDB/GearKnightConstructionCompletedKaytin.sql
- Database/Patches/8 QuestDefDB/GearKnightConstructionCompletedTakahume.sql
- Database/Patches/8 QuestDefDB/GearKnightConstructionTurnInsKaytin.sql
- Database/Patches/8 QuestDefDB/GearKnightConstructionTurnInsTakahume.sql
- Database/Patches/9 WeenieDefaults/Creature/GearKnight/42601.es
- Database/Patches/9 WeenieDefaults/Creature/Human/42116 Master Craftsman Takahume.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/42116.es
Adds the Gear Knight Construction Quest (post-server quest version), with updates to Kaytin and the addition of Master Takahume. 
It was easier to remake the PR instead of fixing the other one apparently.
> Gear Knight Construction Quest

- Database/Patches/6 LandBlockExtendedData/004F.sql
- Database/Patches/6 LandBlockExtendedData/3EF6.sql
- Database/Patches/8 QuestDefDB/BlackSpearIceTotemCompleted.sql
- Database/Patches/8 QuestDefDB/BlackSpearIceTotemStarted.sql
- Database/Patches/8 QuestDefDB/BlackSpearIceTotem_Pickup.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/34062 Arialle du Bellenesse.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/34062_Arialle_du_Bellenesse.es
- Database/Patches/9 WeenieDefaults/Creature/Ruschk/34063 Kalakh.sql
- Database/Patches/9 WeenieDefaults/Creature/Ruschk/34063_Kalakh.es
- Database/Patches/9 WeenieDefaults/Generic/Misc/87632 Black Spear Ice Totem.sql
- Database/Patches/9 WeenieDefaults/Generic/None/87628 TotBS Mukkir Generator.sql
- Database/Patches/9 WeenieDefaults/Generic/None/87629 TotBS Ruschk Generator.sql
- Database/Patches/9 WeenieDefaults/Generic/None/87630 TotBS Shadow Generator.sql
- Database/Patches/9 WeenieDefaults/Portal/Portal/87627 Temple of the Black Spear.sql
- Database/Patches/9 WeenieDefaults/Portal/Portal/87631 Temple Exit.sql
**Added:**
**NPCs:**
Arialle du Bellenesse
Kalakh
**Items:**
Black Spear Ice Totem
Portal(s)
**Dungeons:**
Temple of the Black Spear
> The Black Spear Ice Totem

- Database/Patches/6 LandBlockExtendedData/0015.sql
- Database/Patches/6 LandBlockExtendedData/0016.sql
- Database/Patches/6 LandBlockExtendedData/0017.sql
- Database/Patches/6 LandBlockExtendedData/1A13.sql
- Database/Patches/6 LandBlockExtendedData/1A1E.sql
- Database/Patches/6 LandBlockExtendedData/1C1A.sql
- Database/Patches/6 LandBlockExtendedData/1D13.sql
- Database/Patches/6 LandBlockExtendedData/2111.sql
- Database/Patches/9 WeenieDefaults/Creature/Banderling/35830 Withered Banderling Paragon.sql
- Database/Patches/9 WeenieDefaults/Creature/Drudge/35831 Withered Drudge Seraph Mystic.sql
- Database/Patches/9 WeenieDefaults/Creature/GotrokLugian/35832 Withered Raider Justicar.sql
- Database/Patches/9 WeenieDefaults/Creature/GotrokLugian/35833 Withered Raider Prefect.sql
- Database/Patches/9 WeenieDefaults/Creature/GotrokLugian/35834 Withered Raider Prefect.sql
- Database/Patches/9 WeenieDefaults/Creature/Tumerok/35835 Withered Transcendent Tumerok.sql
- Database/Patches/9 WeenieDefaults/Creature/Tumerok/87276 Withered Revered Tumerok Shaman.sql
- Database/Patches/9 WeenieDefaults/Generic/None/87417 Withered Atoll Tumerok Generator.sql
**Updated Quests and LBs to EoR**
Updates done in Friends and Foe Patch. 
[http://acpedia.org/wiki/Withered_Weapons_Quest](url)
> Withered Weapons Quest Updates

- Database/Patches/9 WeenieDefaults/CraftTool/TinkeringMaterial/36570 Salvage.sql
- Database/Patches/9 WeenieDefaults/CraftTool/TinkeringMaterial/87422 Mucor-altered Opal.sql
> Update Salvage Bag Icons

- Database/Patches/9 WeenieDefaults/Creature/Human/08266 Diyas al-Yat.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/08266.es
Now handles 36212 and 36213 message shards from the Artifex Collegium.
http://acpedia.org/wiki/Artifex_Collegium
The actual Artifex Collegium dungeon, shards, and translations are in PR #1173.
> Update 08266 Diyas al-Yat

- Database/Patches/6 LandBlockExtendedData/462F.sql
- Database/Patches/6 LandBlockExtendedData/8C03.sql
- Database/Patches/8 QuestDefDB/KidnapPrincessComplete_0410.sql
- Database/Patches/8 QuestDefDB/KidnapPrincessStarted_0410.sql
- Database/Patches/8 QuestDefDB/SpokeAyanameChiyoko.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/42731 Ayaname Chiyoko.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/42731.es
- Database/Patches/9 WeenieDefaults/Creature/Human/42734 Sir Draithon.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/42734.es
- Database/Patches/9 WeenieDefaults/Creature/Human/72742 Floating Tower Stopgap.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/72742.es
- Database/Patches/9 WeenieDefaults/Creature/Human/72744 Floating Tower Ground Stopgap.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/72744.es
- Database/Patches/9 WeenieDefaults/Creature/Undead/42727 Wight Kidnapper.sql
- Database/Patches/9 WeenieDefaults/Creature/Undead/42727.es
- Database/Patches/9 WeenieDefaults/Gem/Gem/42729 Attuned Essence Gem.sql
- Database/Patches/9 WeenieDefaults/Gem/Gem/45758 Contract for Kidnapped Handmaiden.sql
- Database/Patches/9 WeenieDefaults/Generic/Gem/72741 Vile Potion.sql
- Database/Patches/9 WeenieDefaults/Portal/Portal/72743 Gateway.sql
Adds the quest:
http://acpedia.org/wiki/Kidnapped_Handmaiden
> Kidnapped Handmaiden Quest

- Database/Patches/8 QuestDefDB/VisionQuestRepeat1007.sql
- Database/Patches/9 WeenieDefaults/Creature/Virindi/08155 Leopold.sql
- Database/Patches/9 WeenieDefaults/Creature/Virindi/8155.es
Added Shadowy Virindi Essence turn in.
> Leopold Update

- Database/Patches/9 WeenieDefaults/Creature/Human/87704 Tanada Han-Tu.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/87704.es
Adds the title reward to the Tanada House of Fire quest
> Tanada House of Fire Title Reward

- Database/Patches/9 WeenieDefaults/Book/Writable/35565 Observations_ Harraag.sql
- Database/Patches/9 WeenieDefaults/Book/Writable/35566 Observations_ Harraag.sql
Adds the fourth page to the Observations: Harraag books from the Archivist quest.
> Archivist Books Page Fix

- Database/Patches/6 LandBlockExtendedData/0051.sql
- Database/Patches/6 LandBlockExtendedData/0061.sql
- Database/Patches/6 LandBlockExtendedData/0063.sql
- Database/Patches/6 LandBlockExtendedData/A5D3.sql
- Database/Patches/8 QuestDefDB/EasternPedestalShard_Pickup.sql
- Database/Patches/8 QuestDefDB/NorthernPedestalShard_Pickup.sql
- Database/Patches/8 QuestDefDB/WesternPedestalShard_Pickup.sql
- Database/Patches/9 WeenieDefaults/Creature/Unknown/34743 Northern Pedestal.sql
- Database/Patches/9 WeenieDefaults/Creature/Unknown/34743.es
- Database/Patches/9 WeenieDefaults/Creature/Unknown/34744 Western Pedestal.sql
- Database/Patches/9 WeenieDefaults/Creature/Unknown/34744.es
- Database/Patches/9 WeenieDefaults/Creature/Unknown/34746 Eastern Pedestal.sql
- Database/Patches/9 WeenieDefaults/Creature/Unknown/34746.es
- Database/Patches/9 WeenieDefaults/Door/Misc/87761 Door.sql
- Database/Patches/9 WeenieDefaults/Generic/Misc/34731 Magical Orb.sql
- Database/Patches/9 WeenieDefaults/Generic/Misc/87755 Shard of the Western Pedestal.sql
- Database/Patches/9 WeenieDefaults/Generic/Misc/87756 Shard of the Eastern Pedestal.sql
- Database/Patches/9 WeenieDefaults/Generic/Misc/87757 Shard of the Northern Pedestal.sql
- Database/Patches/9 WeenieDefaults/Generic/None/87759 Northern Pedestal Dungeon Generator.sql
- Database/Patches/9 WeenieDefaults/Generic/None/87760 Northern Pedestal Dungeon Ghost Generator.sql
- Database/Patches/9 WeenieDefaults/Generic/None/87764 Western Pedestal Dungeon Generator.sql
- Database/Patches/9 WeenieDefaults/Generic/None/87765 Western Pedestal Dungeon Ghost Generator.sql
- Database/Patches/9 WeenieDefaults/Generic/None/87767 Eastern Pedestal Dungeon Generator.sql
- Database/Patches/9 WeenieDefaults/Generic/None/87768 Eastern Pedestal Dungeon Ghost Generator.sql
- Database/Patches/9 WeenieDefaults/HotSpot/Misc/87762 Cold Air.sql
- Database/Patches/9 WeenieDefaults/Portal/Portal/87758 Northern Pedestal Dungeon.sql
- Database/Patches/9 WeenieDefaults/Portal/Portal/87763 Western Pedestal Dungeon.sql
- Database/Patches/9 WeenieDefaults/Portal/Portal/87766 Eastern Pedestal Dungeon.sql
**Added:**
Western Pedestal Dungeon
Eastern Pedestal Dungeon
Northern Pedestal Dungeon
> Bur Portal Summoning

- Database/Patches/9 WeenieDefaults/Caster/Caster/43848 Heart of Darkest Flame.sql
https://github.com/ACEmulator/ACE/pull/3753
updating crit freq from .15 to .4
> Update heart of darkest flame

- Database/Patches/9 WeenieDefaults/Generic/Misc/44738 Golem.sql
- Database/Patches/9 WeenieDefaults/Generic/Misc/44750 Moar.sql
- Database/Patches/9 WeenieDefaults/Generic/Misc/44759 Rat.sql
- Database/Patches/9 WeenieDefaults/Generic/Misc/44762 Ruschk.sql
- Database/Patches/9 WeenieDefaults/Generic/Misc/44768 Simulacrum.sql
- Database/Patches/9 WeenieDefaults/Generic/Misc/44777 Tusker.sql
- Database/Patches/9 WeenieDefaults/Generic/Misc/44783 Zefir.sql
Added the missing paintings for Casino.
> Missing Casino Paintings

- Database/Patches/9 WeenieDefaults/Book/Writable/32226 Mistress Gabille's Notes.sql
- Database/Patches/9 WeenieDefaults/Book/Writable/32229 Master Vaserio's Notes.sql
- Database/Patches/9 WeenieDefaults/Book/Writable/70048 To My Dear Uncle.sql
- Database/Patches/9 WeenieDefaults/Book/Writable/70049 A Warning.sql
- Database/Patches/9 WeenieDefaults/Book/Writable/70050 Augmentation.sql
- Database/Patches/9 WeenieDefaults/Book/Writable/70272 Mistress Halmera's Notes.sql
- Database/Patches/9 WeenieDefaults/Book/Writable/70274 Master Alizari's Notes.sql
Adds page number data for books from Faces of the Mukkir and Enrico's Betrayal
> Fix page number data for several books

- Database/Patches/8 QuestDefDB/GaveJailerPyramid.sql
- Database/Patches/9 WeenieDefaults/Creature/Ghost/37145 Jailer.sql
- Database/Patches/9 WeenieDefaults/Creature/Ghost/37145.es
Can now give the Jailer an Arcane Pyramid (37126) for an Ancient Mhoire Coin (35383) once a day.
http://acpedia.org/wiki/The_Jester
> Update 37145 Jailer

- Database/Patches/9 WeenieDefaults/Creature/Carenzi/11493 Feral Carenzi.sql
- Database/Patches/9 WeenieDefaults/Creature/Carenzi/11497 Carenzi Stalker.sql
- Database/Patches/9 WeenieDefaults/Creature/Carenzi/25850 Mangy Carenzi.sql
- Database/Patches/9 WeenieDefaults/Creature/Carenzi/25853 Tainted Carenzi.sql
- Database/Patches/9 WeenieDefaults/Creature/Carenzi/27708 Carnivorous Carenzi.sql
- Database/Patches/9 WeenieDefaults/Creature/Carenzi/29347 Polar Carenzi.sql
- Database/Patches/9 WeenieDefaults/Creature/Carenzi/34254 Feral Carenzi.sql
Increased liver drop rate on Carenzis.
> Update Liver Drop Rate

- Database/Patches/9 WeenieDefaults/PetDevice/Misc/47168 Snow Tuskie Kennel.sql
removed attuned and bonded per yotes http://ac.yotesfan.com/weenies/items/47168
> Update 47168 Snow Tuskie Kennel.sql

- Database/Patches/9 WeenieDefaults/Creature/Lugian/47210 Tiatus Overseer.sql
- Database/Patches/9 WeenieDefaults/Creature/Lugian/47210.es
- Database/Patches/9 WeenieDefaults/Creature/Undead/47205 Forge Guardian.sql
- Database/Patches/9 WeenieDefaults/Creature/Undead/47205.es
Fixed emotes on Forge Guardian.
> Falatacot Depot Update

- Database/Patches/9 WeenieDefaults/Creature/Human/43526 Fayza.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/43526.es
- Database/Patches/9 WeenieDefaults/Creature/Human/70351 Mortified Soldier.sql
add mmd notes to fayza, adjusted armor on the mortified soldier to match retail video
> gurog creation fixes

- Database/Patches/9 WeenieDefaults/Creature/Unsorted/34306 Altar of Urdhinivix.sql
Added NPCLooksLike among other things missing.
> Update Altar of Urdhinivix

- Database/Patches/9 WeenieDefaults/MissileLauncher/MissileWeapon/42301 Gear Crossbow.sql
- Remove incorrect Bonded.Destroy property
> Update 42301 Gear Crossbow.sql

- Database/Patches/9 WeenieDefaults/Creature/Human/34286 Sayuji Jina.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/34286.es
- Database/Patches/9 WeenieDefaults/Creature/Human/34365 Ookami Kiri.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/34365.es
Changes emotes so the quest counter can actually get stamped
> Tanada Hunting Parties Fix

- Database/Patches/9 WeenieDefaults/Generic/Armor/32698 Shield of Strathelar.sql
- Remove bad Bonded.Destroy property
> Update 32698 Shield of Strathelar.sql

- Database/Patches/6 LandBlockExtendedData/E74E.sql
- Database/Patches/B GameEventDefDB/Monouga120FPHugeGenEvent.sql
- Database/Patches/B GameEventDefDB/Monouga150FPGiantGenEvent.sql
- Database/Patches/B GameEventDefDB/Monouga80FPLargeGenEvent.sql
- Database/Patches/B GameEventDefDB/SavingAsheronsManaBarrierUpEvent.sql
- Database/Patches/B GameEventDefDB/SavingAsheronsStartEvent.sql
Removed NPCs starting events and changed events to start on server start.
> Hebian-To Cleanup and Event Changes

- Database/Patches/9 WeenieDefaults/Creature/Ghost/72556 Spectral Archer.sql
Add stubborn missile, and other properties to match remaining spectral archers.
> Update 72556 Spectral Archer.sql

- Database/Patches/6 LandBlockExtendedData/584E.sql
- Database/Patches/6 LandBlockExtendedData/5FD3.sql
- Database/Patches/8 QuestDefDB/SerpentBurialGroundsBonePickup.sql
- Database/Patches/8 QuestDefDB/SerpentBurialGroundsDone.sql
- Database/Patches/8 QuestDefDB/SerpentBurialGroundsKeyPickup.sql
- Database/Patches/8 QuestDefDB/SerpentBurialGroundsStarted.sql
- Database/Patches/9 WeenieDefaults/Creature/Crystal/72804 Warding Crystal.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/46338 Kraytuss Nallah.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/46338.es
- Database/Patches/9 WeenieDefaults/Creature/Sclavus/72800 Sclavus Neophyte.sql
- Database/Patches/9 WeenieDefaults/Creature/Sclavus/72801 Sclavus Neophyte.sql
- Database/Patches/9 WeenieDefaults/Creature/Sclavus/72802 Sclavus Sentinel.sql
- Database/Patches/9 WeenieDefaults/Creature/Sclavus/72803 Sclavus Sentinel.sql
- Database/Patches/9 WeenieDefaults/Creature/Sclavus/72811 Sclavus Neophyte.sql
- Database/Patches/9 WeenieDefaults/Creature/Slithis/72808 Slithis Tendril Vine.sql
- Database/Patches/9 WeenieDefaults/Creature/Undead/72805 Shikken Moriyaki.sql
- Database/Patches/9 WeenieDefaults/Creature/Undead/72805.es
- Database/Patches/9 WeenieDefaults/Door/Misc/72810 Door.sql
- Database/Patches/9 WeenieDefaults/Generic/Misc/72806 Bone Fragment from Shikken Moriyaki.sql
- Database/Patches/9 WeenieDefaults/Generic/None/72812 Serpent Burial Grounds Gen.sql
- Database/Patches/9 WeenieDefaults/Key/Key/72807 Legendary Key.sql
- Database/Patches/9 WeenieDefaults/Portal/Portal/46336 Serpent Burial Grounds.sql
- Database/Patches/9 WeenieDefaults/Portal/Portal/72809 Surface.sql
Adds the quest.
http://acpedia.org/wiki/Serpent_Burial_Grounds_Quest
> Serpent Burial Grounds Quest

- Database/Patches/6 LandBlockExtendedData/1DB6.sql
- Database/Patches/6 LandBlockExtendedData/24C0.sql
- Database/Patches/8 QuestDefDB/CanPickupLargeCorruptedManaShard.sql
- Database/Patches/8 QuestDefDB/GuardianoftheDeruTrees_Completed.sql
- Database/Patches/8 QuestDefDB/GuardianoftheDeruTrees_FetishHandedIn.sql
- Database/Patches/8 QuestDefDB/GuardianoftheDeruTrees_Flag.sql
- Database/Patches/8 QuestDefDB/GuardianoftheDeruTrees_StartFetish.sql
- Database/Patches/8 QuestDefDB/GuardianoftheDeruTrees_StartJelly.sql
- Database/Patches/8 QuestDefDB/GuardianoftheDeruTrees_StartShard.sql
- Database/Patches/8 QuestDefDB/OlthoiJellyRoyalDeruPickedUp.sql
- Database/Patches/9 WeenieDefaults/Creature/AunTumerok/39054 Aun Kimintari.sql
- Database/Patches/9 WeenieDefaults/Creature/AunTumerok/39054.es
- Database/Patches/9 WeenieDefaults/Creature/Olthoi/87830 Olthoi Slasher.sql
- Database/Patches/9 WeenieDefaults/Creature/Sclavus/87829 Sclavus Acolyte of T'thuun.sql
- Database/Patches/9 WeenieDefaults/Creature/Unknown/87822 Pool of Goo.sql
- Database/Patches/9 WeenieDefaults/Creature/Unsorted/87825 Large Corrupted Mana Shard.sql
- Database/Patches/9 WeenieDefaults/Creature/Unsorted/87825.es
- Database/Patches/9 WeenieDefaults/Creature/Unsorted/87827 Altar of T'thuun.sql
- Database/Patches/9 WeenieDefaults/Creature/Unsorted/87827.es
- Database/Patches/9 WeenieDefaults/Generic/Misc/87823 Royal Olthoi Jelly.sql
- Database/Patches/9 WeenieDefaults/Generic/Misc/87824 Large Corrupted Mana Shard.sql
- Database/Patches/9 WeenieDefaults/Generic/Misc/87826 Wharu Fetish.sql
- Database/Patches/9 WeenieDefaults/Generic/None/87832 Roots of Skuld Generator.sql
- Database/Patches/9 WeenieDefaults/Portal/Portal/87828 Roots of Skuld, Urd and Verdandi.sql
- Database/Patches/9 WeenieDefaults/Portal/Portal/87831 Surface.sql
**Added**
**NPCs:**
Aun Kimintari
**Items:**
Large Corrupted Mana Shard
Wharu Fetish
Altar of T'thuun
**LBs:**
Roots of Skuld, Urd and Verdandi
> Guardian of the Deru Trees of Marae Lassel

- Database/Patches/9 WeenieDefaults/Clothing/Armor/22551 Atlatl Tattoo.sql
- Database/Patches/9 WeenieDefaults/Clothing/Armor/22552 Axe Tattoo.sql
- Database/Patches/9 WeenieDefaults/Clothing/Armor/22553 Bow Tattoo.sql
- Database/Patches/9 WeenieDefaults/Clothing/Armor/22554 Crossbow Tattoo.sql
- Database/Patches/9 WeenieDefaults/Clothing/Armor/22555 Dagger Tattoo.sql
- Database/Patches/9 WeenieDefaults/Clothing/Armor/22556 Mace Tattoo.sql
- Database/Patches/9 WeenieDefaults/Clothing/Armor/22561 Spear Tattoo.sql
- Database/Patches/9 WeenieDefaults/Clothing/Armor/22562 Staff Tattoo.sql
- Database/Patches/9 WeenieDefaults/Clothing/Armor/22563 Sword Tattoo.sql
- Database/Patches/9 WeenieDefaults/Clothing/Armor/22564 Unarmed Tattoo.sql
- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/00540 Lugian Axe.sql
- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/00541 Lugian Club.sql
- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/00542 Lugian Hammer.sql
- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/00543 Lugian Mace.sql
- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/00544 Lugian Morning Star.sql
- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/07765 Lugian Board with Nail.sql
- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/07766 Tumerok Board with Nail.sql
- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/07767 Drudge Board with Nail.sql
- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/25590 Staff of Coercion.sql
- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/27592 Ebon Spine Harpoon.sql
- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/28215 Brass Knuckles.sql
- Database/Patches/9 WeenieDefaults/Missile/MissileWeapon/09510 Rock.sql
- Database/Patches/9 WeenieDefaults/MissileLauncher/MissileWeapon/27594 Sublime Elari Wood Bow.sql
- Database/Patches/9 WeenieDefaults/MissileLauncher/MissileWeapon/29231 Tanami's Crossbow.sql
Updates some items to use Master of Arms weapon skills and end of retail stats.
> Update some MoA skills/stats

- Database/Patches/6 LandBlockExtendedData/8B03.sql
- Database/Patches/9 WeenieDefaults/Creature/Virindi/43206 Apostate Grand Director.sql
- Database/Patches/9 WeenieDefaults/Creature/Virindi/43206.es
Updated the Apostate Grand Director in the Apostate Finale quest to spawn his guards as seen in a Loud Lou retail video.  Previously, the guards were incorrectly left in the landblock.
> Update Apostate Finale

- Database/Patches/9 WeenieDefaults/Clothing/Clothing/35173 Empowered Empyrean Robe.sql
> Empowered Empyrean Robe Fix

- Database/Patches/9 WeenieDefaults/Creature/Sclavus/87480 Sclavus Acolyte of T'thuun.sql
> Eye of T'thuun Quest Update

- Database/Patches/9 WeenieDefaults/Creature/Human/33877 Hoshar ibn Jalaq.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/33877.es
Updated to accept Greater Mukkir Slayer Stone for xp.
> Update to Hoshar ibn Jalaq

- Database/Patches/6 LandBlockExtendedData/00CE.sql
- Database/Patches/9 WeenieDefaults/Generic/None/87845 Upper Catacombs Generator.sql
Reduced PCAP spawned LB to 2 creatures per room per video.
> Update to Upper Catacombs

- Database/Patches/8 QuestDefDB/DireChampDireHuntTitle.sql
- Database/Patches/8 QuestDefDB/DireChampGameWardenTitle.sql
- Database/Patches/8 QuestDefDB/DireChampHonoraryReaTitle.sql
- Database/Patches/9 WeenieDefaults/Creature/AunTumerok/36866 Aun Javhalrea, the Game Warden.sql
- Database/Patches/9 WeenieDefaults/Creature/AunTumerok/36866.es
Fixed to give turn in titles at any point.
> Aun Javhalrea, the Game Warden Updates

- Database/Patches/6 LandBlockExtendedData/88BF.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/31365 Farmer Kao.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/31365.es
Updated XP for items/turn-in to match EoR. 
Replaced custom Farmer Kao with PCAP'd version.
> Farmer Kao Updates

- Database/Patches/8 QuestDefDB/KillTaskGolemSamurai0812.sql
> Golem Samurai Kill Task Fix

- Database/Patches/9 WeenieDefaults/Ammunition/MissileWeapon/47513 Arrow.sql
- Database/Patches/9 WeenieDefaults/Creature/Ghost/47218 Ensorcelled Weapon.sql
Added MissileWeapons skill to Ensorcelled Weapon and reduced damage on 47513 Arrow.
> Ensorcelled Weapon and Arrow Updates

- Database/Patches/9 WeenieDefaults/Creature/Slithis/38823 Eyestalk of T'thuun.sql
I spent many nights on freebooter macroing for Tchk'Tain the Tender. Never do I remember either macroing or running by these things on the way to the beach getting hit with the spell.
> removed weight of the world spell

- Database/Patches/8 QuestDefDB/KothMoxStaffPickedUp.sql
- Database/Patches/9 WeenieDefaults/Generic/Misc/38322 Kothmox's Staff.sql
removed the 20 hr timer. was not there in retail.
> Update 38322 Kothmox's Staff.sql

- Database/Patches/9 WeenieDefaults/Portal/Portal/33517 Surface.sql
added destination and teleloc which fixed the error destination not yet implemented
> Update 33517 Surface.sql

- Database/Patches/9 WeenieDefaults/Portal/Portal/33480 Surface.sql
add portal bitmask 49 to prevent from being able to get free access to viss island without doing the quest
> Update 33480 Surface.sql

- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/41906 Enhanced Fist of the Quiddity.sql
- Add missing WeaponSkill property
> Update 41906 Enhanced Fist of the Quiddity.sql

- Database/Patches/8 QuestDefDB/StolenArtifacts_TurnIn.sql
- Database/Patches/9 WeenieDefaults/Creature/Banderling/35343 Chief Taraash.sql
- Database/Patches/9 WeenieDefaults/Creature/Banderling/35343.es
- Database/Patches/9 WeenieDefaults/Creature/Human/35344 Guard Winterborn.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/35344.es
> Aerbax's Prodigal Banderling Updates

- Database/Patches/9 WeenieDefaults/Portal/Portal/41234 Arrival Chamber.sql
once you talk to the npc, you could bypass the whole quest with a tie to this portal
> arrival chamber

- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/34002 Mi Krau-Li's Remastered Jitte.sql
> Update Mi Krau-Li's Remastered Jitte

- Database/Patches/9 WeenieDefaults/Creature/Human/29769 Guard Devon.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/29769.es
Updated Guard Devon's Emotes/XP and fixed when to hand out MFK.
> Clutch of Kings Update

- Database/Patches/4 CraftTable/07773 Pyreal Glyph.sql
- Database/Patches/4 CraftTable/07774 Prismatic Glyph.sql
- Database/Patches/9 WeenieDefaults/Generic/Misc/32946 Pyreal Glyph.sql
- Add missing Pyreal Glyph
- Recipe corrections
> Prismatic oil

- Database/Patches/9 WeenieDefaults/Generic/Misc/32967 Reflective Shard.sql
> Shard Timer

- Database/Patches/6 LandBlockExtendedData/584E.sql
- Database/Patches/9 WeenieDefaults/Creature/Slithis/72808 Slithis Tendril Vine.sql
https://asheron.fandom.com/wiki/Slithis_Tendril_Vine
also add 2 vines in beginning hallway
> adjusted vine vitals

- Database/Patches/6 LandBlockExtendedData/001F.sql
> Remove Duplicate Spawns in 001F

- Database/Patches/9 WeenieDefaults/Generic/Jewelry/28828 Grand Mother's Medallion.sql
- Add missing ItemCurMana property
> Grand Mother's Medallion Fix

- Database/Patches/9 WeenieDefaults/MissileLauncher/MissileWeapon/30304 Black Cloud Bow.sql
Thanks to "Scyonara" for noticing the issue. This could probably do with a Shard patch, as well.
> Fix Black Cloud Bow ItemXPStyle

- Database/Patches/9 WeenieDefaults/Creature/Human/05119 Inuo KonKou.sql
Updated XP for Magical Lights per Learning From Experience Patch.
> Update Inuo KonKou

- Database/Patches/9 WeenieDefaults/Creature/Human/06890 Miyako Nujou-Wah .sql
Update XP per Learning from Experience Patch.
> Update Miyako Nujou-Wah

- Database/Patches/9 WeenieDefaults/Chest/Container/08972 The Overlord's Chest.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/32650 Lieutenant Rothe.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/32650.es
- Database/Patches/9 WeenieDefaults/Generic/Misc/87436 Mark of the Overlord.sql
Added Mark of the Overlord, updated The Overlord's Chest to contain mark. Updated Lieutenant Rothe to accept the mark.
Per Reforging the Past patch.
>  Overlord's Sword Quest Updates

- Database/Patches/6 LandBlockExtendedData/7D64.sql
- Database/Patches/6 LandBlockExtendedData/A9B4.sql
- Database/Patches/6 LandBlockExtendedData/DA55.sql
- Database/Patches/6 LandBlockExtendedData/DA56.sql
- Database/Patches/9 WeenieDefaults/Book/Writable/32086 Refurbisher's Tally.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/32085 Arcanum Refurbisher.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/32085.es
- Database/Patches/9 WeenieDefaults/Creature/Human/42736 Tailor's Apprentice.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/42736.es
- Database/Patches/9 WeenieDefaults/Creature/Human/42737 Tailor's Apprentice.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/42737.es
- Database/Patches/9 WeenieDefaults/Creature/Human/42738 Tailor's Apprentice.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/42738.es
- Database/Patches/9 WeenieDefaults/Creature/Human/42739 Tailor's Apprentice.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/42739.es
Not much besides Aesthetics......
> Apprentice Additions

- Database/Patches/8 QuestDefDB/EnricoAugmentationLetterTurnIn.sql
- Database/Patches/8 QuestDefDB/EnricoUncleLetterTurnIn.sql
- Database/Patches/8 QuestDefDB/EnricoWarningLetterTurnIn.sql
- Database/Patches/9 WeenieDefaults/Book/Writable/70048 To My Dear Uncle.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/32084 Enrico di Bellenesse.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/32084.es
Updated to work better with contract.
> Enrico's Betrayal Quest Updates

- Database/Patches/8 QuestDefDB/BloodmouthMawRepeat.sql
- Database/Patches/9 WeenieDefaults/Creature/AunTumerok/32107 Aun Ruperea.sql
- Database/Patches/9 WeenieDefaults/Creature/AunTumerok/32107.es
- Database/Patches/9 WeenieDefaults/Creature/Human/31930 Peng-Ya.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/31930.es
- Database/Patches/9 WeenieDefaults/Creature/Human/31931 Algar Oreksun.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/31931.es
- Database/Patches/9 WeenieDefaults/Creature/Human/31932 Dayla Bint Kazm.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/31932.es
- Database/Patches/9 WeenieDefaults/Creature/Human/31934 Colista Fluress.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/31934.es
- Database/Patches/9 WeenieDefaults/Creature/Human/32109 Susana du Loc.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/32109.es
- Database/Patches/9 WeenieDefaults/Creature/Human/32110 Robert Gutsmasher.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/32110.es
- Database/Patches/9 WeenieDefaults/Creature/Merwart/32122 Merwart Pelagurg.sql
- Database/Patches/9 WeenieDefaults/Creature/Merwart/32122.es
Updates to NPC emotes. Matching PCAP text, etc.
> TOD September 2005 Emote Updates

- Database/Patches/9 WeenieDefaults/Creature/Simulacrum/41231 Reaver Simulacrum.sql
> Added T6 loot to Reaver Simulacrum

- Database/Patches/9 WeenieDefaults/Generic/Misc/34884 Imprinting Mote.sql
- Database/Patches/9 WeenieDefaults/Generic/Misc/34889 Quality Imprinting Mote.sql
Removed attuned/bonded. Pcap looks like it was id'd and there was nothing captured.
> Mote Updates

- Database/Patches/9 WeenieDefaults/Creature/Banderling/36819 Banderling Savage.sql
Removed Lugian Axe from wield.
> Update Banderling Savage

- Database/Patches/9 WeenieDefaults/Creature/Human/48794 Grularr Wa'ydo.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/48794.es
- Update the InqQuest query to match the quest stamped by the starting NPC in Kara
> Grularr fix

- Database/Patches/6 LandBlockExtendedData/004C.sql
- Database/Patches/8 QuestDefDB/BarbaricMukkirlordHead_Pickup.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/32217 Qath al-Haddash.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/32217.es
- Database/Patches/9 WeenieDefaults/Creature/Mukkir/31897 Barbaric Mukkir.sql
- Database/Patches/9 WeenieDefaults/Creature/Mukkir/32923 Barbaric Mukkir Nest-lord.sql
- Database/Patches/9 WeenieDefaults/Gem/Gem/32924 Mukkir Nest Portal Gem.sql
- Database/Patches/9 WeenieDefaults/Gem/Gem/36505 Mukkir Nest Portal Gem.sql
- Database/Patches/9 WeenieDefaults/Generic/Misc/32925 Barbaric Mukkir Nest-lord's Head.sql
- Database/Patches/9 WeenieDefaults/Portal/Portal/87418 Mukkir Nest.sql
**Added:**
Mukkir Nest Portal Gem (s)
Barbaric Mukkir Nest-lord + Head
Mukkir Nest Dungeon
Updated Qath al-Haddash emotes
> Mukkir Nest Quest

- Database/Patches/6 LandBlockExtendedData/492D.sql
- Database/Patches/9 WeenieDefaults/Creature/Unsorted/36237 Lo Shoen's Pack.sql
Added pack to LB (missing for some reason?) and added properties to pack.
> Lo Shoen's Pack

- Database/Patches/9 WeenieDefaults/Creature/Human/43029 Niccolo De Luca.sql
Work in progress
https://asheron.fandom.com/wiki/Niccolo_De_Luca
> WIP: Update 43029 Niccolo De Luca.sql

- Database/Patches/9 WeenieDefaults/Caster/Caster/52744 Nether Society Orb.sql
> Update Nether Society Orb

- Database/Patches/9 WeenieDefaults/Generic/Armor/35982 Aegis of the Golden Flame.sql
AL was pcapd with it wielded. Reduced AL.
> Aegis of the Golden Flame fix

- Database/Patches/8 QuestDefDB/forgevaultkeypickuptimer.sql
- Database/Patches/8 QuestDefDB/foundjestermarker1.sql
- Database/Patches/8 QuestDefDB/foundjestermarker10.sql
- Database/Patches/8 QuestDefDB/foundjestermarker2.sql
- Database/Patches/8 QuestDefDB/foundjestermarker3.sql
- Database/Patches/8 QuestDefDB/foundjestermarker4.sql
- Database/Patches/8 QuestDefDB/foundjestermarker5.sql
- Database/Patches/8 QuestDefDB/foundjestermarker6.sql
- Database/Patches/8 QuestDefDB/foundjestermarker7.sql
- Database/Patches/8 QuestDefDB/foundjestermarker8.sql
- Database/Patches/8 QuestDefDB/foundjestermarker9.sql
https://asheron.fandom.com/wiki/Jester%27s_Lost_Marbles#Update_History
> Jester marker update to 20 hr timer

- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/04195 Nekode.sql
- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/23679 Nekode.sql
- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/23680 Nekode.sql
- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/23681 Nekode.sql
- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/23682 Nekode.sql
> Nekode Update

- Database/Patches/9 WeenieDefaults/Creature/GearKnight/52776 Blade Captain.sql
- Database/Patches/9 WeenieDefaults/Creature/GearKnight/52777 Blade Champion.sql
> Update Blade Champion

- Database/Patches/4 CraftTable/09125 Gem of Spectral Force.sql
- Database/Patches/4 CraftTable/09129 Gauntlet Brutality Amplification.sql
> Update 09129 Gauntlet Brutality Amplification.sql

- Database/Patches/9 WeenieDefaults/Caster/Caster/37478 Spectral Staff.sql
- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/70726 Spectral Claw.sql
- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/70727 Spectral Dagger.sql
- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/70728 Spectral Greatsword.sql
- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/70729 Spectral Mace.sql
- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/70730 Spectral  Spear.sql
- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/70731 Spectral Staff.sql
- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/70732 Spectral Sword.sql
- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/70735 Spectral Axe.sql
- Database/Patches/9 WeenieDefaults/MissileLauncher/MissileWeapon/37498 Spectral Bow.sql
- Database/Patches/9 WeenieDefaults/MissileLauncher/MissileWeapon/70733 Spectral Crossbow.sql
- Database/Patches/9 WeenieDefaults/MissileLauncher/MissileWeapon/70734 Spectral Atlatl.sql
> slayer bonus fix for spectrals

- Database/Patches/9 WeenieDefaults/Creature/Human/46338 Kraytuss Nallah.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/46338.es
Kraytuss Nallah wasn't incrementing the LegendaryQuestCounter on completion of the Serpent Burial Grounds quest.
> Add missing LegendaryQuestCounter stamp to Serpent Burial Grounds

- Database/Patches/9 WeenieDefaults/Caster/Caster/30377 Wings of Rakhil.sql
- Database/Patches/9 WeenieDefaults/Caster/Caster/34991 Opal Repugnant Staff.sql
- Database/Patches/9 WeenieDefaults/Caster/Caster/35558 Ice Wand.sql
- Database/Patches/9 WeenieDefaults/Caster/Caster/70895 Chimeric Eye of the Quiddity.sql
- Update values for Critical Multiplier to actually do something
> Wand Crit Multiplier

- Database/Patches/9 WeenieDefaults/Portal/Portal/47154 Surface.sql
Changed drop to near entrance portal.
> Update to Foundry of Izexi Surface Drop

- Database/Patches/6 LandBlockExtendedData/A9B4.sql
- Database/Patches/8 QuestDefDB/KillTaskMGHAbhorrentEater.sql
- Database/Patches/8 QuestDefDB/KillTaskMGHCompleted.sql
- Database/Patches/8 QuestDefDB/KillTaskMGHRemoran.sql
- Database/Patches/8 QuestDefDB/KillTaskMGHTumerok.sql
- Database/Patches/8 QuestDefDB/KillTaskMGHVoraciousEater.sql
- Database/Patches/8 QuestDefDB/KillTaskMGHWasp.sql
- Database/Patches/8 QuestDefDB/MGHEasyCompleted.sql
- Database/Patches/8 QuestDefDB/MGHExtremeCompleted.sql
- Database/Patches/8 QuestDefDB/MGHHardCompleted.sql
- Database/Patches/8 QuestDefDB/MGHModerateCompleted.sql
- Database/Patches/8 QuestDefDB/MGHVeryHardCompleted.sql
- Database/Patches/9 WeenieDefaults/Creature/Eater/28639 Voracious Eater.sql
- Database/Patches/9 WeenieDefaults/Creature/Eater/28641 Abhorrent Eater.sql
- Database/Patches/9 WeenieDefaults/Creature/Eater/28850 Voracious Eater.sql
- Database/Patches/9 WeenieDefaults/Creature/Eater/28851 Abhorrent Eater.sql
- Database/Patches/9 WeenieDefaults/Creature/Eater/30851 Voracious Eater.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/39983 Rand, Game Hunter.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/39983.es
- Database/Patches/9 WeenieDefaults/Creature/PhyntosWasp/31016 Agitated Phyntos Wasp.sql
- Database/Patches/9 WeenieDefaults/Creature/PhyntosWasp/40308 Giant Jungle Phyntos Wasp.sql
- Database/Patches/9 WeenieDefaults/Creature/Remoran/33629 Fouled Remoran.sql
- Database/Patches/9 WeenieDefaults/Creature/Remoran/33736 Remoran Corsair.sql
- Database/Patches/9 WeenieDefaults/Creature/Remoran/33737 Horrid Remoran.sql
- Database/Patches/9 WeenieDefaults/Creature/Remoran/40283 Remoran Corsair.sql
- Database/Patches/9 WeenieDefaults/Creature/Remoran/40284 Horrid Remoran.sql
- Database/Patches/9 WeenieDefaults/Creature/Remoran/70082 Dark Remoran.sql
- Database/Patches/9 WeenieDefaults/Creature/Tumerok/23092 Revered Tumerok Shaman.sql
- Database/Patches/9 WeenieDefaults/Creature/Tumerok/23093 Transcendent Tumerok.sql
- Database/Patches/9 WeenieDefaults/Creature/Tumerok/27506 Revered Tumerok Shaman.sql
Monthly Game Hunter with last known Group Kill Task
Future Update?? Randomize group KTs
> Rand, Game Hunter

- Database/Patches/9 WeenieDefaults/HotSpot/Misc/36180 Magma Pool.sql
- Database/Patches/9 WeenieDefaults/HotSpot/Misc/36181 Freezing Pool.sql
- Database/Patches/9 WeenieDefaults/HotSpot/Misc/36182 Acid Pool.sql
- Database/Patches/9 WeenieDefaults/HotSpot/Misc/36183 Galvanic Pool.sql
Added palette template, shade, and clothing base to the magma, freezing, acid and galvanic pools used in the Prodigal Harbinger quest.
> Correct Pool Art

- Database/Patches/9 WeenieDefaults/Creature/Ghost/88081 Spectral Bloodmage.sql
- Database/Patches/9 WeenieDefaults/Creature/Ghost/88082 Spectral Samurai.sql
- Database/Patches/9 WeenieDefaults/Creature/Ghost/88083 Spectral Archer.sql
- Database/Patches/9 WeenieDefaults/Creature/Ghost/88084 Spectral Archer.sql
- Database/Patches/9 WeenieDefaults/Creature/Ghost/88087 Spectral Samurai.sql
- Database/Patches/9 WeenieDefaults/Creature/Ghost/88088 Spectral Minion.sql
- Database/Patches/9 WeenieDefaults/Creature/Ghost/88089 Spectral Minion.sql
- Database/Patches/9 WeenieDefaults/Creature/Ghost/88090 Spectral Blade Master.sql
- Database/Patches/9 WeenieDefaults/Creature/Ghost/88091 Spectral Bushi.sql
- Database/Patches/9 WeenieDefaults/Creature/Ghost/88092 Spectral Voidmage.sql
- Database/Patches/9 WeenieDefaults/Creature/Ghost/88093 Spectral Voidmage.sql
- Database/Patches/9 WeenieDefaults/Creature/Undead/87589 Mu-miyah Vizier.sql
- Database/Patches/9 WeenieDefaults/Creature/Undead/87614 Mu-miyah Champion.sql
- Database/Patches/9 WeenieDefaults/Creature/Undead/87848 Mu-miyah Lord.sql
- Database/Patches/9 WeenieDefaults/Creature/Undead/87849 Mu-miyah Sentinel.sql
- Database/Patches/9 WeenieDefaults/Creature/Undead/88080 Mu-miyah Guardian.sql
- Database/Patches/9 WeenieDefaults/Generic/None/88206 Temple of Mornings Generator.sql
Creatures were dropping loot they shouldn't.
> Harvesting the Bulb of Mornings Fix

- Database/Patches/8 QuestDefDB/MossyHerb.sql
- Database/Patches/8 QuestDefDB/RenaldMug.sql
- Database/Patches/8 QuestDefDB/capplewine.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/05178 Lubziklan al-Luq.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/28856 Renald the Eldest.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/28857 Gonjoku Den.sql
- Database/Patches/9 WeenieDefaults/Generic/Misc/28830 Mossy Herb.sql
- Database/Patches/9 WeenieDefaults/Generic/Misc/28844 Renald's Old Mug.sql
- Database/Patches/9 WeenieDefaults/Generic/None/28765 Cove Apple Wine.sql
- Adjustments to allow pickup of items only during the quest window
> Trade Agreements quest fix

- Database/Patches/9 WeenieDefaults/Creature/Human/12050 Agent of the Arcanum.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/12050.es
- Database/Patches/9 WeenieDefaults/Creature/Human/33967 Zahir.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/33967.es
- Database/Patches/9 WeenieDefaults/Creature/Human/49604 Agent of the Arcanum.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/49604.es
- Database/Patches/9 WeenieDefaults/Creature/Lugian/24577 Agent Dravos.sql
- Database/Patches/9 WeenieDefaults/Creature/Lugian/24577.es
Update Agent of the Arcanum and Zahir to turn, respond, and give a Writ of Refuge in exchange for a Major Atlan stone.
**Testing**
@create 33967
@create 49604
@create 12050
@ci 6123
@ci 6124
@ci 6125
@ci 6126
> Agent of the Arcanum (both) and Zahir should return a Writ for a Major Stone

- Database/Patches/9 WeenieDefaults/Creature/Unsorted/33894 Abyssal Totem.sql
Added:
, (33894,  40,          1) /* CombatMode - NonCombat */
, (33894,  67,          1) /* Tolerance - NoAttack */
, (33894,  68,          5) /* TargetingTactic - Random, LastDamager */
> Abyssal Totem Update

- Database/Patches/9 WeenieDefaults/Creature/Burun/34820 Shiruuk.sql
- Database/Patches/9 WeenieDefaults/Creature/Burun/34820.es
- Database/Patches/9 WeenieDefaults/Creature/Burun/34821 Brogosh.sql
- Database/Patches/9 WeenieDefaults/Creature/Burun/34821.es
- Database/Patches/9 WeenieDefaults/Creature/Burun/34822 Mohor.sql
- Database/Patches/9 WeenieDefaults/Creature/Burun/34822.es
- Database/Patches/9 WeenieDefaults/Creature/Burun/34823 Kurket.sql
- Database/Patches/9 WeenieDefaults/Creature/Burun/34823.es
- Database/Patches/9 WeenieDefaults/Creature/Burun/34824 Borsh.sql
- Database/Patches/9 WeenieDefaults/Creature/Burun/34824.es
- Database/Patches/9 WeenieDefaults/Creature/Burun/34825 Kushuk.sql
- Database/Patches/9 WeenieDefaults/Creature/Burun/34825.es
> Bridging the Vast Divide Patch Emote Updates

- Database/Patches/8 QuestDefDB/ParadoxEggCount.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/35825 Alicia Swiftblade.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/35825.es
- Database/Patches/9 WeenieDefaults/Creature/Human/35826 Tomihino.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/35826.es
- Database/Patches/9 WeenieDefaults/Creature/Human/35828 Adrien Swiftblade.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/35828.es
Updated Emotes based on PCAP text.
> Intelligent Designs - July 2007 Emote Updates

- Database/Patches/6 LandBlockExtendedData/4AE1.sql
- Database/Patches/6 LandBlockExtendedData/4CE2.sql
- Database/Patches/9 WeenieDefaults/Creature/Ghost/90107 Daimyo Nobanuga.sql
- Database/Patches/9 WeenieDefaults/Creature/Ghost/90108 Daimyo Idah.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/46684 Hanamoto Aki'ko.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/46684.es
- Database/Patches/9 WeenieDefaults/Generic/Misc/53475 Daimyo Nobanuga's Shattered Helm.sql
- Database/Patches/9 WeenieDefaults/Generic/Misc/53476 Daimyo Idah's Tattered Mask.sql
- Database/Patches/9 WeenieDefaults/Generic/None/90109 Daimyo Nobanuga Gen.sql
- Database/Patches/9 WeenieDefaults/Generic/None/90110 Daimyo Idah Gen.sql
- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/46828 Purified Mouryou Katana.sql
- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/46829 Purified Mouryou Nanjou-tachi.sql
- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/46830 Purified Mouryou Nodachi.sql
- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/46831 Purified Mouryou Wakizashi.sql
- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/46832 Purified Mouryou Nekode.sql
- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/90111 Corrupted Mouryou Nanjou-tachi.sql
- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/90113 Corrupted Mouryou Blade.sql
- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/90114 Corrupted Mouryou Blade.sql
- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/90115 Corrupted Mouryou Blade.sql
- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/90116 Corrupted Mouryou Blade.sql
- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/90117 Corrupted Mouryou Blade.sql
- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/90118 Corrupted Mouryou Nanjou-tachi Off Hand.sql
- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/90119 Corrupted Mouryou Nekode.sql
Adds Hosh Bosses Daimyo Idah and Daimyo Nobanuga.  Also adds the Corrupted Weapon drops for turnining in for Purified Mouryou Weapons.   NPC was update for turnins.
This was created with all the information I could find, and there was not very much to go on.  Thanks to TCK for starting this.
> Hosh Rare Bosses

- Database/Patches/4 CraftTable/06970 Keg of Duke Raoul's Distillation.sql
Updated recipe to create 1 Keg instead of 50...
> A Little Less Kegs

- Database/Patches/9 WeenieDefaults/Creature/Ghost/90108 Daimyo Idah.sql
> Update 90108 Daimyo Idah.sql

- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/33945 Enhanced Fetid Dirk.sql
Adds the missing weapon skill (heavy weapons) for the enhanced fetid dirk
> Add weapon skill for enhanced fetid dirk

- Database/Patches/9 WeenieDefaults/Creature/Unsorted/38025 Summoning Stone.sql
- Database/Patches/9 WeenieDefaults/Creature/Unsorted/38026 Summoning Stone.sql
> Updated Delay on GY Summoning Stones

- Database/Patches/9 WeenieDefaults/Creature/Elemental/33231 Harbinger.sql
- Database/Patches/9 WeenieDefaults/Creature/Elemental/36178 Harbinger.sql
- Database/Patches/9 WeenieDefaults/Creature/Elemental/71239 Harbinger.sql
- Add fixed positions for the Surface portals
- Swap arm tokens between the Empowered and Essenceless Harbingers
> Harbinger data fixes

- Database/Patches/9 WeenieDefaults/Creature/AunTumerok/36866 Aun Javhalrea, the Game Warden.sql
- Database/Patches/9 WeenieDefaults/Creature/AunTumerok/36866.es
Changed from NoShare to AwardXP.
> Dire Champ XP Fix

- Database/Patches/6 LandBlockExtendedData/586D.sql
- Database/Patches/9 WeenieDefaults/Stackable/Misc/31686 Yellow Monster Seed.sql
Added missing doors to 586D dungeon for Hive Eviscerator Pincer from vlocs data. 
Adjusted some olthoi positions to fix overlap with doors. 
Added missing clothing base for 31686 Yellow Monster Seed.
> Update 586D and 31686

- Database/Patches/9 WeenieDefaults/Chest/Container/87509 Chorizite Chest.sql
Missing chest in Four Corners dungeon.
> Add missing Chorizite Chest

- Database/Patches/8 QuestDefDB/CanEnterGeraineRefuge.sql
- Database/Patches/9 WeenieDefaults/Creature/Undead/45685 Mhoire Soldier.sql
- Database/Patches/9 WeenieDefaults/Creature/Undead/45685.es
- Database/Patches/9 WeenieDefaults/Portal/Portal/45721 Charged Refuge.sql
- Database/Patches/9 WeenieDefaults/Portal/Portal/45722 Cavernous Refuge.sql
- Database/Patches/9 WeenieDefaults/Portal/Portal/45723 Acidic Refuge.sql
- Database/Patches/9 WeenieDefaults/Portal/Portal/45724 Firey Refuge.sql
- Database/Patches/9 WeenieDefaults/Portal/Portal/45725 Twisted Refuge.sql
- Database/Patches/9 WeenieDefaults/Portal/Portal/45726 Shadowy Refuge.sql
- Database/Patches/9 WeenieDefaults/Portal/Portal/45727 Frozen Refuge.sql
Adds a permanent flag to enter Geraine's Hosts dungeons after completing Mhoire Infiltration.
Previously, the Mhoire Infiltration timer was used, which required players to complete all hosts within 20 hours or lose access.
> Update Geraine Hosts Flag

- Database/Patches/9 WeenieDefaults/Generic/None/87490 Empyrean Rescue Dungeon Upper Generator.sql
- Database/Patches/9 WeenieDefaults/Generic/None/87491 Empyrean Rescue Dungeon Lower Generator.sql
- Database/Patches/9 WeenieDefaults/Generic/None/87492 Empyrean Rescue Dungeon Bottom Generator.sql
Fixed delay and probabilities in Gens.
> Empyrean Rescue Quest Updates

- Database/Patches/9 WeenieDefaults/Generic/None/87655 Enlightened Master's Chambers Generator.sql
- Database/Patches/9 WeenieDefaults/Generic/None/87676 Enlightened Master's Chambers Generator.sql
- Database/Patches/9 WeenieDefaults/Generic/None/87682 Tanada House of Water Generator.sql
- Database/Patches/9 WeenieDefaults/Generic/None/87690 Tanada Temple of Black Water Generator.sql
- Database/Patches/9 WeenieDefaults/Generic/None/87708 Chamber of Scrolls Generator.sql
- Database/Patches/9 WeenieDefaults/Generic/None/87709 Chamber of Elements Generator.sql
> Tanada House Gen Updates

- Database/Patches/9 WeenieDefaults/CraftTool/Misc/34386 Hot Coal.sql
- Database/Patches/9 WeenieDefaults/CraftTool/Misc/34425 Frozen Present.sql
- Database/Patches/9 WeenieDefaults/CraftTool/Misc/36897 Present.sql
Added missing properties to some items. Fixed probabilities in Present.
> Assault on Frost Haven Minor Updates

- Database/Patches/9 WeenieDefaults/Gem/Gem/44400 Contract for Empyrean Rescue.sql
- Database/Patches/9 WeenieDefaults/Gem/Gem/44586 Contract for Harlune's Diplomacy.sql
- Database/Patches/9 WeenieDefaults/Gem/Gem/44587 Contract for Saving Asheron.sql
- Database/Patches/9 WeenieDefaults/Gem/Gem/44655 Contract for Gear Knight Excavation.sql
- Database/Patches/9 WeenieDefaults/Gem/Gem/44656 Contract for Jester Released.sql
- Database/Patches/9 WeenieDefaults/Gem/Gem/44881 Contract for Aerbax's Prodigal Tusker.sql
- Database/Patches/9 WeenieDefaults/Gem/Gem/45848 Contract for Splitting Grael (Low).sql
- Database/Patches/9 WeenieDefaults/Gem/Gem/45849 Contract for Splitting Grael (Mid).sql
- Database/Patches/9 WeenieDefaults/Gem/Gem/46747 Contract for Kill_ Spectral Archers.sql
- Database/Patches/9 WeenieDefaults/Gem/Gem/46748 Contract for Kill_ Spectral Minions.sql
- Database/Patches/9 WeenieDefaults/Gem/Gem/46749 Contract for Kill_ Spectral Blades and Claws.sql
- Database/Patches/9 WeenieDefaults/Gem/Gem/46750 Contract for Kill_ Spectral Bushi.sql
- Database/Patches/9 WeenieDefaults/Gem/Gem/46751 Contract for Kill_ Spectral Samurai.sql
- Database/Patches/9 WeenieDefaults/Gem/Gem/46752 Contract for Kill_ Spectral Samurai Golems.sql
- Database/Patches/9 WeenieDefaults/Gem/Gem/46753 Contract for Kill_ Spectral Mages.sql
- Database/Patches/9 WeenieDefaults/Gem/Gem/46754 Contract for Kill_ Spectral Nanjou Shou-jen.sql
- Database/Patches/9 WeenieDefaults/Gem/Gem/46908 Contract for Unleash the Gearknights.sql
- Database/Patches/9 WeenieDefaults/Gem/Gem/48779 Contract for Lost Lore.sql
> Contract String Updates

- Database/Patches/9 WeenieDefaults/Generic/Misc/34095 Pack Pumpkin P..sql
> Update 34095 Pack Pumpkin P..sql

- Database/Patches/2 SpellTableExtendedData/03680 Prodigal Acid Protection.sql
- Database/Patches/2 SpellTableExtendedData/03687 Prodigal Blade Protection.sql
- Database/Patches/2 SpellTableExtendedData/03690 Prodigal Bludgeon Protection.sql
- Database/Patches/2 SpellTableExtendedData/03692 Prodigal Cold Protection.sql
- Database/Patches/2 SpellTableExtendedData/03702 Prodigal Fire Protection.sql
- Database/Patches/2 SpellTableExtendedData/03719 Prodigal Lightning Protection.sql
- Database/Patches/2 SpellTableExtendedData/03729 Prodigal Piercing Protection.sql
Matches description and pcap. If you don't like it, we'll through in another .09% for free!* 
_* offer not valid in Dereth_
> Update rare life protects to be 99.9% from 99%

- Database/Patches/4 CraftTable/08004.sql
- Database/Patches/4 CraftTable/08005.sql
- Database/Patches/4 CraftTable/08006.sql
- Database/Patches/4 CraftTable/08007.sql
- Database/Patches/4 CraftTable/08008.sql
- Database/Patches/4 CraftTable/08009.sql
- Database/Patches/4 CraftTable/08010.sql
- Database/Patches/4 CraftTable/08011.sql
- Database/Patches/4 CraftTable/08012.sql
- Database/Patches/4 CraftTable/08013.sql
- Database/Patches/4 CraftTable/08014.sql
- Database/Patches/4 CraftTable/08015.sql
- Database/Patches/4 CraftTable/08016.sql
> Update Foolproof recipes

- Database/Patches/9 WeenieDefaults/Creature/Human/30995 Academy Foreman.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/30995.es
> Academy Foreman Emote Update

- Database/Patches/9 WeenieDefaults/Clothing/Clothing/02588 Flared Shirt.sql
- Database/Patches/9 WeenieDefaults/Clothing/Clothing/02590 Baggy Shirt.sql
- Database/Patches/9 WeenieDefaults/Clothing/Clothing/02591 Puffy Shirt.sql
- Database/Patches/9 WeenieDefaults/Clothing/Clothing/02592 Puffy Tunic.sql
- Database/Patches/9 WeenieDefaults/Clothing/Clothing/02593 Loose Tunic.sql
- Database/Patches/9 WeenieDefaults/Clothing/Clothing/02594 Flared Tunic.sql
- Database/Patches/9 WeenieDefaults/Clothing/Clothing/02595 Baggy Tunic.sql
- Database/Patches/9 WeenieDefaults/Clothing/Clothing/02597 Flared Pants.sql
- Database/Patches/9 WeenieDefaults/Clothing/Clothing/02598 Baggy Pants.sql
- Database/Patches/9 WeenieDefaults/Clothing/Clothing/02601 Loose Pants.sql
- Database/Patches/9 WeenieDefaults/Clothing/Clothing/02602 Loose Breeches.sql
- Database/Patches/9 WeenieDefaults/Clothing/Clothing/02603 Baggy Breeches.sql
- Database/Patches/9 WeenieDefaults/Clothing/Clothing/02604 Wide Breeches.sql
No idea WHEN these changed as I couldn't find a patch note about it, but they were at some point to better reflect the style of pants/shirt.
> Adjusted names on some clothing items.

- Database/Patches/9 WeenieDefaults/Clothing/Armor/32759 Prismatic Celdon Breastplate.sql
- Database/Patches/9 WeenieDefaults/Clothing/Armor/32761 Prismatic Celdon Girth.sql
- Database/Patches/9 WeenieDefaults/Clothing/Armor/32762 Prismatic Celdon Leggings.sql
- Database/Patches/9 WeenieDefaults/Clothing/Armor/32765 Prismatic Celdon Sleeves.sql
Adding Prismatic Celdon armor weenies only, not any retired quest elements.
-- Maethor
> Add Prismatic Celdon armor

- Database/Patches/6 LandBlockExtendedData/4CE2.sql
- Database/Patches/6 LandBlockExtendedData/4CE3.sql
Nobanuga was sitting way back in the town, all the times I found him in retail he was closer to the sarc.
> Nobanuga generator relocated

- Database/Patches/9 WeenieDefaults/Creature/Ghost/42027 Shade of Antemy.sql
- Database/Patches/9 WeenieDefaults/Creature/Ghost/42027.es
- Add missing Luminance award for final completion of the Castle of Lord Mhoire Quest
> Shade of Antemy

- Database/Patches/4 CraftTable/08751 Lucky White Rabbit's Foot.sql
- Database/Patches/4 CraftTable/08752 Greater Mukkir Slayer Stone.sql
- Database/Patches/4 CraftTable/08753 Black Skull of Xikma.sql
- Database/Patches/4 CraftTable/08754 Spectral Skull.sql
- Database/Patches/4 CraftTable/08755 A'nekshay Slayer Stone.sql
- Database/Patches/4 CraftTable/08934 Gem of Verdant Force.sql
- Database/Patches/4 CraftTable/09125 Gem of Spectral Force.sql
- Database/Patches/4 CraftTable/09127 Magic Defense Weapon Augmentation.sql
- Database/Patches/4 CraftTable/09128 Missile Defense Weapon Augmentation.sql
- Database/Patches/4 CraftTable/09129 Gauntlet Brutality Amplification.sql
- Database/Patches/4 CraftTable/09131 Gauntlet Defense Amplification.sql
- Add missing rapier sword wcids to the melee Weapon Augmentation recipes
> Add missing elemental rapier swords

- Database/Patches/8 QuestDefDB/ShatteredCoreSampleReceived.sql
- Database/Patches/9 WeenieDefaults/Creature/Unknown/70350 Large Shattered Aetherium Core.sql
- Database/Patches/9 WeenieDefaults/Creature/Unknown/70350.es
Updated to remove inqitem and replace with 5 min quest stamp.
> Large Shattered Aetherium Core Update

- Database/Patches/9 WeenieDefaults/Creature/Unsorted/35007.es
- Database/Patches/9 WeenieDefaults/Creature/Unsorted/35008 Empyrean Blooded Ritual Statue.sql
- Database/Patches/9 WeenieDefaults/Creature/Unsorted/35008.es
Fixed Empyrean Blooded Ritual Statue so its a Death and not WoundedTaunt.
> Saving Asheron Updates

- Database/Patches/9 WeenieDefaults/Portal/Portal/33018 Surface.sql
added destination
http://acpedia.org/wiki/Rossu_Morta_Chapterhouse_Access
Though the entrance portal is not recallable, the surface portal is.
> Update 33018 Surface.sql

- Database/Patches/9 WeenieDefaults/Portal/Portal/46620 Hoshino Tower.sql
https://asheron.fandom.com/wiki/Hoshino_Tower
> Update 46620 Hoshino Tower.sql

- Database/Patches/6 LandBlockExtendedData/F732.sql
- Database/Patches/6 LandBlockExtendedData/F733.sql
- Database/Patches/9 WeenieDefaults/Generic/None/87482 Tchk'Tain the Tender Night Gen.sql
moved the gen from f733 to f732 for more retail placement. I have a nav that I used during retail.
> Tchk'Taine the Tender

- Database/Patches/9 WeenieDefaults/Gem/Gem/30190 Pearl of Blade Baning.sql
add missing ints 106, 107, 108
> Update 30190 Pearl of Blade Baning.sql

- Database/Patches/6 LandBlockExtendedData/3B0B.sql
- Database/Patches/6 LandBlockExtendedData/3D0A.sql
- Database/Patches/6 LandBlockExtendedData/3E0C.sql
- Database/Patches/6 LandBlockExtendedData/410C.sql
- Database/Patches/9 WeenieDefaults/Creature/Moarsman/38292 Spawn.sql
- Database/Patches/9 WeenieDefaults/Creature/Moarsman/38292.es
- Database/Patches/9 WeenieDefaults/Creature/Moarsman/38294 Spawnling.sql
- Database/Patches/9 WeenieDefaults/Creature/Moarsman/38294.es
- Database/Patches/9 WeenieDefaults/Creature/Statue/38265 Egg.sql
- Database/Patches/9 WeenieDefaults/Creature/Statue/38265.es
- Database/Patches/9 WeenieDefaults/Generic/None/88420 Moarsman Spawning Pool 1 Generator.sql
- Database/Patches/9 WeenieDefaults/Generic/None/88421 Moarsman Spawning Pool 2 Generator.sql
- Database/Patches/9 WeenieDefaults/Generic/None/88422 Moarsman Spawning Pool 3 Generator.sql
- Database/Patches/9 WeenieDefaults/Generic/None/88423 Moarsman Spawning Pool 4 Generator.sql
- Database/Patches/9 WeenieDefaults/Generic/None/88424 Moarsman Spawning Pool Generator.sql
Added in Eggs/Spawns/Spawnlings and gave them pizzazz.
> Moarsman Spawning Pools Updates

- Database/Patches/9 WeenieDefaults/Scroll/Writable/36537 Scroll of Colosseum Recall.sql
scroll was not givable in retail
> Colo scroll update

- Database/Patches/9 WeenieDefaults/MissileLauncher/MissileWeapon/35555 Burning Bow.sql
Add correct clothingbase/palettetemplate
> Update 35555 Burning Bow

- Database/Patches/9 WeenieDefaults/CraftTool/CraftAlchemyBase/36732 Enchanted Platinum Phial Pea.sql
Added Bonded property to Enchanted Platinum Phial Pea.
> Enchanted Platinum Phial Pea Update

- Database/Patches/6 LandBlockExtendedData/0044.sql
- Database/Patches/6 LandBlockExtendedData/00D8.sql
- Database/Patches/6 LandBlockExtendedData/934B.sql
- Database/Patches/8 QuestDefDB/LargeEmpyreanTomePickup.sql
- Database/Patches/8 QuestDefDB/NurinoPart1Done.sql
- Database/Patches/8 QuestDefDB/NurinoPart1Start.sql
- Database/Patches/8 QuestDefDB/NurinoPart2Done.sql
- Database/Patches/8 QuestDefDB/NurinoPart2Start.sql
- Database/Patches/8 QuestDefDB/NurinoPart3Done.sql
- Database/Patches/8 QuestDefDB/NurinoPart3Start.sql
- Database/Patches/8 QuestDefDB/PileOfRandomPartsPickup.sql
- Database/Patches/8 QuestDefDB/StrangeManaGemPickup.sql
- Database/Patches/9 WeenieDefaults/Book/Writable/72966 Interactions and Observations, 'Gear Knights'.sql
- Database/Patches/9 WeenieDefaults/Chest/Container/72963 Ancient Chest.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/41208 Nurino.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/41208.es
- Database/Patches/9 WeenieDefaults/Generic/Armor/41204 Gear Shield.sql
- Database/Patches/9 WeenieDefaults/Generic/Misc/41207 Pile of random parts.sql
- Database/Patches/9 WeenieDefaults/Generic/Misc/72964 Strange Mana Gem.sql
- Database/Patches/9 WeenieDefaults/Generic/Misc/72965 Large Empyrean Tome.sql
- Database/Patches/9 WeenieDefaults/Generic/Misc/72967 Gear Knight Head.sql
Adds the Gear Knight Parts quest.
http://acpedia.org/wiki/Gear_Knight_Parts
PR #1494 is a prerequisite for this PR.
This PR modifies the Xarabydun landblock (934B).
It also makes minor changes to spawn placement in landblocks 0044 and 00D8 based on retail screenshots.
> Gear Knight Parts Quest

- Database/Patches/9 WeenieDefaults/Creature/Human/40460 Jusad the Collector.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/40460.es
Adding Jusad the Collector to LB, he accepts Mana Infused Flowers for XP.
[http://acpedia.org/wiki/Jusad](url)
> Jusad the Collector

- Database/Patches/9 WeenieDefaults/Book/Writable/43808 Carefully rolled scroll.sql
- Database/Patches/9 WeenieDefaults/Creature/Unsorted/36777 Strange Device.sql
- Database/Patches/9 WeenieDefaults/Creature/Unsorted/36778 Strange Device.sql
- Database/Patches/9 WeenieDefaults/Creature/Unsorted/36779 Strange Device.sql
- Database/Patches/9 WeenieDefaults/Creature/Unsorted/43837 Enchanted Mnemosyne.sql
- Database/Patches/9 WeenieDefaults/Creature/Unsorted/43838 Enchanted Mnemosyne.sql
- Database/Patches/9 WeenieDefaults/Creature/Unsorted/43839 Enchanted Mnemosyne.sql
- Database/Patches/9 WeenieDefaults/Creature/Unsorted/43840 Enchanted Mnemosyne.sql
- Database/Patches/9 WeenieDefaults/Creature/Unsorted/43841 Enchanted Mnemosyne.sql
- Database/Patches/9 WeenieDefaults/Creature/Unsorted/43843 Enchanted Mnemosyne.sql
- Database/Patches/9 WeenieDefaults/Creature/Unsorted/43844 Enchanted Mnemosyne.sql
- Database/Patches/9 WeenieDefaults/Creature/Unsorted/43845 Enchanted Mnemosyne.sql
- Database/Patches/9 WeenieDefaults/Creature/Unsorted/43846 Enchanted Mnemosyne.sql
Added npc looks like object to Enchanted Mnemosynes (9 of 10 were missing it) and to Strange Device (3 of the 4 were missing it).
Added [You cannot translate this text] to 43808 Carefully rolled scroll.
> Misc Fixes

- Database/Patches/9 WeenieDefaults/PetDevice/Misc/34919 Inactive Fletcher's Golem..sql
- Database/Patches/9 WeenieDefaults/PetDevice/Misc/48957 Incendiary Knight Essence.sql
- Database/Patches/9 WeenieDefaults/PetDevice/Misc/49260 Glacial Knight Essence.sql
- Database/Patches/9 WeenieDefaults/PetDevice/Misc/49267 Caustic Knight Essence.sql
- Database/Patches/9 WeenieDefaults/PetDevice/Misc/49323 Voltaic Wisp Essence.sql
- Database/Patches/9 WeenieDefaults/PetDevice/Misc/49373 Lightning Grievver Essence (50).sql
- Database/Patches/9 WeenieDefaults/PetDevice/Misc/49421 Acid Spectre Essence (50).sql
The inconsistent level skill on the Essence (50)'s matches retail for these two (320); all of the others are 310. Thx, Turbine!
> Update some stats to match pcaps for WeenieType.PetDevice

- Database/Patches/9 WeenieDefaults/Creature/Golem/34498 House Golem.sql
- Database/Patches/9 WeenieDefaults/Creature/Golem/34503 House Golem.sql
- Database/Patches/9 WeenieDefaults/Creature/Golem/34504 House Golem.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/15774 Balthazar, Royal Guardian.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/29322 Samuel.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/30979 Hermit.es
- Database/Patches/9 WeenieDefaults/Creature/Human/30979 Hermit.sql
- Database/Patches/9 WeenieDefaults/Creature/Unsorted/31411 Nightmare Gate.sql
- Database/Patches/9 WeenieDefaults/Creature/Unsorted/31964 Shemza.sql
Added a few give/refuse interactions from pcaps -- mostly just some basic flavor text.
> Some basic interactions from PCAPs

- Database/Patches/9 WeenieDefaults/Creature/Human/33673 Tyrina of Arwic.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/33675 Francois di Terli.sql
- Database/Patches/9 WeenieDefaults/Creature/Unknown/33674 The Deep.sql
SQL fix for PR 1495 (ES was fine)
> Dark Isle Turn In SQL Fix

- Database/Patches/9 WeenieDefaults/Chest/Container/32078 Field Supplies.sql
- Database/Patches/9 WeenieDefaults/Chest/Container/32079 Field Supplies.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/12229 Prospector.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/32360 Londigul Ellic the Armorer.sql
- Database/Patches/9 WeenieDefaults/Creature/Shadow/12228 Void Knight.sql
- Database/Patches/9 WeenieDefaults/Creature/Wall/31669 Pillar of the Eternal Harvester.sql
- Database/Patches/9 WeenieDefaults/Gem/Gem/70292 Stack of Papers.sql
- Database/Patches/9 WeenieDefaults/Generic/None/09187 Random Risen Gen.sql
Fixed some generators that weren't working properly or had config issues that would throw warnings (e.g. initGenerated > maxGenerated) and errors.
Also included `70292 Stack of Papers` that was missing in a generator (spawned on a corpse, `70287 Scrivener's Corpse`) and updated `32360 Londigul Ellic the Armorer` to take and comment on it. (This item, nor the corpse that spawns it were only in-game for an specific event and not in end-of-retail, but the corpse was added so I figured fix this missing item, too)
> Generators

- Database/Patches/9 WeenieDefaults/CraftTool/CraftAlchemyBase/36729 Enchanted Copper Phial Pea.sql
- Database/Patches/9 WeenieDefaults/CraftTool/CraftAlchemyBase/36730 Enchanted Gold Phial Pea.sql
- Database/Patches/9 WeenieDefaults/CraftTool/CraftAlchemyBase/36731 Enchanted Iron Phial Pea.sql
- Database/Patches/9 WeenieDefaults/CraftTool/CraftAlchemyBase/36733 Empowered Platinum Phial Pea.sql
- Database/Patches/9 WeenieDefaults/CraftTool/CraftAlchemyBase/36734 Enchanted Pyreal Phial Pea.sql
- Database/Patches/9 WeenieDefaults/CraftTool/CraftAlchemyBase/36735 Enchanted Silver Phial Pea.sql
Added Bonded property to Enchanted/Empowered Peas per wiki.
> Pea Updates

- Database/Patches/9 WeenieDefaults/Caster/Caster/88446 Piercing Wand of T'thuun.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/88444 High Priestess of T'thuun.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/88444.es
- Database/Patches/9 WeenieDefaults/Creature/Sclavus/41005 T'thuun Sclavus Huntsmaster.sql
- Database/Patches/9 WeenieDefaults/Creature/Sclavus/41005.es
- Database/Patches/9 WeenieDefaults/Creature/Sclavus/88447 Afessa Sclavus Guardian.sql
- Database/Patches/9 WeenieDefaults/Generic/None/71087 MC Random Camp Gen.sql
- Database/Patches/9 WeenieDefaults/Generic/None/88445 MC Rare Spawn Gen.sql
**Added:**
**Creatures:**
High Priestess of T'thuun
T'thuun Sclavus Huntsmaster (Updated)
**Items:**
Piercing Wand of T'thuun
Gens
> Creeping Blight Champions

- Database/Patches/8 QuestDefDB/GearallCorePickup.sql
- Database/Patches/8 QuestDefDB/KierienCorePickup.sql
- Database/Patches/8 QuestDefDB/LurgissCorePickup.sql
- Database/Patches/8 QuestDefDB/TurgosCorePickup.sql
Adds missing core pickup quest entries for the gear knight rare bosses. The cores already have the pickup timer. Only the quest entries were missing.
> Add missing quest entries

- Database/Patches/9 WeenieDefaults/Creature/Human/49584 El'Yst Maggann.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/49584.es
- Database/Patches/9 WeenieDefaults/Creature/Undead/52248 Lingering Spirit of the Recluse.sql
- Database/Patches/9 WeenieDefaults/Creature/Undead/52248.es
> Four Corners of Dereth Updates

- Database/Patches/2 SpellTableExtendedData/03923 Tunnels to the Harbinger.sql
- Database/Patches/9 WeenieDefaults/Creature/Unsorted/33238 Tunnels to the Harbinger.sql
- Database/Patches/9 WeenieDefaults/Creature/Unsorted/33238.es
Updates the Issk side Tunnels to the Harbinger to portal to the correct section of the dungeon (that with the Virindi, since when you side with Issk you fight the Virindi).
> Harbinger Portal Fix

- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/46828 Purified Mouryou Katana.sql
- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/46829 Purified Mouryou Nanjou-tachi.sql
- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/46832 Purified Mouryou Nekode.sql
Updated weapons to be Base Skill req instead of Skill req.
> Purified Weapons Update

- Database/Patches/9 WeenieDefaults/Generic/Misc/45728 Geraine's Tome (2).sql
- Database/Patches/9 WeenieDefaults/Generic/Misc/45729 Geraine's Tome (5).sql
- Database/Patches/9 WeenieDefaults/Generic/Misc/45730 Geraine's Tome (4).sql
- Database/Patches/9 WeenieDefaults/Generic/Misc/45732 Geraine's Tome (7).sql
- Database/Patches/9 WeenieDefaults/Generic/Misc/45734 Geraine's Tome (3).sql
> added attuned and bonded

- Database/Patches/9 WeenieDefaults/Clothing/Clothing/44982 Creeping Blight Cloak.sql
- Database/Patches/9 WeenieDefaults/Clothing/Clothing/44983 House Mhoire Cloak.sql
- Database/Patches/9 WeenieDefaults/Clothing/Clothing/45486 Blackened House Mhoire Cloak.sql
added unenchantable and weild requirements. basically fluff stuff. keeps the id panel from being empty.
> fluff ints added

- Database/Patches/9 WeenieDefaults/Creature/Unsorted/42063 Spectral Fountain.sql
- Database/Patches/9 WeenieDefaults/Creature/Unsorted/42063.es
in retail if you hand a corrupter amber to the fountain it deletes itself
> add delete self

- Database/Patches/2 SpellTableExtendedData/04982 Nimble Fingers - Lockpick.sql
- Database/Patches/2 SpellTableExtendedData/04983 Nimble Fingers - Alchemy.sql
- Database/Patches/2 SpellTableExtendedData/04984 Nimble Fingers - Cooking.sql
- Database/Patches/2 SpellTableExtendedData/04985 Nimble Fingers - Fletching.sql
Changes the various nimble fingers buffs from -20 jump (?) to +5 of their respective skills.
> Fix Nimble Fingers buffs

- Database/Patches/9 WeenieDefaults/Gem/Gem/30141 Hieroglyph of Healing Mastery.sql
https://asheron.fandom.com/wiki/Hieroglyph_of_Healing_Mastery
> fix spell on t5 rare Hieroglyph of Healing Mastery, from Incantation of Heal Self -> Incantation of Healing Mastery Self

- Database/Patches/9 WeenieDefaults/Creature/Undead/45754 Mhoire Soldier.sql
- Database/Patches/9 WeenieDefaults/Creature/Undead/45754.es
http://acpedia.org/wiki/Geraine%27s_Hosts
Note: In order for this quest to count as one of the Legendary Key Quests you must turn in all 7 books to the Mhoire Lieutenant in Wai Jhou.
you were able to get credit for this quest by turning in the 1st 4 books into the soldier. which is not retail
> geraine host fix

- Database/Patches/9 WeenieDefaults/Healer/Misc/43479 Light Infused Healing Kit.sql
ACE-PCAP-Dynamics-Exports/Database/3-Core/9 WeenieDefaults/SQL/Healer/Misc
/43479 Light Infused Healing Kit.sq
> Update 43479 Light Infused Healing Kit.sql

- Database/Patches/4 CraftTable/08518 Channeling Stone Hatchet.sql
Add Channeling Stone Hatchet recipe
> Add Channeling Stone Hatchet recipe

- Database/Patches/9 WeenieDefaults/Creature/Human/38694 Balon Strongarm.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/38694.es
- Database/Patches/9 WeenieDefaults/Creature/Human/38697 Hador the Vengeful.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/38697.es
- Database/Patches/9 WeenieDefaults/Creature/Human/38700 Cullum of Celdon.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/38700.es
error in text that retail meta would not proceed due to the missing ,
> society fix for retail meta

- Database/Patches/9 WeenieDefaults/Creature/Human/38694 Balon Strongarm.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/38694.es
- Database/Patches/9 WeenieDefaults/Creature/Human/38697 Hador the Vengeful.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/38697.es
- Database/Patches/9 WeenieDefaults/Creature/Human/38700 Cullum of Celdon.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/38700.es
While there's no record I could find of the full line these NPCs say when you have 1-7 jaws, the retail meta has a partial match which should now match the new line.
Thanks to @Fire-Chimp
> Updated some text to match retail meta

- Database/Patches/9 WeenieDefaults/MissileLauncher/MissileWeapon/70965 Enhanced Bow of the Quiddity.sql
Adds missing ResistanceModifierType to Enhanced Bow of the Quiddity
> Fix Quiddity Bow Resistance Cleave

- Database/Patches/9 WeenieDefaults/Creature/Golem/33033 Masonry Golem.sql
Thanks to Celcynd for making us aware of this error.
> Correct Masonry Golem Default Palette

- Database/Patches/9 WeenieDefaults/Generic/None/80394 Northwatch Celhan Supply Gen.sql
- Database/Patches/9 WeenieDefaults/Generic/None/80395 Northwatch Eldweb Supply Gen.sql
- Database/Patches/9 WeenieDefaults/Generic/None/80396 Northwatch Radblo Supply Gen.sql
Create northwatch supply crate instead of freebooter
> Fix Northwatch supply gens

- Database/Patches/4 CraftTable/08101 Filled Sacrificial Goblet.sql
- Database/Patches/6 LandBlockExtendedData/007C.sql
- Database/Patches/9 WeenieDefaults/Book/Writable/34316 Soul Hunter's Orders.sql
- Database/Patches/9 WeenieDefaults/Book/Writable/34317 Copy of Soul Hunter's Orders.sql
- Database/Patches/9 WeenieDefaults/Generic/Misc/34308 Sacrificial Goblet.sql
- Database/Patches/9 WeenieDefaults/Generic/Misc/34309 Filled Sacrificial Goblet.sql
- Database/Patches/9 WeenieDefaults/Generic/Misc/34310 Soul Hunter's Untranslated Orders.sql
Added missing properties to several quest items (attuned, bonded, description, etc.). 
Filled section of the dungeon that had been left empty. 
Corrected crafting interaction text (retail text found on Maggie's website).
http://www.thejackcat.com/AC/Hobbies/Quests/soul_hunter.htm
> Update Soul Hunter Quest

- Database/Patches/1 RegionDescExtendedData/2892.sql
- Database/Patches/1 RegionDescExtendedData/2893.sql
- Database/Patches/1 RegionDescExtendedData/2894.sql
- Database/Patches/1 RegionDescExtendedData/2992.sql
- Database/Patches/1 RegionDescExtendedData/2993.sql
- Database/Patches/1 RegionDescExtendedData/2994.sql
- Database/Patches/1 RegionDescExtendedData/2A92.sql
- Database/Patches/1 RegionDescExtendedData/2A93.sql
- Database/Patches/1 RegionDescExtendedData/2A94.sql
- Database/Patches/9 WeenieDefaults/Creature/Shadow/32784 Shadow Wraith.sql
- Database/Patches/9 WeenieDefaults/Creature/Shadow/32789 Shadow Nightmare.sql
- Database/Patches/9 WeenieDefaults/Generic/None/85000 Shadow March Generator.sql
Added missing shadow types (royal and viamontian knight types) and revised spawn density to match retail based on pcaps.
> Update Shadow March

- Database/Patches/6 LandBlockExtendedData/5D4E.sql
Add surface portal to Olthoi Abyssal Chasm
According to vloc data, Surface Portal - @teleloc 0x5D4E0113 [75.250000 -40.819336 -54] 1 0 0. 0. 
Also world objects data confirms 38239 14 5D4E0113 -27.24 -39.72 -0.23 Surface Portal Surface Portal (0.7N, 44.7E). 
Looking at weenies, ace46019-surfaceportal Surface Portal matches this data.
This change addresses issue reported here: https://github.com/ACEmulator/ACE/issues/3950
> Create 5D4E.sql Olthoi Abyssal Chasm Exit Portal - Reported Issue

- Database/Patches/9 WeenieDefaults/Creature/Anekshay/53281 Aangesilus.sql
Corrects appearance of this NPC to match retail (thanks Raile).
> Update 53281 Aangesilus.sql

- Database/Patches/2 SpellTableExtendedData/04816 Novice Soldier's Finesse Weapon Aptitude.sql
- Database/Patches/2 SpellTableExtendedData/04817 Apprentice Soldier's Finesse Weapon Aptitude.sql
- Database/Patches/2 SpellTableExtendedData/04818 Journeyman Soldier's Finesse Weapon Aptitude.sql
- Database/Patches/2 SpellTableExtendedData/04819 Master Soldier's Finesse Weapon Aptitude.sql
Spells updated from Dagger to Finesse Weapons
> Update Swift Set

- Database/Patches/9 WeenieDefaults/Creature/Human/72510 Materialized Hoshino Kei.sql
Swaps motion table to make her float when she moves, as seen in retail video by Immortal Bob.
> Update 72510 Materialized Hoshino Kei.sql

- Database/Patches/6 LandBlockExtendedData/5647.sql
- Database/Patches/9 WeenieDefaults/Creature/Golem/00197 Iron Golem.sql
- Database/Patches/9 WeenieDefaults/Creature/Golem/23345 Iron Golem Guardian.sql
- Database/Patches/9 WeenieDefaults/Creature/Golem/29357 Fractured Glacial Golem.sql
- Database/Patches/9 WeenieDefaults/Creature/Golem/73199 Limestone Sentinel.sql
- Database/Patches/9 WeenieDefaults/Creature/Golem/73200 Obsidian Sentinel.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/23348 Astara Duskshield.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/23348.es
Updates this quest to the end of retail spawns and XP reward.
https://asheron.fandom.com/wiki/Spear_of_the_Given_Heart_Quest
> Update Spear of the Given Heart Quest

- Database/Patches/6 LandBlockExtendedData/5648.sql
- Database/Patches/6 LandBlockExtendedData/5649.sql
- Database/Patches/6 LandBlockExtendedData/574C.sql
- Database/Patches/9 WeenieDefaults/Creature/Golem/23035 Obsidian Excavation Golem.sql
- Database/Patches/9 WeenieDefaults/Creature/Golem/43411 Haze Golem.sql
- Database/Patches/9 WeenieDefaults/Creature/Golem/43413 Voltaic Golem.sql
- Database/Patches/9 WeenieDefaults/Creature/Golem/43414 Hardened Obsidian Golem.sql
- Database/Patches/9 WeenieDefaults/Creature/Golem/43415 Molten Golem.sql
Updates this quest to end of retail spawns.
http://acpedia.org/wiki/Crystal_Minds_and_Shattered_Souls
> Update Crystal Minds Quest

- Database/Patches/9 WeenieDefaults/Creature/Apparition/36773 Olthoi Sentinel Tracker.sql
Changes values using the CreatureSkills PCAP report
> Fix Olthoi Sentinel Tracker LW/MeD values based off PCAP estimates

- Database/Patches/9 WeenieDefaults/Creature/Crystal/40098 Bound Wisp.sql
- Database/Patches/9 WeenieDefaults/Creature/Crystal/40098.es
Thanks to "Duck Dodgers" for notifying us of this bug.
> Updated Bound Wisp to match contract quest flag and added basic stats/info to NPC

- Database/Patches/2 SpellTableExtendedData/04665 Epic Frost Bane.sql
- Database/Patches/2 SpellTableExtendedData/04669 Epic Slashing Bane.sql
Thanks to "An Adventurer" for this bug report.
> Corrected modifier on two epic bane spells

- Database/Patches/9 WeenieDefaults/Book/Misc/46360 The Story of the Lost Sisters.sql
- Database/Patches/9 WeenieDefaults/Book/Misc/46361 The Story of the Lost Sisters.sql
- Database/Patches/9 WeenieDefaults/Book/Misc/46362 The Story of the Lost Sisters.sql
- Database/Patches/9 WeenieDefaults/Book/Misc/87467 The Story of the Lost Sisters.sql
- Database/Patches/9 WeenieDefaults/Book/Misc/87468 The Story of the Lost Sisters.sql
Adds missing attuned, bonded, and description.
> Update Lost Lore Pages

- Database/Patches/9 WeenieDefaults/Clothing/Clothing/28616 Toga.sql
Thanks to "An Adventurer" for the bug report!
> Change Toga to underclothes instead of armor

- Database/Patches/6 LandBlockExtendedData/5F44.sql
- Database/Patches/9 WeenieDefaults/Creature/Tusker/35777 Grunter.sql
- Database/Patches/9 WeenieDefaults/Creature/Tusker/35777.es
Adds Grunter, a tusker NPC in Bobo's throne room. Also slightly adjusts Bobo's location from the pcap.
http://acpedia.org/wiki/Grunter
Thanks to OptimShi for the list of missing NPCs.
> Add Grunter

- Database/Patches/6 LandBlockExtendedData/D798.sql
- Database/Patches/9 WeenieDefaults/Creature/Golem/42543 Deewain.sql
- Database/Patches/9 WeenieDefaults/Creature/Golem/42543.es
Adds to final pcapped location on Asheron's Island.
Thanks to OptimShi for the list of missing NPCs.
> Add Deewain to Asheron's Island

- Database/Patches/9 WeenieDefaults/Creature/Human/43741 Archmage Ichihiri.sql
Updated NPC to have male setup & soundtable. Thanks to Carthar for the bug report.
> Update 43741 Archmage Ichihiri.sql

- Database/Patches/9 WeenieDefaults/Creature/Human/05152 Jilsaya bint Dah.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/05152.es
Thanks to Ethollad for reporting this issue!
> fix missing Seasoned Explorer Axe Cast wcid from Jilsaya bint Dah

- Database/Patches/9 WeenieDefaults/Creature/Elemental/33546 Asheron's Servant.sql
- Database/Patches/9 WeenieDefaults/Creature/Elemental/33546.es
Talking to Asheron's Servant was resetting progress (tower guardian construction). Looks like the success/failure emotes were backwards, so switched those.
> Fix Asheron's Servant Emotes

- Database/Patches/2 SpellTableExtendedData/04059 Endurance Other Incantation.sql
- Database/Patches/2 SpellTableExtendedData/04060 Quickness Other Incantation.sql
Fixes Endurance Other Incantation and Quickness Other Incantation (used by some empyrean quest gear) to affect the right attribute with the right value.
> Fix Endurance/Quickness Other Incantations

- Database/Patches/2 SpellTableExtendedData/05437 Corruptor's Boon.sql
- Database/Patches/2 SpellTableExtendedData/05438 Corruptor's Boon.sql
Gives them the correct skill/value.
> Fix Corruptor's Boon spells

- Database/Patches/2 SpellTableExtendedData/04722 Bleed Other.sql
- Database/Patches/2 SpellTableExtendedData/04986 Assassin's Alchemy Kit.sql
- Database/Patches/2 SpellTableExtendedData/05035 Feeble Sword Aptitude.sql
- Database/Patches/2 SpellTableExtendedData/05073 Moderate Item Tinkering Expertise.sql
- Database/Patches/2 SpellTableExtendedData/06174 Twisting Wounds.sql
- Database/Patches/2 SpellTableExtendedData/06175 Increasing Pain.sql
- Database/Patches/2 SpellTableExtendedData/06182 Over-Exerted.sql
Fixed some spells based off description and category. Think the alchemy one is the only one actually used (wcids 40629, 40631), but may as well fill in some of the gaps.
> Fix Various Spells

- Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/35949 Tusker Bone Sword.sql
> Add missing weapon type (int 353) to Tusker Bone Sword

- Database/Patches/9 WeenieDefaults/Creature/Human/31338 Gronk the Hammer.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/72620 Tanada Neophyte.sql
Corrects the appearance of Gronk the Hammer - thanks Raile for the fix.
Corrects scale of Tanada Neophyte. They were a little smaller compared to the other Tanada. Thanks Fire Chimp for the report.
> Update Gronk and Tanada Neophyte

- Database/Patches/9 WeenieDefaults/Creature/Golem/42543 Deewain.sql
- Database/Patches/9 WeenieDefaults/Creature/Golem/42543.es
- Database/Patches/9 WeenieDefaults/Creature/Human/37074 Ayaname Kina.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/37074.es
Adds missing girth armor to Ayaname Kina and interaction for BDC Quiddity Ingot (PR #1760). 
Updates Deewain dialogue to the correct one at his final location on Asheron's Island.
> Update Ayaname Kina and Deewain

- Database/Patches/6 LandBlockExtendedData/00A8.sql
- Database/Patches/6 LandBlockExtendedData/EC0E.sql
- Database/Patches/8 QuestDefDB/KnorrQuidityIngotPurified.sql
- Database/Patches/9 WeenieDefaults/Creature/Unknown/73251 Pool of Water.sql
- Database/Patches/9 WeenieDefaults/Creature/Unknown/73251.es
- Database/Patches/9 WeenieDefaults/Portal/Portal/37068 Roots of the Deru Tree.sql
- Database/Patches/9 WeenieDefaults/Portal/Portal/73252 Exit.sql
- Database/Patches/9 WeenieDefaults/Stackable/Misc/37078 Purified Quiddity Ingot.sql
Adds the quest:
https://asheron.fandom.com/wiki/Knorr_Quiddity_Ingot_Purification
> Add Knorr Quiddity Ingot Purification Quest

- Database/Patches/6 LandBlockExtendedData/5E45.sql
- Database/Patches/8 QuestDefDB/TanadaDirectives.sql
- Database/Patches/8 QuestDefDB/TanadaDirectivesPickup.sql
- Database/Patches/9 WeenieDefaults/Book/Writable/73258 Directives.sql
- Database/Patches/9 WeenieDefaults/Book/Writable/73259 Directives.sql
- Database/Patches/9 WeenieDefaults/Chest/Container/35736 Corpse.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/35308 Meshenq.sql
- Database/Patches/9 WeenieDefaults/Creature/Human/35308.es
- Database/Patches/9 WeenieDefaults/Generic/Misc/35743 Corpse.sql
- Database/Patches/9 WeenieDefaults/Generic/Misc/35744 Corpse.sql
- Database/Patches/9 WeenieDefaults/Generic/Misc/35745 Corpse.sql
Adds the quest:
https://acpedia.org/wiki/Tanada_House_of_Water%27s_Directives
> Add Tanada Directives Quest
