ACEmulator/ACE-World-16PY-Patches

Database/Patches/AtlanIsparian/4 CraftTable/00793 Quality Infused Pyreal Ingot - Retired.sql, Database/Patches/AtlanIsparian/4 CraftTable/00795 Quality Infused Pyreal Ingot - Retired.sql, Database/Patches/AtlanIsparian/4 CraftTable/00796 Superb Infused Pyreal Ingot - Retired.sql, Database/Patches/AtlanIsparian/4 CraftTable/00797 Quality Infused Pyreal Ingot - Retired.sql, Database/Patches/AtlanIsparian/4 CraftTable/00799 Quality Infused Pyreal Ingot - Retired.sql, Database/Patches/AtlanIsparian/4 CraftTable/00801 Quality Infused Pyreal Ingot - Retired.sql, Database/Patches/AtlanIsparian/4 CraftTable/00802 Superb Infused Pyreal Ingot - Retired.sql, Database/Patches/AtlanIsparian/4 CraftTable/00803 Quality Infused Pyreal Ingot - Retired.sql, Database/Patches/AtlanIsparian/4 CraftTable/00804 Superb Infused Pyreal Ingot - Retired.sql, Database/Patches/AtlanIsparian/4 CraftTable/00805 Quality Infused Pyreal Ingot - Retired.sql, Database/Patches/TrainingAcademy/4 CraftTable/06200 Academy Handwraps.sql, Database/Patches/TrainingAcademy/4 CraftTable/06201 Academy Short Sword.sql, Database/Patches/TrainingAcademy/4 CraftTable/06202 Academy Bastone.sql, Database/Patches/TrainingAcademy/4 CraftTable/06203 Academy Budiaq.sql, Database/Patches/TrainingAcademy/4 CraftTable/06204 Academy Dabus.sql, Database/Patches/TrainingAcademy/4 CraftTable/06205 Academy Knife.sql, Database/Patches/TrainingAcademy/4 CraftTable/06206 Academy Tungi.sql, Database/Patches/TrainingAcademy/4 CraftTable/06214 Academy Knuckles.sql, Database/Patches/TrainingAcademy/4 CraftTable/06215 Academy Broad Sword.sql, Database/Patches/TrainingAcademy/4 CraftTable/06216 Academy Staff.sql, Database/Patches/TrainingAcademy/4 CraftTable/06217 Academy Spear.sql, Database/Patches/TrainingAcademy/4 CraftTable/06218 Academy Club.sql, Database/Patches/TrainingAcademy/4 CraftTable/06219 Academy Dagger.sql, Database/Patches/TrainingAcademy/4 CraftTable/06220 Academy Hand Axe.sql, Database/Patches/TrainingAcademy/4 CraftTable/06221 Academy Spadone.sql
- Add retirement recipe changes for old Atlan weapons that don't exist post 16PY
- Update Academy Weapon recipe IDs to match the Lifestoned data team's work
=> Update2 : Quick Recipie changes

Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Mite/24029 Mite Warrior Queen.sql
Fixed the Mite Queen Staff to drop 1 instead of 250 and 1 Crumbled Note instead of 250.
=> Mite Queen CreateList Fix

Database/Patches/2005-07-ThroneOfDestiny/6 LandBlockExtendedData/E533.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Eater/28827 Marauder.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Human/29317 Jonathan.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Human/29324 Jonathan.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Human/29325 Jonathan.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Human/29326 Jonathan.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Mosswart/42144 Mosswart Warden.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Portal/29503 Karlun's Hall Exit.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Scroll/44621 Scroll of Nether Blast III.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Scroll/44622 Scroll of Nether Blast IV.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Scroll/44623 Scroll of Nether Blast V.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Scroll/44624 Scroll of Nether Blast VI.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Scroll/44625 Scroll of Nether Blast VII.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Vendor/43352 Master Scrivener of Void Magic.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Vendor/43353 Grand Master Scrivener of Void Magic.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Vendor/43354 Scrivener of Void Magic.sql, Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Portal/Portal/43000 Base of the Timaru Plateau Portal.sql
- Fix exit portal from Karlun's Hall to remove level restriction
- Update Marauder Eater to always drop jaw, up from zero chance
- Update Base of the Timaru Plateau Portal to drop player near the NPC that sends the player to the top of the plateau
- Update Jonathan's emote table; token is attuned so cannot be lost.  NPC doesn't need to reissue token to player
- Add Mountain Sewer entry portal
- Fix Void Scriveners attacking
=> Apply some content fixes from bug reports on Trello

Database/Patches/2005-07-ThroneOfDestiny/3 TreasureTable/Death/00998.sql, Database/Patches/2005-07-ThroneOfDestiny/3 TreasureTable/Death/00999.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/CraftTool/TinkeringMaterial/20988 Salvaged Mahogany.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/CraftTool/TinkeringMaterial/21050 Salvaged Green Garnet.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Device/43399 Void Magic Warden of Enlightenment.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Device/45390 Dirty Fighting Warden of Enlightenment.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Device/45392 Recklessness Warden of Enlightenment.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Device/45394 Sneak Attack Warden of Enlightenment.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Device/49483 Summoning Warden of Enlightenment.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Penguin/28659 Uber Penguin.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Penguin/28661 Uber Penguin.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Thrungus/31021 Puffball Thrungus.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Thrungus/31022 Jelly Thrungus.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Thrungus/31023 Black Morel Thrungus.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Thrungus/31024 Mudwort Thrungus.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Thrungus/31025 Fire Morel Thrungus.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Thrungus/31030 Mudwort Thrungus.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Food/Misc/37516 Enhanced Mana Elixir.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Food/Misc/37517 Enhanced Health Elixir.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Gem/Gem/30268 Sanamar Portal Gem.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Gem/Gem/32081 Redspire Portal Gem.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/SkillAlterationDevice/45380 Dirty Fighting Gem of Enlightenment.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/SkillAlterationDevice/45382 Recklessness Gem of Enlightenment.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/SkillAlterationDevice/45384 Sneak Attack Gem of Enlightenment.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/SkillAlterationDevice/49484 Summoning Gem of Enlightenment.sql
- Adjustments for loot tier 7
- Add new skills Gems of Enlightenment
- Update new skills Wardens of Enlightenment to issue their gems
- Update Enhanced Health Elixir
- Add Enhanced Mana Elixir
- Add Redspire Portal Gem that uses newer LinkedPortalOne
- Update Sanamar Portal Gem to use newer LinkedPortalOne
=> Loot tier adjustments and updates from LSD

Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Mosswart/31009 Mosswart Worshipper.sql, Database/Patches/2005-08-FriendAndFoe/9 WeenieDefaults/Creature/Human/31653 Orfeo Orlando.sql
- Match the quest entries listed in the emote table with what is defined in the quest database
=> Mosswart Worshipper Kill Task fix

Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Olthoi/31005 Olthoi Ripper.sql
This is a fix specifically for ACE generators
=> fixing Olthoi Rippers spawning too many ninjas

Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Clothing/Armor/25646 Long Leather Gauntlets.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Tusker/01629 Tusker Guard.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Tusker/21525 Tusker Guard.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Tusker/22592 Tusker Guard.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Tusker/22593 Tusker Guard.sql
- Update Tusker Guard loot tier profile to T4, up from T3, to match wiki
=> Update Loot Tier :: TuskerGuard

Database/Patches/2005-07-ThroneOfDestiny/6 LandBlockExtendedData/018E.sql
- Move the Linked Monster Generator to be within the dungeon, so it will tick and respawn its mobs after they perish
=> Move linked mob gen

Database/Patches/2013-02-BalanceOfPower/9 WeenieDefaults/CombatPet/48879 Golem.sql, Database/Patches/2013-02-BalanceOfPower/9 WeenieDefaults/CombatPet/48881 Golem.sql, Database/Patches/2013-02-BalanceOfPower/9 WeenieDefaults/CombatPet/48883 Golem.sql, Database/Patches/2013-02-BalanceOfPower/9 WeenieDefaults/CombatPet/48885 Golem.sql, Database/Patches/2013-02-BalanceOfPower/9 WeenieDefaults/CombatPet/48887 Golem.sql, Database/Patches/2013-02-BalanceOfPower/9 WeenieDefaults/CombatPet/48889 Golem.sql, Database/Patches/2013-02-BalanceOfPower/9 WeenieDefaults/CombatPet/48891 Golem.sql
- Correct vitals for Geomancer Golems: init_Level should equal current_level minus attribute contribution
=> Correct vitals for Geomancer Golems

Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/05333 Bael'zharon's Nether Arc.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/05362 Nether Arc II.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/05363 Nether Arc III.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/05364 Nether Arc IV.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/05365 Nether Arc V.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/05366 Nether Arc VI.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/05367 Nether Arc VII.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/05368 Incantation of Nether Arc.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/05369 Nether Arc I.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/05442 Acid Spit Arc 1.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/05443 Acid Spit Arc 2.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/05967 Galvanic Arc.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/06162 Thorn Arc.sql
This should fix issues with Nether Arcs and some other spells that didn't have NonTracking set to true and would not be classified properly as Arc spells
=> Set NonTracking to True for later Arc spells.

Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Gem/Gem/22135 Frest Greelving's Emerald.sql
- Remove loot gen properties from quest item; MaterialType causing the client to mangle the name
=> Remove loot gen properties from quest item

Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37187 Olthoi Alduressa Gauntlets.sql, Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37188 Olthoi Amuli Gauntlets.sql, Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37189 Olthoi Celdon Gauntlets.sql, Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37190 Olthoi Koujia Gauntlets.sql, Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37192 Olthoi Celdon Girth.sql, Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37195 Olthoi Alduressa Helm.sql, Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37196 Olthoi Amuli Helm.sql, Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37197 Olthoi Celdon Helm.sql, Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37198 Olthoi Koujia Kabuton.sql, Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37200 Olthoi Alduressa Leggings.sql, Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37201 Olthoi Amuli Leggings.sql, Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37202 Olthoi Celdon Leggings.sql, Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37203 Olthoi Koujia Leggings.sql, Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37205 Olthoi Celdon Sleeves.sql, Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37206 Olthoi Koujia Sleeves.sql, Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37207 Olthoi Alduressa Boots.sql, Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37208 Olthoi Amuli Sollerets.sql, Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37209 Olthoi Celdon Sollerets.sql, Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37211 Olthoi Koujia Sollerets.sql, Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37214 Olthoi Celdon Breastplate.sql, Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37215 Olthoi Koujia Breastplate.sql, Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37217 Olthoi Alduressa Coat.sql, Database/Patches/2008-08-AncientPowers/9 WeenieDefaults/Clothing/Armor/37299 Olthoi Amuli Coat.sql
- Decrease or increase baseline AL values for Olthoi armor types, as appropriate, so when combined with a minor code revision in LootGenerationFactory_Clothing.cs GetArmorLevelModifier() method will result in armor being produced without over-inflated AL values
=> Normalize Olthoi Armor AL values

Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/03865 Glenden Wood Recall.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/03930 Whispering Blade Chapterhouse Recall.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/04084 Bur Recall.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/04128 Call of the Mhoire Forge.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/04198 Paradox-touched Olthoi Infested Area Recall.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/04213 Colosseum Recall.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/04214 Return to the Keep.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/05330 Gear Knight Invasion Area Camp Recall.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/05541 Lost City of Neftet Recall.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/06150 Rynthid Recall.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/06321 Viridian Rise Recall.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/06322 Viridian Rise Great Tree Recall.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/06326 Eldrytch Web Stronghold Recall.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/06327 Radiant Blood Stronghold Recall.sql
Updated drop locations for the following recall spells:
Glenden Wood Recall
Bur Recall
Call of the Mhoire Forge
Paradox-touched Olthoi Infested Area Recall
Colosseum Recall
Return to the Keep
Gear Knight Invasion Area Camp Recall
Lost City of Neftet Recall
Rynthid Recall
Viridian Rise Recall
Viridian Rise Great Tree Recall
Eldrytch Web Stronghold Recall
Radiant Blood Stronghold Recall
=> Updated drop locations for several recall spells

Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/03259 Aura of Infected Spirit Caress.sql
Note that server operators should run Database/Optional/Shard/2019-07-12-00-Match_World_Spells_In_Biota_Enchantment_Registry.sql after upgrading to this world release
=> fixing Aura of Infected Spirit Caress

Database/Patches/2009-12-GainingGround/9 WeenieDefaults/MissileLauncher/41893 Enhanced Assault Bow.sql, Database/Patches/2010-08-TheRisenPrincess/9 WeenieDefaults/Caster/45956 Seasoned Explorer Nether Staff.sql, Database/Patches/2010-08-TheRisenPrincess/9 WeenieDefaults/MeleeWeapon/70211 Seasoned Explorer Knife.sql, Database/Patches/2010-08-TheRisenPrincess/9 WeenieDefaults/MeleeWeapon/70215 Seasoned Explorer Budiaq.sql, Database/Patches/2010-08-TheRisenPrincess/9 WeenieDefaults/MeleeWeapon/70217 Seasoned Explorer Bastone.sql, Database/Patches/2010-08-TheRisenPrincess/9 WeenieDefaults/MeleeWeapon/70219 Seasoned Explorer Simi.sql, Database/Patches/2010-08-TheRisenPrincess/9 WeenieDefaults/MeleeWeapon/70221 Seasoned Explorer Nekode.sql, Database/Patches/2010-08-TheRisenPrincess/9 WeenieDefaults/MeleeWeapon/70223 Seasoned Explorer Claw.sql, Database/Patches/2010-08-TheRisenPrincess/9 WeenieDefaults/MeleeWeapon/70225 Seasoned Explorer Quarter Staff.sql, Database/Patches/2010-08-TheRisenPrincess/9 WeenieDefaults/MeleeWeapon/70227 Seasoned Explorer Dirk.sql, Database/Patches/2010-08-TheRisenPrincess/9 WeenieDefaults/MeleeWeapon/70229 Seasoned Explorer Hand Axe.sql, Database/Patches/2010-08-TheRisenPrincess/9 WeenieDefaults/MeleeWeapon/70231 Seasoned Explorer Trident.sql, Database/Patches/2010-08-TheRisenPrincess/9 WeenieDefaults/MeleeWeapon/70233 Seasoned Explorer Stick.sql, Database/Patches/2010-08-TheRisenPrincess/9 WeenieDefaults/MeleeWeapon/70235 Seasoned Explorer Ken.sql, Database/Patches/2010-08-TheRisenPrincess/9 WeenieDefaults/MeleeWeapon/70237 Seasoned Explorer Board with Nail.sql, Database/Patches/2010-08-TheRisenPrincess/9 WeenieDefaults/MeleeWeapon/70239 Seasoned Explorer Khanjar.sql, Database/Patches/2010-08-TheRisenPrincess/9 WeenieDefaults/MeleeWeapon/70241 Seasoned Explorer Spiked Club.sql, Database/Patches/2010-08-TheRisenPrincess/9 WeenieDefaults/MeleeWeapon/70243 Seasoned Explorer Yari.sql, Database/Patches/2010-08-TheRisenPrincess/9 WeenieDefaults/MeleeWeapon/70245 Seasoned Explorer Tungi.sql, Database/Patches/2010-08-TheRisenPrincess/9 WeenieDefaults/MeleeWeapon/70247 Seasoned Explorer Shamshir.sql, Database/Patches/2010-08-TheRisenPrincess/9 WeenieDefaults/MeleeWeapon/70249 Seasoned Explorer Katar.sql, Database/Patches/2010-08-TheRisenPrincess/9 WeenieDefaults/MeleeWeapon/70251 Seasoned Explorer Morning Star.sql, Database/Patches/2010-08-TheRisenPrincess/9 WeenieDefaults/MeleeWeapon/70253 Seasoned Explorer Greataxe.sql, Database/Patches/2010-08-TheRisenPrincess/9 WeenieDefaults/MeleeWeapon/70254 Amateur Explorer Greataxe.sql
- Fix ElementalDamageMod on Seasoned Explorer Nether Staff
- Add missing Attuned property to Seasoned Explorer melee weapons
=> Add missing attuned prop

Database/Patches/2005-10-TricksAndTreats/9 WeenieDefaults/Creature/ViamontianKnight/32221 Master Alizari.sql, Database/Patches/2005-10-TricksAndTreats/9 WeenieDefaults/Creature/ViamontianKnight/32224 Mistress Halmera.sql, Database/Patches/2005-10-TricksAndTreats/9 WeenieDefaults/Creature/ViamontianKnight/32227 Mistress Gabille.sql, Database/Patches/2005-10-TricksAndTreats/9 WeenieDefaults/Creature/ViamontianKnight/32230 Master Versario.sql
in ACE currently Wield does not drop on corpse, but WieldTreasure can drop, so just marking these differently to be clear.
Retail did handle some of this differently, but trying to not break the current ACE pattern atm
=> Swap a few mobs from WieldTreasure to Wield 

Database/Patches/2013-02-BalanceOfPower/4 CraftTable/6943 Burning Sands Keyring On.sql, Database/Patches/2013-02-BalanceOfPower/4 CraftTable/8360 Shattered Legendary Key.sql, Database/Patches/2013-02-BalanceOfPower/4 CraftTable/8365 Burning Sands Golem Heart to Keyring.sql, Database/Patches/2013-02-BalanceOfPower/4 CraftTable/8366 Burning Sands Keyring Off.sql, Database/Patches/2013-02-BalanceOfPower/9 WeenieDefaults/Chest/48741 Legendary Armor Chest.sql, Database/Patches/2013-02-BalanceOfPower/9 WeenieDefaults/Chest/48742 Legendary Magic Chest.sql, Database/Patches/2013-02-BalanceOfPower/9 WeenieDefaults/Chest/48743 Legendary Chest.sql, Database/Patches/2013-02-BalanceOfPower/9 WeenieDefaults/Chest/48744 Legendary Weapon Chest.sql, Database/Patches/2013-02-BalanceOfPower/9 WeenieDefaults/CraftTool/Misc/48954 Burning Sands Keyring.sql, Database/Patches/2013-02-BalanceOfPower/9 WeenieDefaults/Generic/Misc/48941 Burning Sands Golem Heart.sql, Database/Patches/2013-02-BalanceOfPower/9 WeenieDefaults/Key/48746 Aged Legendary Key.sql, Database/Patches/2013-02-BalanceOfPower/9 WeenieDefaults/Key/48747 Legendary Key.sql, Database/Patches/2013-02-BalanceOfPower/9 WeenieDefaults/Key/48748 Legendary Key 2 Use.sql, Database/Patches/2013-02-BalanceOfPower/9 WeenieDefaults/Key/52010 Legendary Key 5 Use.sql, Database/Patches/2013-02-BalanceOfPower/9 WeenieDefaults/Misc/48908 Shattered Legendary Key.sql
This adds Legendary chests and several keys. Along with shattered, burning sands golem heart, keyring and corresponding recipes.
Additionally establishes the treasure profile with simultaneous LSD submission of this content.
Example:
Mana/Legendary forge Chest 1001/2001
Mana/Legendary armor Chest 1002/2002
Mana/Legendary magic Chest 1003/2003
Mana/Legendary weapon Chest 1004/2004
=> Legendary Keys Chests Recipe 

Database/Patches/2005-11-AshesAndDust/8 QuestDefDB/glendeninvaders.sql, Database/Patches/2005-11-AshesAndDust/8 QuestDefDB/glendeninvadersblockadeE.sql, Database/Patches/2005-11-AshesAndDust/8 QuestDefDB/glendeninvadersblockadeN.sql, Database/Patches/2005-11-AshesAndDust/8 QuestDefDB/glendeninvadersblockadeW.sql, Database/Patches/2005-11-AshesAndDust/8 QuestDefDB/glendeninvadersblockadeguards.sql, Database/Patches/2005-11-AshesAndDust/8 QuestDefDB/glendeninvadersblockadeguardstarted.sql, Database/Patches/2005-11-AshesAndDust/8 QuestDefDB/glendeninvaderskillcount.sql, Database/Patches/2005-11-AshesAndDust/8 QuestDefDB/glendeninvaderskills.sql, Database/Patches/2005-11-AshesAndDust/8 QuestDefDB/glendeninvaderskilltask.sql, Database/Patches/2005-11-AshesAndDust/8 QuestDefDB/glendeninvadersstarted.sql, Database/Patches/2005-11-AshesAndDust/8 QuestDefDB/glendenorbgiven.sql, Database/Patches/2005-11-AshesAndDust/8 QuestDefDB/glendoninvadersblockadekillcount.sql, Database/Patches/2005-11-AshesAndDust/8 QuestDefDB/glendoninvadersblockadekilltask.sql, Database/Patches/2005-11-AshesAndDust/8 QuestDefDB/glendonorbgiven.sql, Database/Patches/2005-11-AshesAndDust/9 WeenieDefaults/Creature/Eater/32314 Engorged Eater.sql, Database/Patches/2005-11-AshesAndDust/9 WeenieDefaults/Creature/Eater/32315 Famished Eater.sql, Database/Patches/2005-11-AshesAndDust/9 WeenieDefaults/Creature/Eater/32316 Eater.sql, Database/Patches/2005-11-AshesAndDust/9 WeenieDefaults/Creature/Human/32360 Londigul Ellic the Armorer.sql, Database/Patches/2005-11-AshesAndDust/9 WeenieDefaults/Creature/ViamontianKnight/32327 Blockade Guard.sql, Database/Patches/2005-11-AshesAndDust/9 WeenieDefaults/Creature/ViamontianKnight/32328 Blockade Guard.sql, Database/Patches/2005-11-AshesAndDust/9 WeenieDefaults/Creature/ViamontianKnight/32329 Viamontian Mercenary.sql, Database/Patches/2005-11-AshesAndDust/9 WeenieDefaults/Creature/ViamontianKnight/32333 Blockade Guard.sql
- Correct Glenden spelling in various places
- Redid quest structure to not rely on Kill Task code hacking that will soon be removed, as Londigul's quest was not really a Kill Task in the sense of other post TOD kill tasks
- Add requirement, per captured NPC text, to kill all three blockade guards
- Match NPC's dialog to PCAP data
=> Londigul Ellic revisit

Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Chest/05015 Large Chest.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Chest/28813 Chest.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Chest/29059 Old Chest.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Chest/29060 Old Chest.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Chest/29061 Old Chest.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Chest/29062 Old Chest.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Chest/29063 Old Chest.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Chest/29077 Old Chest.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Chest/29078 Old Chest.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Chest/29079 Old Chest.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Chest/29080 Old Chest.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Chest/29081 Old Chest.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Chest/29082 Old Chest.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Chest/29083 Old Chest.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Chest/29084 Old Chest.sql, Database/Patches/2009-10-GearsOfChange/1 RegionDescExtendedData/216F.sql, Database/Patches/2009-10-GearsOfChange/1 RegionDescExtendedData/2170.sql
- Fix a number of server log warning messages about chest weenies, either missing MaxGeneratedObjects or loopcount > 1000
- Remove two encounter drops nears the Gear Knight Invasion Area Camp Recall drop point
=> Chest changes and remove two encounters

Database/Patches/2012-08-TheRisenPrincess/9 WeenieDefaults/Generic/Misc/46422 Mastery Reset Certificate.sql
Add IsSellable False
All other items on this vendor have it and the wiki says not sell able. I think the pcap just missed this one for some reason. 
https://asheron.fandom.com/wiki/Mastery_Reset_Certificate
=> Update 46422 Mastery Reset Certificate.sql

Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Human/05178 Lubziklan al-Luq.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Human/28705 Anton Sillezi.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Human/28856 Renald the Eldest.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/Human/28857 Gonjoku Den.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Misc/28830 Mossy Herb.sql, Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Misc/28844 Renald's Old Mug.sql
- Round floats on Trade Alliances NPCs
- Simplify emote chains on quest NPCs for Trade Alliances questline, such as removing pointless quest entry checks that will always return QuestFailure result
=> Trade Alliances cleanup

Database/Patches/2009-10-GearsOfChange/6 LandBlockExtendedData/2170.sql, Database/Patches/2010-08-QuietBeforeTheStorm/6 LandBlockExtendedData/2170.sql, Database/Patches/2010-09-PlansWithinPlans/6 LandBlockExtendedData/2170.sql
Had an issue with out of sync landblock causing a delete from one patch to the next, erasing all the NPC's at the tent out in the direlands.
=> Update Direlands Gearknight Camp

Database/Patches/2005-07-ThroneOfDestiny/4 CraftTable/06010 Prismatic Quarrel.sql, Database/Patches/2005-07-ThroneOfDestiny/4 CraftTable/06011 Prismatic Quarrel.sql, Database/Patches/2005-07-ThroneOfDestiny/4 CraftTable/06012 Greater Prismatic Quarrel.sql, Database/Patches/2005-07-ThroneOfDestiny/4 CraftTable/06013 Greater Prismatic Quarrel.sql, Database/Patches/2005-07-ThroneOfDestiny/4 CraftTable/06016 Prismatic Atlatl Dart.sql, Database/Patches/2005-07-ThroneOfDestiny/4 CraftTable/06017 Prismatic Atlatl Dart.sql, Database/Patches/2005-07-ThroneOfDestiny/4 CraftTable/06018 Greater Prismatic Atlatl Dart.sql, Database/Patches/2005-07-ThroneOfDestiny/4 CraftTable/06019 Greater Prismatic Atlatl Dart.sql
Standard and greater prismatic atlatl and quarrels success_message for crafting were using "you make a bundle of deadly XYZ".
Corrected
=> Correct atlatl/quarrel prismatic success_message

Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/05337 Destructive Curse VII.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/05338 Incantation of Destructive Curse.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/05339 Destructive Curse I.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/05340 Destructive Curse II.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/05341 Destructive Curse III.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/05342 Destructive Curse IV.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/05343 Destructive Curse V.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/05344 Destructive Curse VI.sql
Destructive Curse was missing the special DoT duration signifier, causing it to behave slighltly differently than it should (not getting the tick spread out over an extra +5s, and incorrectly being given boosts by spell duration aug)
=> updating destructive curse dot duration

Database/Patches/2007-10-Masked Memories/9 WeenieDefaults/Container/36561 Colosseum Backpack.sql
Fix colosseum backpack burden to 15, instead of higher incorrect value from pcap
=> Update 36561 Colosseum Backpack.sql

Database/Patches/2005-07-ThroneOfDestiny/6 LandBlockExtendedData/E532.sql
https://asheron.fandom.com/wiki/A_Rising_Darkness
Apprentice Cook (Tou-Tou) - relocated to Mayoi (61.8S, 81.8E)
=> Move Apprentice Cook from Tou-Tou to Mayoi

Database/Patches/2013-02-BalanceOfPower/3 TreasureTable/Death/02000 Tier 8 Loot.sql, Database/Patches/2013-02-BalanceOfPower/3 TreasureTable/Death/02000.sql, Database/Patches/2013-02-BalanceOfPower/3 TreasureTable/Death/02001 Legendary Mixed Equipment Chest.sql, Database/Patches/2013-02-BalanceOfPower/3 TreasureTable/Death/02002 Legendary Armor Chest.sql, Database/Patches/2013-02-BalanceOfPower/3 TreasureTable/Death/02003 Legendary Magic Chest.sql, Database/Patches/2013-02-BalanceOfPower/3 TreasureTable/Death/02004 Legendary Weapon Chest.sql
The following is to add T8 Death Treasure Profiles.  This update will have all creatures that currently use DT 2000 drop T8 Loot.  The old DT 2000 was set for T7.  Server Ops need to be aware of this change.
=> T8 Death Treasure Profiles

Database/Patches/2011-11-MasterOfDesign/9 WeenieDefaults/Clothing/Armor/25982 Battle Pants.sql
Ready for review
http://acpedia.org/wiki/Battle_Pants
This was reported, 
"Battle Pants have foot coverage making them unable to be tailored. The foot coverage was removed in the tailoring patch. I've updated the ACpedia to reflect this change."
Weenie updated to remove foot coverage / match PCAP
Update
(25982,   4,       2816) /* ClothingPriority - OuterwearUpperLegs, OuterwearLowerLegs, OuterwearAbdomen */
(25982,   9,      25600) /* ValidLocations - AbdomenArmor, UpperLegArmor, LowerLegArmor */
Add
(25982,  23,   True ) /* DestroyOnSell */
(25982, 165,       1) /* ArmorModVsNether */
=> Update Battle Pants to EOR/PCAP

Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/05205 Surge of Affliction.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/05208 Surge of Regeneration.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/05337 Destructive Curse VII.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/05338 Incantation of Destructive Curse.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/05339 Destructive Curse I.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/05340 Destructive Curse II.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/05341 Destructive Curse III.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/05342 Destructive Curse IV.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/05343 Destructive Curse V.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/05344 Destructive Curse VI.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/05387 Corrosion I.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/05388 Corrosion II.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/05389 Corrosion III.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/05390 Corrosion IV.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/05391 Corrosion V.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/05392 Corrosion VI.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/05393 Corrosion VII.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/05394 Incantation of Corrosion.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/05395 Corruption I.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/05396 Corruption II.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/05397 Corruption III.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/05398 Corruption IV.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/05399 Corruption V.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/05400 Corruption VI.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/05401 Corruption VII.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/05402 Incantation of Corruption.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/05939 Bleeding Assault.sql, Database/Patches/2017-01-EndOfRetail/2 SpellTableExtendedData/SQL/05943 Bleeding Blow.sql
** This PR must be installed in tandem with https://github.com/ACEmulator/ACE/pull/3166 **
For the DoT enchantment.StatModValues sent over the wire in retail, these were based on the amount per tick, and not total amount over the course of the duration of the spell.
DoTs were a bit weird in this regard, void DoTs especially, as the StatModValue in the enchantment that was sent across the wire would not always equal the StatModValue in the base spell. For void DoTs especially, a 'pre-calculation' would be done, that would factor in things that would buff the outgoing damage, and then it would write this buffed value to the enchantment. ie. for void dots, enchantment.StatModValue = spell.StatModValue * buffs
This can get tricky with the frequency of the ticks. Currently in ACE, the DoT …
=> updating dot statmodvals to match retail (per tick, instead of total)

Database/Patches/2013-02-BalanceOfPower/8 QuestDefDB/countphainorsamuletwait.sql
Updated Quest timer to 20 Hours.
> 
Count Phainor's Amulet | Solo/Group | 10,000 | 10,000 | 20 hours
-- | -- | -- | -- | --
=> Update Count Phainors Amulet Quest Timer

Database/Patches/2009-12-GainingGround/4 CraftTable/04499 Aqua Vitae.sql, Database/Patches/2009-12-GainingGround/4 CraftTable/04500 Aqua Vitae.sql, Database/Patches/2009-12-GainingGround/4 CraftTable/04501 Aqua Vitae.sql, Database/Patches/2009-12-GainingGround/4 CraftTable/04502 Aqua Vitae.sql, Database/Patches/2009-12-GainingGround/4 CraftTable/04503 Aqua Vitae.sql, Database/Patches/2009-12-GainingGround/4 CraftTable/04504 Aqua Vitae.sql
This is my first PR so let me know if there is anything I could be doing differently.
My eventual goal is to make all the alchemy-related changes from the Gaining Ground (2009/12) patch but this one starts by just updating the amounts of Aqua Vitae generated by combining Concentrated Aqua Incanta with pyreal motes (and slivers, etc).  According to the [acpedia wiki](http://acpedia.org/wiki/Gaining_Ground#Alchemy_and_Gearcrafting_Updates), the amount simply tripled, though I'm a little confused by the specified ranges.  After talking with folks in the discord content_recreation channel we decided to just ignore the ranges and go with a static output.
I basically just copy/pasted the sql files from the ACE-World repo and put them in the appropriate patch folder with updated success_amounts. …
=> From Gaining Ground patch, increase the number of generated Aqua Vitae by 3x

Database/Patches/2006-01-Reprisals/9 WeenieDefaults/Creature/Mukkir/31897 Barbaric Mukkir.sql, Database/Patches/2006-07-TowardAncientShores/9 WeenieDefaults/Creature/Mukkir/31901 Fanatical Mukkir.sql, Database/Patches/2006-07-TowardAncientShores/9 WeenieDefaults/Creature/Mukkir/33037 Vile Mukkir.sql, Database/Patches/2006-07-TowardAncientShores/9 WeenieDefaults/Creature/Mukkir/33038 Coruscating Mukkir.sql, Database/Patches/2006-07-TowardAncientShores/9 WeenieDefaults/Creature/Mukkir/33130 Mukkir.sql, Database/Patches/2006-07-TowardAncientShores/9 WeenieDefaults/Creature/Mukkir/33538 Fanatical Mukkir Ward Guardian.sql, Database/Patches/2006-07-TowardAncientShores/9 WeenieDefaults/Creature/Mukkir/33623 Biaka Mukkir.sql, Database/Patches/2006-07-TowardAncientShores/9 WeenieDefaults/Creature/Mukkir/33624 Degenerate Mukkir.sql, Database/Patches/2006-07-TowardAncientShores/9 WeenieDefaults/Creature/Mukkir/33625 Depraved Mukkir.sql, Database/Patches/2006-07-TowardAncientShores/9 WeenieDefaults/Creature/Mukkir/33626 Hellion Mukkir.sql, Database/Patches/2006-07-TowardAncientShores/9 WeenieDefaults/Creature/Mukkir/33732 Degenerate Mukkir.sql, Database/Patches/2006-07-TowardAncientShores/9 WeenieDefaults/Creature/Mukkir/33733 Depraved Mukkir.sql, Database/Patches/2006-07-TowardAncientShores/9 WeenieDefaults/Creature/Mukkir/40281 Degenerate Mukkir.sql, Database/Patches/2006-07-TowardAncientShores/9 WeenieDefaults/Creature/Mukkir/40282 Depraved Mukkir.sql, Database/Patches/2006-08-ShatteringTheDark/9 WeenieDefaults/Creature/Mukkir/33131 Mukkir Laktar.sql, Database/Patches/2006-08-ShatteringTheDark/9 WeenieDefaults/Creature/Mukkir/33132 Mukkir Kartak.sql, Database/Patches/2006-08-ShatteringTheDark/9 WeenieDefaults/Creature/Mukkir/33133 Mukkir Draktehn.sql, Database/Patches/2006-08-ShatteringTheDark/9 WeenieDefaults/Creature/Mukkir/33458 Mukkir Aspect of Grael.sql, Database/Patches/2006-08-ShatteringTheDark/9 WeenieDefaults/Creature/Mukkir/33898 Mukkir Progenitor.sql, Database/Patches/2007-02-RekindlingTheLight/9 WeenieDefaults/Creature/Mukkir/31898 Umbral Mukkir.sql, Database/Patches/2007-02-RekindlingTheLight/9 WeenieDefaults/SQL/Creature/Mukkir/35142 Mukkir Draktehn.sql, Database/Patches/2007-02-RekindlingTheLight/9 WeenieDefaults/SQL/Creature/Mukkir/35143 Mukkir Kartak.sql, Database/Patches/2007-02-RekindlingTheLight/9 WeenieDefaults/SQL/Creature/Mukkir/35144 Mukkir Laktar.sql, Database/Patches/2007-02-RekindlingTheLight/9 WeenieDefaults/SQL/Creature/Mukkir/35145 Umbral Mukkir.sql
Retail pcaps indicate that Mukkir in general are not resistant to
Nether and life magic spells. There are no counter indications known, and it
appears that the resistances may have originally been copied from other mobs.
=> Reset Nether and Life magic resistance for Mukkir

Database/Patches/2012-08-TheRisenPrincess/9 WeenieDefaults/Creature/Shadow/44815 Shadow Flyer.sql
Adjusted XP on Tou-Tou Shadow Flyer from eleven million to 1.1 million to reflect correct end-of-retail value.
=> Update 44815 Shadow Flyer.sql

Database/Patches/2017-01-EndOfRetail/22024 Full Mu-miyah Guise.sql, Database/Patches/2017-01-EndOfRetail/28858 Armored Skeleton Guise.sql, Database/Patches/2017-01-EndOfRetail/28859 Armored Undead Guise.sql, Database/Patches/2017-01-EndOfRetail/28860 Scarecrow Guise.sql
Ive updated the clothing priority and valid locations. to reflect end of retail. Wiki shows screen shots of Full Coverage in these guises. where as ACE core weenies did not cover hands. I believe these were updated sometime in 2006 but I could not find any mention of it on the Wiki, or Fandom.
http://acpedia.org/wiki/Full_Mu-miyah_Guise
http://acpedia.org/wiki/Scarecrow_Guise
http://acpedia.org/wiki/Armored_Undead_Guise
http://acpedia.org/wiki/Armored_Skeleton_Guise
Gmriggs suggested it go in the EOR folder.
=> update to PreTOD Guises

Database/Patches/2013-09-TheQuestForFreedom/9 WeenieDefaults/SQL/Caster/Caster/51899 Casting Stone.sql, Database/Patches/2013-10-ShatteredMasks/9 WeenieDefaults/Clothing/Jewelry/52036 Purified Crimson Scarab.sql
Corrected critical frequency on Casting Stone from 1 to 0.3.
Added missing wield emote for Purified Crimson Scarab (source, retail video, about 3 min in, https://www.youtube.com/watch?v=9Jiqt0sIozg).
=> Casting Stone and Crimson Scarab Update

Database/Patches/2005-06-PreTOD/1 RegionDescExtendedData/7B63.sql
- Remove an three encounter generator spawns from deep water landblock off the coast of Yaraq that is causing failed spawn spam warning messages in the log file
=> Remove Encounter from deep water landblock

Database/Patches/2013-08-EmotionsUnbound/9 WeenieDefaults/Creature/Virindi/51749 Rynthid Minion.sql, Database/Patches/2013-08-EmotionsUnbound/9 WeenieDefaults/Creature/Virindi/51750 Rynthid Minion.sql, Database/Patches/2013-08-EmotionsUnbound/9 WeenieDefaults/Creature/Virindi/51757 Raging Rynthid Sorcerer.sql, Database/Patches/2013-08-EmotionsUnbound/9 WeenieDefaults/Creature/Virindi/51758 Raging Rynthid Sorcerer.sql, Database/Patches/2013-08-EmotionsUnbound/9 WeenieDefaults/Creature/Virindi/51759 Rynthid Sorcerer.sql, Database/Patches/2013-08-EmotionsUnbound/9 WeenieDefaults/Creature/Virindi/51760 Rynthid Sorcerer.sql, Database/Patches/2013-08-EmotionsUnbound/9 WeenieDefaults/Creature/Virindi/52278 Rynthid Sorcerer.sql, Database/Patches/2013-08-EmotionsUnbound/9 WeenieDefaults/Creature/Virindi/52280 Rynthid Minion.sql, Database/Patches/2013-10-ShatteredMasks/9 WeenieDefaults/Creature/Crystal/51971 Sanctum Warding Crystal.sql, Database/Patches/2013-10-ShatteredMasks/9 WeenieDefaults/Creature/Crystal/51972 Sanctum Warding Crystal.sql, Database/Patches/2013-10-ShatteredMasks/9 WeenieDefaults/Creature/Crystal/51973 Sanctum Warding Crystal.sql, Database/Patches/2013-10-ShatteredMasks/9 WeenieDefaults/Creature/Crystal/51974 Sanctum Warding Crystal.sql, Database/Patches/2013-10-ShatteredMasks/9 WeenieDefaults/Creature/Virindi/51938 Tormented Sorcerer.sql, Database/Patches/2013-10-ShatteredMasks/9 WeenieDefaults/MeleeWeapon/51968 Rynthid Tentacle Greatspear.sql
Rynthid Tentacle Greatspear now has correct base damage (previously had buffed instead of base damage).
Added missing mask to Rynthid Minions.
Sanctum Warding Crystals now non-projectile magic immune as in retail.
Adjusted spellcasting probabilities on Rynthid sorcerer type mobs to cast more ring and war spells, less vuls.
=> Rynthid Fixes

Database/Patches/2005-07-ThroneOfDestiny/4 CraftTable/05202 Salvaged Green Garnet.sql
- Update the recipe_mod DataID value, for Green Garnet Salvage recipe, to match value on Lifestoned published recipe to not conflict with Covenant mutation script value
=> Update 05202 Salvaged Green Garnet recipe_mod

Database/Patches/2005-07-ThroneOfDestiny/4 CraftTable/08004 Foolproof Aquamarine.sql, Database/Patches/2005-07-ThroneOfDestiny/4 CraftTable/08005 Foolproof Black Garnet.sql, Database/Patches/2005-07-ThroneOfDestiny/4 CraftTable/08006 Foolproof Emerald.sql, Database/Patches/2005-07-ThroneOfDestiny/4 CraftTable/08007 Foolproof Jet.sql, Database/Patches/2005-07-ThroneOfDestiny/4 CraftTable/08008 Foolproof Red Garnet.sql, Database/Patches/2005-07-ThroneOfDestiny/4 CraftTable/08009 Foolproof White Sapphire.sql, Database/Patches/2005-07-ThroneOfDestiny/4 CraftTable/08010 Foolproof Imperial Topaz.sql, Database/Patches/2005-07-ThroneOfDestiny/4 CraftTable/08011 Foolproof Black Opal.sql, Database/Patches/2005-07-ThroneOfDestiny/4 CraftTable/08012 Foolproof Fire Opal.sql, Database/Patches/2005-07-ThroneOfDestiny/4 CraftTable/08013 Foolproof Sunstone.sql, Database/Patches/2005-07-ThroneOfDestiny/4 CraftTable/08014 Foolproof Zircon.sql, Database/Patches/2005-07-ThroneOfDestiny/4 CraftTable/08015 Foolproof Yellow Topaz.sql, Database/Patches/2005-07-ThroneOfDestiny/4 CraftTable/08016 Foolproof Peridot.sql
Foolproof salvage did not use the tinkering difficulty formula, and did not send out broadcasts to the landblock:
https://youtu.be/V5XWzF8KuLE?t=84s
salvage_Type should be considered more like difficulty_Type, determining which difficulty formula to use (0 = standard recipe, use the recipe.difficulty, 1 = tinkering, use the tinkering difficulty formula, 2 = imbues, use the imbues difficulty formula). If you want something with a 100% success rate, then it would be salvage_Type=0, difficulty=0
=> update foolproof salvage to match retail

Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/MeleeWeapon/45541 Training Dabus.sql
Gear Knights w/ Finesse Weapons trained start with this item
This prevents some decal exceptions being written to the chat window for characters w/ this item
There are many more items in the DB that still have retired WeaponSkills, but this is the only remaining one I found in the starterGear.json
=> update training dabus to have post-MoA WeaponSkill

Database/Patches/2006-06-FromTheDarkestDepths/9 WeenieDefaults/Clothing/Armor/87038 Helm of Isin Dule.sql
- Remove spells that make mobs wielding it overly capable in the defense department, throwing off balance, and removing unneeded properties / helm item is basically for looks only, when wielded by mobs
=> Update 87038 Helm of Isin Dule.sql

Database/Patches/2006-09-ComeWhatFollows/9 WeenieDefaults/Creature/Lugian/31003 Tukora Commander.sql, Database/Patches/2006-09-ComeWhatFollows/9 WeenieDefaults/Creature/Mosswart/31010 Mosswart Elder.sql, Database/Patches/2006-09-ComeWhatFollows/9 WeenieDefaults/Creature/Undead/31015 Mu-miyah Sentinel.sql, Database/Patches/2006-09-ComeWhatFollows/9 WeenieDefaults/Creature/Zefir/31017 Kirit Zefir.sql
Update the Nanjou Shou-Jen Armor Quest.
Currently only Olthoi Rippers 31005 and Kirit Zefir 31017 generate Tanada Nanjou Shou-jen 34014.
Added 31010 Mosswart Elder, 31003 Tukora Commander, and 31015 Mu-miyah Sentinel to generate them.
Based on mobtracker numbers fixed all spawn rates at 2% which is the same as original contributor used on Olthoi Ripper 31005.
Kirit Zefir was changed from 15% down to 2%.  Olthoi Ripper 31005 has not been changed.
Weenies currently located in ACE-World-16PY-Patches/Database/Patches/2005-07-ThroneOfDestiny/9 WeenieDefaults/Creature/
=> Nanjou shou jen armor quest update

Database/Patches/2005-09-UnderCoverOfNight/9 WeenieDefaults/Creature/Golem/31919 Wave Golem.sql, Database/Patches/2005-09-UnderCoverOfNight/9 WeenieDefaults/Creature/Golem/31920 Aqueous Golem.sql
Both Golems were dropping T7 weapons only profile (ie Mana Forge Weapon Chest).  Switched to a generic T7 profile
=> Viss Isle Golem Updated Death Treasure Profile

Database/Patches/2007-08-CorruptedSovereigns/9 WeenieDefaults/Creature/Paradox Olthoi/35875 Paradox-touched Olthoi Sentinel.sql, Database/Patches/2007-08-CorruptedSovereigns/9 WeenieDefaults/Creature/Paradox Olthoi/35877 Paradox-touched Olthoi Sentinel.sql
Update to Paradox Touched Olthoi Sentinel.  Had chance to drop 2 Venom Sacs (Alt Currency) at an 80% drop rate.  This was being abused.  Removed the double chance and reduced drop rate to 20% which is more inline with stats from Trophy Hunter (which is 14.8%).  See [http://www.trophyhunteronline.com/trophy-monster.php?trophy=Small+Olthoi+Venom+Sac](http://www.trophyhunteronline.com/trophy-monster.php?trophy=Small+Olthoi+Venom+Sac)
=> ParadoxTouchedOlthoiSentinel

Database/Patches/2010-11-FromDarknessLight/6 LandBlockExtendedData/011C.sql, Database/Patches/2010-11-FromDarknessLight/6 LandBlockExtendedData/0136.sql
Updated the Mountain Fortress and Empyrean Foundry dungeons to EoR spawns. These were missed when the Hamud's Demise quest was updated and were pulling from py16.
=> Hamud's Demise Dungeon Updates

Database/Patches/2014-01-ForcesOfNature/9 WeenieDefaults/Caster/53330 Oak Stormwood Wand.sql, Database/Patches/2014-01-ForcesOfNature/9 WeenieDefaults/Caster/53333 Oak Derubloom Wand.sql, Database/Patches/2014-01-ForcesOfNature/9 WeenieDefaults/Caster/53334 Oak Corrupted Heartwood Wand.sql, Database/Patches/2014-01-ForcesOfNature/9 WeenieDefaults/MeleeWeapon/53320 Oak Stormwood Axe.sql, Database/Patches/2014-01-ForcesOfNature/9 WeenieDefaults/MeleeWeapon/53323 Oak Stormwood Dagger.sql, Database/Patches/2014-01-ForcesOfNature/9 WeenieDefaults/MeleeWeapon/53324 Oak Stormwood Mace.sql, Database/Patches/2014-01-ForcesOfNature/9 WeenieDefaults/MeleeWeapon/53325 Oak Stormwood Spear.sql, Database/Patches/2014-01-ForcesOfNature/9 WeenieDefaults/MeleeWeapon/53327 Oak Stormwood Greatsword.sql, Database/Patches/2014-01-ForcesOfNature/9 WeenieDefaults/MeleeWeapon/53328 Oak Stormwood Sword.sql, Database/Patches/2014-01-ForcesOfNature/9 WeenieDefaults/MeleeWeapon/53329 Oak Stormwood Claw.sql, Database/Patches/2014-01-ForcesOfNature/9 WeenieDefaults/MeleeWeapon/72005 Oak Stormwood Staff.sql, Database/Patches/2014-01-ForcesOfNature/9 WeenieDefaults/MissileLauncher/52732 Storming Portal Axe.sql, Database/Patches/2014-01-ForcesOfNature/9 WeenieDefaults/MissileLauncher/53321 Oak Stormwood Bow.sql, Database/Patches/2014-01-ForcesOfNature/9 WeenieDefaults/MissileLauncher/53322 Oak Stormwood Crossbow.sql, Database/Patches/2014-01-ForcesOfNature/9 WeenieDefaults/MissileLauncher/72004 Oak Stormwood Atlatl.sql
Removed Oak from the name string of all superior versions of the weapons. Removed int 47 from Storming Portal Axe.
=> Viridian Rise Weapon Revisions

Database/Patches/2012-08-TheRisenPrincess/9 WeenieDefaults/Creature/Human/46014 Umbral Guard.sql, Database/Patches/2012-08-TheRisenPrincess/9 WeenieDefaults/Creature/Human/46015 Royal Guard.sql, Database/Patches/2012-08-TheRisenPrincess/9 WeenieDefaults/Creature/Human/46016 Umbral Guard.sql, Database/Patches/2012-08-TheRisenPrincess/9 WeenieDefaults/Creature/Human/46017 Royal Guard.sql, Database/Patches/2012-08-TheRisenPrincess/9 WeenieDefaults/Creature/Human/46018 Royal Guard.sql, Database/Patches/2012-08-TheRisenPrincess/9 WeenieDefaults/Creature/Human/52272 Royal Guard.sql
Exported from ACE, using original Weenies from Original Tou-Tou update.  Tested.  Works with retail meta.
=> Fixes Tou-Tou NPCs chat that was removed last update

Database/Patches/2010-11-FromDarknessLight/6 LandBlockExtendedData/79E9.sql, Database/Patches/2010-11-FromDarknessLight/8 QuestDefDB/BloodstoneFactoryKeyPickup.sql, Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/Creature/Crystal/51340 Bloodstone Fragment.sql, Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/Creature/Crystal/51353 Bloodstone Fragment.sql, Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/Creature/Crystal/51354 Bloodstone Shard.sql, Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/Creature/Crystal/51355 Bloodstone Shard.es, Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/Creature/Crystal/51355 Bloodstone Shard.sql, Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/Creature/Crystal/70368 Master Bloodstone.es, Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/Creature/Crystal/70368 Master Bloodstone.sql, Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/Creature/Crystal/72636 Unstable Master Bloodstone Satellite.es, Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/Creature/Crystal/72636 Unstable Master Bloodstone Satellite.sql, Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/Key/72635 Legendary Key.sql, Database/Patches/2010-11-FromDarknessLight/9 WeenieDefaults/Portal/72634 Surface Bloodstone Factory.sql
Added missing door and legendary chests at the end of the Bloodstone Factory dungeon.
Added missing 3-use legendary key from the Master Bloodstone.
Added missing Master Bloodstone Satellites.
Corrected bloodstone spellbooks based on pcap spell info and available video.
Added missing surface portals.
Revised spawns in Lord Kastellar's room based on teaser screenshot.
Revised spawns in tunnel before the jump and Master Bloodstone room based on video and retail screenshots.
Bloodstone Shards now have a 50% chance to spawn 2 Bloodstone Fragments on death, as seen on video.
=> Bloodstone Investigation Update

Database/Patches/2007-04-StrangeSightings/9 WeenieDefaults/Creature/Ghost/72230 Lady Tairla Mhoire NPC.sql, Database/Patches/2010-11-FromDarknessLight/6 LandBlockExtendedData/79E9.sql, Database/Patches/2013-03-DisturbanceInTheDesert/9 WeenieDefaults/Creature/Elemental/49637 Elemental Protector.sql, Database/Patches/2013-03-DisturbanceInTheDesert/9 WeenieDefaults/Creature/Simulacrum/49641 Simulacrum Shifter.es, Database/Patches/2013-03-DisturbanceInTheDesert/9 WeenieDefaults/Creature/Simulacrum/49641 Simulacrum Shifter.sql, Database/Patches/2013-08-EmotionsUnbound/9 WeenieDefaults/Creature/Unsorted/51887 Corrupted Crystal of Torments.sql, Database/Patches/2013-08-EmotionsUnbound/9 WeenieDefaults/Creature/Unsorted/72130 Corrupted Crystal of Rage.sql
Graveyard
Lady Mhoire NPC emote now matches the emote script, turning off her reward event. 
Bloodstone Factory
Replaced reward room door with one that has a 5 min reset. 
Moved two of the chests in the reward room to flank the surface portal for a better match to retail layout.
The Master Bloodstone will now spawn in the same location as the Bloodstone Stockpile, as in retail.
Uziz Liberation
Simulacrum Shifter now has a chance to spawn Elemental Protectors instead of automatically spawning them to match retail.
Rynthid Artifact Collection
Removed buggy kill task message from Corrupted Crystal of Torments and Corrupted Crystal of Rage.
=> Misc Bug Fixes and Updates

Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Creature/Human/09492 Monty the Munificent.sql, Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Creature/Human/09493 Arshid al-Qiyid.sql, Database/Patches/2017-01-EndOfRetail/9 WeenieDefaults/SQL/Creature/Human/09494 Mi Gan-Zo.sql
Casinos currently gives the prompt for "10 High Stakes Tokens" for all three currencies. This changes them to Low/Mid/High. 
This is just a text change; the items given are the same.
=> Fix Prompt When Buying Multiple Casino Tokens

Database/Patches/6 LandBlockExtendedData/4AE2.sql, Database/Patches/6 LandBlockExtendedData/4AE3.sql, Database/Patches/6 LandBlockExtendedData/4BE2.sql
Move door 46310 (GUID 0x74BE2003) in landblock 4BE2 slightly to prevent bypassing the first part of the Hoshino Fortress Infiltration quest.
=> Hoshino Door Fix

Database/Patches/6 LandBlockExtendedData/006E.sql, Database/Patches/9 WeenieDefaults/Creature/Golem/70972 Atlan's Crafting Golem.sql
Minor updates to the Empyrean Workshop dungeon:
Adjusted location of Inner Chamber Door from virindi data. It was was not placed correctly before, with a small gap between the door and frame.
Adjusted Atlan's Laboratory portal location.
Adjusted a surface portal location.
Added missing door.
Added on death flavor text to Atlan's Crafting Golem, seen in a retail video (around 19 min 45 sec in):
https://www.youtube.com/watch?v=_oWzOuJiXZI
=> Update Shadowfire Stone Quest

Database/Patches/6 LandBlockExtendedData/5877.sql, Database/Patches/9 WeenieDefaults/Creature/Shadow/51682 Shadow Captive.sql, Database/Patches/9 WeenieDefaults/Creature/Shadow/51682.es, Database/Patches/9 WeenieDefaults/Creature/Shadow/51683 Shadow Captive.sql, Database/Patches/9 WeenieDefaults/Creature/Shadow/51683.es, Database/Patches/9 WeenieDefaults/Generic/None/72780 Fear Factory Shadow Captive Gen.sql, Database/Patches/9 WeenieDefaults/Generic/None/72781 Feat Factory Corrupt Lugian Gen.sql
Adjusted the quest based on retail video, and virindi locations.
Specific changes:
Shadow Captive spawn is now random, with 8 out of 13 possible locations in the dungeon.
Corrupt Lugian guards now only spawn where a Shadow Captive spawns.
Added spell casting animation when a Shadow Captive is rescued.
Added some missing Dread Figment traps.
Slight adjustment to surface portal location from virindi data, in area of the dungeon that was not pcapped.
=> Update Fear Factory Quest

Database/Patches/9 WeenieDefaults/Creature/Human/46678 Lieutenant Aurin.sql, Database/Patches/9 WeenieDefaults/Creature/Human/46678.es, Database/Patches/9 WeenieDefaults/Creature/Human/46679 Sergeant Trebuus.sql, Database/Patches/9 WeenieDefaults/Creature/Human/46679.es, Database/Patches/9 WeenieDefaults/Creature/Human/46680 Lord Eorlinde.sql, Database/Patches/9 WeenieDefaults/Creature/Human/46680.es, Database/Patches/9 WeenieDefaults/Creature/Human/46681 Corporal Irashi.sql, Database/Patches/9 WeenieDefaults/Creature/Human/46681.es, Database/Patches/9 WeenieDefaults/Creature/Human/46682 Griffon.sql, Database/Patches/9 WeenieDefaults/Creature/Human/46682.es, Database/Patches/9 WeenieDefaults/Creature/Human/46683 Aun Kirtal.sql, Database/Patches/9 WeenieDefaults/Creature/Human/46683.es, Database/Patches/9 WeenieDefaults/Creature/Human/46684 Hanamoto Aki'ko.sql, Database/Patches/9 WeenieDefaults/Creature/Human/46684.es, Database/Patches/9 WeenieDefaults/Creature/Human/46686 Lieutenant Takamaki.sql, Database/Patches/9 WeenieDefaults/Creature/Human/46686.es
Fixes Hoshino area kill task rewards to match PCAP data.
Data taken from PCAP Part 1\Callaway-01-30-2017-BurQuests\pkt_2017-1-30_1485791858_log.pcap
=> Fix Hoshino KT rewards to match PCAP data

Database/Patches/2 SpellTableExtendedData/04264 Arcane Death.sql, Database/Patches/2 SpellTableExtendedData/04282 Arcane Death.sql, Database/Patches/2 SpellTableExtendedData/04283 Arcane Death.sql, Database/Patches/6 LandBlockExtendedData/654D.sql, Database/Patches/9 WeenieDefaults/Creature/Human/72523 Hall of Agony.sql, Database/Patches/9 WeenieDefaults/Creature/Human/72578 Hall of Agony.sql, Database/Patches/9 WeenieDefaults/Creature/Human/72579 Hall of Agony.sql, Database/Patches/9 WeenieDefaults/Creature/Human/72580 Hall of Agony.sql, Database/Patches/9 WeenieDefaults/Creature/Human/72581 Hall of Agony.sql, Database/Patches/9 WeenieDefaults/Creature/Human/72582 Hall of Agony.sql, Database/Patches/9 WeenieDefaults/Creature/Human/72583 Hall of Agony.sql, Database/Patches/9 WeenieDefaults/Creature/Human/72584 Hall of Agony.sql, Database/Patches/9 WeenieDefaults/Creature/Human/72585 Hall of Agony.sql
Increased the damage on the Arcane Death spell used for traps in the Jester, Empyrean Rescue and Hoshino Must Die.
Sample damage numbers on a player with pierce pro 8, legendary pierce ward, and old school aegis equipped:
412, 455, 425, 486, 495, 474, 454, 439, 403, 427
Updated name of Hoshino Must Die traps to Hall of Agony as seen in a retail video.
Updated comments in the dungeon landblock with the traps to match.
=> Update Arcane Death

Database/Patches/8 QuestDefDB/FreedJester.sql, Database/Patches/9 WeenieDefaults/Creature/Empyrean/72262 Jester.sql, Database/Patches/9 WeenieDefaults/Creature/Empyrean/72262.es, Database/Patches/9 WeenieDefaults/Creature/Empyrean/72263 Jester.sql, Database/Patches/9 WeenieDefaults/Creature/Empyrean/72263.es, Database/Patches/9 WeenieDefaults/Creature/Ghost/35401 Lord Cynreft Mhoire.sql, Database/Patches/9 WeenieDefaults/Creature/Ghost/35401.es, Database/Patches/9 WeenieDefaults/Creature/Ghost/37145 Jailer.sql, Database/Patches/9 WeenieDefaults/Creature/Ghost/37145.es, Database/Patches/9 WeenieDefaults/Creature/Ghost/37146 Laylana.sql, Database/Patches/9 WeenieDefaults/Creature/Ghost/37146.es, Database/Patches/9 WeenieDefaults/Creature/Human/48921 Lieutenant Karul.sql, Database/Patches/9 WeenieDefaults/Creature/Human/48921.es, Database/Patches/9 WeenieDefaults/Creature/Unsorted/72256 Jester's Cell.sql, Database/Patches/9 WeenieDefaults/Creature/Unsorted/72256.es
Jester
Resolved an issue where a player could get stuck in the Jester quest series if they did not talk to Laylana within 20 hours of completing part 1.
Fixed a potential exploit created by the change to the FreedJester quest flag.
Fixed a problem where the player could get stuck on part 2 of the quest. The two versions of the Jester's Prison Key (version M and version J) can now be used to switch between parts 1 and 2 of the quest, respectively.
Added missing interaction with Lord Cynreft Mhoire allowing the player to get a new Jester's Prison Key (version M) without having to hand in a new Pleading Letter. The letter is only required on the first run. 
Save Karul
Karul no longer gets up when rewarding players to match retail video.
Removed no longer necessary sleeping heartbeat emote on …
=> Jester and Save Karul Fixes

Database/Patches/9 WeenieDefaults/Creature/Ghost/42027 Shade of Antemy.sql, Database/Patches/9 WeenieDefaults/Creature/Ghost/42027.es, Database/Patches/9 WeenieDefaults/Creature/Ghost/45201 Shade of Terelev.sql, Database/Patches/9 WeenieDefaults/Creature/Ghost/45201.es, Database/Patches/9 WeenieDefaults/Creature/Ghost/72501 Spirit of Bist'elle.sql, Database/Patches/9 WeenieDefaults/Creature/Ghost/72501.es, Database/Patches/9 WeenieDefaults/Creature/Human/42734 Sir Draithon.sql, Database/Patches/9 WeenieDefaults/Creature/Human/42734.es, Database/Patches/9 WeenieDefaults/Creature/Human/46445 Mareeno Donn.sql, Database/Patches/9 WeenieDefaults/Creature/Human/46445.es, Database/Patches/9 WeenieDefaults/Creature/Human/48853 Lord Brem.sql, Database/Patches/9 WeenieDefaults/Creature/Human/48853.es, Database/Patches/9 WeenieDefaults/Creature/Human/48921 Lieutenant Karul.sql, Database/Patches/9 WeenieDefaults/Creature/Human/48921.es, Database/Patches/9 WeenieDefaults/Creature/Human/51987 Morgethais.sql, Database/Patches/9 WeenieDefaults/Creature/Human/51987.es, Database/Patches/9 WeenieDefaults/Creature/Undead/45685 Mhoire Soldier.sql, Database/Patches/9 WeenieDefaults/Creature/Undead/45685.es, Database/Patches/9 WeenieDefaults/Creature/Undead/45754 Mhoire Soldier.sql, Database/Patches/9 WeenieDefaults/Creature/Undead/45754.es, Database/Patches/9 WeenieDefaults/Creature/Undead/45792 Mhoire Lieutenant.sql, Database/Patches/9 WeenieDefaults/Creature/Undead/45792.es
Adds the legendary quest bits stamp to several NPCs that were missing it.
http://ac.yotesfan.com/0E00001D-ContractTable/questbits.php
List of NPCs
Shade of Antemy for Castle Mhoire
Shade of Terelev for Mhoire Oubliette
72501 Spirit of Bist'elle for Hoshino Must Die
Mareeno Donn for Hoshino Fortress Infiltration
Lieutenant Karul for Saving Karul
Morgethais for Defeating the Curator of Torment
45685 Mhoire Soldier for Geraine's Library
45754 Mhoire Soldier for Geraine's Hosts
Mhoire Lieutenant for Geraine's Hosts
Minor bug fixes for other NPCs.
Lord Brem
Corrected level requirement from 200 to 150.
Lieutenant Karul
Added back heartbeat sleeping emote to make sure he stays sleeping.
Sir Draithon
Corrected MMD reward from 8 to 10.
=> Add Legendary Quest Flags

Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/33050 Red Rune Silveran Dagger.sql
Missed on my first set of fixes (PR 1183). Changing red rune silveran dagger's base stats to match retail base stats instead of buffed stats.
=> Fix Red Rune Silveran Dagger

Database/Patches/6 LandBlockExtendedData/17B2.sql
Updates 17B2.sql, removing the duplicate entry for Janus.
=> Fix duplicate Landblock entry for Janus Roma the Shopkeep in Redspire

Database/Patches/9 WeenieDefaults/Caster/Caster/27836 Singularity Scepter of Life Magic.sql, Database/Patches/9 WeenieDefaults/Caster/Caster/27837 Bound Singularity Scepter of Life Magic.sql, Database/Patches/9 WeenieDefaults/Caster/Caster/27838 Ultimate Singularity Scepter of Life Magic.sql, Database/Patches/9 WeenieDefaults/Caster/Caster/27839 Ultimate Singularity Scepter of War Magic.sql, Database/Patches/9 WeenieDefaults/Caster/Caster/27840 Singularity Scepter of War Magic.sql, Database/Patches/9 WeenieDefaults/Caster/Caster/27841 Bound Singularity Scepter of War Magic.sql, Database/Patches/9 WeenieDefaults/Caster/Caster/41885 Ultimate Singularity Scepter of Life Magic.sql, Database/Patches/9 WeenieDefaults/Caster/Caster/41886 Ultimate Singularity Scepter of War Magic.sql, Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/41879 Ultimate Singularity Axe.sql, Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/41882 Ultimate Singularity Dagger.sql, Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/41883 Ultimate Singularity Katar.sql, Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/41884 Ultimate Singularity Mace.sql, Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/41887 Ultimate Singularity Spear.sql, Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/41888 Ultimate Singularity Staff.sql, Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/41889 Ultimate Singularity Sword.sql, Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/41890 Ultimate Singularity Greatsword.sql, Database/Patches/9 WeenieDefaults/MissileLauncher/MissileWeapon/41880 Ultimate Singularity Bow.sql, Database/Patches/9 WeenieDefaults/MissileLauncher/MissileWeapon/41881 Ultimate Singularity Crossbow.sql, Database/Patches/9 WeenieDefaults/MissileLauncher/MissileWeapon/70970 Ultimate Singularity Atlatl.sql
Well if you look at the sing weapons they are 1.8. Why would a weapon upgrade kit jump the stats plus add extra slayer bonus?
Plus if you look at the slayer bonus on acpedia and compare them to pre tod weapons they match up exactly. Why would you not believe all the other %s are not legit.
41788 had 1.8 slayer bonus already
=> singularity weapon slayer bonus adjustments

Database/Patches/9 WeenieDefaults/Creature/AunTumerok/14571 Aun Aulakhe.sql, Database/Patches/9 WeenieDefaults/Creature/AunTumerok/14571.es
During the [Filling in the Blanks](http://acpedia.org/wiki/Filling_in_the_Blanks) event, the experience reward was increased from 28,000,000xp (30% up to level 110) to 30,000,000xp (100% up to level 81).
=> Invoker Quest XPUpdate

Database/Patches/4 CraftTable/06637 Blackfire Shimmering Isparian Dagger.sql
- Correct the target wcid in the cookbook recipe for the Blackfire Shimmering Isparian Dagger
=> Update 06637 Blackfire Shimmering Isparian Dagger.sql

Database/Patches/8 QuestDefDB/KillTaskPhyntosKiller1109.sql, Database/Patches/9 WeenieDefaults/Creature/PhyntosWasp/40308 Giant Jungle Phyntos Wasp.sql, Database/Patches/9 WeenieDefaults/Creature/PhyntosWasp/41799 Killer Phyntos Queen.sql
Updated KT to 50 kills per pcap data:
You have killed 36 Killer Phyntos Swarms! You must kill 50 to complete your task.
Removed KT from Jungle wasp and queen as no evidence to backup they were part of KT.
=> Killer Phyntos Wasp Kill Task Updates

Database/Patches/9 WeenieDefaults/Caster/Caster/71446 Exquisite Lense.sql
I noticed the spellcraft on the Exquisite Lense (level IV spells) is set to 100.  This appears to be a mistake since it should be 220.  I looked through the other lenses and they all seem to be correct, so I think it's just this one.
See here: http://acpedia.org/wiki/Exquisite_Lense
=> Fix Exquisite Lense Spellcraft to be 220

Database/Patches/9 WeenieDefaults/Book/Writable/43808 Carefully rolled scroll.sql
removed pickup timer. There was no pickup timer for this scroll in retail. Ran the quest alot. When I picked up the first scroll, go turn in, come back thru and you could pick up another with no timer. Besides why have a timer on the scroll, it does nothing but move you to the next step of the quest, no way to exploit or abuse.
=> Update 43808 Carefully rolled scroll.sql

Database/Patches/9 WeenieDefaults/Creature/Simulacrum/36599 Paradox Simulacrum War Mage.sql
Adds item enchantment so its item debuffs have an attack skill greater than 0 and can land. 
Changes spellbook values to be more reasonable (i.e. so that 99% of its spells aren't item debuffs and it actually casts all its spells). 
Changes magic skill values to match those in the CreatureSkills document.
=> Fix spellbook and stats for Paradox Simulacrum War Mage

Database/Patches/9 WeenieDefaults/Creature/Human/31692 Jun Sawashima.sql, Database/Patches/9 WeenieDefaults/Creature/Human/31692.es
The InqQuestBitsOn for Gold and Platinum medallions wasn't working since their quest failure states weren't reachable, resulting in the quests not counting for the contract counter. Don't think EmoteScript liked the labeled QuestFailures in the original .es file.
=> Fix Jun Sawashima emotes for Gold/Plat medallions

Database/Patches/9 WeenieDefaults/Creature/Human/72337 Geraine.sql
Added the missing 45680 Book trophy on the Geraine from the Mhoire Infiltration quest to match retail as per bug report:
http://acpedia.org/wiki/Geraine_(Creature)
This makes a total of 9 books, enough for a full fellowship (8 from side rooms, 1 on body).
=> Update 72337 Geraine.sql

Database/Patches/1 RegionDescExtendedData/C8E2.sql, Database/Patches/1 RegionDescExtendedData/C8E3.sql, Database/Patches/1 RegionDescExtendedData/C9E2.sql
Cleared the spawns from the Vissidal drop to match Hells retail video:
https://www.twitch.tv/videos/48337756?t=0h48m18s
There were no spawns at the drop, and going toward town.
=> Vissidal Clear Drop Spawns

Database/Patches/6 LandBlockExtendedData/4AE1.sql, Database/Patches/6 LandBlockExtendedData/4BE1.sql, Database/Patches/6 LandBlockExtendedData/4CE1.sql, Database/Patches/6 LandBlockExtendedData/4CE2.sql, Database/Patches/6 LandBlockExtendedData/4CE3.sql
Respawn time for static spawns (including sarcophagi) in the Hoshino area towns is reduced to 5 min to match the encounters generator respawn times.
=> Faster Hoshino Town Respawn

Database/Patches/1 RegionDescExtendedData/B34A.sql, Database/Patches/1 RegionDescExtendedData/B44A.sql, Database/Patches/1 RegionDescExtendedData/B64C.sql, Database/Patches/1 RegionDescExtendedData/B749.sql, Database/Patches/1 RegionDescExtendedData/B74A.sql, Database/Patches/9 WeenieDefaults/Generic/None/70846 Viridian Outer Camp Gen.sql, Database/Patches/9 WeenieDefaults/Generic/None/70847 Viridian Inner Camp Gen.sql, Database/Patches/9 WeenieDefaults/Generic/None/70851 Viridian Entrance Camp Gen.sql
Cleared more encounters that had been forgotten, resulting in double spawns.
Adjusted generator respawn rate.
=> Viridian Rise Spawn Fix

Database/Patches/9 WeenieDefaults/Generic/None/72217 GY Corrupted Gravestone Gen.sql, Database/Patches/9 WeenieDefaults/Generic/None/72219 GY Night Exhumed Bones Gen.sql, Database/Patches/9 WeenieDefaults/Generic/None/72220 GY Day Rat Camp Gen.sql, Database/Patches/9 WeenieDefaults/Generic/None/72221 GY Day Pyre Skeleton Camp Gen.sql, Database/Patches/9 WeenieDefaults/Generic/None/72222 GY Day Pyre Champion Camp Gen.sql, Database/Patches/9 WeenieDefaults/Generic/None/72224 GY Night Pyre Champion Camp Gen.sql, Database/Patches/9 WeenieDefaults/Generic/None/72225 GY Night Undead Camp Gen.sql, Database/Patches/9 WeenieDefaults/Generic/None/72226 GY Night Ghost Wanderer Gen.sql, Database/Patches/9 WeenieDefaults/Generic/None/72227 GY Night Wisp Wanderer Gen.sql, Database/Patches/9 WeenieDefaults/Generic/None/87012 GY Night Bunker Top Gen.sql
Added line item delays to prevent instant respawn. These were previously set to 0.
Adjusted regen interval on some generators to match the rest.
=> GY Spawn Fix

Database/Patches/9 WeenieDefaults/Creature/Elemental/52260 Pillar of Frost.sql, Database/Patches/9 WeenieDefaults/Creature/Elemental/52261 Pillar of Lightning.sql, Database/Patches/9 WeenieDefaults/Creature/Elemental/52262 Pillar of Acid.sql, Database/Patches/9 WeenieDefaults/Creature/Unsorted/52263 Pillar of Fire.sql
Updates the magic skills of the pillars spawns on the Four Corners of Dereth quest. Their associated PCAP (PCAP Part 3/miscpcaps1/pkt_2017-1-29_1485719326_log.pcap) unfortunately had a 0% resist rate at 412 magic defense so I can't get much actual data. I figured matching the skill levels of the other high skill pillars (e.g. 51831) was reasonable enough with what I do have.
=> Update magic skill levels on the 4 corners pillars

Database/Patches/9 WeenieDefaults/MissileLauncher/MissileWeapon/53310 Stormwood Crossbow.sql, Database/Patches/9 WeenieDefaults/MissileLauncher/MissileWeapon/53322 Stormwood Crossbow.sql
Stormwood crossbows were using bow stats. Changed them to crossbow stats from MagToolsInventory logs.
=> Fix VR Crossbow stats

Database/Patches/9 WeenieDefaults/Creature/Human/33596 Pathwarden Thorolf.sql, Database/Patches/9 WeenieDefaults/Creature/Human/33596.es, Database/Patches/9 WeenieDefaults/Creature/Human/33614 Pathwarden Koro Ijida.sql, Database/Patches/9 WeenieDefaults/Creature/Human/33614.es, Database/Patches/9 WeenieDefaults/Creature/Human/33615 Pathwarden Thierra Molanti.sql, Database/Patches/9 WeenieDefaults/Creature/Human/33615.es, Database/Patches/9 WeenieDefaults/Creature/Human/33616 Pathwarden Qanara bint Qolosh.sql, Database/Patches/9 WeenieDefaults/Creature/Human/33616.es
Turning in pathwarden items currently chooses 1 of 3 rewards randomly. They should be static. The hauberk, leggings, and robe reward a SIK, the sollerets and gauntlets reward steel salvage, and the helm rewards granite salvage. This can be seen to be 100% consistent in the dozen or so PCAPs recording these interactions. 
Also updates the robe turn-in dialogue based off PCAP data.
=> Fix pathwarden turn-ins to be static

Database/Patches/9 WeenieDefaults/Creature/Ghost/45196 Blinded Apparition.sql
Fixes blinded apparition aggro behavior to be more like retail. Based off PCAP "PCAP Part 3\MrBoomBoom-01-22-2017-SeveralLegendaryQuests\pkt_2017-1-29_1485719449_log.pcap". See https://www.youtube.com/watch?v=D4aIPvOaxWo for a small video portion taken from PCAP player. 
Requires ACE PR 3903 to behave properly (adds support for AuralAwarenessRange), but should still be an improvement without it.
=> Fix Blinded Apparition aggro behavior

Database/Patches/9 WeenieDefaults/Creature/Elemental/39288 Asheron's Investigator.sql, Database/Patches/9 WeenieDefaults/Creature/Elemental/39288.es
Fixes the bitfield check for Asheron's Investigator (Summoning T'thuun), which was using the decimal value (as hex) instead of the correct hex value for a 12-bit completed flag.
=> Fix bitfield check for Asheron's Investigator

Database/Patches/9 WeenieDefaults/Creature/Empyrean/44950 Chafulumisa.sql, Database/Patches/9 WeenieDefaults/Creature/Empyrean/44950.es
Timer cooldown text was referring to this NPC, not the player. Fixes "You have 10675199 day , 2 hour , 48 minute and 5 second left to adjust your attributes." error to the more meaningful, and accurate display of <30min (quest was working properly, just wrong display string)
=> Fixed cooldown display text

Database/Patches/6 LandBlockExtendedData/7D64.sql, Database/Patches/6 LandBlockExtendedData/977B.sql, Database/Patches/6 LandBlockExtendedData/A9B4.sql, Database/Patches/6 LandBlockExtendedData/DA55.sql, Database/Patches/8 QuestDefDB/WritOfApology_0508.sql, Database/Patches/9 WeenieDefaults/Creature/Human/37518 Royal Guard.sql, Database/Patches/9 WeenieDefaults/Creature/Human/37518.es, Database/Patches/9 WeenieDefaults/Gem/Gem/37515 Pack Aerbax.sql, Database/Patches/9 WeenieDefaults/Generic/Misc/37519 Enhanced Mana Elixir Orders.sql, Database/Patches/9 WeenieDefaults/Generic/Misc/37520 Foolproof Aquamarine Orders.sql, Database/Patches/9 WeenieDefaults/Generic/Misc/37521 Foolproof Black Garnet Orders.sql, Database/Patches/9 WeenieDefaults/Generic/Misc/37522 Foolproof Black Opal Orders.sql, Database/Patches/9 WeenieDefaults/Generic/Misc/37523 Foolproof Emerald Orders.sql, Database/Patches/9 WeenieDefaults/Generic/Misc/37524 Foolproof Fire Opal Orders.sql, Database/Patches/9 WeenieDefaults/Generic/Misc/37525 Foolproof Imperial Topaz Orders.sql, Database/Patches/9 WeenieDefaults/Generic/Misc/37526 Foolproof Jet Orders.sql, Database/Patches/9 WeenieDefaults/Generic/Misc/37527 Foolproof Peridot Orders.sql, Database/Patches/9 WeenieDefaults/Generic/Misc/37528 Foolproof Red Garnet Orders.sql, Database/Patches/9 WeenieDefaults/Generic/Misc/37529 Foolproof Sunstone Orders.sql, Database/Patches/9 WeenieDefaults/Generic/Misc/37530 Foolproof Yellow Topaz Orders.sql, Database/Patches/9 WeenieDefaults/Generic/Misc/37531 Foolproof Zircon Orders.sql, Database/Patches/9 WeenieDefaults/Generic/Misc/37532 Aerbax Pack Doll Orders.sql, Database/Patches/9 WeenieDefaults/Generic/Misc/37533 Aluvian Casino Key Orders.sql, Database/Patches/9 WeenieDefaults/Generic/Misc/37534 Gharu'ndim Casino Key Orders.sql, Database/Patches/9 WeenieDefaults/Generic/Misc/37535 Sho Casino Key Orders.sql, Database/Patches/9 WeenieDefaults/Generic/Misc/37536 Experience Orders.sql, Database/Patches/9 WeenieDefaults/Generic/Misc/37537 Enhanced Health Elixir Orders.sql, Database/Patches/9 WeenieDefaults/Stackable/Misc/37559 Writ of Apology.sql, Database/Patches/9 WeenieDefaults/Vendor/Creature/37538 Royal Quartermaster.sql
Adds all the NPCs and Items for the Writ of Apology.
https://asheron.fandom.com/wiki/Writ_of_Apology
Admin would need to manually bestow the quest "WritOfApology_0508" on any player(s) who deserve an apology, at which point it gets removed from their quest log when complete, allowing it to be re-added if needed.
Note: This does not add a login message as the tech for that does not currently exist.
=> Writ of Apology

Database/Patches/6 LandBlockExtendedData/3150.sql, Database/Patches/9 WeenieDefaults/Generic/None/88221 Vine Hotspot Generator.sql, Database/Patches/9 WeenieDefaults/HotSpot/Misc/88220 Vine.sql, Database/Patches/9 WeenieDefaults/Portal/Portal/88218 Temple Exit.sql
Updated the Harvesting the Bulb of Harvests quest based on retail video:
https://www.youtube.com/watch?v=SUSow5MBOjg
- Added missing Adolescent Ash Gromnie spawns in the cave. 
- Improved vine hotspots to cover the entire area using a single large hotspot instead of multiple small hotspots spawned at random. 
- Moved Sanctum Guardian Spirit on the platform at the bottom of the case as seen in the retail video. 
- Corrected Temple Exit portal drop to match the retail video.
=> Update Bulb of Harvests

Database/Patches/9 WeenieDefaults/Clothing/Armor/00296 Crown.sql
Despite 16PY having 0.0 modifiers for protection against 3 of the 4 elements, magloot corpse logs from retail showed these values never dropping below 0.4 for this item.
Some possibilities:
- They changed the base data on this item some point after 16PY, possibly during UCoN when diadems/circlets/coronets/etc. were added?
- There was special logic in the loot mutation system for jewelry w/ armor specifically, with the minimum ArmorModVsTypes there. Jewelry w/ armor already seemed to be sort of a weird outlier there.
If unmutated crowns were sold at vendors, and if there is a pcap of someone appraising one in retail from a vendor store, then it could possibly be differentiated there if the base weenie was modified, or if something was going on in the loot mutation system for jewelry w/ …
=> updating crown to magloot corpse log mins

Database/Patches/9 WeenieDefaults/Creature/Drudge/27893 Drudge Prowler.sql, Database/Patches/9 WeenieDefaults/Creature/PhyntosWasp/19435 Red Phyntos Wasp.sql, Database/Patches/9 WeenieDefaults/Creature/Shreth/04109 Carrion Shreth.sql
4109 Carrion Shreth, 19435 Red Phyntos Wasp, and 27893 Drudge Prowler were dropping red and/or gold letters. They should not be doing so, as they are not level 80 creatures.
=> Fixing 3 low level creatures that were dropping red/gold letters

Database/Patches/6 LandBlockExtendedData/01CF.sql, Database/Patches/8 QuestDefDB/EasthamSewerSwordPickup1110.sql, Database/Patches/9 WeenieDefaults/Chest/Container/01315 Chest.sql, Database/Patches/9 WeenieDefaults/Chest/Container/01316 Chest.sql, Database/Patches/9 WeenieDefaults/Creature/Human/25896 Samuel, Former Guardian.es, Database/Patches/9 WeenieDefaults/Creature/Human/25896 Samuel, Former Guardian.sql, Database/Patches/9 WeenieDefaults/Door/Misc/01318 Door.sql, Database/Patches/9 WeenieDefaults/Generic/Armor/01313 Metal Round Shield.sql, Database/Patches/9 WeenieDefaults/Generic/Misc/43417 Slimy Broad Sword.sql
Updates Eastham Sewer to end of retail.
- Upgraded Spawns in dungeon
- mostly Drudge Raveners and Maulus Shreth, with a couple of random lesser drudges and key-droppers. Compared with PCAPs + PcapPlayer
- Updated lockpick difficulty on some doors and chests
- Added Slimy Broad Sword reward to final chest on a 20 hour pickup timer
- Updated Shield found in same chest.
- Updated Samuel, Former Guardian to reward for returning the sword.
=> Eastham Sewer

Database/Patches/9 WeenieDefaults/Ammunition/MissileWeapon/46629 Greater Deadly Lightning Arrow.sql, Database/Patches/9 WeenieDefaults/MissileLauncher/MissileWeapon/46633 Lightning Longbow.sql
Most of the changes are completely useless for monster-only items, just made to be consistent with the others. The main changes are: 
1. Removal of the melee defense mod that only shows up on the lightning bow. Guessing they took it from the wiki page for the Master Archer version of the weapon?
2. Changing weapon mod and arrow damage to match other versions, making them equally as dangerous as other spectral archers.
=> Fix lightning spectral archer gear to match other spectral archer gear

Database/Patches/9 WeenieDefaults/Creature/Golem/37455 Forge Golem.sql, Database/Patches/9 WeenieDefaults/Creature/Golem/37455.es, Database/Patches/9 WeenieDefaults/Creature/Moarsman/40306 Verdant Moarsman.sql, Database/Patches/9 WeenieDefaults/Creature/Moarsman/41181 Verdant Moarsman.sql, Database/Patches/9 WeenieDefaults/Creature/Penguin/45853 Mouf.sql, Database/Patches/9 WeenieDefaults/Door/Misc/44061 Door.sql, Database/Patches/9 WeenieDefaults/Generic/None/88125 Rynthid Test 4 Portal Generator.sql, Database/Patches/9 WeenieDefaults/Portal/Portal/37513 Armory.sql, Database/Patches/9 WeenieDefaults/Portal/Portal/37514 Forges.sql
Adds on death local broadcast to Forge Golem seen in retail video by Xeo, and updates the golem's skills and casting probability. Some of its base skills were set to what should be its effective skills. 
Adds flavor text to Forges portal seen in the retail video. 
Adds a regular door reset interval of 300 seconds to regular (not lever activated) Neftet-style door. This was not set, and doors closed too quickly  (in under a min). In retail video, these doors stay open for much longer. 
Updated one of the Rynthid Testing portal generators to match the other portal generators. The others are set to 5 sec regen interval, this one was left at 600 seconds, forcing players to wait around for 10 min for a new color portal to spawn. 
Added missing T7 loot profile to Verdant Moarsman.
Corrects art …
=> Flavor Text and Other Updates

Database/Patches/9 WeenieDefaults/Caster/Caster/46941 Modified Taulandoi.sql, Database/Patches/9 WeenieDefaults/Caster/Caster/46942 Modified Taulandoi.sql, Database/Patches/9 WeenieDefaults/Caster/Caster/46943 Modified Taulandoi.sql, Database/Patches/9 WeenieDefaults/Caster/Caster/46944 Modified Taulandoi.sql
Sets the critical frequency of the 4 Modified Taulandoi to 0.25. Previously, was set to 1 by mistake.
=> Fix Modified Taulandoi Crit Freq

Database/Patches/6 LandBlockExtendedData/584D.sql, Database/Patches/8 QuestDefDB/chestchorizite73155.sql, Database/Patches/9 WeenieDefaults/Chest/Container/73155 Chorizite Chest.sql, Database/Patches/9 WeenieDefaults/Creature/Elemental/42338 Hoarfrost.sql, Database/Patches/9 WeenieDefaults/Creature/Elemental/73154 Algid Warrior.sql, Database/Patches/9 WeenieDefaults/Creature/Penguin/46143 Baby Penguin.sql, Database/Patches/9 WeenieDefaults/Creature/Penguin/46143.es, Database/Patches/9 WeenieDefaults/Creature/Penguin/46299 Tiny.sql, Database/Patches/9 WeenieDefaults/Creature/Penguin/46307 Penguin Guard.sql, Database/Patches/9 WeenieDefaults/Creature/Penguin/46307.es, Database/Patches/9 WeenieDefaults/Creature/Snowman/46278 Cowardly Snowman.sql, Database/Patches/9 WeenieDefaults/Creature/Snowman/46278.es, Database/Patches/9 WeenieDefaults/Creature/Unsorted/46303 Wall of Ice.sql, Database/Patches/9 WeenieDefaults/Creature/Unsorted/46320 Security Station.sql, Database/Patches/9 WeenieDefaults/Creature/Unsorted/46320.es, Database/Patches/9 WeenieDefaults/Missile/MissileWeapon/46282 Iceball.sql, Database/Patches/9 WeenieDefaults/PressurePlate/Misc/73153 Penguin's Friend.sql
Revisions based on Loud Lou and Berek retail videos:
Populates a previously empty section of the dungeon with Algid Warrior guarding a Chorizite Chest (seen on Lou video). Also cleans up positions of some other spawns.
Adds roaming emote to Baby Penguins.
Corrects Wall of Ice scale and transparency (it should have none) based on pcap and video.
Cowardly Snowmen are now armed with their pcapped iceballs, and set to persistent missile, as seen in the Lou video. Also added flavor text emote.
Corrected Tiny's spellbook (he casts level 8s) as seen on the Berek video.
Added Penguin's Friend floor traps (seen in both videos), which cast level 8 cold vul.
Revised the guard station penguin scene to match timing from the video (meaning, players can now see the guard penguin before he disappears). …
=> Rescue Mouf Updates

Database/Patches/6 LandBlockExtendedData/587A.sql, Database/Patches/9 WeenieDefaults/Creature/Drudge/88154 Drudge Wilter.sql, Database/Patches/9 WeenieDefaults/Creature/Gurog/88145 Gurog Bruiser.sql, Database/Patches/9 WeenieDefaults/Creature/Human/88109 Rynthid Assessment Door Controller.sql, Database/Patches/9 WeenieDefaults/Creature/Human/88109.es, Database/Patches/9 WeenieDefaults/Generic/None/88106 Moars Test Master Generator.sql, Database/Patches/9 WeenieDefaults/Generic/None/88123 Wasp Test Master Generator.sql, Database/Patches/9 WeenieDefaults/Generic/None/88140 Margul Test Master Generator.sql, Database/Patches/9 WeenieDefaults/Generic/None/88150 Grievver Test Master Generator.sql, Database/Patches/9 WeenieDefaults/Generic/None/88155 Drudge Test Master Generator.sql, Database/Patches/9 WeenieDefaults/Generic/None/88162 Remoran Test Master Generator.sql, Database/Patches/9 WeenieDefaults/Generic/None/88168 Mukkir Test Master Generator.sql
Currently, the door tests in this quest only reset when the landblock resets, meaning players are stuck waiting for a respawn that will never come. This corrects this issue by having the door controller stopgap delete itself after it closes its door, allowing the generator it is on to start its cycle from the beginning.
Drudge Wilter scale is adjusted to match retail video.
Gurog Bruiser stats and art are adjusted to match retail video. These Gurog do not appear to ever cast and only melee with their fists. They do not wield an axe. Also, their HP was lower than it should be based on how much damage it takes to kill them on the video.
More Gurog Bruisers added to locations that were missing them. 
No corpse is set on both of these mobs, and loot profile removed, as seen on the video.
A …
=> Rynthid Testing Fix Broken Reset

Database/Patches/6 LandBlockExtendedData/584E.sql, Database/Patches/9 WeenieDefaults/Creature/Human/46338 Kraytuss Nallah.sql, Database/Patches/9 WeenieDefaults/Creature/Human/46338.es
Adds missing spawns near the entrance of the dungeon, as seen on Loud Lou retail video.
Adds delays and turn to target in emote for the NPC.
=> Serpent Burial Ground Updates

Database/Patches/9 WeenieDefaults/Creature/Shadow/27426 Shadow Nightmare.sql, Database/Patches/9 WeenieDefaults/Creature/Shadow/33163 Captain Faalx.sql, Database/Patches/9 WeenieDefaults/Creature/Shadow/33165 Shadow Cyst.sql, Database/Patches/9 WeenieDefaults/Creature/Shadow/33165.es, Database/Patches/9 WeenieDefaults/Creature/Shadow/33166 Isin Dule's Lieutenant.sql, Database/Patches/9 WeenieDefaults/Creature/Shadow/33167 Umbral Soldier.sql, Database/Patches/9 WeenieDefaults/Creature/Shadow/33168 Panumbral Soldier.sql, Database/Patches/9 WeenieDefaults/Creature/Shadow/33170 Lieutenant Beraxis.sql, Database/Patches/9 WeenieDefaults/Creature/Shadow/33171 Lieutenant Shenza.sql, Database/Patches/9 WeenieDefaults/Creature/Shadow/33172 Lieutenant Yezusthule.sql, Database/Patches/9 WeenieDefaults/Creature/Shadow/33174 Panumbral Soldier.sql, Database/Patches/9 WeenieDefaults/Creature/Shadow/33175 Umbral Soldier.sql, Database/Patches/9 WeenieDefaults/Creature/Shadow/73156 Isin Dule's Captain.sql, Database/Patches/9 WeenieDefaults/Generic/None/87017 Isin Dule Generator.sql
Revisions to the Shield of Isin Dule quest based on pcap and ImmortalBob retail video:
Corrects Shadow Cyst spell book based on what it casts in the video. The spells are just level 7 versions of the same spells the low level Shadow Cyst (from world db) casts, with a few replacements.
Adds missing mobs the Shadow Cyst can generate. In the pcap, there is Isin Dule's Lieutenant, and in a retail screenshot, there is Isin Dule's Captain.  Neither appear in the video. This could be because dealing enough damage can skip over the health ranges to generate them (if this was based on wounded taunt).
Adjusts Shadow Cyst resistances (using those for the world Shadow Cyst, with higher armor level). ImmortalBob deals very high damage (over 6k on criticals) prior to the Shadow Cyst casting fire …
=> Climbing the Spire Updates

Database/Patches/9 WeenieDefaults/Book/Writable/47190 Orders for Zrikux.sql, Database/Patches/9 WeenieDefaults/Creature/Human/52084 Training Dummy.sql, Database/Patches/9 WeenieDefaults/Creature/Human/52085 Training Dummy.sql, Database/Patches/9 WeenieDefaults/Creature/Human/52086 Training Dummy.sql, Database/Patches/9 WeenieDefaults/Creature/Shadow/45705 Formless Shadow.sql, Database/Patches/9 WeenieDefaults/Door/Misc/44062 Door.sql, Database/Patches/9 WeenieDefaults/Missile/MissileWeapon/51436 Frozen Coconut.sql, Database/Patches/9 WeenieDefaults/Stackable/Misc/46347 Partially Restored Page.sql, Database/Patches/9 WeenieDefaults/Stackable/Misc/46349 Torn Strip of Parchment.sql
Lowers war magic on Training Dummies to give a chance to resist. The one casting Heavy Lightning Ring now casts the alternative, less damaging version of the spell, since damage seemed excessive (could easily 1-hit player). This ring spell's visual effect also does not match its hit box, making it particularly difficult to avoid.
Formless Shadows in Shadow Geraine's Host now die on their own as they should, and cast Dark Vortex on death, like the Aerbax Formless Shadows.
Adds missing palette and clothing base to Frozen Coconut.
Adds ItemUseable - No to two Lost Lore pages. These are either the result or target of a crafting interaction, and should not be useable.
Adds missing "You cannot translate this text" to Orders for Zrukux.
=> Misc Updates

Database/Patches/6 LandBlockExtendedData/5860.sql, Database/Patches/9 WeenieDefaults/Creature/Mosswart/72970 Mosswart Messenger.sql, Database/Patches/9 WeenieDefaults/Creature/Mosswart/72970.es, Database/Patches/9 WeenieDefaults/Creature/Mosswart/72972 Mosswart Worker.sql, Database/Patches/9 WeenieDefaults/Creature/Mosswart/72973 Mosswart Grunt.sql, Database/Patches/9 WeenieDefaults/Creature/Mosswart/72982 Mosswart Tribesman.sql, Database/Patches/9 WeenieDefaults/Creature/Rat/72983 Scavenging Rat.sql, Database/Patches/9 WeenieDefaults/Door/Misc/72990 Door.sql, Database/Patches/9 WeenieDefaults/Door/Misc/73162 Door.sql, Database/Patches/9 WeenieDefaults/HotSpot/Misc/73161 Fire.sql
Revisions to the quest based on Loud Lou retail video:
Rebalanced mobs, and corrected their spell books.
Entrance door now stays open for 3 min.
Respawn set to 5 min (up from 3 min).
Updated emote of Mosswart Messenger to spawn 2 adds. 
Added missing fire hotspots.
Corrected appearance of a door.
=> On Strike Updates

Database/Patches/9 WeenieDefaults/Creature/Unsorted/33239 Tunnels to the Harbinger.sql
Current spell ID is sending players to the Essenceless Harbinger room when they attempt to return after dying to Prodigal Harbinger. Issk portal appears to be working correctly.
=> Fix spell ID for Prodigal Harbinger teleport on Vincadi Harbinger Tunnels portal

Database/Patches/9 WeenieDefaults/Creature/GearKnight/42112 Atamarr.sql, Database/Patches/9 WeenieDefaults/Creature/GearKnight/42112.es
Emotescript did not agree with how Atamarr's emotes were written, so when they were run through ES it broke his behavior. Namely it was using the same Success/Fail emotes for multiple invocations of an InqQuest (e.g. two calls of InqQuest: AtamarrIron, but only one Success and one Fail total associated with them). This works normally, but ES adds the @# to the end, causing one to no longer reach its Success and Fail branches. Removing the @# allows it to work, but it would break again next time it gets run through ES, so I used some ugly Gotos to reconfigure the emotes to make them ES-safe.
=> Fix Atamarr emotes

Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/53314 Stormwood Staff.sql, Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/72005 Stormwood Staff.sql
Changes stormwood staves to cast LW Mastery 8 instead of HW Mastery 8 (as PCAPed for 53314)
=> Stormwood Staff Spell Fix

Database/Patches/9 WeenieDefaults/Caster/Caster/45956 Seasoned Explorer Nether Staff.sql
Changes Storm's Boon to Aura of Spirit Drinker Self VI on Seasoned Explorer Nether Staff to match PCAP.
=> Fix spells on Seasoned Explorer Nether Staff

Database/Patches/9 WeenieDefaults/Gem/Gem/46749 Contract for Kill_ Spectral Blades and Claws.sql
Fixes the Kill: Spectral Blade and Claws contract to point to the right contract (242) instead of the Archers one (236).
=> Fix Spectral Blade and Claws Contract

Database/Patches/9 WeenieDefaults/Creature/Human/32992 Eddred the Wolf.sql, Database/Patches/9 WeenieDefaults/Creature/Human/32992.es, Database/Patches/9 WeenieDefaults/Creature/Human/33015 Meerana du Renari.sql, Database/Patches/9 WeenieDefaults/Creature/Human/33015.es
Fixes the red rune silveran weapon turn-in to accept the mace instead of the Binding Realm portal.
=> Fix Red Rune Silveran Mace TurnIn

Database/Patches/9 WeenieDefaults/Generic/Misc/87823 Royal Olthoi Jelly.sql
The royal olthoi jelly in Guardians of the Deru Tree was using the stats of the royal olthoi jelly from the Renegade Mace quest. The main differences are the attuned, bonded, and lifespan properties. This wasn't PCAPed, so relying on wiki pictures here.
=> Fix deru tree royal olthoi jelly

Database/Patches/9 WeenieDefaults/Portal/Portal/70346 Scintillating Apostate Nexus.sql, Database/Patches/9 WeenieDefaults/Portal/Portal/70347 Shimmering Apostate Nexus.sql, Database/Patches/9 WeenieDefaults/Portal/Portal/70380 Heart of the Apostate Nexi.sql
Correction for the summoned portals on the Apostate Finale quest taken from PCAP 
PCAP Part 1\AC1Live-The-Ripley-Collection-part01\AC1Live-The-Ripley-Collection\aclog pcaps\pkt_2017-1-28_1485659343_log.pcap 
Namely changes PORTAL_BITMASK_INT to 49 (no summon/recall) and MIN_LEVEL_INT to 120. I don't know why the min level is 120 since the first portal in the chain is 150+, but that's what the PCAP says so that's what it is I guess.
=> Fix Apostate Finale portal restrictions

Database/Patches/9 WeenieDefaults/MissileLauncher/MissileWeapon/34995 Channeling Bone Bow.sql
Adds the missing proc rate to the channeling bone bow (set to match the crossbow).
=> Add proc rate to channeling bone bow

Database/Patches/9 WeenieDefaults/Creature/Olthoi/35151 Swarm Demon.sql
Removes the NonProjectileMagicImmune property from Swarm Demons based off retail video https://youtu.be/6aSxe8gFhAM?t=2113
=> Remove Swarm Demon Life Immunity

Database/Patches/9 WeenieDefaults/Creature/Human/47799 Colton Reeyan.sql, Database/Patches/9 WeenieDefaults/Creature/Human/47799.es
Emote changes to fix two bugs:
1. If you left the dungeon after convincing the workers but before saving the pets, you were "permanently" locked out of the quest (unless someone else let you back in) since you couldn't get another letter. 
2. It effectively wasn't checking the "convince workers" kill task condition for rewards, only the pets saved.
=> Fix Protecting Picketed Pets Bugs

Database/Patches/9 WeenieDefaults/Creature/Human/43526 Fayza.sql, Database/Patches/9 WeenieDefaults/Creature/Human/43526.es, Database/Patches/9 WeenieDefaults/Door/Misc/43760 Door.sql, Database/Patches/9 WeenieDefaults/Door/Misc/43780 Door.sql
Started from bug report: https://discord.com/channels/261242462972936192/729525560421646469/1169189606969835571
Claim 1: Defender doors (maze jump room) close too soon. (Currently 60 seconds)
People didn't stay around this room very long once the Fiery Defender was dead. The longest I could find was 2 minutes, 19 seconds on "PCAP Part 1\jojii2\pkt_2017-1-22_1485133915_log.pcap". I found no instances of the defenders respawning or the doors closing in either PCAP or video. The report indicated the door reset interval matched the respawn time, which seemed reasonable enough without conflicting evidence. 
Claim 2: Reward room doors close too soon. (Currently 60 seconds)
People stayed around this room a lot longer after killing ~~Deewain~~ Iron Golem. The longest was in Lou's retail video …
=> Fix Deewain timers and turn-in emote

Database/Patches/8 QuestDefDB/GYColoRewardGiverInProgress.sql, Database/Patches/8 QuestDefDB/GYColoWinRewardReceived.sql
Lowers the timer of the reward NPC (wcid 35401) on GY colo from 5 to 3 minutes based off PCAPs: 
PCAP Part 1\Callaway-1-25-2017-RadiantManaInfusion-GraveyardCol\pkt_2017-1-25_1485399800_log.pcap 
PCAP Part 1\Callaway-01-10-2017-MountLetheGraveyard\pkt_2017-1-9_1484006624_log.pcap 
PCAP Part 1\CatDevnull-01-30-2017-GY-Colo\pkt_2017-1-30_1485831256_log.pcap 
Offsets the NPC duration by 5 seconds to (mostly) account for the heartbeat interval used to despawn it. Also offsets the quest timer to fix an exploit where a player could get rewarded at the beginning of the NPC's duration and again at the end due to delay-induced overlap in the timers (which was the reason I looked into this in the first place).
=> Fix GY colo timers

Database/Patches/9 WeenieDefaults/Portal/Portal/46590 Great Hall.sql
currently when you go thru the great hall portal you are able to recall. which allows you skip half the quest.
=> hosh infiltration portal fix

Database/Patches/9 WeenieDefaults/Generic/None/87810 Stephanie Event Gen.sql
Stephanie is part of the GiftGopherEvent for the quest Package Delivery.
=> 87810 should be tied to the GiftGopherEvent

Database/Patches/4 CraftTable/07645 Adept's Gem of Blade Protection.sql
Quantity fixed to match other adept gem recipes
=> Fix adept gem of blade prot recipe to create 2 gems

Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/29912 Littoral Siraluun Hoeroa.sql
Update spell from staff mastery (LW) to HW to match weapon type
=> Fix Littoral Siraluun Hoeroa for MOA

Database/Patches/9 WeenieDefaults/Creature/Human/28700 Grand Knight.sql, Database/Patches/9 WeenieDefaults/Creature/Human/28700.es
The Ancient Discoveries turn-in was going to the Dericost Tome reward logic instead of its own, making the Kam'shir shield reward unobtainable.
=> Fix Grand Knight emote logic for Dericost Ruin rewards

Database/Patches/6 LandBlockExtendedData/7E04.sql, Database/Patches/9 WeenieDefaults/Creature/Human/40897 Ries Woron.sql, Database/Patches/9 WeenieDefaults/Creature/Human/40897.es, Database/Patches/9 WeenieDefaults/PressurePlate/Misc/72950 Pressure Plate.sql
Adds reset interval to pressure plates controlling bridges to resolve issue of the bridge constantly going up and down as multiple players step on the plate. 
Ries Woron will now take a piece of armor and hand back the same piece as per retail. This can be used to reset any dyed piece back to its original color.
=> Armor of Darkness Quest Fixes

Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/37402 Club of Surprising Cunning.sql, Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/87477 Club of Remarkable Cunning.sql
Adds missing ProcSpellRate to clubs of cunning. Rates themselves are admittedly asspulls, just based them off the ones for Princely/Royal Runed weapons.
=> Add ProcSpellRate to Clubs of Cunning

Database/Patches/9 WeenieDefaults/Creature/Unknown/32734 Essence of Enchantment.sql, Database/Patches/9 WeenieDefaults/Creature/Unknown/32735 Essence of Artifice.sql, Database/Patches/9 WeenieDefaults/Creature/Unknown/32737 Essence of Strife.sql, Database/Patches/9 WeenieDefaults/Creature/Unsorted/33239 Tunnels to the Harbinger.sql, Database/Patches/9 WeenieDefaults/Creature/Unsorted/33239.es
Updates the Vincadi portal to the Weakened Harbinger to send the player to the correct dungeon (6446).
=> Update 33239 Tunnels to the Harbinger

Database/Patches/8 QuestDefDB/inscribedpurplegem.sql, Database/Patches/8 QuestDefDB/pyrealmoteayan.sql, Database/Patches/8 QuestDefDB/pyrealmotewai.sql
Sets the quest pickup timers to 20 hours for the level 15-79 version of Bur flagging. This quest is not on the exception list from the Quest for Freedom, and should have a 20 hour timer like most others.
=> Update Asheron's Departure Lower

Database/Patches/9 WeenieDefaults/Food/Misc/37517 Enhanced Health Elixir.sql
when potions stacked they would become 775 bu each, should be 75 each
=> Update 37517 Enhanced Health Elixir.sql

Database/Patches/6 LandBlockExtendedData/00EC.sql, Database/Patches/9 WeenieDefaults/Book/Writable/37102 Ley-Leech's Orders.sql, Database/Patches/9 WeenieDefaults/Book/Writable/37103 Node-Leech's Orders.sql, Database/Patches/9 WeenieDefaults/Creature/Human/37089 Nomendar al-Rakh.sql, Database/Patches/9 WeenieDefaults/Creature/Human/37089.es, Database/Patches/9 WeenieDefaults/Generic/Gem/24872 Golden Gromnie.sql, Database/Patches/9 WeenieDefaults/Generic/Misc/32967 Reflective Shard.sql, Database/Patches/9 WeenieDefaults/Generic/Misc/37092 Node Leech's Medallion.sql, Database/Patches/9 WeenieDefaults/Generic/Misc/37093 Ley Leech's Medallion.sql
Adds missing properties to Shroud Cabal quest items (value, description), and MMD reward to this quest.
Adds missing clothing base to Reflective Shard (from low Harbinger quest) to match retail screenshot.
https://asheron.fandom.com/wiki/Reflective_Shard
Corrects clothing base on Golden Gromnie (item in Ulgrim's basement) to match retail screenshot (i.e., so gromnie is actually gold, not blue). The wrong clothing base appears in World DB, and this appears to have been corrected at some point in retail.
https://asheron.fandom.com/wiki/Golden_Gromnie_(Object)
=> Update Shroud Cabal and Others

Database/Patches/9 WeenieDefaults/Caster/Caster/43813 Sturdy Bloodstone Wand.sql, Database/Patches/9 WeenieDefaults/Caster/Caster/43814 Delicate Bloodstone Wand.sql
Increased critical frequency to 0.25 from 0.06. This is a wand from a level 200 quest, and should be on the upper end for quest critical frequencies (for example, in the world db, the singularity scepte has a critical frequency of 0.25).
=> Update Bloodstone Wand

Database/Patches/9 WeenieDefaults/Creature/Golem/44031 Dust Golem.sql, Database/Patches/9 WeenieDefaults/Creature/Golem/44032 Dust Golem.sql, Database/Patches/9 WeenieDefaults/Creature/Golem/44033 Burning Sands Golem.sql, Database/Patches/9 WeenieDefaults/Creature/Golem/44034 Burning Sands Golem.sql, Database/Patches/9 WeenieDefaults/Creature/Undead/44039 Mu-miyah Lord.sql, Database/Patches/9 WeenieDefaults/Creature/Undead/44040 Mu-miyah Lord.sql, Database/Patches/9 WeenieDefaults/Creature/Undead/44045 Mu-miyah Vizier.sql, Database/Patches/9 WeenieDefaults/Creature/Undead/44046 Mu-miyah Vizier.sql, Database/Patches/9 WeenieDefaults/Creature/Undead/44093 Mu-miyah Vizier.sql, Database/Patches/9 WeenieDefaults/Creature/Undead/44096 Mu-miyah Lord.sql, Database/Patches/9 WeenieDefaults/Creature/Undead/71388 Mu-miyah Vizier.sql, Database/Patches/9 WeenieDefaults/Creature/Undead/87589 Mu-miyah Vizier.sql, Database/Patches/9 WeenieDefaults/Creature/Undead/87848 Mu-miyah Lord.sql
Updated skill levels for Neftet golems and mummies based on pcaps. Also corrected some spellbooks. In general, magic skills were too high, while some melee skills were too low.
=> Neftet Skill Rebalance

Database/Patches/9 WeenieDefaults/Caster/Caster/37585 Soul Bound Staff.sql
Adjusts critical multiplier and critical frequency on the SB staff for a closer match to retail.
Based on a retail video of Berek fighting Aerbax, with pierce vul 8, the average on normal hits was 1317 (based on 66 shots). The critical average was 4432 (based on 11 shots).
Without pierce vul (only on the staff's pierce rend), the normal hit average is 1031 (total 40 shots) and 3506 on criticals (total 10 shots).
Either way, criticals are about 3.5 more damage than normal hits. Also, out of the 149 shots in the video, 25 were criticals, which is a .1677 rate. Subtracting 1% for eye of remorseless aug, and rounding down to be more conservative, gives 15% chance to critical.
=> Update 37585 Soul Bound Staff.sql

Database/Patches/6 LandBlockExtendedData/0117.sql, Database/Patches/6 LandBlockExtendedData/0119.sql, Database/Patches/6 LandBlockExtendedData/011A.sql, Database/Patches/6 LandBlockExtendedData/011B.sql, Database/Patches/9 WeenieDefaults/Creature/Olthoi/46279 Olthoi Swarm Soldier.sql, Database/Patches/9 WeenieDefaults/Creature/Undead/46281 Dark Master.sql
Updates the dungeons (jahannan, serac, amprehelion, and incunabula vault) to end of retail spawns based on the pcaps.
Adds two missing creatures (Dark Master and Olthoi Swarm Soldier, edge slide versions) found in the dungeons.
=> Update Major Atlan Stone Quests

Database/Patches/6 LandBlockExtendedData/0089.sql, Database/Patches/9 WeenieDefaults/Portal/Portal/32674 Cells of the Black Book.sql, Database/Patches/9 WeenieDefaults/Portal/Portal/32675 Cells of the Black Book.sql, Database/Patches/9 WeenieDefaults/Portal/Portal/32676 Cells of the Black Book.sql, Database/Patches/9 WeenieDefaults/Portal/Portal/32677 Cells of the Black Book.sql, Database/Patches/9 WeenieDefaults/Portal/Portal/32678 Surface.sql
Database/Patches/6 LandBlockExtendedData/0089.sql (Cells of the Black Book Surface Portal) 
Database/Patches/9 WeenieDefaults/Portal/Portal/32674 Cells of the Black Book.sql 
Database/Patches/9 WeenieDefaults/Portal/Portal/32675 Cells of the Black Book.sql 
Database/Patches/9 WeenieDefaults/Portal/Portal/32676 Cells of the Black Book.sql 
Database/Patches/9 WeenieDefaults/Portal/Portal/32677 Cells of the Black Book.sql 
Database/Patches/9 WeenieDefaults/Portal/Portal/32678 Surface.sql (Cells of the Black Book Surface Portal)
32674, 32675, 32676, 32677 Cells of the Black Book Portal drops Updated portal destinations for Cells of the Black Book portals to match Landblocks Google Sheets PCAPS.
PCAP Data (from Landblocks Google Sheet) shows four entrances Cells of the Black Book (Entrance 1) …
=> Updated Cells of the Black Book Portals 32674, 32675, 32676, 32677, 32678, 0089

Database/Patches/9 WeenieDefaults/Portal/Portal/43118 Forgotten Tunnels.sql, Database/Patches/9 WeenieDefaults/Portal/Portal/43119 Forgotten Tunnels.sql, Database/Patches/9 WeenieDefaults/Portal/Portal/43120 Forgotten Tunnels.sql
Database/Patches/9 WeenieDefaults/Portal/Portal/43118 Forgotten Tunnels.sql 
Database/Patches/9 WeenieDefaults/Portal/Portal/43119 Forgotten Tunnels.sql 
Database/Patches/9 WeenieDefaults/Portal/Portal/43120 Forgotten Tunnels.sql
-- Set Destinations according to Landblock Google Sheet PCAP data
43118 Source: 93.1S, 56.9W
@teleloc 0x380B0102 [60.0445 20.7545 -5.663] -0.999965 0 0 0.008334 -- Set Destination:
@teleloc 0x8B02026b [0 -20 18.004999160767] 0.70710700750351 0 0 -0.70710700750351 -- W side of dungeon
43119 Source 92.9S, 56.4W
@teleloc 0x380B0106 [179.998 69.0345 -5.663] -0.999579 0 0 -0.028995 -- Set Destination:
@teleloc 0x8B020282 [130 -200 18.004999160767] 1 0 0 0 -- S side of dungeon
43120 Source 93.6S, 56.6W
@teleloc 0x380A0102 [132.106 92.8269 -5.663] 0.999826 0 0 0.018646 …
=> Update Forgotten Tunnnels 43118, 43119, 43120 portals 'not yet implemented'

Database/Patches/9 WeenieDefaults/Portal/Portal/43536 Passage to Olthoi Island.sql, Database/Patches/9 WeenieDefaults/Portal/Portal/43580 Passage to Olthoi Island.sql
Database/Patches/9 WeenieDefaults/Portal/Portal/43536 Passage to Olthoi Island.sql Database/Patches/9 WeenieDefaults/Portal/Portal/43580 Passage to Olthoi Island.sql
43536-43580 Passage to Olthoi Island - portal ID 43536 & 43580 not yet implemented! -- https://asheron.fandom.com/wiki/Passage_to_Olthoi_Island?so=search
43580
-- Portal 1 source 63.1N, 76.4E
-- Portal 1 drops at 66.3N, 84.2E
world_objects db confirms destination as
34257	14	DECE003B	76.37	63.12	0.01	Passage to Olthoi Island	Passage to Olthoi Island (66.3N, 84.2E). 
-- @teleloc 0xE8D2002B [132 60 42.006001] 1 0 0 0
43536
-- Portal 2 source 63.7N, 75.6E
-- Portal 2 drops at 69.6N, 80.7E
world_objects db shows this
34256	14	DDCF0039	75.58	63.7	0.01	Passage to Olthoi Island	Passage to Olthoi Island (69.6N, 80.7E). 
-- @teleloc …
=> Update Passage to Olthoi Island 43536 43580 are not yet implemented

Database/Patches/6 LandBlockExtendedData/F65D.sql, Database/Patches/9 WeenieDefaults/Portal/Portal/43559 Olthoi Tunnel.sql, Database/Patches/9 WeenieDefaults/Portal/Portal/43705 Olthoi Tunnel.sql
Database/Patches/9 WeenieDefaults/Portal/Portal/43559 Olthoi Tunnel.sql 
Database/Patches/9 WeenieDefaults/Portal/Portal/43705 Olthoi Tunnel.sql 
Database/Patches/6 LandBlockExtendedData/F65D.sql (43561 Olthoi Tunnel)
43559 43705 Olthoi Tunnel not yet implemented
43561 Olthoi Tunnel is missing (from F65D)
https://asheron.fandom.com/wiki/Olthoi_Island
(See portals section)
Candeth Keep	87.8S, 65.1W	Olthoi Island	68.5N 79.7E
43559 Olthoi Tunnel (Candeth Keep)
Source: @teleloc 0x2E110107 [11.9795 164.794 50.337] 1 0 0 0 -- Destination is not yet implemented
vloc2loc E3D5 shows this
Olthoi Tunnel - @teleloc 0xE3D50001 [8.941406 11.824219 0] 1 0 0 0
Dark Isle	85.4N, 57.3E	Olthoi Island	69.4N 80.3E
43705 Olthoi Tunnel (Dark Isle)
Source: @teleloc 0xC7EA0102 [11.9171 45.1593 -5.663] 1 0 0 0 -- …
=> Update Olthoi Tunnel Portals not yet implemented 43559 43705 F65D (43561)

Database/Patches/9 WeenieDefaults/Creature/Shadow/30834 Shadow Lugian Portal.sql
Database/Patches/9 WeenieDefaults/Creature/Shadow/30834 Shadow Lugian Portal.sql
Updated 30834 Shadow Lugian Portal (Balor's Rescue Quest)
The "Shadow Lugian Portal" creature was missing the portal spell to cast upon death. Add back in the portal spell on death (from core py16 version) 
30844	portalshadowlugianstrongholdendroom (aka Purple Portal Template)
Aligns with wiki information about Shadow Lugian behavior upon death https://asheron.fandom.com/wiki/Shadow_Lugian_Portal?so=search "Casts portal upon death"
https://asheron.fandom.com/wiki/Balor%27s_Rescue
"Kill the Shadow Lugian Portal, and a portal will spawn Enter, and you will see a NPC Shadow Lugian, called Shadow."
https://asheron.fandom.com/wiki/Inner_Stronghold
see the Inner Stronghold map, bottom left
Portal goes to small room …
=> Updated 30834 Shadow Lugian Portal (Balor's Rescue Quest)

Database/Patches/6 LandBlockExtendedData/0030.sql, Database/Patches/6 LandBlockExtendedData/0043.sql, Database/Patches/6 LandBlockExtendedData/0049.sql, Database/Patches/6 LandBlockExtendedData/004D.sql, Database/Patches/6 LandBlockExtendedData/009D.sql, Database/Patches/9 WeenieDefaults/Portal/Portal/33035 Surface.sql, Database/Patches/9 WeenieDefaults/Portal/Portal/35038 Bur Catacombs.sql, Database/Patches/9 WeenieDefaults/Portal/Portal/87641 Surface.sql
Contributing Portal Updates 
per PCAPS google sheet, vloc2loc dungeon data.
and (virindi) world objects database sources
Database/Patches/9 WeenieDefaults/Portal/Portal/35038 Bur Catacombs.sql
Database/Patches/9 WeenieDefaults/Portal/Portal/33035 Surface.sql (Ancient Masonry)
Database/Patches/9 WeenieDefaults/Portal/Portal/87641 Surface.sql (Tanada House of Storms Exit Portal)
Database/Patches/6 LandBlockExtendedData/009D.sql (Swamp Temple Cavern Exit)
Database/Patches/6 LandBlockExtendedData/0030.sql (Renegade Incursion Change Exit Portal to Fort Tethana)
Database/Patches/6 LandBlockExtendedData/0043.sql (Master_Vaserio's_Dig Surface Portal)
Database/Patches/6 LandBlockExtendedData/0049.sql (Camp Entemarre Surface Portal)
Database/Patches/6 LandBlockExtendedData/004D.sql (Temple …
=> Portal Updates 35038 33035 87641 009D 0030 0043 0049 004D

Database/Patches/6 LandBlockExtendedData/E3D5.sql, Database/Patches/6 LandBlockExtendedData/E3D6.sql, Database/Patches/9 WeenieDefaults/Portal/Portal/90130 Olthoi Tunnel.sql, Database/Patches/9 WeenieDefaults/Portal/Portal/90131 Olthoi Tunnel.sql
Database/Patches/9 WeenieDefaults/Portal/Portal/90130 Olthoi Tunnel.sql 
Database/Patches/9 WeenieDefaults/Portal/Portal/90131 Olthoi Tunnel.sql 
Database/Patches/6 LandBlockExtendedData/E3D5.sql
Database/Patches/6 LandBlockExtendedData/E3D6.sql
https://asheron.fandom.com/wiki/Olthoi_Island
Of the twelve pair (24 total) of Olthoi Tunnels, we have 22 weenies, we are missing 2. Requested and received approval for 2 new weenies: 90130 & 90131.
-- Dark Isle Pair:
90130 (new) Olthoi Tunnel Source 69.4N, 80.3E
Destination 85.4N, 57.3E
Note: ace43705-olthoitunnel is existing return portal ---
-- Candeth Keep Pair:
90131 (new) Olthoi Tunnel Source 68.5N, 79.7E
Destination 87.7S, 65.1W
Note: ace43559-olthoitunnel is existing return portal
=> Update 90130 90131 E3D5 E3D6 Olthoi Tunnel Final 2 Portals

Database/Patches/6 LandBlockExtendedData/00B5.sql, Database/Patches/9 WeenieDefaults/Portal/Portal/90273 Surface.sql
Database/Patches/9 WeenieDefaults/Portal/Portal/ace90273 Surface.sql 
Database/Patches/6 LandBlockExtendedData/00B5.sql
Mosswart Worship Cavern
Using vloc2loc data on 00B5, we are missing a door 
Door - @teleloc 0x00B5012B [159.949951 -65.351562 -24] 1 0 0 0
Using vloc2loc data on 00B5, we are missing a Surface portal
Surface - @teleloc 0x00B50200 [9.992065 -195.851562 0] 1 0 0 0
Requested and received permission for new weenie
ace90273-surface
Destination of portal using world_objects data is here: exit - Surface (41.1S, 48.8W).
@teleloc 0x424C0019 [83.999023 12 7.005837] 1 0 0 0
Using vloc2loc data on 00B5, Ahumba (npc) should be 'nudged' into proper position behind the altar 
Ahumba - @teleloc 0x00B50129 [159.999390 -48 -24] 1 0 0 0
=> Update 00B5 Mosswart Worship Cavern

Database/Patches/6 LandBlockExtendedData/0031.sql
Database/Patches/6 LandBlockExtendedData/0031.sql
Update 0031 Surface .sql portal for Creepy Canyons Surface portal was failing to spawn
AddWorldObjectInternal: couldn't spawn 0x70031003:Surface [31314 - Portal] at 0x00310106 [193.641006 -151.292007 -90.063004] 0 0 -0.707107 0.707107
Using vloc2loc data, nudged surface portal to
@teleloc 0x00310106 [193.639526 -151.292969 -90] 1 0 0 0
=> Update 0031 Surface.sql portal for Creepy Canyons

Database/Patches/9 WeenieDefaults/Caster/Caster/23890 Assault Orb.sql, Database/Patches/9 WeenieDefaults/Caster/Caster/41898 Enhanced Assault Orb.sql
Removed clothing base, which was causing the orb to look incorrect (like glitched graphics).
=> Fix Assault Orb Appearance

Database/Patches/6 LandBlockExtendedData/C4F2.sql, Database/Patches/9 WeenieDefaults/Creature/ParadoxOlthoi/35888 Paradox-touched Olthoi Queen.sql, Database/Patches/9 WeenieDefaults/Creature/Rat/35100 Grave Rat.sql, Database/Patches/9 WeenieDefaults/Creature/Rat/36172 Blood Curse Rat.sql, Database/Patches/9 WeenieDefaults/Creature/Rat/36173 DeathTail.sql, Database/Patches/9 WeenieDefaults/Creature/Rat/37456 Grave Rat.sql, Database/Patches/9 WeenieDefaults/Creature/Rat/43166 Grave Rat.sql, Database/Patches/9 WeenieDefaults/Creature/Unsorted/34947 Rock.sql, Database/Patches/9 WeenieDefaults/Creature/Unsorted/34947.es, Database/Patches/9 WeenieDefaults/Generic/None/72142 Rynthid Platforms 1 Gen.sql, Database/Patches/9 WeenieDefaults/Generic/None/72143 Rynthid Platforms 2 Gen.sql, Database/Patches/9 WeenieDefaults/Scroll/Writable/53369 Scroll of Radiant Blood Recall.sql, Database/Patches/9 WeenieDefaults/Scroll/Writable/87875 Scroll of Celestial Hand Recall.sql, Database/Patches/9 WeenieDefaults/Scroll/Writable/88053 Scroll of Eldrytch Web Recall.sql
Adds attuned, bonded to society recall spell scrolls. 
Fixes graveyard rat breath attacks and sets skills from pcaps. 
Sets Rynthid platforms generator respawn to 10 min (timed from a Loud Lou retail video). It was previously 3 min. 
Adds NPC looks like object to a rock on Bur.
Adds leyline hotspot to Radiant Blood Infusion quest dungeon.
=> Various Bug Fixes

Database/Patches/9 WeenieDefaults/PressurePlate/Misc/87841 Large Pressure Plate.sql, Database/Patches/9 WeenieDefaults/PressurePlate/Misc/87843 Large Pressure Plate.sql
Fixed a pair of Pressure Plates that were not triggering since they were not ethereal, meaning the quest could never be completed.
=> Harlune's Diplomacy

Database/Patches/9 WeenieDefaults/Creature/FireElemental/45711 Ember.sql
Makes Embers that shoot flame waves in Geraine's Hosts quest visible to the player (as in retail).
=> Update 45711 Ember.sql

Database/Patches/6 LandBlockExtendedData/0076.sql, Database/Patches/9 WeenieDefaults/PressurePlate/Misc/73171 Mukkir Spawn Trap.sql
Adds mukkir spawn traps to the dungeon Mukkir Infested Black Spear Temple as per retail and cleans up the landblock from duplicate spawns (and spawns that come from the traps).
The traps are also noted on the wiki page, though pcap shows they did not necessarily spawn 4 mukkir: https://asheron.fandom.com/wiki/Mukkir_Infested_Black_Spear_Temple?so=search
=> Update Mukkir Slayer Dungeon

Database/Patches/9 WeenieDefaults/Creature/Ghost/88084 Spectral Archer.sql, Database/Patches/9 WeenieDefaults/Creature/Undead/87589 Mu-miyah Vizier.sql, Database/Patches/9 WeenieDefaults/Generic/Misc/88228 Seed of Essence.sql
Adds missing kill task stamp to a Vizier and missing stubborn missile to a Spectral Archer.
=> Fix Mobs in Bulb of Mornings

Database/Patches/9 WeenieDefaults/Creature/ParadoxOlthoi/35731 Paradox-touched Olthoi Eviscerator Grub.sql, Database/Patches/9 WeenieDefaults/Creature/ParadoxOlthoi/35732 Paradox-touched Olthoi Noble Grub.sql, Database/Patches/9 WeenieDefaults/Creature/ParadoxOlthoi/35733 Paradox-touched Olthoi Eviscerator Nymph.sql, Database/Patches/9 WeenieDefaults/Creature/ParadoxOlthoi/35734 Paradox-touched Olthoi Flyer Nymph.sql, Database/Patches/9 WeenieDefaults/Creature/ParadoxOlthoi/35735 Paradox-touched Olthoi Warrior Nymph.sql, Database/Patches/9 WeenieDefaults/Creature/ParadoxOlthoi/35812 Paradox-touched Olthoi Ward Guardian.sql, Database/Patches/9 WeenieDefaults/Creature/ParadoxOlthoi/35875 Paradox-touched Olthoi Sentinel.sql, Database/Patches/9 WeenieDefaults/Creature/ParadoxOlthoi/35877 Paradox-touched Olthoi Sentinel.sql, Database/Patches/9 WeenieDefaults/Creature/ParadoxOlthoi/35878 Paradox-touched Olthoi Lacerator.sql, Database/Patches/9 WeenieDefaults/Creature/ParadoxOlthoi/35879 Paradox-touched Olthoi Ripper.sql, Database/Patches/9 WeenieDefaults/Creature/ParadoxOlthoi/35880 Paradox-touched Olthoi Slasher.sql, Database/Patches/9 WeenieDefaults/Creature/ParadoxOlthoi/35881 Paradox-touched Olthoi Swarm Eviscerator.sql, Database/Patches/9 WeenieDefaults/Creature/ParadoxOlthoi/35882 Paradox-touched Olthoi Eviscerator.sql, Database/Patches/9 WeenieDefaults/Creature/ParadoxOlthoi/35883 Paradox-touched Olthoi Lancer.sql, Database/Patches/9 WeenieDefaults/Creature/ParadoxOlthoi/35884 Paradox-touched Olthoi Noble.sql, Database/Patches/9 WeenieDefaults/Creature/ParadoxOlthoi/35885 Paradox-touched Olthoi Warrior.sql, Database/Patches/9 WeenieDefaults/Creature/ParadoxOlthoi/36961 Olthoi Protector.sql
Sets skills and armor values from the pcap, and revises resistance mods to match existing olthoi. 
Corrects scale of Ward Guardian, and a few other olthoi. 
Corrects body table of Sentinel type olthoi, which were previously doing 0 damage with one of their body part. 
Adds missing idle emote to some olthoi.
Adjusts damage on some olthoi. For example, Olthoi Swarm Eviscerators were doing too little damage while some low level olthoi were doing too much damage - the same as their higher level counterpart.
=> Update Paradox Olthoi

Database/Patches/9 WeenieDefaults/Portal/Portal/40250 Entrance to the pyramid.sql, Database/Patches/9 WeenieDefaults/Portal/Portal/40485 Crystalline Portal.sql, Database/Patches/9 WeenieDefaults/Portal/Portal/71390 Catacombs.sql
Nudge these three portal destinations to remove error messages from our ACEmulator server log. 
[37] WARN  (ACE.Server.Entity.PositionExtensions) detected bad quaternion x y z w for Entrance to the pyramid (0x773C8002) | WCID: 40250 | WeenieType: Portal | PositionType: Destination [37] WARN  (ACE.Server.Entity.PositionExtensions) before fix: 0x00CB0100 [0.000000 0.000000 -29.995001] 0.020795 0.000000 0.000000 -1.000000 [37] WARN  (ACE.Server.Entity.PositionExtensions)  after fix: 0x00CB0100 [0.000000 0.000000 -29.995001] 0.020791 0.000000 0.000000 -0.999784
[26] WARN  (ACE.Server.Entity.PositionExtensions) detected bad quaternion x y z w for Crystalline Portal (0x788031B8) | WCID: 40485 | WeenieType: Portal | PositionType: Destination
[26] WARN  (ACE.Server.Entity.PositionExtensions) …
=> 40250, 40485, 71390 Fixed 'detected bad quaternion' errors in server log

Database/Patches/6 LandBlockExtendedData/76E9.sql, Database/Patches/9 WeenieDefaults/Book/Writable/43517 Journal of a Soldier.sql, Database/Patches/9 WeenieDefaults/Book/Writable/51583 Journal of a Soldier.sql, Database/Patches/9 WeenieDefaults/Creature/Human/70351 Mortified Soldier.sql, Database/Patches/9 WeenieDefaults/Creature/Human/70351.es
Minor updates and bug fixes to this quest based on retail videos by Kala Glow and Geffers58.
The Journal of a Soldier can now be read.
The Mortified Soldier is now in a ShiverState as seen in the video. 
Set location of two doors from vlocs (these were not papped, and were previously manually placed). 
Adjusted some spawns in non-pcapped sections of the dungeon to match the video. 
Respawn increased to 5 min (was previously 3 min). The video shows it was longer than 3 min.
=> Update Gurog Creation

Database/Patches/4 CraftTable/09225 Prismatic Amuli Coat.sql, Database/Patches/4 CraftTable/09226 Prismatic Amuli Leggings.sql, Database/Patches/4 CraftTable/09227 Prismatic Celdon Breastplate.sql, Database/Patches/4 CraftTable/09228 Prismatic Celdon Girth.sql, Database/Patches/4 CraftTable/09229 Prismatic Celdon Leggings.sql, Database/Patches/4 CraftTable/09230 Prismatic Celdon Sleeves.sql
Adds recipes to create these Shadow Armor pieces. Although retired, they could still be made at the end of retail if a person had left over armor pieces, and could be useful for server operators who wish to make this armor available again.
=> Add Prismatic Amuli and Celdon Recipes

Database/Patches/9 WeenieDefaults/Creature/Rat/36172 Blood Curse Rat.sql, Database/Patches/9 WeenieDefaults/Creature/Rat/49586 Infectious Rat.sql
Adds missing spells based on the wiki description, and skills, armor levels from pcap. Also corrects combat table so the Infectious Rat will use its breath attack.
=> Update Health Draining Rats

Database/Patches/6 LandBlockExtendedData/0046.sql, Database/Patches/6 LandBlockExtendedData/40D8.sql, Database/Patches/9 WeenieDefaults/Book/Writable/32515 Underminer Notes.sql, Database/Patches/9 WeenieDefaults/Creature/AunTumerok/52015 Aun Ol'tra.sql, Database/Patches/9 WeenieDefaults/Creature/GearKnight/70712 Iron Blade Warmaster.sql, Database/Patches/9 WeenieDefaults/Creature/Human/41545 Sir Yanov.sql, Database/Patches/9 WeenieDefaults/Creature/Human/41546 Dame Trielle.sql, Database/Patches/9 WeenieDefaults/Creature/Human/42360 Sir Durnstad.sql, Database/Patches/9 WeenieDefaults/Creature/Shadow/33542 Lanaith.sql, Database/Patches/9 WeenieDefaults/Creature/ViamontianKnight/32833 Escaped Thief.sql
Updates clothing (mostly missing cloaks) of some Gearknight Direlands Invasion area NPCs, and setup of Iron Blade Warmaster, to match their appearance on a Loud Lou retail video. 
Adds missing clothing base and palette to Aun Oltra at Rynthid Infested Plains Camp. 
Escaped Thief in Sword of Belenesse quest now has friend type Eater, so his eaters will come to his aid when attacked from a distance, like in retail. Removes flamma and flare spawns in the Sword of Belenesse dungeon. All of these spawn from the Infernos and should not be in the linkable monster gen. 
Adds missing attuned, bonded, and description to Underminer Notes from Shield of Yanshi quest, and changes respawn to 5 min. This had been left with the default pcap gen (of about 13 min). The respawn was not that slow.
=> Misc Updates July

Database/Patches/9 WeenieDefaults/Creature/Human/81084 Ardenson.sql, Database/Patches/9 WeenieDefaults/Creature/Human/81084.es, Database/Patches/9 WeenieDefaults/Creature/Human/81086 Maximas.sql, Database/Patches/9 WeenieDefaults/Creature/Human/81086.es
Thanks to SoulRapture for the bug report!
=> Fixed issue with Bypass NPCs in Assassin's Roost Quests

Database/Patches/6 LandBlockExtendedData/F93B.sql, Database/Patches/9 WeenieDefaults/Generic/None/73209 Empyrean Rescue Dungeon 2 Gen.sql, Database/Patches/9 WeenieDefaults/Generic/None/87053 Empyrean Rescue Armored Guardian Gen.sql, Database/Patches/9 WeenieDefaults/Generic/None/87493 Empyrean Rescue Undead Commander Gen.sql, Database/Patches/9 WeenieDefaults/Generic/None/87494 Empyrean Rescue Filinuvekta Gen.sql, Database/Patches/9 WeenieDefaults/Generic/None/87495 Empyrean Rescue Engorged Bloodstone Gen.sql, Database/Patches/9 WeenieDefaults/Portal/Portal/87499 Gateway.sql
Corrected an issue where duplicates from the same wave could spawn during the final fight. 
Removed destroyed portals from dungeon 2 spawns. These were only found in dungeons 1 and 3. 
Changed gateway summoned by Virindi boss in dungeon 2 to no summon (can now be tied, recalled) to match retail behavior as per reports from players.
=> Update Empyrean Rescue

Database/Patches/9 WeenieDefaults/Creature/Anekshay/44101 Nephthys.sql, Database/Patches/9 WeenieDefaults/Creature/Anekshay/44101.es, Database/Patches/9 WeenieDefaults/Creature/Anekshay/44138 Nephthys.sql, Database/Patches/9 WeenieDefaults/Creature/Anekshay/44138.es
Fixed an issue where the player could get stuck if their scrying rod decays after getting the crystals but before bringing them back to the device.
Added turn to target on the NPC spawned by the device.
=> Update Slave Master Quest

Database/Patches/9 WeenieDefaults/Ammunition/MissileWeapon/47513 Arrow.sql, Database/Patches/9 WeenieDefaults/Creature/Ghost/46563 Spectral Archer.sql, Database/Patches/9 WeenieDefaults/Creature/Ghost/47217 Ensorcelled Weapon.sql, Database/Patches/9 WeenieDefaults/Creature/Ghost/47226 Ensorcelled Weapon.sql, Database/Patches/9 WeenieDefaults/Creature/Ghost/88084 Spectral Archer.sql, Database/Patches/9 WeenieDefaults/Creature/Human/45692 Geraine.sql, Database/Patches/9 WeenieDefaults/Creature/Undead/44347 Filinuvekta Emissary.sql, Database/Patches/9 WeenieDefaults/Creature/Undead/45703 Geraine.sql, Database/Patches/9 WeenieDefaults/Creature/Unsorted/72493 Enchanted Mnemosyne.sql, Database/Patches/9 WeenieDefaults/Creature/Unsorted/72493.es, Database/Patches/9 WeenieDefaults/Creature/Unsorted/72494 Enchanted Mnemosyne.sql, Database/Patches/9 WeenieDefaults/Creature/Unsorted/72494.es, Database/Patches/9 WeenieDefaults/Creature/Unsorted/72495 Enchanted Mnemosyne.sql, Database/Patches/9 WeenieDefaults/Creature/Unsorted/72495.es, Database/Patches/9 WeenieDefaults/Creature/ViamontianKnight/87530 Summoning Chamber Adept.sql, Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/47219 Ensorcelled Sword.sql, Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/47227 Ensorcelled Mace.sql
Fixes dual wielding ghost weapons based on Loud Lou retail video. Previously, it was possible for a ghost weapon to spawn unarmed or wield only in its left hand, which was incorrect.
Corrects undefined damage type on bow wielding ghost weapons. It is now set to pierce, as seen in the video.
Sets scale of Summoning Chamber Adept to 1 to match retail screenshot.
Adds missing stubborn missile to a spectral archer in the Hoshino Fortress Infiltration quest, which could cause it to become stuck and unable to attack.
Fixes bug with two Geraines, where guards would spawn after some period of time, even if Geraine had not been attacked.
Corrects generator and skill levels for Filinuvekta Emissary (rare spawn in Neftet). Also increases armor to match other similar mobs.
Added quest success text to …
=> Misc Fixes October

Database/Patches/9 WeenieDefaults/Creature/Unsorted/46457 Lock.sql, Database/Patches/9 WeenieDefaults/Creature/Unsorted/46457.es, Database/Patches/9 WeenieDefaults/Door/Misc/46310 Door.sql, Database/Patches/9 WeenieDefaults/Door/Misc/46311 Door.sql, Database/Patches/9 WeenieDefaults/Door/Misc/46312 Door.sql, Database/Patches/9 WeenieDefaults/Generic/None/73210 Landblock KeepAlive Gen.sql
In retail, the main gate of Hoshino Fort would stay open for a longer period of time (around 30 min), as far as I remember, even when no one was around to keep the landblock active.
To replicate this behavior, when activated, the lock now spawns a Landblock KeepAlive with a lifespan of 25 min, and the reset interval on the gate is set to 30 min.
=> Update Hoshino Fort Main Gate

Database/Patches/6 LandBlockExtendedData/008B.sql, Database/Patches/9 WeenieDefaults/Creature/Golem/33033 Masonry Golem.sql, Database/Patches/9 WeenieDefaults/Creature/Golem/33033.es, Database/Patches/9 WeenieDefaults/Creature/Golem/40775 Ancient Golem.sql, Database/Patches/9 WeenieDefaults/Creature/Golem/40775.es, Database/Patches/9 WeenieDefaults/Creature/Golem/40861 Ancient Golem.sql, Database/Patches/9 WeenieDefaults/Creature/Golem/40861.es, Database/Patches/9 WeenieDefaults/Creature/Undead/32952 Ancient Steward.sql, Database/Patches/9 WeenieDefaults/Creature/Undead/32954 Foul Mason.sql, Database/Patches/9 WeenieDefaults/Creature/Undead/32955 Wretched Architect.sql, Database/Patches/9 WeenieDefaults/Creature/Undead/32956 Heavy Builder.sql
Adjusts armor, skills and spells from the pcaps. Overall, this makes the creatures tougher.
Corrects appearance of Masonry Golem and Heavy Builder.
Adds missing new enemy flavor text to Masonry and Ancient Golem.
Removes a duplicate mob from the Ancient Masonry.
=> Update Masonry Mobs

Database/Patches/2 SpellTableExtendedData/04082 Big Fire.sql, Database/Patches/9 WeenieDefaults/Creature/Human/43526 Fayza.sql, Database/Patches/9 WeenieDefaults/Creature/Human/43526.es, Database/Patches/9 WeenieDefaults/Creature/Human/88411 Elysa Strathelar.sql, Database/Patches/9 WeenieDefaults/MeleeWeapon/MeleeWeapon/25907 Gikar's Dream.sql, Database/Patches/9 WeenieDefaults/ProjectileSpell/None/35461 Big Fire.sql
Removes mana forge key reward from Fayza for Deewain's Dark cavern quest. As seen in a Loud Lou retail video, this key was no longer given (replaced by a legendary key in the dungeon).
Elysa's bow now appears green. Previously, the correct color was overwritten by the create list of the NPC wielding it.
Gikar's Dream updated to match the pcap, which also makes it tailorable.
Corrects the projectile for the Big Fire spell and increase damage to match level 7 fire bolt.
=> Misc Fixes

Database/Patches/9 WeenieDefaults/MissileLauncher/MissileWeapon/40425 Renegade Kalindan of the Mountains.sql, Database/Patches/9 WeenieDefaults/MissileLauncher/MissileWeapon/88177 Renegade Kalindan of the Chase.sql, Database/Patches/9 WeenieDefaults/MissileLauncher/MissileWeapon/88178 Renegade Kalindan of the Forests.sql, Database/Patches/9 WeenieDefaults/MissileLauncher/MissileWeapon/88179 Renegade Kalindan of the Heights.sql, Database/Patches/9 WeenieDefaults/MissileLauncher/MissileWeapon/88248 Renegade Kalindan of the Vortex.sql, Database/Patches/9 WeenieDefaults/MissileLauncher/MissileWeapon/88249 Renegade Kalindan of the Rivers.sql
Renegade kalindans (crossbows) had a useless value set for CriticalMultiplier. Changed it to match the other renegade weapons.
=> Add Crit Multiplier for Renegade Kalindans

Database/Patches/9 WeenieDefaults/Creature/Anekshay/49571 Bak'tshay Keeper.sql, Database/Patches/9 WeenieDefaults/Creature/Anekshay/49573 Bak'tshay Keeper.sql, Database/Patches/9 WeenieDefaults/Creature/Anekshay/49574 Bak'tshay Keeper.sql
Increase Init MaxHealth on Bak'tshay Keepers (4 corners boss versions) to match current/pcap value.
=> Fix Baktshay Keeper Health

Database/Patches/9 WeenieDefaults/Portal/Portal/88185 Surface.sql
Renegade Fortress 120+. Surface portal wasn't pcaped, it wasn't appraised on the video I found, and the wiki has no info, but a 200+ level restriction on the surface portal seems unlikely. Don't see where else that would have come from, so just assuming it was mistakenly carried over from the portal it was copied from.
=> Fix Renegade Fortress Surface

Database/Patches/9 WeenieDefaults/Creature/Aerbax/36951 Aerbax's Shadow.sql, Database/Patches/9 WeenieDefaults/Creature/Aerbax/36951.es, Database/Patches/9 WeenieDefaults/Creature/Aerbax/37377 Aerbax's Shadow.sql, Database/Patches/9 WeenieDefaults/Creature/Aerbax/37377.es, Database/Patches/9 WeenieDefaults/Creature/Aerbax/37378 Aerbax's Shadow.sql, Database/Patches/9 WeenieDefaults/Creature/Aerbax/37378.es, Database/Patches/9 WeenieDefaults/Creature/Aerbax/37379 Aerbax's Shadow.sql, Database/Patches/9 WeenieDefaults/Creature/Aerbax/37379.es, Database/Patches/9 WeenieDefaults/Creature/Aerbax/37380 Aerbax's Shadow.sql, Database/Patches/9 WeenieDefaults/Creature/Aerbax/37380.es, Database/Patches/9 WeenieDefaults/Creature/Aerbax/37381 Aerbax's Shadow.sql, Database/Patches/9 WeenieDefaults/Creature/Aerbax/37381.es
There have been groups that apparently do too much damage, so that they're skipping over the WoundedTaunt range on Aerbax and breaking the quest from progressing to the next event. Summons also don't trigger WoundedTaunt, which is probably a bug causing most of these issues, but I don't see any real reason to not widen the ranges on the low end.
=> Widen WoundedTaunt ranges for Aerbax

Database/Patches/9 WeenieDefaults/Creature/Unsorted/51646 Thick Rock Wall.sql
The Thick Rock Wall in Empyrean Rescue wasn't being deleted if the Engorged Bloodstone died in the (roughly) back third of the room. This increases the HearLocalSignalsRadius to reach the entire room.
=> Increase Listening Range for Thick Rock Wall (Empyrean Rescue)

Database/Patches/2 SpellTableExtendedData/06187 Screeching Howl.sql, Database/Patches/2 SpellTableExtendedData/06188 Earthquake.sql, Database/Patches/9 WeenieDefaults/Creature/Armoredillo/52709 Stinging Armoredillo.sql, Database/Patches/9 WeenieDefaults/Creature/Burun/46690 Guruk Grunt.sql, Database/Patches/9 WeenieDefaults/Creature/Burun/52712 Ruuk Ranger.sql, Database/Patches/9 WeenieDefaults/Creature/Burun/52712.es, Database/Patches/9 WeenieDefaults/Creature/Grievver/52779 Pike Grievver.sql, Database/Patches/9 WeenieDefaults/Creature/Idol/88074 Holcha.sql, Database/Patches/9 WeenieDefaults/Creature/Idol/88074.es, Database/Patches/9 WeenieDefaults/Generic/Armor/46707 Corrupted Aegis.sql
Ruuk Ranger
-Fixed so it casts its special spell. It was using a WoundedTaunt with no health condition, so it never triggered. Moved it to a Taunt. 
-Added war/life skills so it can actually land its spells instead of always being resisted.
Screeching Howl
-Makes it actually do damage.
-Changed from bludge to pierce damage (despite using the bludge graphic, PCAP: "Ruuk Ranger gores you for 315 points with Screeching Howl.")
Guruk Grunt
-Removed "vulnerable" effect that caused it to do nothing the first 60 seconds after spawning. PCAPs don't show this effect, nor do ImmortalBob's two videos after the May 2015 patch (patch note: "debuff mechanic removed entirely"). 
Pike Grievver
-Increased VisualAwarenessRange to match other grievvers, since they weren't aggroing if they spawned at the …
=> Gauntlet Fixes

Database/Patches/4 CraftTable/09234 Damaged Shadow Blade.sql, Database/Patches/4 CraftTable/09235 Damaged Shadow Blade.sql, Database/Patches/4 CraftTable/09236 Damaged Shadow Blade.sql, Database/Patches/4 CraftTable/09237 Damaged Shadow Blade.sql, Database/Patches/4 CraftTable/09238 Damaged Shadow Blade.sql, Database/Patches/9 WeenieDefaults/CraftTool/Gem/51914 Damaged Shadow Blade.sql, Database/Patches/9 WeenieDefaults/Creature/Shadow/44805 Void Lord.sql, Database/Patches/9 WeenieDefaults/Creature/Shadow/44806 Panumbris Shadow.sql, Database/Patches/9 WeenieDefaults/Creature/Shadow/44807 Panumbris Shadow.sql, Database/Patches/9 WeenieDefaults/Creature/Shadow/44808 Panumbris Shadow.sql, Database/Patches/9 WeenieDefaults/Creature/Shadow/52275 Void Lord.sql
I did a pcap dive and added the Damaged Shadow Blade as a 1% drop on all the mobs that dropped it in the pcaps (Tou Tou mobs, mix of Panumbris Shadows and Void Lords). I did not validate that drop rate in pcaps, but as a purely cosmetic/tailor item I figure it did not matter too much.
Some of the Cookbook items do not currently exist; that's because the loot gen is currently dropping the wrong weenies for some of these items and they may or may not be added later.
=> Add Damaged Shadow Blade and recipes to tailor it onto swords

Database/Patches/9 WeenieDefaults/Clothing/Armor/29542 Enscorcelled Robe.sql
Updates Enscorcelled Robe to have missing spell (Corruptor's Boon) to match PCAP.
=> Add Missing Spell to Enscorcelled Robe

Database/Patches/9 WeenieDefaults/Book/Misc/36930 Thief of Dreams Message Shard.sql, Database/Patches/9 WeenieDefaults/Creature/Shadow/36926 Shade of Dule.sql, Database/Patches/9 WeenieDefaults/Creature/Shadow/36926.es
Corrected an issue with the Shade of Dule emote where the on use text was missing if the player was in a fellow.
Added the standard "you cannot read the writing on this" text on the untranslated Thief of Dreams Message Shard.
=> Update Ithaenc Quiddity Seed

Database/Patches/6 LandBlockExtendedData/24C0.sql, Database/Patches/9 WeenieDefaults/Creature/Slithis/38826 Eyestalk of T'thuun.sql, Database/Patches/9 WeenieDefaults/Creature/Slithis/38827 Tendril of T'thuun.sql, Database/Patches/9 WeenieDefaults/Creature/Slithis/38828 Tentacle of T'thuun.sql, Database/Patches/9 WeenieDefaults/Creature/Slithis/73256 Eyestalk of T'thuun.sql, Database/Patches/9 WeenieDefaults/Creature/Unsorted/87827 Altar of T'thuun.sql, Database/Patches/9 WeenieDefaults/Creature/Unsorted/87827.es, Database/Patches/9 WeenieDefaults/Generic/Misc/73255 Wharu Fetish.sql, Database/Patches/9 WeenieDefaults/Generic/Misc/87826 Wharu Fetish.sql, Database/Patches/9 WeenieDefaults/Generic/None/87832 Roots of Skuld Generator.sql, Database/Patches/9 WeenieDefaults/Portal/Portal/87828 Roots of Skuld, Urd and Verdandi.sql
Updates the quest: https://acpedia.org/wiki/Guardian_of_the_Deru_Trees_of_Marae_Lassel
Revises dungeon spawns for a closer match to retail (sclavus in areas with olthoi corpses, olthoi in organic areas).
All tentacles of tthuun outside now count for the kill task (not just those with tentacle in the name) as seen in retail screenshots.
Corrects spells, armor levels, and skills of the tentacles to match the pcap, wiki, and screenshots.
Removed weight of the world from eyestalks (this was limited to eyestalks on moar city, and the tthuun boss fight).
Added missing wharu fetish effect to the tthuun altar (fetish spawns above the altar) as seen in retail screenshots.
Revised the final scene (where olthoi, tentacles, and sclavus fight each other) to match retail screenshot.
Corrected …
=> update guardian of the deru

Database/Patches/6 LandBlockExtendedData/4198.sql, Database/Patches/6 LandBlockExtendedData/4298.sql, Database/Patches/9 WeenieDefaults/Creature/Human/11504 Mercenary.sql, Database/Patches/9 WeenieDefaults/Creature/Human/32699 Mercenary Mage.sql, Database/Patches/9 WeenieDefaults/Creature/ViamontianKnight/32700 Viamontian Portal Mage.sql, Database/Patches/9 WeenieDefaults/Creature/ViamontianKnight/32702 Captain Vietre Lasallia.sql, Database/Patches/9 WeenieDefaults/Creature/ViamontianKnight/32767 Viamontian Footman.sql, Database/Patches/9 WeenieDefaults/Creature/ViamontianKnight/32768 Viamontian Footman.sql
Adds missing mob 32767 Viamontian Footman.
Adjusts mob armor levels, skills, spells and missing damage rating based on the pcap.
Replaces the default monster and item gens with 5 min and 25 sec gens, respectively.
Adds missing spawns in landblock 4298.
=> update plateau village transit

Database/Patches/9 WeenieDefaults/Generic/None/21183 Low North Forest Mix Generator.sql, Database/Patches/9 WeenieDefaults/Generic/None/23146 Low North Plains Mix Generator.sql, Database/Patches/9 WeenieDefaults/Generic/None/73260 Low Scarecrow Gen.sql
Adds a scarecrow gen tied to EventFallFestival to Low North Forest Mix and Low Plains Mix Gens. The gen can spawn Nasty, Naughty and Nefarious Scarecrows, and an inanimate look-alike version.
=> Add Scarecrows to Landscape
